<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <?= $this->headMeta(); ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
    </head>
    <body>
        <?php if (isset($this->files)) { ?>
            <table class="traffic-table-iframe traffic-table-left">
                <tr>
                    <th>&nbsp;</th>
                    <th>Firmante</th>
                    <th>RFC Consulta</th>
                    <th>Patente</th>
                    <th>Aduana</th>
                    <th>Archivo</th>
                    <th>Referencia</th>
                    <th>Pedimento</th>
                    <th>Tipo</th>
                    <th>&nbsp;</th>
                </tr>     
                <?php 
                foreach($this->files as $k => $item) { ?>
                <tr>
                    <td>&nbsp;</td>
                    <td><?= $item["firmante"] ?></td>
                    <td><?= $item["rfc"] ?></td>
                    <td><?= $item["patente"] ?></td>
                    <td><?= $item["aduana"] ?></td>
                    <td><?= basename($item["name"]) ?></td>
                    <td><?= isset($item["referencia"]) ? $item["referencia"] : '&nbsp;' ?></td>
                    <td><?= isset($item["pedimento"]) ? $item["pedimento"] : '&nbsp;' ?></td>
                    <td><?= isset($item["tipo"]) ? $item["tipo"] . ' - ' . $this->tipoEdoc($item["tipo"]) : '&nbsp;' ?></td>
                    <td>
                        <div class="traffic-icon traffic-icon-delete" onclick="parent.borrarArchivo('<?= $k ?>');"></div>
                    </td>
                </tr>
                <?php } ?>
            </table>
        <?php } ?>
    </body>
</html>
