<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">     
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <?= $this->headMeta(); ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
    </head>
    <body>
        <?php if (isset($this->files)) { ?>
            <table>
                <tr>
                    <td colspan="13"><button class="btn-vucem btn-vucem-green" id="sendall" >Enviar todo</button></td>
                </tr>
                <tr>
                    <th style="width: 25px;"><input type="checkbox" id="checkall" ></th>
                    <th style="width: 25px;">&nbsp;</th>
                    <th style="width: 50px;">&nbsp;</th>
                    <th style="width: 100px;">Firmante</th>
                    <th style="width: 100px;">RFC Consulta</th>
                    <th style="width: 50px;">Operación</th>
                    <th>Referencia</th>
                    <th>Archivo</th>
                    <th>Tamaño</th>
                    <th>Tipo</th>
                    <th>&nbsp;</th>
                </tr>     
                <?php foreach ($this->files as $k => $item) { ?>
                    <tr class="hover">
                        <?php if ($item["solicitud"] == null) { ?>
                            <td><input type="checkbox" name="send" value="check_<?= $item["id"] ?>" ></td>
                            <td>
                                <div id="progress-bar_<?= $item["id"] ?>">
                                    <div id="progress_<?= $item["id"] ?>" style="text-align: center; width: 25px;">&nbsp;</div>
                                </div>
                            </td>
                            <td><form id="form_<?= $item["id"] ?>"><input type="hidden" name="id" value="<?= $item["id"] ?>" ></form><button class="btn-vucem btn-vucem-orange" id="send_<?= $item["id"] ?>" onclick="enviarDocumento('<?= $item["id"] ?>');">Enviar</button>&nbsp;</td>
                        <?php } else { ?>
                            <td colspan="3" style="text-align: center;"><?= $item["solicitud"] ?></td>
                        <?php } ?>
                        <td><?= $item["firmante"] ?></td>
                        <td><?= $item["rfcConsulta"] ?></td>
                        <td><?= $item["aduana"] . '-' . $item["patente"] . '-' . $item["pedimento"] ?></td>
                        <td><?= isset($item["referencia"]) ? $item["referencia"] : '&nbsp;' ?></td>
                        <td><?= basename($item["nomArchivo"]) ?></td>
                        <td style="text-align: right;"><?= $this->filesize(filesize($item["nomArchivo"])) ?></td>
                        <td>
                            <div id="edit_<?= $item["id"] ?>"><?= isset($item["tipoArchivo"]) ? $item["tipoArchivo"] . ' - ' . $this->tipoEdoc($item["tipoArchivo"]) : '&nbsp;' ?></div>
                        </td>
                        <?php if ($item["solicitud"] == null) { ?>
                            <td>
                                <div id="icon_<?= $item["id"] ?>">
                                    <div class="traffic-icon traffic-icon-edit" onclick="editarArchivo('<?= $item["id"] ?>');"></div>
                                    <div class="traffic-icon traffic-icon-delete" onclick="borrarArchivo('<?= $item["id"] ?>');"></div>
                                </div>
                            </td>
                        <?php } else { ?>
                            <td>&nbsp;</td>
                        <?php } ?>
                    </tr>
                <?php } ?>
            </table>
        <?php } else { ?>
            <table>
                <tr>
                    <td colspan="13"><button class="btn-vucem btn-vucem-green" id="sendall" >Enviar todo</button></td>
                </tr>
                <tr>
                    <th style="width: 25px;"><input type="checkbox" id="checkall" ></th>
                    <th style="width: 25px;">&nbsp;</th>
                    <th style="width: 50px;">&nbsp;</th>
                    <th style="width: 100px;">Firmante</th>
                    <th style="width: 100px;">RFC Consulta</th>
                    <th style="width: 50px;">Operación</th>
                    <th>Referencia</th>
                    <th>Archivo</th>
                    <th>Tamaño</th>
                    <th>Tipo</th>
                    <th>&nbsp;</th>
                </tr>
                <tr>
                    <td colspan="13" style="text-align: center;"><em>No ha subido documentos.</em></td>
                </tr>
            </table>
        <?php } ?>
    </body>
    <script type="text/javascript">
        $(function () {
            $("#sendall").click(function () {
                var values = [];
                $("input[name=send]").each(function () {
                    if ($(this).prop("checked") === true) {
                        var value = $(this).val();
                        var res = value.split("_");
                        values.push(res[1]);
                        enviarDocumentoMultiple(res[1]);
                    }
                });
                if (values.length === 0) {
                    alert("No ha seleccionado.");
                }
            });
            $("#checkall").click(function () {
                if ($("#checkall").prop("checked") === true) {
                    $("input[name=send]").each(function () {
                        $(this).prop("checked", true);
                    });
                } else {
                    $("input[name=send]").each(function () {
                        $(this).prop("checked", false);
                    });
                }
            });
        });

        function borrarArchivo(value) {
            $.ajax({
                url: "/vucem/data/delete-file",
                cache: false,
                method: 'post',
                data: {id: value},
                success: function () {
                    document.location.reload(true);
                }
            });
        }

        function changeFile(value) {
            $.ajax({
                url: "/vucem/data/change-edoc-file-type",
                context: document.body,
                data: {id: value, type: $("#select_" + value).val()},
                type: 'GET'
            }).done(function (data) {
                var obj = jQuery.parseJSON(data);
                if (obj.success === true) {
                    $("#edit_" + value).html(obj.type);
                    $("#icon_" + value).html(obj.icons);
                } else if (obj.success === false) {
                    alert("Ocurrio un error al guardar cambios.");
                }
            });
        }

        function cancelEdit(value) {
            $.ajax({
                url: "/vucem/data/cancel-edit",
                context: document.body,
                data: {id: value, type: $("#select_" + value).val()},
                type: 'GET'
            }).done(function (data) {
                var obj = jQuery.parseJSON(data);
                if (obj.success === true) {
                    $("#edit_" + value).html(obj.type);
                    $("#icon_" + value).html(obj.icons);
                } else if (obj.success === false) {
                    alert("Ocurrio un error al guardar cambios.");
                }
            });
        }

        function editarArchivo(value) {
            $.ajax({
                beforeSend: function () {
                    $("#icon_" + value).html('<a style="cursor:pointer;" onclick="changeFile(' + value + ')"><img src="/images/icons/disk.png" /></a>&nbsp;<a style="cursor:pointer;" onclick="cancelEdit(' + value + ')"><img src="/images/icons/cancel.png" /></a>');
                },
                url: "/vucem/data/edoc-file-types",
                context: document.body,
                data: {id: value},
                type: 'GET'
            }).done(function (data) {
                $("#edit_" + value).html(data);
            });
        }

        function enviarDocumentoMultiple(value) {
            $.ajax({
                url: "/vucem/data/send-new-file-multiple",
                type: 'post',
                async: false,
                data: {id: value},
                beforeSend: function () {
                    $("#progress_" + value).html("<img src=\"/images/preloader.gif\" />");
                },
                complete: function () {
                    uploadProgess(value);
                }
            });
        }

        function enviarDocumento(value) {
            var options = {
                url: "/vucem/data/send-new-file",
                type: 'POST',
                async: true,
                beforeSend: function () {
                    $("#progress_" + value).html("<img src=\"/images/preloader.gif\" />");
                }
            };
            $('#form_' + value).ajaxForm(options);
            $('#form_' + value).ajaxSubmit(options);
            uploadProgess(value);
        }

        function uploadProgess(value) {
            $.ajax({
                url: "/vucem/data/get-progress-upload",
                cache: false,
                async: true,
                method: 'post',
                data: {id: value},
                success: function (data) {
                    if (data) {
                        if (data === '100') {
                            $.post("/vucem/data/mark-as-send", {id: value});
                            $("#progress_" + value).html("<img src=\"/images/icons/ok.png\" />");
                        } else {
                            $("#progress_" + value).html("<img src=\"/images/preloader.gif\" />");
                        }
                    }
                }
            });
        }
    </script>
</html>
