<div id="modalWindow">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h3>Facturas disponibles</h3>
    </div>
    <div class="modal-body">
        <?php if($this->facturas && !$this->warning) { ?>
        <table class="table table-striped table-bordered table-hover small">
            <thead>
                <tr>
                    <th>Referencia</th>
                    <th>Tipo</th>
                    <th>Regimen</th>
                    <th>Clave de pedimento</th>
                    <th>Consolidado</th>
                    <th>Rectificación</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><?= $this->pedimento["Referencia"] ?></td>
                    <td><?= $this->pedimento["TipoOperacion"] ?></td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>    
                </tr>
            </tbody>
        </table>
        <table class="table table-striped table-bordered table-hover small">
            <thead>
                <tr>
                    <th colspan="7" style="text-align: center; background: #ffffee">FACTURAS DEL PEDIMENTO</th>
                </tr>
                <tr>
                    <th rowspan="2" style="border-bottom: 0">&nbsp;</th>
                    <th rowspan="2" style="border-bottom: 0">Factura</th>
                    <th colspan="2" style="border-bottom: 0">Cliente</th>
                    <th colspan="2" style="border-bottom: 0">Proveedor</th>
                </tr>
                <tr>
                    <th style="border-bottom: 0">RFC/Tax Id</th>
                    <th style="border-bottom: 0">Nombre</th>
                    <th style="border-bottom: 0">RFC/Tax Id</th>
                    <th style="border-bottom: 0">Nombre</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->facturas as $item) { ?>
                <tr>
                    <td><input type="checkbox" name="facts" value="<?= urlencode($item["NumFactura"]) ?>" /></td>
                    <td><?= $item["NumFactura"] ?></td>
                    <td><?= $item["CteRfc"] ?></td>
                    <td><?= $item["CteNombre"] ?></td>
                    <td><?= $item["ProTaxID"] ?></td>
                    <td><?= $item["ProNombre"] ?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
        <?php } elseif($this->warning) { ?>
<!--        <h3>No existe pedimento o no tiene facturas.</h3>-->
            <h4><?= $this->warning ?></h4>
        <?php } ?>
    </div>
    <div class="modal-footer">
      <?php if($this->facturas) { ?>
        <a id="selectallinvoices" class="btn btn-info" style="float: left"><i class="icon-white icon-check"></i>&nbsp;Seleccionar todas</a>
        <a id="invoices" class="btn btn-primary">Seleccionar facturas</a>
      <?php } ?>
      <a id="closeModal" class="btn btn-danger" data-dismiss="modal">Cerrar</a>
    </div>
</div>
<script>
    $("a#invoices").click(function(event) {        
        event.preventDefault();        
        var ids = [];
        var boxes = $('input[name=facts]:checked');
        if((boxes).size() > 0) {
            $(boxes).each(function(){
                ids.push($(this).val());
            });
            var facts = ids.toString();
            facts = facts.replace(/,/g, '|');
            $.ajax({
                url: "/vucem/data/seleccionar-facturas-slam?referencia=<?= $this->pedimento["Referencia"] ?>&facts="+facts,
                cache: false
            }).done(function(html) {
                $('#closeModal').trigger('click');
                window.location.reload();
            });
        }        
    });
    $("a#selectallinvoices").click(function(event) {
        $('input[name=facts]').each(function() {
            $(this).attr('checked',!$(this).attr('checked'));
        });
    });
</script>