<div id="modalWindow">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h3>Destinatarios Exportación</h3>
    </div>
    <div class="modal-body">
        <?php if($this->destinatarios) { ?>
        <table class="table table-striped table-bordered table-hover small">
            <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th>RFC</th>
                    <th>NOMBRE</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->destinatarios as $item) { ?>
                <tr>
                    <td>&nbsp;<a href="/vucem/data/detalle-destinatario-exp?cvedest=<?= $item["cvedest"] ?>&tipo=<?= $this->tipo ?>" class="detalle-destinatario"><i class="icon-ok-sign"></i></a></td>
                    <td><?= $item["rfc"] ?></td>
                    <td><?= $item["razon_soc"] ?></td>
                </tr>
                <?php } ?>
            </tbody>            
        </table>
        <?php } else { ?>
        <h4>No tiene destinatarios asignados.</h4>
        <?php } ?>
    </div>
    <div class="modal-footer">
      <a id="closeModal" class="btn btn-danger" data-dismiss="modal">Cerrar</a>
    </div>
</div>
<script>    
    $(".detalle-destinatario").click(function(e){
        e.preventDefault();
        $.ajax({
            url: $(this).attr('href'),
            cache: false,
            dataType: 'json'
        }).done(function(data) {
            $("#bootstrap-CteIden").val(data.identificador);
            $("#bootstrap-CteRfc").val(data.rfc);
            $("#bootstrap-CteNombre").val(data.razon_soc);
            $("#bootstrap-CteCalle").val(data.calle);
            $("#bootstrap-CteColonia").val(data.colonia);
            $("#bootstrap-CteNumExt").val(data.numext);
            $("#bootstrap-CteNumInt").val(data.numint);
            $("#bootstrap-CteMun").val(data.municipio);
            $("#bootstrap-CteEdo").val(data.estado);
            $("#bootstrap-CteCP").val(data.cp);
            $("#bootstrap-CtePais").val(data.pais);
            $('#closeModal').trigger('click');
        });
    });
</script>