<div id="modalWindow">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Destinatarios</h3>
    </div>
    <div class="modal-body">
        <?php if (isset($this->data)) { ?>        
            <table class="table table-striped table-bordered small">
                <tr>
                    <th>&nbsp;</th>
                    <th>RFC/TAX ID</th>
                    <th>Nombre</th>
                </tr>
                <?php foreach ($this->data as $item) { ?>
                    <tr>
                        <td>&nbsp;</td>
                        <td><?= $item["rfc"] ?></td>
                        <td><?= $item["razon_soc"] ?></td>
                    </tr>
                <?php } ?>
            </table>
        <?php } else { ?>
            <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h4>Advertancia!</h4>
                El cliente no tiene destinatarios.
            </div>
        <?php } ?>
    </div>
    <div class="modal-footer">
        <?php if ($this->facturas) { ?>
            <a id="selectallinvoices" class="btn btn-info" style="float: left"><i class="icon-white icon-check"></i>&nbsp;Seleccionar todas</a>
            <a id="invoices" class="btn btn-primary">Seleccionar facturas</a>
        <?php } ?>
        <a href="/vucem/catalogo/agregar-destinatario?search=<?= $this->search ?>" class="btn btn-success">Agregar destinatario</a>
        <a id="closeModal" class="btn btn-danger" data-dismiss="modal">Cerrar</a>
    </div>
</div>