<style>
    .row {
        font-size: 14px;
    }
</style>
<input type="hidden" id="id" name="id" value="<?= $this->row['id'] ?>" />
<div class="row">
    <div class="col"><strong>REFERENCIA:</strong> <?= $this->row['referencia'] ?></div>
    <div class="col"><strong>RFC:</strong> <?= $this->row['rfcCliente'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>CLIENTE:</strong> <?= $this->row['nombreCliente'] ?></div>
    <div class="w-100"></div>
    <br>
    <div class="col ml-1">
        <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
            <a href="/mobile/bodega/entrada?id=<?= $this->row['id'] ?>" class="btn btn-secondary">Básico</a>
            <a href="/mobile/bodega/archivos?id=<?= $this->row['id'] ?>" class="btn btn-secondary">Archivos</a>
            <a href="/mobile/bodega/fotos?id=<?= $this->row['id'] ?>" class="btn btn-secondary">Fotos</a>
            <a href="/mobile/bodega/comentarios?id=<?= $this->row['id'] ?>" class="btn btn-primary active">Comentarios</a>
            <a href="/mobile/bodega/bitacora?id=<?= $this->row['id'] ?>" class="btn btn-secondary">Bitacora</a>
        </div>
        <br><br>
    </div>
    <div class="w-100"></div>
    <div class="col">
        <table class="table table-sm table-striped facturas">
            <thead>
                <tr>
                    <th>USUARIO</th>
                    <th>COMENTARIO</th>
                    <th>FECHA</th>
                </tr>
            </thead>
            <tbody>
                <?php if (!empty($this->comments['comentarios'])) { ?>
                    <?php foreach ($this->comments['comentarios'] as $item) { ?>
                        <tr>
                            <td><?= $item['nombre'] ?></td>
                            <td><?= $item['mensaje'] ?></td>
                            <td><?= date("d/m/Y", strtotime($item['creado'])) ?></td>
                        </tr>
                    <?php } ?>
                <?php } else { ?>
                    <tr>
                        <td colspan="3"><em>No hay comentarios</em></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <div class="w-100"></div>
</div>

<a href="javascript:window.history.back();" class="btn btn-sm btn-secondary ml-1">
    <i class="fas fa-angle-left"></i> Regresar</a>
