<style>
    .row {
        font-size: 14px;
    }

    .inputfile {
        width: 0.1px;
        height: 0.1px;
        opacity: 0;
        overflow: hidden;
        position: absolute;
        z-index: -1;
    }
</style>
<div class="row">
    <div class="col">
        <div id="reader" width="600px"></div>
    </div>
</div>

<a href="/mobile/bodega/escanear?id=<?= $this->row['idTrafico'] ?>" class="btn btn-sm btn-secondary ml-1 mt-2">
    <i class="fas fa-angle-left"></i> Regresar</a>