<style>
    .row {
        font-size: 14px;
    }
</style>
<input type="hidden" id="id" name="id" value="<?= $this->row['id'] ?>" />
<div class="row">
    <div class="col"><strong>REFERENCIA:</strong> <?= $this->row['referencia'] ?></div>
    <div class="col"><strong>RFC:</strong> <?= $this->row['rfcCliente'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>CLIENTE:</strong> <?= $this->row['nombreCliente'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>BULTOS:</strong> <?= $this->row['bultos'] ?></div>
    <div class="col"><strong>IMP/EXP:</strong> <?= ($this->row["ie"] == 'TOCE.IMP') ? '<i class="fas fa-arrow-circle-down" style="color: #2f3b58"></i>' : '<i class="fas fa-arrow-circle-up" style="color: #2f3b58"></i>' ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>CANDADOS:</strong> <?= $this->row['candados'] ?></div>
    <div class="col"><strong>PLACAS:</strong> <?= $this->row['contenedorCaja'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>LÍNEA:</strong> <?= $this->row['lineaTransporte'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>PROVEEDOR:</strong> <?= $this->row['proveedores'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>UBICACIÓN:</strong> <?= $this->row['ubicacion'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>PESO KG:</strong> <?= $this->row['pesoKg'] ?></div>
    <div class="col"><strong>PESO LBS:</strong> <?= $this->row['pesoLbs'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>CAJA ENTRADA:</strong> <?= $this->row['contenedorCajaEntrada'] ?></div>
    <div class="col"><strong>CAJA SALIDA:</strong> <?= $this->row['contenedorCajaSalida'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>USUARIO:</strong> <?= mb_strtoupper($this->row['nombre']) ?><br><br></div>
    <div class="w-100"></div>
    <div class="col">
        <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
            <a href="/mobile/traficos/trafico?id=<?= $this->row['id'] ?>" class="btn btn-primary active">Básico</a>
            <a href="/mobile/traficos/archivos?id=<?= $this->row['id'] ?>" class="btn btn-secondary">Archivos</a>
            <a href="/mobile/traficos/fotos?id=<?= $this->row['id'] ?>" class="btn btn-secondary">Fotos</a>
            <a href="/mobile/traficos/comentarios?id=<?= $this->row['id'] ?>" class="btn btn-secondary">Comentarios</a>
            <a href="/mobile/traficos/bitacora?id=<?= $this->row['id'] ?>" class="btn btn-secondary">Bitacora</a>
        </div>
        <br><br>
    </div>
    <div class="w-100"></div>
    <div class="col">
        <table class="table table-sm table-striped facturas">
            <thead>
                <tr class="table-active">
                    <th colspan="3" class="">
                        FACTURAS <a href="/mobile/traficos/agregar-factura?id=<?= $this->row['id'] ?>"><i class="fas fa-plus-square float-right" style="font-size: 20px"></i></a>
                    </th>
                </tr>
                <tr>
                    <th>Num. Factura</th>
                    <th>COVE</th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <div class="w-100"></div>
    <div class="col">
        <table class="table table-sm table-striped guias">
            <thead>
                <tr class="table-active">
                    <th colspan="3" class="">
                        BULTOS  <a href="/mobile/bodega/agregar-bulto?id=<?= $this->row['id'] ?>"><i class="fas fa-plus-square float-right" style="font-size: 20px"></i></a>
                    </th>
                </tr>
                <tr>
                    <th>BULTO</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
        <form id="form-packages" method="post" enctype="multipart/form-data">
            <input type="hidden" id="id" name="id" value="<?= $this->row['id'] ?>" />
            <label for="camera" class="btn btn-success">
                <i class="fas fa-qrcode"></i> Escanear
            </label>
            <input type="file" accept="image/*" capture="camera" id="camera" class="inputfile">
        </form>
        <!--<img id="frame" src="/mobile/20190829_182013.png" style="width: 80%">-->
        <img id="frame" class="img-fluid">
        <canvas id="canvas" width="1024" class="img-fluid" style="display: none"></canvas>
<!--        <br>
        <button id="qr" class="btn btn-success" onclick="analizarCodigo()">
            <i class="fas fa-qrcode"></i> Escanear
        </button>
        <br><br>-->
        <script>
            var camera = document.getElementById('camera');
            var frame = document.getElementById('frame');
            
            var canvas = document.getElementById("canvas");
            var ctx = canvas.getContext("2d");
            var img = new Image();
            
            img.onload = function () {
                // set size proportional to image
                canvas.height = canvas.width * (img.height / img.width);

                // step 1 - resize to 50%
                var oc = document.createElement('canvas'),
                    octx = oc.getContext('2d');

                oc.width = img.width * 0.5;
                oc.height = img.height * 0.5;
                octx.drawImage(img, 0, 0, oc.width, oc.height);

                // step 2
                octx.drawImage(oc, 0, 0, oc.width * 0.5, oc.height * 0.5);

                // step 3, resize to final size
                ctx.drawImage(oc, 0, 0, oc.width * 0.5, oc.height * 0.5,
                0, 0, canvas.width, canvas.height);
                
                var dataurl = canvas.toDataURL("image/png");
                document.getElementById('frame').src = dataurl;
            };

            camera.addEventListener('change', function (e) {
                var file = e.target.files[0]; 
                frame.src = URL.createObjectURL(file);
                img.src = URL.createObjectURL(file);
                
                analizarCodigo();                
            });
            
            function mostrarQr(obj) {
                alert(obj.uuid);
            }

        </script>
        <script type="text/javascript" src="https://unpkg.com/@zxing/library@latest"></script>
        <script type="text/javascript">
            async function analizarCodigo() {

                const codeReader = new ZXing.BrowserQRCodeReader();
                const img = document.getElementById('frame');

                try {
                    const result = await codeReader.decodeFromImage(img);
                    //console.log(result);
                    //console.log(JSON.parse(result));
                    var obj = JSON.parse(result);
                    mostrarQr(obj);
                    
                } catch (err) {
                    console.error(err);
                }
            }
        </script>
    </div>
</div>
<style>
    .inputfile {
        width: 0.1px;
        height: 0.1px;
        opacity: 0;
        overflow: hidden;
        position: absolute;
        z-index: -1;
    }
</style>

<a href="javascript:window.history.back();" class="btn btn-sm btn-secondary"><i class="fas fa-angle-left"></i> Regresar</a>
