<style>
    .row {
        font-size: 14px;
    }
</style>
<input type="hidden" id="id" name="id" value="<?= $this->row['id'] ?>" />
<input type="hidden" id="estatus" name="estatus" value="<?= $this->estatus ?>" />
<div class="row">
    <div class="col"><strong>REFERENCIA:</strong> <?= $this->row['referencia'] ?></div>
    <div class="col"><strong>RFC:</strong> <?= $this->row['rfcCliente'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>CLIENTE:</strong> <?= $this->row['nombreCliente'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>BULTOS:</strong> <?= $this->row['bultos'] ?></div>
    <div class="col"><strong>PLACAS:</strong> <?= $this->row['contenedorCaja'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>CANDADOS:</strong> <?= $this->row['candados'] ?></div>
    <div class="col"><strong>UBICACIÓN:</strong> <?= $this->row['ubicacion'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>LÍNEA:</strong> <?= $this->row['lineaTransporte'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>PROVEEDOR:</strong> <?= $this->row['proveedores'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>PESO KG:</strong> <?= $this->row['pesoKg'] ?></div>
    <div class="col"><strong>PESO LBS:</strong> <?= $this->row['pesoLbs'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>CAJA ENTRADA:</strong> <?= $this->row['contenedorCajaEntrada'] ?></div>
    <div class="col"><strong>CAJA SALIDA:</strong> <?= $this->row['contenedorCajaSalida'] ?></div>
    <div class="w-100"></div>
    <br>
    <div class="col ml-1">
        <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
            <a href="/mobile/bodega/entrada?id=<?= $this->row['id'] ?>&estatus=<?= $this->estatus ?>" class="btn btn-primary active">Básico</a>
            <a href="/mobile/bodega/archivos?id=<?= $this->row['id'] ?>&estatus=<?= $this->estatus ?>" class="btn btn-secondary">Archivos</a>
            <a href="/mobile/bodega/fotos?id=<?= $this->row['id'] ?>&estatus=<?= $this->estatus ?>" class="btn btn-secondary">Fotos</a>
            <a href="/mobile/bodega/comentarios?id=<?= $this->row['id'] ?>&estatus=<?= $this->estatus ?>" class="btn btn-secondary">Comentarios</a>
            <a href="/mobile/bodega/bitacora?id=<?= $this->row['id'] ?>&estatus=<?= $this->estatus ?>" class="btn btn-secondary">Bitacora</a>
        </div>
        <br><br>
    </div>
    <div class="w-100"></div>
    <div class="col">
        <table class="table table-sm table-striped facturas">
            <thead>
                <tr class="table-active">
                    <th colspan="3" class="">
                        FACTURAS <a href="/mobile/bodega/agregar-factura?id=<?= $this->row['id'] ?>&estatus=<?= $this->estatus ?>"><i class="fas fa-plus-square float-right" style="font-size: 20px"></i></a>
                    </th>
                </tr>
                <tr>
                    <th>Num. Factura</th>
                    <th>COVE</th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <div class="w-100"></div>
    <div class="col">
        <table class="table table-sm table-striped guias">
            <thead>
                <tr class="table-active">
                    <th colspan="3" class="">
                        BULTOS <a href="/mobile/bodega/agregar-bulto?id=<?= $this->row['id'] ?>&estatus=<?= $this->estatus ?>"><i class="fas fa-plus-square float-right" style="font-size: 20px"></i></a>
                    </th>
                </tr>
                <tr>
                    <th>BULTO</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
<style>
    .inputfile {
        width: 0.1px;
        height: 0.1px;
        opacity: 0;
        overflow: hidden;
        position: absolute;
        z-index: -1;
    }
</style>

<a href="/mobile/bodega" class="btn btn-sm btn-info ml-1">
    <i class="fas fa-angle-left"></i> Regresar</a>

<a href="/mobile/bodega/escanear?id=<?= $this->row['id'] ?>&estatus=<?= $this->estatus ?>" class="btn btn-sm btn-success mr-1 float-right">
    <i class="fas fa-qrcode"></i> Escanear</a>