<style>
    .row {
        font-size: 14px;
    }
</style>
<input type="hidden" id="id" name="id" value="<?= $this->row['id'] ?>" />
<div class="row">
    <div class="col"><strong>REFERENCIA:</strong> <?= $this->row['referencia'] ?></div>
    <div class="col"><strong>RFC:</strong> <?= $this->row['rfcCliente'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>CLIENTE:</strong> <?= $this->row['nombreCliente'] ?></div>
    <div class="w-100"></div>
    <br>
    <div class="col ml-1">
        <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
            <a href="/mobile/bodega/entrada?id=<?= $this->row['id'] ?>" class="btn btn-secondary">Básico</a>
            <a href="/mobile/bodega/archivos?id=<?= $this->row['id'] ?>" class="btn btn-secondary">Archivos</a>
            <a href="/mobile/bodega/fotos?id=<?= $this->row['id'] ?>" class="btn btn-primary active">Fotos</a>
            <a href="/mobile/bodega/comentarios?id=<?= $this->row['id'] ?>" class="btn btn-secondary">Comentarios</a>
            <a href="/mobile/bodega/bitacora?id=<?= $this->row['id'] ?>" class="btn btn-secondary">Bitacora</a>
        </div>
        <br><br>
    </div>
    <div class="w-100"></div>
    <div class="col">
        <form id="form-photos" method="post" action="/mobile/post/subir-fotos-bodega" enctype="multipart/form-data">
            <input type="hidden" id="id" name="id" value="<?= $this->row['id'] ?>" />
            <input type="hidden" id="referencia" name="referencia" value="<?= $this->row['referencia'] ?>" />
            <input type="hidden" id="rfcCliente" name="rfcCliente" value="<?= $this->row['rfcCliente'] ?>" />
            <input type="hidden" id="idBodega" name="idBodega" value="<?= $this->row['idBodega'] ?>" />
            <input type="file" name="photos[]" id="photos" accept="image/*" class="ml-2">
            <button type="submit" id="upload" class="btn btn-sm btn-success mr-2 float-right">
                Subir
            </button>
        </form>
        <br>
        <br>
    </div>
    <div class="w-100"></div>
    <div class="col">
        <table class="table table-sm table-striped photos">
            <thead>
                <tr>
                    <th>NOMBRE</th>
                </tr>
            </thead>
            <tbody>
                <?php if (!empty($this->gallery)) { ?>
                    <?php foreach ($this->gallery as $item) { ?>
                        <tr>
                            <td colspan="2">

                                <a title="Trafico Image <?= $item["id"] ?>" class="image-link traffic-thumb" href="/mobile/get/read-image?id=<?= $item["id"] ?>&time=<?= microtime() ?>" data-id="<?= $item["id"] ?>">
                                    <?php if (isset($item['miniatura']) && file_exists($item["carpeta"] . DIRECTORY_SEPARATOR . $item["imagen"])) { ?>
                                        <img class="view-photo" src="/mobile/get/read-thumbnail?id=<?= $item["id"] ?>&time=<?= microtime() ?>">
                                    <?php } else { ?>
                                        <img class="view-photo" src="/images/not_available.gif" width="150px">
                                    <?php } ?>
                                </a>

                            </td>
                        </tr>
                    <?php } ?>
                <?php } else { ?>
                    <tr>
                        <td colspan="2"><em>No hay fotos cargadas</em></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<a href="javascript:window.history.back();" class="btn btn-sm btn-secondary ml-1">
    <i class="fas fa-angle-left"></i> Regresar</a>