<style>
    .card .card-header button,
    table td {
        font-size: 1.5rem;
    }
</style>

<form class="form-inline" style="margin-top: 5px" action="/mobile/bodega">
    <div class="form-group mx-sm-3 mb-2">
        <label for="search" class="sr-only">Buscar</label>
        <input type="text" class="form-control" id="search" name="search" placeholder="Buscar referencia" value="<?= $this->search ?>">
    </div>
    <button type="submit" class="btn btn-primary mb-2 float-right">Buscar</button>
</form>

<div id="accordion">
    <div class="card">
        <div class="card-header" id="headingOne">
            <h5 class="mb-0">
                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    DESCARGA
                </button>
            </h5>
        </div>

        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body" style="padding: 0;">

                <table class="table table-sm table-striped">
                    <tbody>
                        <?php if (isset($this->paginator)) { ?>
                            <?php foreach ($this->paginator as $item) { ?>
                                <tr>
                                    <td>
                                        <a href="/mobile/bodega/entrada?id=<?= $item['id'] ?>"><?= $item["referencia"] ?></a>
                                    </td>
                                    <td>
                                        <a href="/mobile/bodega/entrada?id=<?= $item['id'] ?>"><i class="fas fa-pencil-alt"></i></a>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>

    </div>

    <div class="card">
        <div class="card-header" id="headingTwo">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    REVISIÓN
                </button>
            </h5>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body">
                
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header" id="headingThree">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    CARGA
                </button>
            </h5>
        </div>
        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
            <div class="card-body">
                
            </div>
        </div>
    </div>

</div>