<form method="post" id="form">
    <?php if(isset($this->id)) { ?>
        <input type="hidden" id="id" name="id" value="<?= $this->id ?>" />
    <?php } ?>    
    <table class="traffic-table traffic-table-left">
        <tr>
            <td style="width: 80px">
                <label for="patente">Patente:</label>
            </td>
            <td>
                <?= $this->form->patente ?>
            </td>
        </tr>
        <tr>
            <td><label for="rfc">RFC:</label></td>
            <td><?= $this->form->rfc ?></td>
        </tr>
        <tr>
            <td><label for="nombre">Nombre:</label></td>
            <td><?= $this->form->nombre ?></td>
        </tr>
        <tr>
            <td colspan="6"><div id="errors"></div></td>
        </tr>
    </table>
</form>
<div class="traffic-clear-5"></div>
<?php if(!isset($this->id)) { ?>
    <button class="traffic-btn traffic-btn-right" id="submit" tabindex="99">
        <i class="far fa-save"></i> Guardar
    </button>
<?php } else { ?>
    <button class="traffic-btn traffic-btn-right" id="update" tabindex="99">
        <i class="far fa-save"></i> Guardar
    </button>
<?php } ?>
<a class="traffic-btn" onclick="window.history.back();">
    <i class="fas fa-angle-double-left"></i> Regresar
</a>
<div class="traffic-clear-5"></div>