<fieldset>
    <legend>Editar operación: Patente <b><?= $this->patente ?></b> Aduana <b><?= $this->aduana ?></b></legend>
    <?= $this->form ?>    
</fieldset>
<script>    
    $("#bootstrap-fechanotif").datepicker({
        format: 'yyyy-mm-dd'
    });
    $("#bootstrap-fechadoc").datepicker({
        format: 'yyyy-mm-dd'
    });
    $("#bootstrap-fecharevalidacion").datepicker({
        format: 'yyyy-mm-dd'
    });
    $("#bootstrap-fechaarribo").datepicker({
        format: 'yyyy-mm-dd'
    });
    $("#bootstrap-fecharecepanti").datepicker({
        format: 'yyyy-mm-dd'
    });
    $("#bootstrap-fechaprevio").datepicker({
        format: 'yyyy-mm-dd'
    });
    $("#bootstrap-fechappedimento").datepicker({
        format: 'yyyy-mm-dd'
    });
    $("#bootstrap-fechaeir").datepicker({
        format: 'yyyy-mm-dd'
    });
    $("#bootstrap-fechaexp").datepicker({
        format: 'yyyy-mm-dd'
    });
    $("#bootstrap-fechaenvio").datepicker({
        format: 'yyyy-mm-dd'
    });
</script>