<form id="form">
    <table class="traffic-table traffic-table-left">
        <thead>
            <tr>
                <th style="width: 120px">Patente</th>
                <th style="width: 120px">Aduana</th>
                <th style="width: 120px">Referencia</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <input class="traffic-input-small" type="text" />
                </td>
                <td>
                    <input class="traffic-input-small" type="text" />
                </td>
                <td>
                    <input class="traffic-input-small" type="text" />
                </td>
                <td>
                    <button type="submit" id="submit" class="traffic-btn">
                        Buscar
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</form>