<div class="traffic-cols">
    <form method="post" action="/trafico/ajax/editar-cliente" id="form">
        <?= $this->form->id ?>
        <table class="traffic-table traffic-table-left">
            <tr>
                <th style="text-align: right; width: 150px">Empresa:</th>
                <td colspan="3">
                    <select id="idEmpresa" name="idEmpresa" class="traffic-select-large">
                        <option value="">---</option>
                        <?php if (isset($this->empresas)) { ?>
                            <?php foreach ($this->empresas as $item) { ?>
                                <?php if ($this->idEmpresa == $item["id"]) { ?>
                                    <option value="<?= $item["id"] ?>" selected="selected"><?= $item["razonSocial"] ?></option>
                                <?php } else { ?>
                                    <option value="<?= $item["id"] ?>"><?= $item["razonSocial"] ?></option>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>
                    </select>
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 150px">RFC:</th>
                <td class="traffic-td-left"><?= $this->form->rfc ?></td>
            </tr>
            <tr>
                <th style="text-align: right">Nombre:</th>
                <td class="traffic-td-left"><?= $this->form->nombre ?></td>
            </tr>
            <tr>
                <th style="text-align: right">RFC de sociedad:</th>
                <td class="traffic-td-left"><?= $this->form->rfcSociedad ?></td>
            </tr>
        </table>
        <div class="traffic-clear-5"></div>
        <button class="traffic-btn-add traffic-btn-right" id="submit" tabindex="4">Guardar</button>
        <a class="traffic-btn traffic-btn-back" onclick="window.history.back();" tabindex="99">&Lt;&nbsp;Regresar</a>
        <div class="traffic-clear-5"></div>
    </form>
</div>