<form method="post" action="/trafico/ajax/nueva-oficina" id="form">
    <?php if(isset($this->id)) { ?>
        <input type="hidden" id="id" name="id" value="<?= $this->id ?>" />
    <?php } ?>
    <table class="traffic-table traffic-table-left">
        <tr>
            <td style="width: 150px">
                <label for="patente">Patente:</label>
            </td>
            <td style="width: 350px">
                <?= $this->form->patente ?>
            </td>
            <td rowspan="5">
                <button class="button-group" id="addAgent" title="Agregar agente aduanal." style="float: left"></button>                
            </td>
        </tr>            
        <tr>
            <td><label for="aduana">Aduana:</label></td>
            <td><?= $this->form->aduana ?></td>
        </tr>
        <tr>
            <td><label for="tipoAduana">Tipo de Aduana:</label></td>
            <td><?= $this->form->tipoAduana ?></td>
        </tr>
        <tr>
            <td><label for="corresponsal">Corresponsal:</label></td>
            <td><?= $this->form->corresponsal ?></td>
        </tr>
        <tr>
            <td><label for="nombre">Nombre:</label></td>
            <td><?= $this->form->nombre ?></td>
        </tr>
        <tr>
            <td colspan="6"><div id="errors"></div></td>
        </tr>
    </table>
</form>
<div class="traffic-clear-5"></div>
<button class="traffic-btn traffic-btn-right" id="submit">
    <i class="far fa-save"></i> Agregar</button>
<a class="traffic-btn" onclick="window.history.back();">
    <i class="fas fa-angle-double-left"></i> Regresar</a>
<div class="traffic-clear-5"></div>