<?php if (!isset($this->error) && isset($this->form)) { ?>
    <?php if (isset($this->form)) { ?>
        <form method="post" action="<?= $this->url ?>" id="form-requests">
            <table class="traffic-table traffic-table-left">
                <tr>
                    <th colspan="4" class="invoice-title">NUEVA SOLICITUD DE ANTICIPO</th>                    
                </tr>
                <tr>
                    <th style="text-align: left; width: 250px"><label for="aduana">ADUANA:</label></th>
                    <th colspan="3" style="text-align: left"><label for="cliente">CLIENTE:</label></th>
                </tr>
                <tr>
                    <td class="traffic-td-left"><div id="divcustoms"><?= $this->form->aduana ?></div></td>
                    <td colspan="3" class="traffic-td-left"><div id="divcustomers"><?= $this->form->cliente ?></div></td>
                </tr>
                <tr>
                    <th style="text-align: left"><label for="operacion">TIPO OPERACIÓN:</label></th>
                    <th style="text-align: left; width: 120px"><label for="pedimento">PEDIMENTO:</label></th>
                    <th style="text-align: left"><label for="referencia">REFERENCIA:</label></th>
                    <th>&nbsp;</th>
                </tr>
                <tr>
                    <td class="traffic-td-left"><div id="divops"><?= $this->form->operacion ?></div></td>
                    <td><?= $this->form->pedimento ?></td>
                    <td><?= $this->form->referencia ?></td>
                    <td><div class="control-group"><button id="add-request" class="traffic-btn traffic-btn-right">Agregar</button></div></td>
                </tr>
            </table>
        </form>
        <iframe src="/trafico/data/mis-solicitudes" id="requests-frame" width="100%" style=""></iframe>
        <div class="traffic-clear-5"></div>
    <?php } ?>
    <a href="/trafico/index/ultimas-solicitudes" class="traffic-btn">&Lt; Regresar</a>    
    <div class="traffic-clear-5"></div>
<?php } else { ?>
    <h3 style="margin-left: 5px; line-height: 20px; margin-top: 20px">ERROR 505<br><span style="font-size: 16px"><?= $this->error ?></span></h3>
<?php } ?>