<div class="row-fluid">
    <div id="mm" class="easyui-menu" data-options="onClick:menuHandler" style="width: 220px;">
        <div data-options="name:'open'">Abrir</div>
        <div data-options="name:'soia'">Estatus SOIA</div>
        <div data-options="name:'documents'">Documentos completos</div>
        <div data-options="name:'cancel'">Cancelar Operación</div>
        <div data-options="name:'justification'">Justificar</div>
        <div data-options="name:'delete'">Eliminar</div>
        <div class="menu-sep"></div>
        <div data-options="name:'status', status: 1, iconCls:'icon-status-1'">Programado</div>
        <div data-options="name:'status', status: 7, iconCls:'icon-status-7'">En captura</div>
        <div data-options="name:'status', status: 5, iconCls:'icon-status-5'">Proforma</div>
        <div data-options="name:'status', status: 2, iconCls:'icon-status-2'">Pagado</div>
        <div data-options="name:'status', status: 3, iconCls:'icon-status-3'">Liberado</div>
        <div data-options="name:'status', status: 8, iconCls:'icon-status-8'">Urgente</div>
        <div class="menu-sep"></div>
        <div>Salir</div>
    </div>

    <div style="float: left; margin-left: 2px"> 
        <img style="float: left" src="/images/menus/traffic.png" />
        <h5 style="float: left; margin-left: 5px" style="margin: 0;">TRÁFICOS</h5>
    </div>
    <div class="semaphoreBox">
        <div class="semaphore-holder">
            <div class="semaphore-black"></div><span>Programado</span>
        </div>
        <div class="semaphore-holder">
            <div class="semaphore-pink"></div><span>En captura</span>
        </div>
        <div class="semaphore-holder">
            <div class="semaphore-yellow"></div><span>Proforma</span>
        </div>
        <div class="semaphore-holder">
            <div class="semaphore-blue"></div><span>Pagado</span>
        </div>
        <div class="semaphore-holder">
            <div class="semaphore-green"></div><span>Liberado</span>
        </div>
        <div class="semaphore-holder">
            <div class="semaphore-red"></div><span>Urgente</span>
        </div>
        <div class="semaphore-holder">
            <i class="fas fa-arrow-circle-down" style="color: #2f3b58"></i><span style="padding-left: 3px">Importación</span>
        </div>
        <div class="semaphore-holder">
            <i class="fas fa-arrow-circle-up" style="color: #2e963a"></i><span style="padding-left: 3px">Exportación</span>
        </div>
    </div>
    <div class="semaphoreBox">
        <i class="fas fa-archive" style="color: #c1c1c1"><span style="color: #555; font-family: sans-serif; font-weight: normal">&nbsp;Sin checklist</span></i>
        <i class="fas fa-archive" style="color: green"><span style="color: #555; font-family: sans-serif; font-weight: normal">&nbsp;Expediente completo</span></i>
        <i class="fas fa-archive" style="color: #0099ff"><span style="color: #555; font-family: sans-serif; font-weight: normal">&nbsp;Rev. Admon.</span></i>
        <i class="fas fa-archive" style="color: #F59211"><span style="color: #555; font-family: sans-serif; font-weight: normal">&nbsp;Rev. Ope.</span></i>
    </div>
    <div id="dlg" class="easyui-dialog" style="width:600px"
         closed="true" buttons="#dlg-buttons">
        <form id="fm" method="post" novalidate style="margin:0;padding:20px 50px">
            <div style="margin-bottom:20px;font-size:14px;border-bottom:1px solid #ccc">Nuevo trafico</div>
            <div style="margin-bottom:10px">
                <input name="pedimento" class="easyui-textbox" required="true" label="Pedimento:" style="width:170px">
            </div>
            <div style="margin-bottom:10px">
                <input name="referencia" class="easyui-textbox" required="true" label="Referencia:" style="width:170px">
            </div>
            <div style="margin-bottom:10px">
                <input name="rfcCliente" class="easyui-combobox" required="true" label="Cliente:" style="width:100%" data-options="
                       valueField:'rfc',
                       textField:'nombre',
                       method:'post',
                       url:'/trafico/crud/obtener-clientes'">
            </div>
        </form>
    </div>
    <div id="dlg-buttons">
        <a href="javascript:void(0)" class="easyui-linkbutton c6" iconCls="icon-ok" onclick="saveUser()" style="width:90px">Guardar</a>
        <a href="javascript:void(0)" class="easyui-linkbutton" onclick="javascript:$('#dlg').dialog('close')" style="width:90px">Cancelar</a>
    </div>
    <table id="dg" style="width:100%;height:630px"></table>
    <div class="traffic-clear-10"></div>
    <a href="/trafico/index/crear-trafico" class="traffic-btn traffic-btn-right">
        <i class="fas fa-file"></i> Nuevo tráfico
    </a>
    <button class="traffic-btn traffic-btn-right" id="traficosLiberados">
        Trafico del día (liberados)
    </button>
    <button class="traffic-btn traffic-btn-right" id="traficosAperturados">
        Trafico del día
    </button>
    <button class="traffic-btn traffic-btn-right" id="inventario">
        Inventario del día
    </button>
</div>
<div class="row-fluid-mobile">
    
</div>
