<div id="mm" class="easyui-menu" style="width: 220px;">
    <div onclick="javascript:openTraffic()">Abrir</div>
    <div onclick="javascript:updateSitawin()">Actualizar desde SITAWIN</div>
    <div onclick="javascript:documentsComplete()">Documentos completos</div>
    <div onclick="javascript:justification()">Justificar</div>
    <div onclick="javascript:deleteTraffic()">Eliminar</div>
    <div class="menu-sep"></div>
    <div>Salir</div>
</div>
<div style="float: left; margin-left: 2px"> 
    <img style="float: left" src="/images/menus/plane.png" />
    <h5 style="float: left; margin-left: 5px" style="margin: 0;">TRÁFICO AÉREO</h5>
</div>
<div class="semaphoreBox">
    <div class="semaphore-holder">
        <div class="semaphore-black"></div><span>Programado</span>
    </div>
    <div class="semaphore-holder">
        <div class="semaphore-pink"></div><span>En captura</span>
    </div>
    <div class="semaphore-holder">
        <div class="semaphore-yellow"></div><span>Proforma</span>
    </div>
    <div class="semaphore-holder">
        <div class="semaphore-blue"></div><span>Pagado</span>
    </div>
    <div class="semaphore-holder">
        <div class="semaphore-green"></div><span>Liberado</span>
    </div>
    <div class="semaphore-holder">
        <div class="semaphore-red"></div><span>Urgente</span>
    </div>
    <div class="semaphore-holder">
        <i class="fas fa-arrow-circle-down" style="color: #2f3b58"></i><span style="padding-left: 3px">Importación</span>
    </div>
    <div class="semaphore-holder">
        <i class="fas fa-arrow-circle-up" style="color: #2e963a"></i><span style="padding-left: 3px">Exportación</span>
    </div>
</div>
<div class="semaphoreBox">
    <i class="fas fa-archive" style="color: #c1c1c1"><span style="color: #555; font-family: sans-serif; font-weight: normal">&nbsp;Sin checklist</span></i>
    <i class="fas fa-archive" style="color: green"><span style="color: #555; font-family: sans-serif; font-weight: normal">&nbsp;Expediente completo</span></i>
    <i class="fas fa-archive" style="color: #0099ff"><span style="color: #555; font-family: sans-serif; font-weight: normal">&nbsp;Rev. Admon.</span></i>
    <i class="fas fa-archive" style="color: #F59211"><span style="color: #555; font-family: sans-serif; font-weight: normal">&nbsp;Rev. Ope.</span></i>
</div>
<div id="dlg" class="easyui-dialog" style="width:600px"
        closed="true" buttons="#dlg-buttons">
    <form id="fm" method="post" novalidate style="margin:0;padding:20px 50px">
        <div style="margin-bottom:20px;font-size:14px;border-bottom:1px solid #ccc">Nuevo trafico</div>
        <div style="margin-bottom:10px">
            <input name="pedimento" class="easyui-textbox" required="true" label="Pedimento:" style="width:170px">
        </div>
        <div style="margin-bottom:10px">
            <input name="referencia" class="easyui-textbox" required="true" label="Referencia:" style="width:170px">
        </div>
        <div style="margin-bottom:10px">
            <input name="rfcCliente" class="easyui-combobox" required="true" label="Cliente:" style="width:100%" data-options="
                valueField:'rfc',
                textField:'nombre',
                method:'post',
                url:'/trafico/crud/obtener-clientes'">
        </div>
    </form>
</div>
<div id="dlg-buttons">
    <a href="javascript:void(0)" class="easyui-linkbutton c6" iconCls="icon-ok" onclick="saveUser()" style="width:90px">Guardar</a>
    <a href="javascript:void(0)" class="easyui-linkbutton" onclick="javascript:$('#dlg').dialog('close')" style="width:90px">Cancelar</a>
</div>
<table id="dg" style="width:100%;height:630px"></table>
<div class="traffic-clear-10"></div>
<a href="javascript:void(0)" onclick="javascript:window.history.back();" class="traffic-btn" tabindex="99"> 
    <i class="fas fa-angle-double-left"></i> Regresar
</a>
<a href="/trafico/index/crear-trafico" class="traffic-btn traffic-btn-right">
    <i class="fas fa-file"></i> Nuevo tráfico
</a>
<button class="traffic-btn traffic-btn-right" id="traficosLiberados">
    <i class="fas fa-table"></i> Trafico del día
</button>