<?php if (isset($this->form)) { ?>
    <div class="traffic-clear-5"></div>
    <?php if (isset($this->edit) && $this->edit === true) { ?>
        <a target="_blank" class="traffic-btn traffic-btn-right" onclick="deleteRequest(<?= $this->data["header"]["id"] ?>);" id="deleteRequest">
            <i class="far fa-trash-alt"></i> Borrar
        </a>
    <?php } ?>
    <a target="_blank" href="/trafico/data/imprimir-solicitud?id=<?= $this->data["header"]["id"] ?>" class="traffic-btn traffic-btn-right">
        <i class="fas fa-print"></i> Imprimir
    </a>
    <a onclick="verSolicitud(<?= $this->data["header"]["id"] ?>)" class="traffic-btn traffic-btn-right">
        <i class="fas fa-eye"></i> Ver solicitud
    </a>
    <div class="traffic-clear-5"></div>
    <input type="hidden" name="rol" id="rol" value="<?= $this->rol ?>" >
    <?php if (isset($this->edit) && $this->edit === true) { ?>
        <table class="traffic-table">
            <tr>
                <th>PEDIMENTO</th>
                <th>REFERENCIA</th>
                <th>OPERACIÓN</th>
                <th>CLIENTE</th>
                <th>COMPLEMENTO</th>
            </tr>
            <tr>
                <td><?= $this->data["header"]["aduana"] . "-" . $this->data["header"]["patente"] . "-" . $this->data["header"]["pedimento"] ?></td>
                <td><?= $this->data["header"]["referencia"] ?></td>
                <td><?= $this->data["header"]["tipoOperacion"] ?></td>
                <td><?= $this->data["header"]["nombreCliente"] ?></td>
                <td><?= isset($this->data["header"]["complemento"]) ? 'S' : 'N' ?></td>
            </tr>        
        </table>
        <?php if (isset($this->form)) { ?>
            <form id="form-approved">
                <table class="traffic-table traffic-table-left">
                    <tr>
                        <th style="width: 300px"><label for="esquema">Esquema de fondos</label></th>
                        <td>
                            <?= $this->form->idSolicitud ?>
                            <?= $this->form->esquema ?>
                        </td>
                        <td style="width: 150px">
                            <?php if (isset($this->disabled)) { ?>
                                <button class="traffic-btn traffic-btn-right" id="add-complement">
                                    <i class="fas fa-plus-circle"></i> Complemento
                                </button>
                            <?php } else { ?>
                                <button class="traffic-btn traffic-btn-right" id="save-approved" <?= isset($this->disabled) ? 'disabled="disabled"' : '' ?>>
                                    <i class="far fa-save"></i> Guardar
                                </button>
                            <?php } ?>
                        </td>
                    </tr>
                    <tr>
                        <th><label for="proceso">Proceso actual</label></th>
                        <td>
                            <?= $this->form->proceso ?>
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                </table>
            </form>
        <?php } ?>
    <?php } else { ?>
        <div class="traffic-clear-5"></div>
        <form id="<?= $this->form->getAttrib("id") ?>" method="<?= $this->form->getMethod() ?>" action="<?= $this->form->getAction() ?>">
            <?= $this->form->idSolicitud ?>
            <table class="traffic-table">
                <tr>
                    <td>
                        <button class="traffic-btn traffic-btn-right" id="add-complement">
                            <i class="fas fa-plus-circle"></i> Complemento
                        </button>
                    </td>
                </tr>
            </table>
        </form>
    <?php } ?>
    <br>
    <form id="formFiles" method="post">
        <?= $this->form->idSolicitud ?>
        <input type="hidden" id="patente" name="patente" value="<?= $this->data["header"]["patente"] ?>" >
        <input type="hidden" id="aduana" name="aduana" value="<?= $this->data["header"]["aduana"] ?>" >
        <input type="hidden" id="pedimento" name="pedimento" value="<?= $this->data["header"]["pedimento"] ?>" >
        <input type="hidden" id="referencia" name="referencia" value="<?= $this->data["header"]["referencia"] ?>" >
        <table class="traffic-table traffic-table-left">
            <tr>
                <th style="width: 220px">Seleccionar archivo</th>
                <td>
                    <input type="file" name="file[]" id="file" class="required" multiple />
                </td>
                <td>
                    <button type="submit" id="uploadFiles" class="traffic-btn traffic-btn-right">
                        <i class="fas fa-upload"></i> Subir archivo
                    </button>
                </td>
            </tr>
        </table>
    </form>
    <div id="files"></div>
    <div style="width: 100%">
        <div style="float: left; width: 50%">
            <table class="traffic-table">
                <tr>
                    <th colspan="3">
                        BITACORA
                    </th>
                </tr>
                <tr>
                    <th style="text-align: left;">Evento</th>
                    <th style="text-align: left;">Fecha</th>
                    <th style="text-align: left;">Usuario</th>
                </tr>
                <?php if (isset($this->bitacora) && !empty($this->bitacora)) { ?>
                    <?php foreach ($this->bitacora as $item) { ?>
                        <tr>
                            <td style="text-align: left;"><?= $item["bitacora"] ?></td>
                            <td style="text-align: left;"><?= date("d/m/Y h:i a", strtotime($item["creado"])) ?></td>
                            <td style="text-align: left;"><?= strtoupper($item["usuario"]) ?></td>
                        </tr>
                    <?php } ?>        
                <?php } else { ?>        
                    <tr>
                        <td colspan="3" style="text-align: center;">
                            <em>No hay información en la bitacora</em>
                        </td>
                    </tr>
                <?php } ?>        
            </table>
        </div>
        <div style="float: left; width: 50%">
            <table class="traffic-table">
                <tr>
                    <th colspan="3">
                        COMENTARIOS
                    </th>
                </tr>
                <tr>
                    <th style="text-align: left;">Comentario</th>
                    <th style="text-align: left;">Fecha</th>
                    <th style="text-align: left;">Usuario</th>
                </tr>
                <?php if (isset($this->comentarios) && !empty($this->comentarios)) { ?>
                    <?php foreach ($this->comentarios as $item) { ?>
                        <tr>
                            <td style="text-align: left;"><?= strtoupper($item["comentario"]) ?></td>
                            <td style="text-align: left;"><?= date('d/m/Y h:i a', strtotime($item["creado"])) ?></td>
                            <td style="text-align: left;"><?= strtoupper($item["nombre"]) ?></td>
                        </tr>
                    <?php } ?>
                <?php } else { ?>        
                    <tr>
                        <td colspan="3" style="text-align: center;">
                            <em>No hay información en la bitacora</em>
                        </td>
                    </tr>
                <?php } ?>
                <tr>
                    <td style="text-align: left; vertical-align: top" colspan="3">
                        <form id="form-comments" method="post">
                            <input type="hidden" id="solicitud" name="solicitud" value="<?= $this->data["header"]["id"] ?>" >
                            <input type="hidden" id="pedimento" name="pedimento" value="<?= $this->data["header"]["pedimento"] ?>" >
                            <input type="hidden" id="referencia" name="referencia" value="<?= $this->data["header"]["referencia"] ?>" >
                            <label for="comments">Comentarios:</label>                                    
                            <textarea id="comments" name="comments" style="width: 300px; height: 80px"></textarea>
                            <button id="add-comment" class="traffic-btn traffic-btn-right">
                                <i class="fas fa-plus-circle"></i> Agregar
                            </button>
                        </form>
                    </td>
                </tr>
            </table>
        </div>
    </div>
<?php } else { ?>
    <div class="traffic-clear-5"></div>
    <div class="alert alert-danger">
        <strong>¡Advertencia!</strong> <?= isset($this->error) ? $this->error : 'La solicitud no existe.' ?>
    </div>
<?php } ?>
<div class="traffic-clear-5"></div>
<a href="/trafico/index/ultimas-solicitudes" class="traffic-btn">
    <i class="fas fa-angle-double-left"></i> Regresar
</a>
<div class="traffic-clear"></div>
<div class="jqmWindow" id="confirm" style="top: 15%">    
    <h4 class="traffic-h4">Cancelar solicitud de anticipo</h4>
    <form id="form-cancel" class="traffic-form" action="/trafico/ajax/borrar-solicitud" method="post">
        <?= $this->form->idSolicitud ?>
        <label for="comentario">Comentario:</label>
        <textarea id="comentario" name="comentario"></textarea>
    </form>
    <div class="traffic-clear-10"></div>
    <a id="saveRequest" class="traffic-btn traffic-btn-save traffic-btn-right">Guardar</a>
    <a id="closeModal" class="traffic-btn traffic-btn-close traffic-btn-right">Cerrar</a>
</div>
<div class="jqmWindow" id="modal">
    Please wait... <img src="/images/loader.gif" alt="loading" />
</div>