<div class="pagination pagination-small">
    <ul>
        <?php if (isset($this->previous)): ?>
        <li><a href="<?= $this->url(array('page' => $this->first,'fechaIni'=>$this->fechaIni,'fechaFin'=>$this->fechaFin)); ?>">«</a></li>
        <?php else: ?>
        <li class="disabled"><a>«</a></li>
        <?php endif; ?>
        
        <?php if (isset($this->previous)): ?>
        <li><a href="<?= $this->url(array('page' => $this->previous,'fechaIni'=>$this->fechaIni,'fechaFin'=>$this->fechaFin)); ?>">Ant.</a></li>
        <?php else: ?>
        <li class="disabled"><a>Ant.</a></li>
        <?php endif; ?>
        
        <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
        <li><a href="<?= $this->url(array('page' => $page,'fechaIni'=>$this->fechaIni,'fechaFin'=>$this->fechaFin)); ?>"><?= $page; ?></a></li>
        <?php else: ?>
        <li class="disabled"><a><?= $page; ?></a></li>
        <?php endif; ?>
        <?php endforeach; ?>
            
        <?php if (isset($this->next)): ?>
        <li><a href="<?= $this->url(array('page' => $this->next,'fechaIni'=>$this->fechaIni,'fechaFin'=>$this->fechaFin)); ?>">Sig.</a></li>
        <?php else: ?>
        <li class="disabled"><a>Sig.</a></li>
        <?php endif; ?>
        
        <?php if (isset($this->next)): ?>
        <li><a href="<?= $this->url(array('page' => $this->last,'fechaIni'=>$this->fechaIni,'fechaFin'=>$this->fechaFin)); ?>">»</a></li>
        <?php else: ?>
        <li class="disabled"><a>»</a></li>
        <?php endif; ?>
    </ul>
</div>