<form action="/archivo/index/cuentas-de-gasto" id="form" method="get">
    <table class="traffic-table traffic-table-left">
        <tr>
            <td><?= $this->form->rfc ?></td>
            <td><?= $this->form->fechaIni ?> <i class="far fa-calendar-alt" style="font-size: 1.2em"></i></td>
        </tr>
        <tr>
            <td style="width: 500px"><?= $this->form->nombre ?></td>
            <td><?= $this->form->fechaFin ?> <i class="far fa-calendar-alt" style="font-size: 1.2em"></i></td>
        </tr>
        <tr>
            <td colspan="2">
                <button class="traffic-btn traffic-btn-right" type="submit" id="submit"><i class="fas fa-search"></i> Buscar</button>
            </td>
        </tr>
    </table>
</form>
<div class="traffic-clear-5"></div>
<!--<ul id="download-links">
    <li style="font-family: sans-serif; font-size: 12px">
        Descargar este reporte en: &nbsp;<img src="/images/icons/email.png" />&nbsp;
        <a href="/archivo/index/enviar-email" data-toggle="modal">Adjuntar a email</a>&nbsp;
        <input type="checkbox" id="includepdf">&nbsp;Incluir PDF
    </li>
</ul>-->
<div style="margin-left: 5px">    
    <a class="traffic-btn" href="" id="downloadZip">
        <i class="fas fa-file-archive"></i> Descargar ZIP</a>
</div>

<table id="dg" style="width:100%;height:630px"></table>
