<div id="modalWindow">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Enviar E-Document</h3>
    </div>
    <div class="modal-body">
        <table class="table table-striped table-bordered table-hover small">
            <tr>
                <th>Patente</th>
                <td><?= $this->archivo["patente"] ?></td>
            </tr>
            <tr>
                <th>Aduana</th>
                <td><?= $this->archivo["aduana"] ?></td>
            </tr>
            <tr>
                <th>Pedimento</th>
                <td><?= $this->form->pedimento ?></td>
            </tr>
            <tr>
                <th>Nombre de archivo</th>
                <td><?= $this->archivo["nom_archivo"] ?></td>
            </tr>
            <tr>
                <th>Tipo de archivo</th>
                <td><?= $this->archivo["tipo_archivo"] ?></td>
            </tr>
<!--            <tr>
                <th>Ubicacion de archivo</th>
                <td><?= $this->archivo["ubicacion"] ?></td>
            </tr>-->
            <tr>
                <th>Firmante (Sello)</th>
                <td><?= $this->form->firmante ?></td>
            </tr>
        </table>
    </div>
    <div class="modal-footer">
        <a id="invoices" class="btn btn-primary">Enviar a VUCEM</a>
        <a id="closeModal" class="btn btn-danger" data-dismiss="modal">Cerrar</a>
    </div>
</div>
<script>
    $("#pedimento").focus(function(){
        $("#pedimento").closest('.control-group').removeClass('error');
        $('#pedimento').next('span').remove();
    });
    $("#firmante").focus(function(){
        $("#firmante").closest('.control-group').removeClass('error');
        $('#firmante').next('span').remove();
    });
    $("a#invoices").click(function(event) {
        event.preventDefault();
        if ($("#firmante").val() === '' || $("#pedimento").val() === '') {
            if ($("#pedimento").val() === '') {
                $("#pedimento").closest('.control-group').addClass('error');
                if(!$("#pedimento").next().is('span')) {
                    $("#pedimento").after('<span class="help-inline">Debe proporcionar pedimento</span>');
                }
            }
            if ($("#firmante").val() === '') {
                $("#firmante").closest('.control-group').addClass('error');
                if(!$("#firmante").next().is('span')) {
                    $("#firmante").after('<span class="help-inline">Debe proporcionar firmante</span>');
                }
            }
            alert("Debe proporcinar todo los datos.");
        } else {
            $.ajax({
                url: "/archivo/ajax/enviar-vucem",
                cache: false,
                data: {id: <?= $this->archivo["id"] ?>, rfc: $("#firmante").val(), pedimento: $("#pedimento").val() }
            }).done(function() {
                $('#closeModal').trigger('click');                
            });
        }
    });
</script>