<div id="modalWindow">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h3>Enviar por correo</h3>
    </div>
    <div class="modal-body">
        <h4>El correo será enviado a los siguiente destinatarios.</h4><br />
        
    </div>
    <div class="modal-footer">
      <a id="send" class="btn btn-primary">Enviar por correo</a>
      <a id="closeModal" class="btn" data-dismiss="modal">Cerrar</a>
    </div>
</div>
<script type="text/javascript" src="/js/archivo/index-enviar-email.js"></script>