<div id="modalWindow">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h3>Movimientos de referencia</h3>
    </div>
    <div class="modal-body">
        <table class="table table-striped table-bordered table-hover small">
            <thead>
                <tr>
                    <th>Fecha</th>
                    <th>Mov</th>
                    <th>Poliza</th>
                    <th>Cuenta</th>
                    <th>Cargo</th>
                    <th>Abono</th>
                    <th>Descripción</th>
                    <th>Estatus</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->movimientos as $item) { ?>
                <tr>
                    <td><?= $item["fecha"] ?></td>
                    <td><?= $item["movimiento"] ?></td>
                    <td><?= $item["poliza"] ?></td>
                    <td><?= $item["cuenta"] ?></td>
                    <td><?= $item["cargo"] ?></td>
                    <td><?= $item["abono"] ?></td>
                    <td><?= $item["descripcion"] ?></td>
                    <td><?= $item["estatus"] ?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <div class="modal-footer">
      <?php if($this->facturas) { ?>
        <a id="selectallinvoices" class="btn btn-info" style="float: left"><i class="icon-white icon-check"></i>&nbsp;Seleccionar todas</a>
        <a id="invoices" class="btn btn-primary">Seleccionar facturas</a>
      <?php } ?>
      <a id="closeModal" class="btn btn-danger" data-dismiss="modal">Cerrar</a>
    </div>
</div>