<style>
    #archivos {
        clear: both;
        padding-top: 10px;
        position: relative;
    }
    #archivos #listado,
    #archivos #preview {
        /*border: 1px #ddd solid;*/
        float: left;        
    }
    #archivos #listado {
        /*width: 650px;*/
        margin-bottom: 10px;
        /*padding: 5px;*/
    }
    #archivos #preview {
        /*margin-left: 5px;*/
        /*padding-top: 5px;*/        
    }
    #listado .header {
        display:table;
        width: 645px;
    }
    #listado .header .icon,
    #listado .header .name,
    #listado .header .type,
    #listado .header .edoc,
    #listado .header .date,
    #listado .header .action {
        background: #1883BA;
        color: #fff;
        position: relative;
        border-bottom: 1px #116789 solid;
        border-left: 1px #116789 solid;
        border-top: 1px #116789 solid;
        display:table-cell;		
    }
    #listado .header .last {
        border-right: 1px #116789 solid;        
    }
    #listado .header .icon {     width: 6%; }
    #listado .header .name {     width: 28%; }
    #listado .header .type {     width: 30%; }
    #listado .header .edoc {     width: 13%; }
    #listado .header .date {     width: 15%; }
    #listado .header .action {   width: 5%; }
    #listado .header p {
        margin-left: 5px;
    }
    #listado .info {
        display: table;
        width: 645px;
    }
    #listado .info .icon,
    #listado .info .name,
    #listado .info .type,
    #listado .info .date,
    #listado .info .edoc,
    #listado .info .action {
        display:table-cell;
        border: 0;
        border-bottom: 1px #E3EFF4 solid;
        border-left: 1px #E3EFF4 solid;
    }
    #listado .info .last {
        border-right: 1px #E3EFF4 solid;
    }
    #listado .info .icon {     width: 5%; }
    #listado .info .name {     width: 28%; }
    #listado .info .type {     width: 30%; }
    #listado .info .edoc {     width: 13%; }
    #listado .info .date {     width: 15%; }
    #listado .info .action {   width: 5%; }
    #listado .info p {
        margin-left: 5px;
        font-size: 12px;		
    }
    #listado .info .icon:hover,
    #listado .info .name:hover,
    #listado .info .type:hover,
    #listado .info .edoc:hover,
    #listado .info .date:hover,
    #listado .info .action:hover {
        background: #E3EFF4;
    }
    #preview iframe {
        width: 552px; 
        height: 552px; 
        border: 1px #116789 solid; 
        background: #E3EFF4;
        padding: 5px;
    }
    .sysfiles th {
        background-color: #D5E5F5;
    }
</style>
<fieldset>
    <legend>Archivos de patente <b><?= $this->patente ?></b>, aduana <b><?= $this->aduana ?></b> referencia <b><?= $this->referencia ?></b></legend>
    
</fieldset>
<table class="table table-striped table-bordered table-hover small sysfiles" width="100%" style="width:100%">
    <thead>
        <tr>
            <th>&nbsp;</th>
            <th>Nombre de archivo</th>
            <th>Tipo</th>
            <th>EDoc</th>
            <th>Fecha</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->archivos as $item) { ?>
        <tr>
            <td><?= $this->icon($item['nom_archivo']) ?></td>
            <td><a href="/archivo/index/descargar-archivo?id=<?= urlencode($this->encrypt($item['id'])) ?>"><?= $this->trim($item['nom_archivo']) ?></a></td>
            <td><?= $item['nombre'] ?></td>
            <td><?= $this->eDoc($item['id']) ?></td>
            <td><?= date('Y-m-d',  strtotime($item['creado'])) ?></td>
            <td><?= $this->download($item['id'],$item['nom_archivo']) ?></td>
        </tr>
        <?php if($item['ubicacion_pdf'] != NULL) { ?>
        <tr>
            <td><img src="/images/icons/pdf-icon.png" border="0" style="margin: 0 7px" /></td>
            <td><a href="/archivo/index/descargar-archivo?id=<?= urlencode($this->encrypt($item['id'])) ?>&type=pdf"><?= str_replace('.xml','',$item['nom_archivo']) . '.pdf' ?></a></td>
            <td><?= $item['nombre'] ?></td>
            <td>&nbsp;</td>
            <td><?= date('Y-m-d',  strtotime($item['creado'])) ?></td>
            <td><a href="/archivo/index/load-file-repo?id=<?= $item['id'] ?>" class="openfile"><i class="icon-eye-open"></i></a></td>
        </tr>
        <?php } ?>
        <?php } ?>
    </tbody>
</table>
<a class="btn btn-success" href=""><i class="icon-circle-arrow-up icon-white"></i>&nbsp;Subir más archivos</a>
<script>
    $(".openfile").click(function(e){
        e.preventDefault();
        console.log($(this).attr('href'));     
        window.open($(this).attr('href'), '_blank', 'toolbar=0,location=0,menubar=0,height=550,width=800,scrollbars=yes');
    });
</script>
