<style type="text/css">
    body {
    	background: #d3d3d3;
    	font-family: sans-serif;
    	font-size: 11px;
    }
    table {
    	background: #fff;
    	border: 1px #a7a7a7 solid;
    	border-spacing: 0;
    }
    table td , table th {
    	border: 1px #e9e9e9 solid;
    }
    table th {
    	background: #d3d3d3;
    }
    table td, table th {
    	font-size: 11px;
    	text-align: center;
    }
</style>
<table>
	<thead>
		<tr>
			<th>Importacion</th>
			<th>Operacion</th>
			<th>Patente</th>
			<th>Pedimento</th>
			<th>Aduana</th>
			<th>SeccionAd</th>
			<th>TransporteEntrada</th>
			<th>TransporteArribo</th>
			<th>TransporteSalida</th>
			<th>FechaEntrada</th>
			<th>FechaPago</th>
			<th>TipoCambio</th>
			<th>CvePed</th>
			<th>ValorDolares</th>
			<th>ValorAduana</th>
			<th>FacturaNo</th>
			<th>FechaFactura</th>
			<th>Incoterm</th>
			<th>Fletes</th>
			<th>Seguros</th>
			<th>Embalajes</th>
			<th>Otros_Incr</th>
			<th>DTA</th>
			<th>IVA</th>
			<th>IGI</th>
			<th>Prevalid</th>
			<th>TotalEfectivo</th>
			<th>Nomproveedor</th>
			<th>TaxId</th>
			<th>PaisVendComp</th>
			<th>Divisa</th>
			<th>NumParte</th>
			<th>Descripcion</th>
			<th>FraccionA</th>
			<th>ValorDolares</th>
			<th>ValorAduana</th>			
			<th>UMT</th>
			<th>Cant.UMT</th>
			<th>UMC</th>
			<th>Cant.UMC</th>
			<th>PaisOrigen</th>
			<th>TasaAdv</th>
			<th>FormaPagoAdv</th>
			<th>PaisVendedor</th>
			<th>IVA</th>
			<th>IEPS</th>
			<th>ISAN</th>
			<th>PesoBru</th>
			<th>COVE</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->data as $item) { ?>
		<tr>
			<td><?= $item["operacion"] ?></td>
			<td><?= ($item["tipoOperacion"] == 'Importacion') ? 'IMP' : 'EXP' ?></td>
			<td><?= $item["patente"] ?></td>
			<td><?= $item["pedimento"] ?></td>
			<td><?= substr($item["aduana"],0,2) ?></td>
			<td><?= substr($item["aduana"],2) ?></td>
			<td><?= $item["medioTransporteEntrada"] ?>&nbsp;</td>
			<td><?= $item["medioTransporteArribo"] ?>&nbsp;</td>
			<td><?= $item["medioTransporteSalida"] ?>&nbsp;</td>
			<td><?= $item["fechaEntrada"] ?>&nbsp;</td>
			<td><?= $item["fechaPagoContribuciones"] ?>&nbsp;</td>
			<td><?= number_format($item["tipoCambio"], 4, '.', ',') ?>&nbsp;</td>
			<td><?= $item["claveDocumento"] ?>&nbsp;</td>
			<td><?= number_format($item["valorDolares"], 2, '.', ',') ?>&nbsp;</td>
			<td><?= number_format($item["valorAduanalTotal"], 2, '.', ',') ?>&nbsp;</td>
			<td><?= $item["numeroFactura"] ?>&nbsp;</td>
			<td><?= $item["fechaFactura"] ?>&nbsp;</td>
			<td><?= $item["terminoFacturacion"] ?>&nbsp;</td>
			<td><?= number_format($item["fletes"], 2, '.', ',') ?>&nbsp;</td>
			<td><?= number_format($item["seguros"], 2, '.', ',') ?>&nbsp;</td>
			<td><?= number_format($item["embalajes"], 2, '.', ',') ?>&nbsp;</td>
			<td><?= number_format($item["incrementables"], 2, '.', ',') ?>&nbsp;</td>
			<td><?= number_format($item["DTA"], 2, '.', ',') ?>&nbsp;</td>
			<td><?= number_format($item["IVA"], 2, '.', ',') ?>&nbsp;</td>
			<td><?= number_format($item["IGI"], 2, '.', ',') ?>&nbsp;</td>
			<td><?= number_format($item["Prev"], 2, '.', ',') ?>&nbsp;</td>
			<td><?= number_format($item["efectivo"], 2, '.', ',') ?>&nbsp;</td>
			<td><?= $item["proveedorComprador"] ?>&nbsp;</td>
			<td><?= $item["identificadorFiscalProveedorComprador"] ?>&nbsp;</td>
			<td><?= $item["proPais"] ?>&nbsp;</td>
			<td><?= $item["moneda"] ?>&nbsp;</td>
			<td><?= $item["numeroParte"] ?>&nbsp;</td>
			<td><?= base64_decode($item["descripcionMercancia"]) ?>&nbsp;</td>
			<td><?= $item["fraccion"] ?>&nbsp;</td>
			<td><?= number_format($item["partValorDolares"], 2, '.', ',') ?>&nbsp;</td>
			<td><?= number_format($item["partValorAduana"], 2, '.', ',') ?>&nbsp;</td>
			<td><?= $item["UMT"] ?>&nbsp;</td>
			<td><?= $item["CantUMT"] ?>&nbsp;</td>
			<td><?= $item["UMC"] ?>&nbsp;</td>
			<td><?= $item["CantUMC"] ?>&nbsp;</td>
			<td><?= $item["origen"] ?>&nbsp;</td>
			<td><?= $item["TasaAdv"] ?>&nbsp;</td>
			<td>0&nbsp;</td>
			<td><?= $item["vendedor"] ?>&nbsp;</td>
			<td><?= number_format($item["partValorAgregado"], 2, '.', ',') ?>&nbsp;</td>
			<td><?= number_format(0, 2, '.', ',') ?>&nbsp;</td>
			<td><?= number_format(0, 2, '.', ',') ?>&nbsp;</td>
			<td><?= number_format($item["pesoBruto"], 2, '.', ',') ?>&nbsp;</td>
			<td><?= $item["COVE"] ?>&nbsp;</td>
		</tr>
		<?php } ?>
	</tbody>
</table>