<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <title>Reportes</title>
        <style type="text/css">
            body {margin:0;padding:0; font-family:sans-serif;}
            h1,h2,h3 {margin: 0; padding: 10px 5px;}
        </style>
        <link href="/less/traffic-module.css" media="screen" rel="stylesheet" type="text/css" >
    </head>
    <body>
        <h3><?= $this->message ?></h3>
    </body>
</html>