<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Parcial <?= $this->aduana ?></title>
    </head>
    <style>body {margin:0;padding:0; font-family:sans-serif;}
        table {border-collapse:collapse; }
        table th, table td {font-size: 12px; border: 1px #555 solid; padding: 2px 5px;}
        table th {background: #f1f1f1;
        }
        h1,h2,h3 {
            margin: 0; padding:0;
        }
    </style>
</head>
<body>
    <table id="table2excel">
        <tr>
            <th>Referencia</th>
            <th>CvePedimento</th>
            <th>ReferenciaAA</th>
            <th>ClaveProyecto</th>
            <th>Factura</th>
            <th>OrdenCompra</th>
            <th>ClaveCliente</th>
            <th>NumFactura</th>
            <th>NumeroParte</th>
            <th>PaisOrigen</th>
            <th>Secuencial</th>
            <th>Fraccion</th>
            <th>UMC</th>
            <th>CantUMC</th>
            <th>PrecioUnitario</th>
            <th>Total</th>
            <th>PatenteOrig</th>
            <th>PedimentoOrig</th>
            <th>AduanaOrig</th>
        </tr>
        <?php if (isset($this->data)) { ?>
            <?php foreach ($this->data as $item) { ?>
                <tr>
                    <td><?= $item["Referencia"] ?></td>
                    <td><?= isset($item["CvePedimento"]) ? $item["CvePedimento"] : "" ?></td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td><?= isset($item["Factura"]) ? $item["Factura"] : "" ?></td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td><?= $item["NumFactura"] ?></td>
                    <td><?= strtoupper($item["NumParte"]) ?></td>
                    <td><?= $item["PaisOrigen"] ?></td>
                    <td><?= isset($item["Secuencia"]) ? $item["Secuencia"] : "" ?></td>
                    <td><?= $item["Fraccion"] ?></td>
                    <td><?= $item["UMC"] ?></td>
                    <td style="text-align:right;"><?= number_format($item["CantUMC"], 2) ?></td>
                    <td style="text-align:right;"><?= number_format($item["ValorFacturaUsd"] / $item["CantUMC"], 2) ?></td>
                    <td style="text-align:right;"><?= number_format($item["ValorFacturaUsd"], 2) ?></td>
                    <td><?= $item["PatenteOrig"] ?></td>
                    <td><?= $item["PedimentoOrig"] ?></td>
                    <td><?= $item["AduanaOrig"] ?></td>
                </tr>
            <?php } ?>
        <?php } ?>
    </table>
</body>
</html>