<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>No resultados</title>
    </head>
    <style>body {margin:0;padding:0; font-family:sans-serif;}
        table {border-collapse:collapse; }
        table th, table td {font-size: 12px; border: 1px #555 solid; padding: 2px 5px;}
        table th {background: #f1f1f1;
        }
        h1,h2,h3 {
            margin: 0; padding:0;
        }
    </style>
</head>
<body>
    <h3>No existen pedimentos en la aduana y fechas seleccionados.</h3>
</body>
</html>