<table class="traffic-table traffic-table-left hover" id="archiveList">
    <thead>
        <tr>
            <th style="width: 60px">Patente</th>
            <th style="width: 60px">Aduana</th>
            <th>&nbsp;</th>
            <th style="width: 32px">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php if ($this->data) {?>
            <?php foreach ($this->data as $item) {?>
                <tr>
                    <td style="text-align: center"><?=($item["patente"] == '0') ? 'Todas' : $item["patente"]?></td>
                    <td style="text-align: center"><?=($item["aduana"] == '0') ? 'Todas' : $item["aduana"]?></td>
                    <td>&nbsp;</td>
                    <td>
                        <!--<a style="cursor: pointer;" onclick="parent.borrarRepositorio('<?=$item["id"]?>');"><img src="/images/icons/small_delete.png" /></a>-->
                        <i class="far fa-trash-alt" onclick="parent.borrarRepositorio('<?=$item["id"]?>');" style="font-size: 1.3em; color: #2f3b58; cursor: pointer"></i>
                    </td>
                </tr>
            <?php }?>
        <?php } else {?>
            <tr>
                <td colspan="4" style="text-align: center"><em>El usuario no tiene aduanas asignadas.</em></td>
            </tr>
        <?php }?>
    </tbody>
</table>
<?php if ($this->data) {?>
    <script type="text/javascript">
        $("#archiveList").DataTable({
        "lengthMenu": [[15, 25, 50, -1], [15, 25, 50, "All"]],
        "language": {
            "decimal": "",
            "emptyTable": "No data available in table",
            "info": "Mostrando _START_ a _END_ de _TOTAL_ registros",
            "infoEmpty": "Showing 0 to 0 of 0 entries",
            "infoFiltered": "(filtered from _MAX_ total entries)",
            "infoPostFix": "",
            "thousands": ",",
            "lengthMenu": "Mostrando _MENU_ registros",
            "loadingRecords": "Cargando ...",
            "processing": "Procesando ...",
            "search": "Buscar:",
            "zeroRecords": "No matching records found",
            "paginate": {
                "first": "Primero",
                "last": "Último",
                "next": "Sig.",
                "previous": "Ant."
            }
        }
    });
    </script>
<?php }?>
