<table class="traffic-table traffic-table-left hover" id="customersList">
    <thead>
        <tr>
            <th style="width: 380px; text-align: left">Aduana</th>
            <th>Cliente</th>
            <th style="width: 32px">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php if ($this->data) {?>
            <?php foreach ($this->data as $item) {?>
                <tr>
                    <td style="text-align: left"><?=$item["patente"] . "-" . $item["aduana"] . " " . $item["nombreAduana"]?></td>
                    <td><?=($item["patente"] != 0) ? $item["nombre"] : "TODAS"?></td>
                    <td>
                        <!--<a style="cursor: pointer;" onclick="removerClienteTrafico(<?=$this->idUsuario?>, <?=$item["idAduana"]?>, <?=$item["idCliente"]?>);"><img src="/images/icons/small_delete.png" /></a>-->
                        <i class="far fa-trash-alt" onclick="removerClienteTrafico(<?=$this->idUsuario?>, <?=$item["idAduana"]?>, <?=$item["idCliente"]?>);" style="font-size: 1.3em; color: #2f3b58; cursor: pointer"></i>
                    </td>
                </tr>
            <?php }?>
        <?php } else {?>
            <tr>
                <td colspan="3" style="text-align: center"><em>El usuario no tiene aduanas asignadas.</em></td>
            </tr>
        <?php }?>
    </tbody>
</table>
<?php if ($this->data) {?>
    <script type="text/javascript">
        $("#customersList").DataTable({
        "lengthMenu": [[15, 25, 50, -1], [15, 25, 50, "All"]],
        "language": {
            "decimal": "",
            "emptyTable": "No data available in table",
            "info": "Mostrando _START_ a _END_ de _TOTAL_ registros",
            "infoEmpty": "Showing 0 to 0 of 0 entries",
            "infoFiltered": "(filtered from _MAX_ total entries)",
            "infoPostFix": "",
            "thousands": ",",
            "lengthMenu": "Mostrando _MENU_ registros",
            "loadingRecords": "Cargando ...",
            "processing": "Procesando ...",
            "search": "Buscar:",
            "zeroRecords": "No matching records found",
            "paginate": {
                "first": "Primero",
                "last": "Último",
                "next": "Sig.",
                "previous": "Ant."
            }
        }
    });
    </script>
<?php }?>
