<table class="traffic-table traffic-table-left hover" id="customersList">
    <thead>
        <tr>
            <th style="width: 380px; text-align: left">Aduana</th>
            <th>Cliente</th>
            <th style="width: 32px">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php if ($this->data) { ?>
            <?php foreach ($this->data as $item) { ?>
                <tr>
                    <td style="text-align: left"><?= $item["patente"] . "-" . $item["aduana"] . " " . $item["nombreAduana"] ?></td>
                    <td><?= ($item["patente"] != 0) ? $item["nombre"] : "TODAS" ?></td>
                    <td>
                        <!--<a style="cursor: pointer;" onclick="removerClienteTrafico(<?= $this->idUsuario ?>, <?= $item["idAduana"] ?>, <?= $item["idCliente"] ?>);"><img src="/images/icons/small_delete.png" /></a>-->
                        <i class="far fa-trash-alt" onclick="removerClienteTrafico(<?= $this->idUsuario ?>, <?= $item["idAduana"] ?>, <?= $item["idCliente"] ?>);" style="font-size: 1.3em; color: #2f3b58; cursor: pointer"></i>
                    </td>
                </tr>
            <?php } ?>
        <?php } else { ?>
            <tr>
                <td colspan="3" style="text-align: center"><em>El usuario no tiene aduanas asignadas.</em></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
<?php if ($this->data) { ?>
    <script type="text/javascript">    
        $("#customersList").dataTable({
            "sDom": "<'traffic-cols'<'traffic-col-50'l><'traffic-col-50'f><'traffic-clear-5'>t<'traffic-clear-5'><'traffic-col-50'i><'traffic-col-50'p><'traffic-clear-5'>>",
            "sPaginationType": "bootstrap",
            "oLanguage": {
                "sLengthMenu": "_MENU_ registros por página"
            },
            "iDisplayLength": 15,
            "aaSorting": [[15, "desc"]]
        });    
    </script>
<?php } ?>
    