<table class="traffic-table traffic-table-left">
    <tr>
        <th>Contenido</th>
        <td>
            <pre style="padding: 2px; line-height: 12px; margin: 0">
                <code style="padding: 2px; line-height: 12px"><?= htmlentities($this->contenido) ?></code>
            </pre>
        </td>
    </tr>
</table>
<div class="traffic-clear-5"></div>
<a class="traffic-btn-close" id="closeModal">Cerrar</a>
<div class="traffic-clear-5"></div>
<script>
    $("#closeModal").click(function () {
        $("#modalRegister").html('Please wait... <div class="traffic-icon traffic-loader"></div>');
        $("#modalRegister").jqmHide();
    });
    $(document).ready(function() {
        $("pre code").each(function(i, block) {
            hljs.highlightBlock(block);
        });
    });
</script>