<form id="form_incidence">
    <input type="hidden" name="id" id="id" value="<?= $this->row['id'] ?>" />
    <table class="traffic-table traffic-table-left">
        <thead>
            <tr>
                <th colspan="2">
                    DATOS DE LA INCIDENCIA
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th style="text-align: right">ADUANA:</th>
                <td>
                    <?php if (isset($this->aduanas) && !empty($this->aduanas)) { ?>
                        <select class="traffic-select-large" name="idAduana" id="idAduana" disabled="true">
                            <option value="">-- Seleccionar --</option>
                            <?php foreach ($this->aduanas as $k => $v) { ?>
                                <option value="<?= $k ?>" <?= ($this->row['idAduana'] == $k) ? 'selected="true"' : '' ?>><?= $v ?></option>
                            <?php } ?>
                        </select>
                    <?php } ?>
                </td>
            </tr>
            <tr>
                <th style="text-align: right">CLIENTE:</th>
                <td>
                    <?php if (isset($this->clientes) && !empty($this->clientes)) { ?>
                        <select class="traffic-select-large" name="idCliente" id="idCliente" disabled="true">
                            <option value="">-- Seleccionar --</option>
                            <?php foreach ($this->clientes as $item) { ?>
                                <option value="<?= $item['id'] ?>" <?= ($this->row['idCliente'] == $item['id']) ? 'selected="true"' : '' ?>><?= $item['razonSocial'] ?></option>
                            <?php } ?>
                        </select>
                    <?php } ?>
                </td>
            </tr>
            <tr>
                <th style="text-align: right">PEDIMENTO:</th>
                <td>
                    <input class="traffic-input-medium" type="text" name="pedimento" id="pedimento" value="<?= $this->row['pedimento'] ?>" />
                </td>
            </tr>
            <tr>
                <th style="text-align: right">REFERENCIA:</th>
                <td>
                    <input class="traffic-input-medium" type="text" name="referencia" id="referencia" value="<?= $this->row['referencia'] ?>" />
                </td>
            </tr>
            <tr>
                <th style="text-align: right">ACTA:</th>
                <td>
                    <input class="traffic-input-medium" type="text" name="acta" id="acta" value="<?= $this->row['acta'] ?>" />
                </td>
            </tr>
            <tr>
                <th style="text-align: right">MULTA:</th>
                <td>
                    <input class="traffic-input-medium" type="text" name="multa" id="multa" value="<?= $this->row['multa'] ?>" />
                </td>
            </tr>
            <tr>
                <th style="text-align: right">PAGADA:</th>
                <td>
                    <input type="checkbox" name="pagada" id="pagada" <?= ($this->row['pagada'] == 1) ? 'checked="true"' : '' ?>/>
                </td>
            </tr>
            <tr>
                <th style="text-align: right">RESPONSABLE:</th>
                <td>
                    <input class="traffic-input-large" type="text" name="responsable" id="responsable" value="<?= $this->row['responsable'] ?>" />
                </td>
            </tr>
            <tr>
                <th style="text-align: right">OBSERVACIONES:</th>
                <td>
                    <textarea class="traffic-textarea-medium" name="observaciones" id="observaciones"><?= $this->row['observaciones'] ?></textarea>
                </td>
            </tr>
            <tr>
                <th style="text-align: right">COMENTARIOS:</th>
                <td>
                    <textarea class="traffic-textarea-medium" name="comentarios" id="comentarios" ><?= $this->row['comentarios'] ?></textarea>
                </td>
            </tr>
            <tr>
                <th style="text-align: right">FECHA:</th>
                <td>
                    <input class="traffic-input-date" type="text" name="fecha" id="fecha" value="<?= date("Y-m-d", strtotime($this->row['fecha'])) ?>" /><i class="far fa-calendar-alt" style="padding-left: 5px; font-size: 1.2em"></i>
                </td>
            </tr>
        </tbody>
    </table>
</form>
<script type="text/javascript">    
    
    $("#form_letter").validate({
        errorPlacement: function (error, element) {
            $(element)
                    .closest("form")
                    .find("#" + element.attr("id"))
                    .after(error);
        },
        errorElement: "span",
        errorClass: "traffic-error",
        rules: {
            idAduana: "required",
            idCliente: "required"
        },
        messages: {
            idAduana: "Campo necesario",
            idCliente: "Campo necesario"
        }
    });
    
    $("#fecha").datepicker({
        calendarWeeks: true,
        autoclose: true,
        language: "es",
        format: "yyyy-mm-dd"
    });

    $(document).on("input", "#responsable, #comentarios, #observaciones, #referencia", function() {
        var input = $(this);
        var start = input[0].selectionStart;
        $(this).val(function (_, val) {
            return val.toUpperCase();
        });
        input[0].selectionStart = input[0].selectionEnd = start;
    });
    
</script>