<form id="form">
    <table>
        <tr>
            <td>Id Empresa:</td>
            <td>
                <input type="text" name="idEmpresa" value="<?= $this->idEmpresa ?>" readonly="true" style="width: 50px" />                            
            </td>
        </tr>
        <tr>
            <td>Id Depto:</td>
            <td>
                <input type="text" name="idDepto" readonly="true" style="width: 50px" />                            
            </td>
        </tr>
        <tr>
            <td>Id:</td>
            <td>
                <input type="text" name="id" readonly="true" style="width: 50px" />                            
            </td>
        </tr>
        <tr>
            <td>Tipo:</td>
            <td>
                <input type="text" name="tipo" readonly="true" />                            
            </td>
        </tr>
        <tr>
            <td>Nombre:</td>
            <td>
                <input type="text" name="nombre" />
            </td>
        </tr>
        <tr>
            <td>Descripción:</td>
            <td>
                <input type="text" name="descripcion" />
            </td>
        </tr>
    </table>
    <button type="submit" id="submit" class="traffic-btn-small traffic-btn-close">Guardar</button>
</form>