<style>
    .table-pedimento {
        border-top: 1px #777 solid;
        text-align: left;
    }
    .table-pedimento th {
        vertical-align: middle;
        background-color: #d4d4d4;
    }
    .table-pedimento td {
        vertical-align: middle;
        background-color: #fff;
        border: 1px #bbb solid !important;
    }
    .table-pedimento td > .traffic-input-small,
    .table-pedimento td > .traffic-input-medium,
    .table-pedimento td > .traffic-input-large {
        font-size: 11px;
        border: 1px #0088cc solid !important;
        border-radius: 0;
        height: 15px;
    }
    .table-pedimento td > .traffic-select-small,
    .table-pedimento td > .traffic-select-medium {
        font-size: 11px;
        border: 1px #0088cc solid !important;
        border-radius: 0;
        height: 20px !important;
        padding: 0 !important;
    }
    .table-pedimento td > .traffic-textarea-medium {
        font-size: 11px;
        border: 1px #0088cc solid !important;
        border-radius: 0;
    }
    input[name='tipoCambio'] {
        text-align: center;
    }
</style>
<input type="hidden" name="idPedimento" id="idPedimento" value="<?= $this->idPedimento ?>" />
<table class="traffic-table table-pedimento">
    <tbody>
        <tr>
            <th width="90">Pedimento</th>
            <td width="170"><?= $this->aduana . '-' . $this->patente . '-' . $this->pedimento ?></td>
            <th width="120">T. Ope.</th>
            <td width="160"><?= $this->tipoOperacion ?></td>
            <th width="170">Cve. pedimento</th>
            <td width="180">
                <select id="cvePedimento" name="cvePedimento" class="traffic-select-small">
                    <option value="">---</option>
                    <?php foreach ($this->cves AS $item) { ?>
                        <option value="<?= $item['clave'] ?>" <?= ($this->cvePedimento !== $item['clave']) ? '' : 'selected=true' ?>><?= $item['clave'] ?></option>
                    <?php } ?>
                </select>
            </td>
            <th width="120">Regimen</th>
            <td>
                <?php if ($this->tipoOperacion == 'TOCE.IMP') { ?>
                    <select id="regimen" name="regimen" class="traffic-select-small" disabled="true">
                        <option value="">---</option>
                        <?php foreach ($this->cves AS $item) { ?>
                            <option value="<?= $item['regimenImportacion'] ?>" <?= ($this->cvePedimento !== $item['clave']) ? '' : 'selected=true' ?>><?= $item['regimenImportacion'] ?></option>
                        <?php } ?>
                    </select>
                <?php } else { ?>
                    <select id="regimen" name="regimen" class="traffic-select-small" disabled="true">
                        <option value="">---</option>
                        <?php foreach ($this->cves AS $item) { ?>
                            <option value="<?= $item['regimenExportacion'] ?>" <?= ($this->cvePedimento !== $item['clave']) ? '' : 'selected=true' ?>><?= $item['regimenExportacion'] ?></option>
                        <?php } ?>
                    </select>
                <?php } ?>
            </td>
        </tr>
    </tbody>
</table>

<table class="traffic-table table-pedimento">
    <tbody>
    <tr>
        <th width="90">DEST./ORIGEN</th>
        <td width="170">
            <select id="destinoOrigen" name="destinoOrigen" class="traffic-select-small">
                <option value="">---</option>
                <?php foreach ($this->destinos AS $item) { ?>
                    <option value="<?= $item['clave'] ?>" <?= ($this->destinoOrigen !== $item['clave']) ? '' : 'selected=true' ?>>
                        <?= $item['clave'] . ' - ' . '<em>' . $item['descripcion'] . '</em>' ?></option>
                <?php } ?>
            </select>
        </td>
        <th width="120">TIPO CAMBIO</th>
        <td width="160">
            <input type="text" id="tipoCambio" name="tipoCambio" class="traffic-input-small" value="<?= isset($this->tipoCambio) ? $this->tipoCambio : 0 ?>" />
        </td>
        <th width="170">PESO BRUTO</th>
        <td width="180">
            <input type="text" id="pesoBruto" name="pesoBruto" class="traffic-input-small" value="<?= isset($this->pesoBruto) ? $this->pesoBruto : '' ?>" />
        </td>
        <th width="120">ADUANA E/S</th>
        <td>
            <select id="aduanaDespacho" name="aduanaDespacho" class="traffic-select-medium">
                <option value="">---</option>
                <?php foreach ($this->a_despacho AS $item) { ?>
                    <option value="<?= $item['aduana'] . $item['seccion'] ?>" <?= ($this->aduanaDespacho !== $item['aduana'] . $item['seccion']) ? '' : 'selected=true' ?>>
                        <?= $item['aduana'] . $item['seccion'] . ' - ' . '<em>' . $item['descripcion'] . '</em>' ?></option>
                <?php } ?>
            </select>
        </td>
    </tr>
    </tbody>
</table>

<table class="traffic-table table-pedimento">
    <tbody>
    <tr>
        <th colspan="3">MEDIOS DE TRANSPORTE</th>
        <th colspan="2"></th>
    </tr>
    <tr>
        <th>Trans. Entrada/salida</th>
        <th>Trans. Arribo</th>
        <th>Trans. Salida</th>
        <th>Valor dolares</th>
        <td>
            <input type="text" id="valorDolares" name="valorDolares" class="traffic-input-small" />
        </td>
    </tr>
    <tr>
        <td>
            <select id="transEntrada" name="transEntrada" class="traffic-select-medium">
                <option value="">---</option>
                <?php foreach ($this->medios AS $item) { ?>
                    <option value="<?= $item['clave'] ?>" <?= ($this->transArribo !== $item['clave']) ? '' : 'selected=true' ?>>
                        <?= $item['clave'] . ' - ' . '<em>' . $item['descripcion'] . '</em>' ?></option>
                <?php } ?>
            </select>
        </td>
        <td>
            <select id="transArribo" name="transArribo" class="traffic-select-medium">
                <option value="">---</option>
                <?php foreach ($this->medios AS $item) { ?>
                    <option value="<?= $item['clave'] ?>" <?= ($this->transArribo !== $item['clave']) ? '' : 'selected=true' ?>>
                        <?= $item['clave'] . ' - ' . '<em>' . $item['descripcion'] . '</em>' ?></option>
                <?php } ?>
            </select>
        </td>
        <td>
            <select id="transSalida" name="transSalida" class="traffic-select-medium">
                <option value="">---</option>
                <?php foreach ($this->medios AS $item) { ?>
                    <option value="<?= $item['clave'] ?>" <?= ($this->transArribo !== $item['clave']) ? '' : 'selected=true' ?>>
                        <?= $item['clave'] . ' - ' . '<em>' . $item['descripcion'] . '</em>' ?></option>
                <?php } ?>
            </select>
        </td>
        <th>Valor aduana</th>
        <td>
            <input type="text" id="valorAduana" name="valorAduana" class="traffic-input-small" />
        </td>
    </tr>
    <tr>
        <td colspan="3"></td>
        <th>Valor comercial</th>
        <td>
            <input type="text" id="valorComercial" name="valorComercial" class="traffic-input-small" />
        </td>
    </tr>
    </tbody>
</table>

<table class="traffic-table table-pedimento">
    <tbody>
    <tr>
        <th colspan="2">DATOS DEL IMPORTADOR / EXPORTADOR</th>
        <th></th>
    </tr>
    <tr>
        <th>RFC</th>
        <td>
            <input type="text" id="rfcCliente" name="rfcCliente" value="<?= $this->rfcCliente ?>" class="traffic-input-small" readonly="true" />
        </td>
        <th>
            NOMBRE, DENOMINACIÓN O RAZÓN SOCIAL
        </th>
    </tr>
    <tr>
        <th>CURP</th>
        <td></td>
        <td>
            <input type="text" id="nomCliente" name="nomCliente" value="<?= $this->nomCliente ?>" class="traffic-input-large" readonly="true" />
        </td>
    </tr>
    <tr>
        <th>DOMICILIO</th>
        <td></td>
        <td style="text-align: center">
            <textarea class="traffic-textarea-medium" readonly="true" style="width: 350px !important;"></textarea>
        </td>
    </tr>
    </tbody>
</table>

<table class="traffic-table table-pedimento">
    <tbody>
    <tr>
        <th>VAL. SEGUROS</th>
        <th>SEGUROS</th>
        <th>FLETES</th>
        <th>EMBALAJES</th>
        <th>OTROS INCREMENTABLES</th>
    </tr>
    <tr>
        <td>
            <input type="text" id="valorSeguros" name="valorSeguros" class="traffic-input-small" />
        </td>
        <td>
            <input type="text" id="seguros" name="seguros" class="traffic-input-small" />
        </td>
        <td>
            <input type="text" id="fletes" name="fletes" class="traffic-input-small" />
        </td>
        <td>
            <input type="text" id="embalajes" name="embalajes" class="traffic-input-small" />
        </td>
        <td>
            <input type="text" id="otrosIncrementables" name="otrosIncrementables" class="traffic-input-small" />
        </td>
    </tr>
    </tbody>
</table>

<table class="traffic-table table-pedimento">
    <tbody>
    <tr>
        <th width="250">MARCAS, NUMEROS Y TOTAL DE BULTOS</th>
        <td style="text-align: left">
            <input type="text" id="bultos" name="bultos" class="traffic-input-large" />
        </td>
    </tr>
    </tbody>
</table>

<table class="traffic-table table-pedimento">
    <tbody>
    <tr>
        <th colspan="2" rowspan="2">Fechas</th>
        <th colspan="3">Tasas a nivel pedimento</th>
    </tr>
    <tr>
        <th>Contrib.</th>
        <th>Cve. T. Tasa</th>
        <th>Tasa</th>
    </tr>
    <tr>
        <td colspan="2"></td>
        <td colspan="3"></td>
    </tr>
    </tbody>
</table>

<table class="traffic-table table-pedimento">
    <tbody>
    <tr>
        <th colspan="5">CUADRO DE LIQUIDACIÓN</th>
    </tr>
    <tr>
        <th>Concepto</th>
        <th>F.P.</th>
        <th>Importe</th>
        <th colspan="2">Totales</th>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <th>Efectivo</th>
        <td>
            <input type="text" id="efectivo" name="efectivo" class="traffic-input-small" />
        </td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <th>Otros</th>
        <td>
            <input type="text" id="otros" name="otros" class="traffic-input-small" />
        </td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <th>Total</th>
        <td>
            <input type="text" id="totalLiquidacion" name="totalLiquidacion" class="traffic-input-small" />
        </td>
    </tr>
    </tbody>
</table>

<table class="traffic-table table-pedimento">
    <thead>
    <tr>
        <th colspan="7">            
            <div style="float: left; margin-left: 10px">
                <button onclick="procesarFacturas();" style="background-color: #fff; border-radius: 3px; border: 1px #444 solid" title="Procesar facturas"><i class="fas fa-sync" style="font-size: 14px; cursor: pointer"></i></button>
            </div>
            DATOS DEL PROVEEDOR O COMPRADOR
        </th>
    </tr>
    <tr>
        <th>Id fiscal</th>
        <th colspan="2">Nombre, denominación o razón social</th>
        <th colspan="3">Domicilio</th>
        <th>Vincuación</th>
    </tr>
    </thead>
    <tbody id="facturas-pedimento">
        <?php if (isset($this->facturas) && !empty($this->facturas)) { ?>
            <?php foreach ($this->facturas as $item) { ?>
                <tr>
                    <td><?= $item['proveedor']['idFiscal'] ?></td>
                    <td colspan="2"><?= $item['proveedor']['razonSocial'] ?></td>
                    <td colspan="3"><?= implode(" ,", array_filter(array($item['proveedor']['calle'], $item['proveedor']['numExterior'], $item['proveedor']['numInterior'], $item['proveedor']['colonia'], $item['proveedor']['municipio'], $item['proveedor']['estado'], $item['proveedor']['codigoPostal'], $item['proveedor']['pais']))) ?></td>
                    <td>
                        <input type="checkbox" id="proveedor-vinculacion" data-id="<?= $item['id'] ?>" <?= ($item['proveedor']['vinculacion'] == 1) ? 'checked="true"' : '' ?> />
                    </td>
                </tr>
                <?php if (!empty($item['facturas'])) { ?>
                    <tr>
                        <td><b>NUM. FACTURA</b></td>
                        <td><b>FECHA</b></td>
                        <td><b>INCOTERM</b></td>
                        <td><b>MONEDA FACT.</b></td>
                        <td><b>VAL. MON. FACT.</b></td>
                        <td><b>FACTOR MON. FACT.</b></td>
                        <td><b>VAL. DOLARES</b></td>
                    </tr>
                    <?php foreach ($item['facturas'] as $f) { ?>
                        <tr>
                            <td><?= $f['numFactura'] ?></td>
                            <td><?= date("d/m/Y", strtotime($f['fecha'])) ?></td>
                            <td><?= $f['incoterm'] ?></td>
                            <td><?= $f['monedaFactura'] ?></td>
                            <td><?= $f['valorMonedaFactura'] ?></td>
                            <td><?= $f['factorMonedaFactura'] ?></td>
                            <td><?= $f['valorDolares'] ?></td>
                        </tr>
                    <?php } ?>
                <?php } ?>
            <?php } ?>
        <?php } else { ?>
        <tr>
            <td colspan="4">
                <em>No hay facturas</em>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>

<table class="traffic-table table-pedimento">
    <tbody>
    <tr>
        <th width="150">TRANSPORTE</th>
        <th width="150">INDENTIFICACIÓN</th>
        <td>
            <input type="text" id="idenTransporte" name="idenTransporte" class="traffic-input-small" />
        </td>
        <th>País</th>
        <td>
            <select id="paisTransporte" name="paisTransporte" class="traffic-select-small">
                <option value="">---</option>
                <?php foreach ($this->paises AS $item) { ?>
                    <option value="<?= $item['clave_m3'] ?>" <?= ($this->paisTransporte !== $item['clave']) ? '' : 'selected=true' ?>>
                        <?= $item['clave_m3'] . ' - ' . '<em>' . $item['nombre'] . '</em>' ?></option>
                <?php } ?>
            </select>
        </td>
    </tr>
    </tbody>
</table>

<table class="traffic-table table-pedimento">
    <tbody>
    <tr>
        <th width="150">NÚMERO CANDADO</th>
        <td>
            <input type="text" id="candados" name="candados" class="traffic-input-medium" />
        </td>
    </tr>
    </tbody>
</table>

<table class="traffic-table table-pedimento">
    <thead>
    <tr>
        <th colspan="4">IDENTIFICADORES</th>
    </tr>
    <tr>
        <th>Clave / clomp. identificador</th>
        <th>Complemento 1</th>
        <th>Complemento 2</th>
        <th>Complemento 3</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    </tbody>
</table>

<table class="traffic-table table-pedimento">
    <thead>
    <tr>
        <th>OBSERVACIONES</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <textarea class="traffic-textarea-medium" readonly="true" style="width: 350px !important;"></textarea>
        </td>
    </tr>
    </tbody>
</table>

<table class="traffic-table table-pedimento">
    <thead>
    <tr>
        <th colspan="16">
            <div style="float: left; margin-left: 10px">
                <button onclick="procesarPartidas();" style="background-color: #fff; border-radius: 3px; border: 1px #444 solid" title="Procesar partidas"><i class="fas fa-sync" style="font-size: 14px; cursor: pointer"></i></button>
                &nbsp;
                <button onclick="verPartidas();" style="background-color: #fff; border-radius: 3px; border: 1px #444 solid" title="Ver partidas de las facturas"><i class="fas fa-book-open" style="font-size: 14px; cursor: pointer"></i></button>
            </div>
            PARTIDAS
            <div style="float: right; margin-right: 10px">
                <!--<input type="checkbox" id="agrupar-partidas" /> Agrupar partidas-->
            </div>
        </th>
    </tr>
    <tr>
        <th rowspan="3">SEC</th>
        <th>FRACCION</th>
        <th>SUBD.</th>
        <th>VINC.</th>
        <th>MET VAL</th>
        <th>UMC</th>
        <th>CANT. UMC</th>
        <th>UMT</th>
        <th>CANT. UMT</th>
        <th>P. C/V</th>
        <th>P. O/D</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    <tr>
        <th colspan="10">DESCRIPCION</th>
        <th>CON</th>
        <th>TASA</th>
        <th>TT</th>
        <th>FP</th>
        <th>IMPORTE</th>
    </tr>
    <tr>
        <th colspan="3">VAL. ADU.</th>
        <th colspan="3">IMP. PRECIO PAG.</th>
        <th colspan="2">PRECIO UNT.</th>
        <th colspan="2">VAL. AGREG.</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    </thead>
    <tbody id="pedimento-partidas">
    <?php if (isset($this->partidas) && !empty($this->partidas)) { ?>
        <?php foreach ($this->partidas as $item) { ?>
            <tr>
                <td rowspan="4"><?= $item['secuencia'] ?></td>
                <td><?= $item['fraccion'] ?></td>
                <td><input type="checkbox" class="subdivision" data-id="<?= $item['id'] ?>" />&nbsp;</td>
                <td><input type="checkbox" class="vinculacion" data-id="<?= $item['id'] ?>" />&nbsp;</td>
                <td>&nbsp;</td>
                <td><?= $item['umc'] ?></td>
                <td><?= $item['cantidadFactura'] ?></td>
                <td><?= $item['umt'] ?></td>
                <td><?= $item['cantidadTarifa'] ?></td>
                <td><?= $item['paisOrigen'] ?></td>
                <td><?= $item['paisVendedor'] ?></td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td colspan="10"><?= $item['descripcion'] ?></td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td colspan="3"><?= $item['valorAduana'] ?></td>
                <td colspan="3"><?= $item['valorComercial'] ?></td>
                <td colspan="2"><?= $item['precioUnitario'] ?></td>
                <td colspan="2"></td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td colspan="15"><?= $item['observacion'] ?></td>
            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="18"><em>No hay partidas.</em></td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<!--<button class="traffic-btn" id="csv-aduanet" style="float:right; margin-top:5px">CSV (Aduanet)</button>-->
<a class="traffic-btn" style="float:right; margin-top:5px" href="/principal/get/csv-aduanet?idTrafico=<?= $this->idTrafico ?>&idPedimento=<?= $this->idPedimento ?>">
    CSV (Aduanet)
</a>
<button class="traffic-btn" id="send-aduanet" style="float:right; margin-top:5px">Enviar (Aduanet)</button>
<script src="/js/pedimentos/trafico-pedimento.js?<?= time() ?>"></script>