<table class="traffic-table">
    <thead>
        <tr>
            <th style="width: 90px">
                Pedimento
            </th>
            <td style="text-align: right;">
                <button onclick="descargaXmlpedimento()">Descargar XML</button>
            </td>
        </tr>
        <tr>
            <th style="width: 90px">
                COVES
            </th>
            <td style="text-align: left;">
                <?php foreach ($this->coves as $item) {
                    if ($item['edocument']) {
                        continue;
                    }
                    preg_match('/COVE[0-9A-Z]{9}/', $item['nom_archivo'], $m);
                ?>
                    <?= $item['nom_archivo'] ?>
                    <?= ($item['xml'] == null) ? "<button style=\"float: right\" onclick=\"descargaXmlCove(" . $item['id'] . ",'" . $m[0] . "');\">Descargar XML</button><br>" : '' ?><br>
                <?php } ?>
            </td>
        </tr>
        <!--<tr>
            <th style="width: 90px">
                EDOCUMENTS
            </th>
            <td style="text-align: left;">
                <?php foreach ($this->edocuments as $item) {
                    if ($item['edocument']) {
                        continue;
                    }
                    preg_match('/ED[0-9A-Z]{13}/', $item['nom_archivo'], $m);
                ?>
                    <?= $item['nom_archivo'] ?>
                    <?= ($item['xml'] == null) ? '<button style="float: right">Descargar XML</button>' : '' ?><br>
                <?php } ?>
            </td>
        </tr>-->
        <tr>
            <th>EDOCUMENTS</th>
            <td style="text-align: left;">
                <input type="text" name="numEdocument" id="numEdocument" />
                <button style="float: right" onclick="descargaManualEdocument()">
                    Descarga Manual XML
                </button>
            </td>
        </tr>
    </thead>
</table>
<table class="traffic-table">
    <thead>
        <tr>
            <th colspan="5">EDOCUMENTS PARA CONSULTA (11 pm)</th>
        </tr>
        <tr>
            <th>Edocument</th>
            <th>Mensaje</th>
            <th>Creado</th>
            <th>Actualizado</th>
            <th></th>
        </tr>
    </thead>
    <tbody id="eds-consulta">
        <?php foreach ($this->consultaEds as $item) { ?>
            <tr id="eds-consulta-<?= $item['id'] ?>">
                <td><?= $item['edocument'] ?></td>
                <td></td>
                <td><?= $item['creado'] ?></td>
                <td><?= $item['actualizado'] ?></td>
                <td><i class="fas fa-trash-alt" onclick="deleteEdocument(<?= $item['id'] ?>)" style="cursor: pointer"></i></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
<script src="/js/trafico/pedimentos/descarga.js"></script>