<style type="text/css">
    table.activities {
        width: 100%;
    }
    table.activities th,
    table.activities-form th {
        font-size: 12px;
        background: #f5f5f5;
        color: #333;
        height: 18px;
        line-height: 18px;
        top: 2px;
        padding: 0 3px;
        border-radius: 4px 4px 4px 4px;
        font-family: sans-serif !important;
    }    
    table.activities th.subtitle {
        background: #fafafa;
        color: #8d8d8d;
    }
    table.activities-form th,
    table.activities-form td {
        padding: 2px 2px;
        text-align: left;
    }
    table.activities tr {
        background: #fdfdfd;
    }
    table.activities td {
        font-size: 12px;
        color: #333;
        height: 18px;
        line-height: 18px;
        top: 2px;
        padding: 0 3px;
        border-radius: 4px 4px 4px 4px;
        font-family: sans-serif !important;        
    }
    table.activities tr:hover {
        background-color: #ffffdd;
    }
    tr.activityRow {
        cursor: pointer;
    }
</style>
<div class="row-fluid">
    <div class="span3">
        <div id="cc" style="width: 100%"></div>
    </div>
    <div class="span9"style="border: 1px #ddd solid">
        <table class="activities">
            <thead>
                <tr style="border-top: 1px #f3f3f3 solid; border-left: 1px #f3f3f3 solid; border-right: 1px #f3f3f3 solid">
                    <th colspan="4" style="text-align: left">Lista de actividades&nbsp;<div id="selectedDate" style="float: right"><?= date("Y-m-d") ?></div></th>
                </tr>
                <tr>
                    <th style="text-align: left; width: 150px">Usuario</th>
                    <th style="text-align: left">Actividad</th>
                    <th style="text-align: left; width: 75px">Fecha</th>
                    <th style="text-align: left; width: 125px">Creado</th>
                </tr>
            </thead>
            <tbody id="activities">
                <?php if (isset($this->actividades)) { ?>
                    <?php foreach ($this->actividades as $item) { ?>
                        <tr style="border: 1px #f3f3f3 solid">
                            <td style="padding: 3px; cursor: pointer" class="activityRow" data-id="<?= $item["id"] ?>"><?= mb_strtoupper($item["titulo"]) ?></td>
                            <td style="width: 20px; text-align: right">
                                <img data-id="<?= $item["id"] ?>" src="/images/icons/small_delete.png" class="deleteActivity" style="cursor: pointer"/>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } else { ?>
                    <tr style="border: 1px #f3f3f3 solid">
                        <td colspan="2" style="padding: 3px">
                            <em>No hay actividades.</em>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>        
    </div>
</div>
<div style="clear: both; height: 5px"></div>
<a onclick="window.history.back();" class="traffic-btn-back" style="margin-left: 6px">«&nbsp;Regresar</a>