<div class="traffic-cols">
    <div class="traffic-col-50">
        <form id="form">
            <table class="traffic-table traffic-table-left">
                <thead>
                    <tr>
                        <th style="width: 180px">Sistema operativo:</th>
                        <td>
                            <select id="sistemaOperativo" name="sistemaOperativo" class="traffic-select-medium">
                                <option value="">---</option>
                                <option value="android">Android</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <th>Aplicación:</th>
                        <td>
                            <select id="appName" name="appName" class="traffic-select-medium">
                                <option value="">---</option>
                                <option value="oaq-movil">OAQ Móvil</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <th>Versión:</th>
                        <td>
                            <input type="text" id="versionName" name="versionName" class="traffic-input-small" />
                        </td>
                    </tr>
                    <tr>
                        <th>Código:</th>
                        <td>
                            <input type="text" id="versionCode" name="versionCode" class="traffic-input-small" />
                        </td>
                    </tr>
                    <tr>
                        <th>Archivo:</th>
                        <td>
                            <input type="file" id="archivo" name="archivo" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <button id="submit" class="traffic-btn-create traffic-btn-right">Subir</button>
                        </td>
                    </tr>
                </thead>
            </table>
        </form>
    </div>
    <div class="traffic-col-50">
        <table class="traffic-table">
            <thead>
                <tr>
                    <th>S.O.</th>
                    <th>App</th>
                    <th>Versión</th>
                    <th>Código</th>
                    <th>Archivo</th>
                    <th>Actualización</th>
                </tr>
            </thead>
            <tbody>
                <?php if (isset($this->aplicaciones)) { ?>
                    <?php foreach ($this->aplicaciones as $item) { ?>
                        <tr>
                            <td><?= ucfirst($item["sistemaOperativo"]) ?></td>
                            <td><?= $item["appName"] ?></td>
                            <td><?= $item["versionName"] ?></td>
                            <td><?= $item["versionCode"] ?></td>
                            <td><?= $item["filename"] ?></td>
                            <td><?= $item["creado"] ?></td>
                        </tr>
                    <?php } ?>
                <?php } else { ?>
                    <tr>
                        <td colspan="6">
                            <em>No hay aplicaciones.</em>
                        </td>
                    </tr>
                <?php } ?>                
            </tbody>
        </table>
    </div>
</div>