<div class="row-fluid">
    <ul class="nav nav-tabs" id="traffic-tabs" style="margin-bottom: 0;">
        <li><a href="#information" data-toggle="tab">Datos usuario</a></li>
        <li><a href="#vucem" data-toggle="tab">VUCEM</a></li>
        <li><a href="#traffic" data-toggle="tab">Trafico</a></li>
        <li><a href="#validator" data-toggle="tab">Validador</a></li>
        <li><a href="#repository" data-toggle="tab">Expediente Digital</a></li>
        <li><a href="#warehouse" data-toggle="tab">Bodegas</a></li>
        <li><a href="#equipment" data-toggle="tab">Equipos y mantenimientos</a></li>
        <?php if (isset($this->inhouse)) { ?>
            <li><a href="#inhouseTab" data-toggle="tab">RFC Cliente</a></li>
            <li><a href="#documentosTab" data-toggle="tab">Documentos</a></li>
        <?php } ?>
    </ul>
    <div class="tab-content">
        <div class="tab-pane" id="information">
            <form method="post" id="formUsuario">
                <?php if (isset($this->idUsuario)) { ?>
                    <input type="hidden" name="idUsuario" value="<?= $this->idUsuario ?>" />
                <?php } ?>
                <table id="user-data" class="traffic-table traffic-table-left">
                    <tr>
                        <th colspan="2" class="traffic-table-title">DATOS DEL USUARIO</th>
                    </tr>
                    <?php if (isset($this->idUsuario)) { ?>
                        <tr>
                            <th>Habilitado:</th>
                            <td><?= $this->form->estatus ?></td>
                        </tr>
                    <?php } ?>
                    <tr>
                        <th style="width: 220px"><label for="nombre">Nombre del usuario:</label></th>
                        <td><?= $this->form->nombre ?></td>
                    </tr>
                    <tr>
                        <th><label for="email">Email:</label></th>
                        <td><?= $this->form->email ?></td>
                    </tr>
                    <tr>
                        <th><label for="usuario">Usuario:</label></th>
                        <td><?= $this->form->usuario ?></td>
                    </tr>
                    <tr>
                        <th><label for="empresa">Empresa:</label></th>
                        <td><?= $this->form->empresa ?></td>
                    </tr>
                    <tr>
                        <th><label for="patenteUsuario">Patente:</label></th>
                        <td><?= $this->form->patenteUsuario ?></td>
                    </tr>
                    <tr>
                        <th><label for="aduanaUsuario">Aduana:</label></th>
                        <td><?= $this->form->aduanaUsuario ?></td>
                    </tr>
                    <tr>
                        <th><label for="departamento">Departamento:</label></th>
                        <td><?= $this->form->departamento ?></td>
                    </tr>
                    <tr>
                        <th><label for="rol">Rol:</label></th>
                        <td><?= $this->form->rol ?></td>
                    </tr>
                    <tr>
                        <th><label for="password">Contraseña:</label></th>
                        <td>
                            <?= $this->form->password ?>
                            <button id="viewPassword" class="traffic-btn traffic-btn-small" style="width: 50px; min-width: 50px; margin-top: 3px">Ver</button>
                        </td>
                    </tr>
                    <tr>
                        <th><label for="confirm">Repetir Contraseña:</label></th>
                        <td><?= $this->form->confirm ?></td>
                    </tr>
                    <tr>
                        <th><label for="sispedimentos">Sistema de pedimentos:</label></th>
                        <td><?= $this->form->sispedimentos ?></td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <?php if (isset($this->idUsuario)) { ?>
                            <td>
                                <button id="actualizarUsuario" class="traffic-btn-right traffic-btn" style="">
                                    <i class="far fa-save"></i> Guardar
                                </button>
                            </td>
                        <?php } ?>
                    </tr>
                </table>
            </form>
        </div><!-- information -->
        <div class="tab-pane" id="vucem">
            <form method="post" id="formFiel">
                <input type="hidden" name="idUsuario" id="idUsuario" value="<?= $this->idUsuario ?>" />
                <table class="traffic-table traffic-table-left">
                    <tr>
                        <th colspan="4" class="traffic-table-title">SELLOS ASIGNADOS</th>
                    </tr>
                    <tr>
                        <th style="width: 360px">Razón Social:</th>
                        <th style="width: 130px">Patente:</th>
                        <th style="width: 130px">Aduana:</th>
                        <th>&nbsp;</th>
                    </tr>
                    <tr>
                        <td><?= $this->fiel->razonSocial ?></td>
                        <td>
                            <div id="patentesFiel"><?= $this->fiel->patenteFiel ?></div>
                        </td>
                        <td>
                            <div id="aduanasFiel"><?= $this->fiel->aduanaFiel ?></div>
                        </td>
                        <td>
                            <button id="agregarFiel" class="traffic-btn traffic-btn-right" style="">
                                <i class="fas fa-plus-circle"></i> Asignar
                            </button>
                        </td>
                    </tr>
                </table>
            </form>
            <div id="usuarioSellos" style="display: none; max-height: 350px; overflow-y: scroll"></div>
        </div><!-- vucem -->
        <div class="tab-pane" id="traffic">
            <form method="post" id="formTraffic">
                <input type="hidden" name="idUsuario" id="idUsuario" value="<?= $this->idUsuario ?>" />
                <table class="traffic-table traffic-table-left">
                    <tr>
                        <th colspan="4" class="traffic-table-title">ACCESO TRAFICO</th>
                    </tr>
                    <tr>
                        <th style="width: 350px">Aduana:</th>
                        <th style="width: 360px">Cliente:</th>
                        <th>&nbsp;</th>
                    </tr>
                    <tr>
                        <td>
                            <div id="traficoAduanas"><?= $this->selectAduanas("idAduana") ?></div>
                        </td>
                        <td>
                            <div id="traficoClientes"><?= $this->clientes ?></div>
                        </td>
                        <td>
                            <button id="agregarTrafico" class="traffic-btn traffic-btn-right" style="">
                                <i class="fas fa-plus-circle"></i> Asignar
                            </button>
                        </td>
                    </tr>
                </table>
            </form>
            <div id="usuarioTraficos" style="display: none"></div>
        </div><!-- traffic -->
        <div class="tab-pane" id="validator">
            <form method="post" id="formValidador">
                <input type="hidden" name="idUsuario" id="idUsuario" value="<?= $this->idUsuario ?>" />
                <table class="traffic-table traffic-table-left">
                    <tr>
                        <th colspan="2" class="traffic-table-title">VALIDADOR ASIGNADO</th>
                    </tr>
                    <tr>
                        <th>Aduana:</th>
                        <th>&nbsp;</th>
                    </tr>
                    <tr>
                        <td>
                            <div id="divIdAduanas"><?= $this->selectValidador("idAduanaValidador") ?></div>
                        </td>
                        <td>
                            <button id="addValidador" class="traffic-btn traffic-btn-right" style="">
                                <i class="fas fa-plus-circle"></i> Asignar
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="4">
                            <div id="validadorErrors"></div>
                        </td>
                    </tr>
                </table>
            </form>
            <div id="usuarioValidador" style="display: none"></div>
        </div><!-- validator -->
        <div class="tab-pane" id="repository">
            <form method="post" id="formRepositorio">
                <input type="hidden" name="idUsuario" id="idUsuario" value="<?= $this->idUsuario ?>" />
                <table class="traffic-table traffic-table-left">
                    <tr>
                        <th colspan="4" class="traffic-table-title">ACCESO EXPEDIENTE</th>
                    </tr>
                    <tr>
                        <th style="width: 125px">Patente:</th>
                        <th style="width: 125px">Aduana:</th>
                        <th colspan="2">&nbsp;</th>
                    </tr>
                    <tr>
                        <td>
                            <div id="divpatentes"><?= $this->repositorio->patentesExpediente ?></div>
                        </td>
                        <td>
                            <div id="divaduanas"><?= $this->repositorio->aduanasExpediente ?></div>
                        </td>
                        <td>
                            <input id="allCustoms" name="allCustoms" type="checkbox" style="float: left; margin-right: 5px">
                            <label style="float: left; margin-left: 5px; font-size: 11px !important" class="checkbox-label">Todas las aduanas</label>
                        </td>
                        <td>
                            <button id="agregarRepositorio" class="traffic-btn traffic-btn-right" style="">
                                <i class="fas fa-plus-circle"></i> Asignar
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="4">
                            <div id="archiveErrors"></div>
                        </td>
                    </tr>
                </table>
            </form>
            <div id="usuarioRepositorio" style="display: none; max-height: 390px"></div>
        </div><!-- repository -->

        <div class="tab-pane" id="warehouse">
            <form method="post" id="formWarehouse">
                <input type="hidden" name="idUsuario" id="idUsuario" value="<?= $this->idUsuario ?>" />
                <table class="traffic-table traffic-table-left">
                    <tr>
                        <th colspan="3" class="traffic-table-title">ACCESO EXPEDIENTE</th>
                    </tr>
                    <tr>
                        <th style="width: 125px">Bodega:</th>
                        <th colspan="2">&nbsp;</th>
                    </tr>
                    <tr>
                        <td>
                            <div id="divpatentes"><?= $this->bodegas->idBodega ?></div>
                        </td>
                        <td>
                            &nbsp;
                        </td>
                        <td>
                            <button id="addWarehouse" class="traffic-btn traffic-btn-right" style="">
                                <i class="fas fa-plus-circle"></i> Asignar
                            </button>
                        </td>
                    </tr>
                </table>
            </form>
            <div id="usuarioBodegas" style="display: none; max-height: 390px"></div>
        </div><!-- warehouse -->

        <div class="tab-pane" id="equipment">

            <table class="traffic-table traffic-table-center">
                <thead>
                    <tr>
                        <th colspan="8" class="traffic-table-title">EQUIPOS ASIGNADOS</th>
                    </tr>
                    <tr>
                        <th>NOMBRE (de red)</th>
                        <th>MARCA</th>
                        <th>MODELO</th>
                        <th>NUM. SERIE</th>
                        <th>ESTADO</th>
                        <th>ENTREGADA</th>
                        <th>REGRESADA</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (isset($this->equipos) && !empty($this->equipos)) { ?>
                        <?php foreach ($this->equipos as $item) { ?>
                            <tr>
                                <td style="width: 120px"><?= $item['nombre'] ?></td>
                                <td><?= $item['marca'] ?></td>
                                <td><?= $item['modelo'] ?></td>
                                <td><?= $item['numeroSerie'] ?></td>
                                <td>
                                    <?php if ($item['numeroSerie'] == 0) { ?>
                                        Equipo nuevo
                                    <?php } else if ($item['numeroSerie'] == 1) { ?>
                                        Equipo usado
                                    <?php } else { ?>
                                        Equipo reparado
                                    <?php } ?>
                                </td>
                                <td><?= isset($item['entregada']) ? date("d/m/Y", strtotime($item['entregada'])) : '&nbsp;' ?></td>
                                <td><?= isset($item['regresada']) ? date("d/m/Y", strtotime($item['regresada'])) : '&nbsp;' ?></td>
                                <td style="font-size: 1.2rem !important; width: 140px">
                                    <i class="fas fa-pencil-alt edit-equipment" style="cursor: pointer;" data-id="<?= $item['id'] ?>"></i>
                                    &nbsp;
                                    <i class="far fa-trash-alt"></i>
                                    &nbsp;
                                    <i class="fas fa-plus"></i>
                                    &nbsp;
                                    <a target="_blank" href="/usuarios/get/imprimir-comprobante?id=<?= $item['id'] ?>">
                                        <i class="fas fa-print"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php } ?>
                    <?php } else { ?>
                        <tr>
                            <td colspan="8" style="text-align: center;">
                                <em>El usuario no tiene equipos asignados.</em>
                            </td>
                        </tr>
                    <?php } ?>
                    <tr>
                        <td colspan="8">
                            <button class="traffic-btn-right traffic-btn add-equipment" data-id="<?= $this->idUsuario ?>">
                                <i class="far fa-save"></i> Agregar equipo
                            </button>
                        </td>
                    </tr>
                </tbody>
            </table>


        </div><!-- equipment -->

        <?php if (isset($this->inhouse)) { ?>
            <div class="tab-pane" id="inhouseTab">
                <form id="formInhouse">
                    <input type="hidden" name="idUsuario" id="idUsuario" value="<?= $this->idUsuario ?>" />
                    <table class="traffic-table traffic-table-left">
                        <tr>
                            <th colspan="3" class="traffic-table-title">RFC CLIENTE</th>
                        </tr>
                        <tr>
                            <th>
                                Cliente:
                            </th>
                            <td>
                                <?= $this->clientes ?>
                            </td>
                            <td>
                                <button id="agregarCliente" class="traffic-btn traffic-btn-right" style="">
                                    <i class="fas fa-plus-circle"></i> Agregar</button>
                            </td>
                        </tr>
                    </table>
                </form>
                <div id="inhouseRfc" style="display: none; max-height: 390px"></div>
            </div>
            <div class="tab-pane" id="documentosTab">
                <form id="permittedDocuments">
                    <?php if (isset($this->idUsuario)) { ?>
                        <input type="hidden" name="idUsuario" value="<?= $this->idUsuario ?>" />
                    <?php } ?>
                    <table cellspacing="0" cellpadding="0" border="0" width="100%" class="traffic-table traffic-table-left">
                        <tr>
                            <th class="traffic-table-title">DOCUMENTOS PARA VISUALIZAR</th>
                        </tr>
                        <tr>
                            <td>
                                <table cellspacing="0" cellpadding="1" border="1" width="100%" class="traffic-table traffic-table-left">
                                    <tr style="color:white;background-color:grey">
                                        <th style="width: 32px">&nbsp;</th>
                                        <th style="text-align: left; width: 50px">ID</th>
                                        <th style="text-align: left">NOMBRE</th>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div style="width:100%; height:460px; overflow:auto;">
                                    <table cellspacing="0" cellpadding="1" border="1" width="100%" class="traffic-table traffic-table-left hover" id="documentos">
                                        <?php if (isset($this->documentos)) { ?>
                                            <?php foreach ($this->documentos as $item) { ?>
                                                <tr>
                                                    <td style="text-align: center; width: 32px">
                                                        <input type="checkbox" class="document" data-id="<?= $item["id"] ?>" />
                                                    </td>
                                                    <td style="width: 50px"><?= $item["id"] ?></td>
                                                    <td><?= $item["nombre"] ?></td>
                                                </tr>
                                            <?php } ?>
                                        <?php } ?>
                                    </table>
                                </div>
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
        <?php } ?>
    </div>
    <div class="traffic-clear-5"></div>
    <a href="/usuarios/index/usuarios" class="traffic-btn" tabindex="99">
        <i class="fas fa-angle-double-left"></i>&nbsp;Regresar
    </a>
    <div class="traffic-clear"></div>
</div>
<div class="row-fluid-mobile">
    <table id="user-data" class="traffic-table traffic-table-left">
        <tr>
            <th colspan="2" class="traffic-table-title">DATOS DEL USUARIO</th>
        </tr>
        <?php if (isset($this->idUsuario)) { ?>
            <tr>
                <th style="width: 150px">Habilitado:</th>
                <td><?= $this->form->estatus ?></td>
            </tr>
        <?php } ?>
        <tr>
            <td colspan="2">
                <label for="nombre">Nombre del usuario:</label>
                <?= $this->form->nombre ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <label for="email">Email:</label>
                <?= $this->form->email ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <label for="usuario">Usuario:</label>
                <?= $this->form->usuario ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <label for="empresa">Empresa:</label>
                <?= $this->form->empresa ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <label for="patenteUsuario">Patente:</label>
                <?= $this->form->patenteUsuario ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <label for="aduanaUsuario">Aduana:</label>
                <?= $this->form->aduanaUsuario ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <label for="departamento">Departamento:</label>
                <?= $this->form->departamento ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <label for="rol">Rol:</label>
                <?= $this->form->rol ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <label for="password">Contraseña:</label>
                <?= $this->form->password ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <label for="confirm">Repetir contraseña:</label>
                <?= $this->form->confirm ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button id="actualizarUsuarioMobile" class="traffic-btn-right traffic-btn" style="">
                    <i class="far fa-save"></i> Guardar
                </button>
            </td>
        </tr>
    </table>
</div>