<div class="traffic-clear-10"></div>
<form id="add-action">
    <table class="traffic-table traffic-table-left">
        <tr>
            <th colspan="9" class="traffic-table-title">NUEVA ACCION</th>
        </tr>
        <tr>
            <th><label for="module">Modulo:</label></th>
            <td>
                <?php if (isset($this->modules)) { ?>
                    <select name="module" id="module">
                        <option value=''>---</option>
                        <?php foreach ($this->modules as $item) { ?>
                            <option value='<?= $item["id"] ?>'><?= $item["nombre"] ?></option>
                        <?php } ?>
                    </select>
                <?php } ?>
            </td>
            <th><label for="controller">Controlador:</label></th>
            <td>
                <?php if (isset($this->controllers)) { ?>
                    <select name="controller" id="controller">
                        <option value=''>---</option>
                        <?php foreach ($this->controllers as $item) { ?>
                            <option value='<?= $item["id"] ?>'><?= $item["modulo"] . '-' . $item["controlador"] ?></option>
                        <?php } ?>
                    </select>
                <?php } ?>
            </td>
        </tr>
        <tr>
            <th><label for="action">Accion:</label></th>
            <td>
                <input type="text" name="action" id="action">
            </td>
            <th><label for="name">Nombre:</label></th>
            <td>
                <input type="text" name="name" id="name">
            </td>
            <td>
                <button class="traffic-btn traffic-btn-primary" id="save-action">Agregar</button>
            </td>
        </tr>
    </table>
</form>
<form id="roles">    
    <table class="traffic-table traffic-table-left">
        <tr>
            <th colspan="3" class="traffic-table-title">CARGAR MENUS</th>
        </tr>
        <tr>
            <th style="width: 200px"><label for="rol">Rol</label></th>
            <td style="width: 250px">
                <?php if (isset($this->roles)) { ?>
                    <select name="rol" id="rol">
                        <option value=''>---</option>
                        <?php foreach ($this->roles as $item) { ?>
                            <option value='<?= $item["nombre"] ?>'><?= ucfirst($item["id"]) ?> - <?= ucfirst($item["nombre"]) ?></option>
                        <?php } ?>
                    </select>
                <?php } ?>
            </td>
            <td>
                <button class="traffic-btn traffic-btn-save" id="load">Cargar</button>
            </td>
        </tr>
    </table>
    <div id='estatus'></div>
    <div id='editor'></div>
</form>
<div class="traffic-clear-10"></div>
<a onclick="window.history.back();" class="traffic-btn traffic-btn-back">&Lt; Regresar</a>
<div class="traffic-clear-10"></div>