<div class="row-fluid">
    <div class="traffic-clear-5"></div>
    <?php if ($this->paginator) { ?>
        <table class="traffic-table hover" id="users-table">
            <thead>
                <tr>
                    <th>Aduana</th>
                    <th>Usuario</th>
                    <th>Nombre</th>
                    <th>Email</th>
                    <th>Rol</th>
                    <th>Último acceso</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $item) { ?>
                    <tr>
                        <td><?= $item["patente"] . '-' . $item["aduana"] ?></td>
                        <td>
                            <a href="/usuarios/index/editar-usuario?id=<?= $item["id"] ?>" style="display: float">
                                <?= $item["usuario"] ?>
                            </a>
                        </td>
                        <td><?= $item["nombre"] ?></td>
                        <td><?= $item["email"] ?></td>
                        <td><?= ucfirst($item["rol"]) ?></td>
                        <td><?= isset($item["acceso"]) ? date("d/m/Y H:i a", strtotime($item["acceso"])) : "" ?></td>
                        <td style="text-align: center; width: 24px">
                            <a href="/usuarios/index/editar-usuario?id=<?= $item["id"] ?>" style="font-size: 1.2em; margin-right: 5px">
                                <i class="fas fa-pencil-alt" style="cursor: pointer"></i>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
        <div class="traffic-clear-10"></div>
        <a class="traffic-btn traffic-btn-right" href="/usuarios/index/agregar-usuario">
            <i class="fas fa-plus"></i>&nbsp;Añadir usuario
        </a>
        <div class="traffic-clear-10"></div>
    <?php } ?>
</div>