<table class="traffic-table traffic-table-left hover" id="warehouseList">
    <thead>
        <tr>
            <th>Bodega</th>
            <th style="width: 32px">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php if ($this->data) { ?>
            <?php foreach ($this->data as $item) { ?>
                <tr>
                    <td style="text-align: left"><?= $item["nombreBodega"] ?></td>
                    <td>
                        <i class="far fa-trash-alt" onclick="removerBodega(<?= $item["id"] ?>, <?= $this->idUsuario ?>);" style="font-size: 1.3em; color: #2f3b58; cursor: pointer"></i>
                    </td>
                </tr>
            <?php } ?>
        <?php } else { ?>
            <tr>
                <td colspan="2" style="text-align: center"><em>El usuario no tiene bodegas asignadas.</em></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
    