<div style="float: left; margin-left: 2px">
    <h5 style="float: left; margin-left: 5px" style="margin: 0;">NUEVA MANIFESTACION DE VALOR</h5>
</div>

<form method="post" action="<?= $this->url ?>" id="form">
    <table class="traffic-table traffic-table-left">
        <tr>
            <th style="width: 150px; text-align: right"><label for="idAduana">ADUANA:<span style="color: red">*</span></label></th>
            <td colspan="3">
                <div style="float: right">
                    <span style="color: red">*</span>&nbsp;<span style="font-size: 10px">Campos requeridos.</span>
                </div>
                <?= $this->form->idAduana ?>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="cliente">CLIENTE:<span style="color: red">*</span></label></th>
            <td style="width: 360px">
                <div id="divcustomers"><?= $this->form->idCliente ?></div>
            </td>
            <td style="width: 100px">
                <label style="display: table-cell; float: left; font-weight: bold">RFC SOCIEDAD: </label>                
            </td>
            <td>
                <input type="text" id="rfcSociedad" value="" disabled="disabled" style="width: 150px"/>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="tipoOperacion">TIPO OPERACIÓN: <span style="color: red">*</span></label></th>
            <td colspan="3">
                <div id="divops"><?= $this->form->tipoOperacion ?></div>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="cvePedimento">CVE PED: <span style="color: red">*</span></label></th>
            <td colspan="3"><?= $this->form->cvePedimento ?></td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="pedimento">PEDIMENTO: <span style="color: red">*</span></label></th>
            <td colspan="3">
                <?= $this->form->pedimento ?>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="referencia">REFERENCIA: <span style="color: red">*</span></label></th>
            <td colspan="3">
                <?= $this->form->referencia ?>
            </td>
        </tr>
    </table>
</form>

<div class="traffic-clear-5"></div>

<a href="/manifestacion/index/index" class="traffic-btn">
    <i class="fas fa-angle-double-left"></i> Regresar</a>

<a class="traffic-btn traffic-btn-right" id="save">Guardar</a>
