<table class="traffic-table traffic-table-left">
    <tbody>
        <tr>
            <th style="text-align: right"><label for="aduana">ADUANA:<span style="color: red">*</span></label></th>
            <td><?= $this->form->aduana ?></td>
            <th>
                Facturas a transmitir
            </th>
        </tr>
        <tr>
            <th style="text-align: right"><label for="cliente">CLIENTE:<span style="color: red">*</span></label></th>
            <td>
                <div id="divcustomers"><?= $this->form->cliente ?></div>
            </td>
            <td rowspan="14" style="padding: 0 !important">
                <?php if (isset($this->rows) && !empty($this->rows)) { ?>
                    <table class="traffic-table traffic-table-left">
                        <tr>
                            <th>
                                Num. factura
                            </th>
                            <th>
                                Proveedor
                            </th>
                        </tr>
                        <?php foreach ($this->rows as $row) { ?>
                            <tr>
                                <td>
                                    <?= $row['numfactura']  ?>
                                </td>
                                <td>
                                    <?= $row['nomProveedor'] ?>
                                </td>
                            </tr>
                        <?php } ?>
                    </table>
                <?php } else { ?>
                    <p style="text-align: center;">
                        <em>
                            No hay facturas
                        </em>
                    </p>
                <?php } ?>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="planta">PLANTA:</label></th>
            <td>
                <div id="divplanta"><?= $this->form->planta ?></div>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="operacion">TIPO OPERACIÓN: <span style="color: red">*</span></label></th>
            <td>
                <div id="divops"><?= $this->form->operacion ?></div>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="cvePedimento">CVE PED: <span style="color: red">*</span></label></th>
            <td><?= $this->form->cvePedimento ?></td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="pedimento">PEDIMENTO: <span style="color: red">*</span></label></th>
            <td>
                <?= $this->form->pedimento ?><button id="consecutive" class="traffic-btn traffic-btn-small">Consecutivo</button>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="referencia">REFERENCIA: <span style="color: red">*</span></label></th>
            <td>
                <?= $this->form->referencia ?>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="referencia">GUÍA: <span style="color: red">*</span></label></th>
            <td>
                <?= $this->form->blGuia ?>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="consolidado">CONS:</label></th>
            <td><?= $this->form->consolidado ?></td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="rectificacion">RECT:</label></th>
            <td>
                <?= $this->form->rectificacion ?>
                <label for="pedimentoRectificar">Pedimento a rectificar:</label><input type="text" name="pedimentoRectificar" id="pedimentoRectificar" value="" class="traffic-input-small" readonly="true">
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="remesa">REMESA:</label></th>
            <td>
                <?= $this->form->remesa ?>
                <label for="referenciaOrigen">Ref. origen:</label><input type="text" name="referenciaOrigen" id="referenciaOrigen" value="" class="traffic-input-small" readonly="true">
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="contenedorCaja">CONT. / CAJA:</label></th>
            <td>
                <?= $this->form->contenedorCaja ?>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="tipoCambio">TIPO CAMBIO:</label></th>
            <td><?= $this->form->tipoCambio ?></td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="fechaEta">FECHA ETA: <span style="color: red">*</span></label></th>
            <td><?= $this->form->fechaEta ?></td>
        </tr>
    </tbody>
</table>
<script src="/js/operaciones/get/enviar-carta.js"></script>