<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="<?= $this->appConfig('website-description') ?>">
        <meta name="author" content="Jaime E. Valdez">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <title><?= $this->title ?></title>
        <link rel="icon" type="image/png" href="<?= $this->appConfig("favicon") ?>" />
        <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
        <?= $this->headMeta(); ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
        <!--[if lt IE 9]>
        <script src="/js/common/html5shiv/dist/html5shiv.js"></script>
        <![endif]-->
    </head>
    <body>
        <nav class="fixed-nav-bar">
            <!-- Fixed navigation bar content -->
            <a href="/v2/inicio/inicio">
                <img src="/images/oaq_queretaro_small.png" class="logo">
            </a>
            <p>
                <a href="/v2/trafico/inicio">Tráfico</a>
            </p>
            <p>
                <a href="/v2/usuarios/inicio">Usuarios</a>
            </p>
            <p class="right">
                <a id="logout">Salir</a>
            </p>
            <p class="right">
                <input type="text" placeholder="Buscar" id="buscar" class="search">
            </p>
        </nav>
        <div class="content"><?= $this->layout()->content ?></div>
    </body>
</html>
