<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="OAQ Web Portal">
  <meta name="author" content="Jaime E. Valdez">
  <title><?= $this->title ?></title>
  <link rel="icon" type="image/png" href="/favicon.png" />
  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <?= $this->headMeta(); ?>
  <?= $this->headLink() ?>
  <?= $this->headScript() ?>
  <!--[if lt IE 9]>
  <script src="/js/common/html5shiv/dist/html5shiv.js"></script>
  <![endif]-->
</head>
<style>
    body, html {
        margin: 0;
        height: 100%;
    }
</style>
<body>
    <code>
        <?= $this->layout()->content ?>
    </code><!-- wrap -->      
</body>
</html>