<fieldset>
    <h4>GRAFICAS</h4>
    <form method="get" action="<?= $this->url ?>">
        <table>
            <tr>
                <th>Patente</th>
                <th>Aduana</th>
                <th>Año</th>
                <th>&nbsp;</th>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td><button class="btn btn-primary btn-small" style="float: right;" value="Buscar" type="submit" id="submit" name="submit">Mostrar</button></td>
            </tr>
        </table>
    </form>
</fieldset>