<style>
    #datatable th.title {
        width: 75px;
    }
    #datatable td {
        background-color: #fff;
    }    
</style>
<?= $this->form ?>
<table>
    <tr>
        <td colspan="3" style="width: 100%; background-color: #fff">
            <div id="container-monthly" style="max-width: 100%; height: 300px; margin: 0"></div>
        </td>
    </tr>
    <tr>
        <td style="width: 450px; background-color: #fff">
            <div id="container-monthly-impexp-qro" style="max-width: 460px; height: 300px; margin: 0"></div>
        </td>
        <td style="width: 450px; background-color: #fff">
            <div id="container-monthly-impexp-aero" style="max-width: 460px; height: 300px; margin: 0"></div>            
        </td>
        <td>
            <div id="container-monthly-impexp-nl" style="max-width: 460px; height: 300px; margin: 0"></div>            
        </td>
    </tr>
</table>