<form id="form-validation" method="post">
    <input type="hidden" id="idUsuario" name="idUsuario" value="<?= $this->idUsuario ?>" />
    <table class="traffic-table">
        <tr>
            <th colspan="4" class="traffic-table-title">VALIDADOR WEB</th>
        </tr>
        <tr>
            <th><label for="patente">PATENTE:</label></th>
            <th><label for="aduana">ADUANA:</label></th>
            <th>&nbsp;</th>
            <th  style="text-align: right;">Buscar anteriores:</th>
        </tr>
        <tr>
            <td style="width: 100px;"><?= $this->form->patente ?></td>
            <td style="width: 100px;"><div id="divcustoms"><?= $this->form->aduana ?></div></td>
            <td>
                <div class="control-group" style="float:left;">
                    <button id="load-files" tabindex="5" class="traffic-btn">
                        <i class="fas fa-sync-alt"></i> Obtener archivos
                    </button>
                    <button id="uploadFile" tabindex="6" class="traffic-btn">
                        <i class="fas fa-upload"></i> Subir archivo
                    </button>
                </div>
            </td>
            <td style="text-align: right;">
                <input type="text" name="search" id="search" style="width: 110px;">
                <button id="search-files" class="traffic-btn traffic-btn-right">
                    <i class="fas fa-search"></i> Buscar
                </button>
            </td>
        </tr>
    </table> 
</form>
<div class="traffic-cols">
    <div class="traffic-col-70">
        <div style="float: left; width: 25%">
            <h4 class="traffic-section">VALIDACIÓN (M3)</h4>
            <div id="archivos" style="overflow-y: scroll; border: 1px #aaa solid; height: 280px; background-color: #f5f5f5; background: #f5f5f5;"></div>
        </div>
        <div style="float: left; width: 25%">
            <h4 class="traffic-section">PAGO</h4>
            <div id="pagos" style="overflow-y: scroll; border: 1px #aaa solid; height: 280px; background-color: #f5f5f5; background: #f5f5f5;"></div>
        </div>
        <div style="float: left; width: 50%">
            <div id="estatus" style="min-height: 270px; width: 100%"></div>
        </div>
    </div>
    <div class="traffic-col-30">
        <h4 class="traffic-section">ESTATUS VALIDADOR</h4>
        <div id="worker-status" style="overflow-y: scroll; border: 1px #aaa solid; width: 100%; height: 280px;"></div>
    </div>
</div><!-- traffic-cols -->
<div class="traffic-cols">
    <div class="traffic-col-70">
        <h4 class="traffic-section">CONTENIDO DE ARCHIVO</h4>
        <textarea id="file-content" style="height: 350px; width: 95%"></textarea>
        <div id="download-link"></div>
    </div>
    <div class="traffic-col-30">
        <h4 class="traffic-section">ARCHIVOS EN ASOCIACIÓN</h4>
            <div id="remote-files" style="height: 366px; overflow-y: scroll; background-color: #fff; border: 1px #bbb solid">                
                <table class="traffic-table traffic-table-left">
                    <thead>
                        <tr>
                            <td colspan="4" style="text-align: left">
                                Actualizar ftp: 
                                <button style="background: #f6f6f6; background-position: 3px 3px; border-radius: 5px; background-repeat: no-repeat; height: 24px; width: 24px;border: 1px #999 solid;background-image: url('/images/icons/refresh.png');" onclick="javascript:alert('Funcionalidad no disponible por el momento.')" id="reload-ftp">&nbsp;</button>
                                <div id="loading" style="float: right; margin-right: 5px; display: none"><img src="/images/preloader.gif" ></div>
                            </td>
                        </tr>
                        <tr>
                            <th>Archivo</th>
                            <th>Tamaño</th>
                            <th>Hora</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="4">&nbsp;</td>
                        </tr>                        
                    </tbody>
                </table>
            </div>
    </div>
</div><!-- traffic-cols -->
<table class="traffic-table"></table>
