<h4>VALIDACIÓN</h4>
<form id="form-validation" method="post" action="<?= $this->baseUrl() ?>/operaciones/data/obtener-archivos-validacion-historico">
    <table style="width: 100%;">
        <tr>
            <th>PATENTE:</th>
            <th>ADUANA:</th>
            <th>PEDIMENTO:</th>
            <th>&nbsp;</th>
        </tr>
        <tr>
            <td><?= $this->form->patente ?></td>
            <td><div id="divcustoms"><?= $this->form->aduana ?></div></td>
            <td><?= $this->form->pedimento ?></td>
            <td>
                <div class="control-group" style="float:right;">
                    <button id="load-files" tabindex="5" class="btn btn-primary btn-small" style="font-size:11px; padding: 1px 3px; margin-right: 2px;">Actualizar</button>
                </div>
            </td>
        </tr>
    </table> 
</form>
<div class="row-fluid">
    <div class="span6">
        <div id="files" style="height: 400px; overflow: scroll">&nbsp;</div>
    </div>
    <div class="span6">
        <div id="activity" style="height: 400px; overflow: scroll; background-color: #fff;"></div>
    </div>
</div>
<div class="row-fluid">    
    <div class="span12">
        <div id="descargar-archivo" style="display: none; font-size: 11px; font-family: sans-serif">
            Descargar archivo: <div id="descarga"></div>
        </div>
        <div id="files"><textarea id="file-content" style="width: 90%; height: 350px; padding: 5px; margin: 0;"></textarea></div>
    </div>
</div>