<form id="subdivision">    
    <input type="hidden" name="id" value="<?= $this->id ?>" />
    <input type="hidden" name="ids" value="<?= $this->ids ?>" />
    <table class="traffic-table traffic-table-left">
        <tbody>
            <tr>
                <th style="width: 180px">NUEVA REFERENCIA:</th>
                <td>
                    <input type="text" name="n_referencia" id="n_referencia" value="<?= $this->n_referencia ?>" />
                </td>
            </tr>
            <tr>
                <th>TOTAL DE BULTOS:</th>
                <td>
                    <input type="text" name="total_bultos" id="total_bultos" value="<?= $this->total ?>" readonly="true" />
                </td>
            </tr>
            <tr>
                <th>A SUBDIVIDIR:</th>
                <td>
                    <input type="text" name="a_subdividir" id="a_subdividir" value="<?= $this->cantidad ?>" readonly="true" />
                </td>
            </tr>
            <tr>
                <th>RESTANTES:</th>
                <td>
                    <input type="text" name="bultos_restantes" id="bultos_restantes" value="<?= $this->restantes ?>" readonly="true" />
                </td>
            </tr>
        </tbody>    
    </table>
</form>