<?php if ($this->data && $this->relfact == false) { ?>
    <div class="traffic-clear-5"></div>
    <a href="/vucem/index/index" class="traffic-btn">
        <i class="fas fa-angle-double-left"></i> Regresar</a>
    <div class="btn-group" style="float: right; margin-right: 5px">
        <a href="/vucem/data/download-xml?id=<?= $this->id ?>" target="_blank" class="traffic-btn">Descargar XML</a>
        <a href="/vucem/data/descarga-xml?id=<?= $this->id ?>" target="_blank" class="traffic-btn">Ver XML</a>
    </div>
    <div class="btn-group" style="float: right; margin-right: 5px">
        <a href="/automatizacion/vucem/imprimir-detalle-cove?id=<?= $this->id ?>&download=true" target="_blank" class="traffic-btn">Detalle COVE</a>
        <a href="/automatizacion/vucem/imprimir-acuse-cove?id=<?= $this->id ?>&download=true" target="_blank" class="traffic-btn">Acuse COVE</a>
    </div>
    <a href="/automatizacion/vucem/print-cove?id=<?= $this->id ?>&download=true" class="traffic-btn-right traffic-btn">Imprimir en PDF</a>
    <a href="/automatizacion/vucem/proforma-cove?uuid=<?= $this->uuid ?>" target="_blank" class="traffic-btn traffic-btn-right">PROFORMA</a>
    <div class="traffic-clear-5"></div>
    <div class="traffic-edocument">
        <?php if (isset($this->error)) { ?>
            <table class="table-error">
                <tr>
                    <th>ERRORES ENCONTRADOS</th>
                </tr>
                <?php if (is_array($this->error)) { ?>
                    <?php foreach ($this->error as $error) { ?>
                        <tr>
                            <td><?= utf8_encode($error) ?></td>
                        </tr>
                    <?php } ?>
                <?php } ?>            
                <?php if (isset($this->selloNoVigente)) { ?>
                    <tr>
                        <td>El sello con RFC <?= $this->selloNoVigente["rfc"] ?> ha sobrepasado su fecha de vigencia de <?= $this->selloNoVigente["vigencia"] ?> por lo que todas las operaciones en VUCEM ya no están permitidas, favor de comunicarse con el departamento de Comercialización para gestionar nuevos sellos.</td>
                    </tr>
                <?php } ?>
            </table>
        <?php } ?>
        <h4>Datos del comprobante <?= $this->valid($this->estatus, $this->cove) ?></h4>
        <p><strong>Referencia:</strong> <?= $this->referencia ?>, <strong>Pedimento:</strong> <?= $this->pedimento ?>, <strong>Solicitud:</strong> <?= $this->solicitud ?></p>
        <table class="traffic-table">
            <tr>
                <th>Tipo de operación</th>
                <th>Relación de facturas</th>
                <th>No. de factura</th>                
            </tr>
            <tr>
                <td><?= ($this->data["tipoOperacion"] == 'TOCE.EXP') ? 'Exportación' : 'Importación' ?></td>
                <td><?= (isset($this->data["numeroRelacionFacturas"])) ? 'CON RELACIÓN DE FACTURAS' : 'SIN RELACIÓN DE FACTURAS' ?></td>
                <td><?= $this->data["numeroFacturaOriginal"] ?></td>
            </tr>
            <tr>
                <th>Tipo de figura</th>                
                <th colspan="2">Fecha Exp.</th>                
            </tr>            
            <tr>
                <?php
                switch ($this->data["tipoFigura"]) {
                    case '1':
                        $tipoFigura = 'Agente aduanal';
                        break;
                    case '2':
                        $tipoFigura = 'Apoderado Aduanal';
                        break;
                    case '3':
                        $tipoFigura = 'Mandatario';
                        break;
                    case ('4' && $this->data["tipoOperacion"] == 'TOCE.IMP'):
                        $tipoFigura = 'Importador';
                        break;
                    case ('4' && $this->data["tipoOperacion"] == 'TOCE.EXP'):
                        $tipoFigura = 'Exportador';
                        break;
                }
                ?>
                <td><?= $tipoFigura ?></td>
                <td colspan="2"><?= $this->data["fechaExpedicion"] ?></td>
            </tr>
            <tr>
                <th colspan="3">Observaciones</th>
            </tr>
            <tr>
                <td colspan="3"><?= isset($this->data["observaciones"]) ? $this->data["observaciones"] : '&nbsp;' ?></td>
            </tr>
        </table>
        <h4>RFC con permisos de consulta</h4>
        <table>
            <tr>
                <th>RFC de consulta</th>
            </tr>
            <?php if (is_array($this->data["rfcConsulta"])) { ?>
                <?php foreach ($this->data["rfcConsulta"] as $rfcConsulta) { ?>
                    <tr>
                        <td><?= $rfcConsulta ?></td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <tr>
                    <td><?= (isset($this->data["rfcConsulta"])) ? $this->data["rfcConsulta"] : '&nbsp;' ?></td>
                </tr>
            <?php } ?>
        </table>
        <h4>Número de patente aduanal</h4>
        <table>
            <tr>
                <th>Número autorización aduanal</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["patenteAduanal"])) ? $this->data["patenteAduanal"] : '&nbsp;' ?></td>
            </tr>
        </table>
        <h4>Datos de la factura</h4>
        <table>
            <tr>
                <th>Subdivisión</th>
                <th>Certificado de origen</th>
                <th>No. de exportador autorizado</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["factura"]["subdivision"]) && (int) $this->data["factura"]["subdivision"] != 0) ? 'Con Subdivisión' : 'Sin subdivisión' ?></td>
                <td><?= (isset($this->data["factura"]["certificadoOrigen"]) && $this->data["factura"]["certificadoOrigen"] != 0 && !is_array($this->data["factura"]["certificadoOrigen"])) ? "Si funge como certificado de origen" : 'NO funge como certificado de origen' ?></td>
                <td><?= (isset($this->data["factura"]["numeroExportadorAutorizado"]) && $this->data["factura"]["numeroExportadorAutorizado"] != '') ? $this->data["factura"]["numeroExportadorAutorizado"] : '' ?></td>
            </tr>
        </table>    
        <h4>Datos generales del emisor</h4>
        <table>
            <tr>
                <th>Tipo de identificador</th>
                <th colspan="3">Tax ID/Sin Tax ID/RFC/CURP</th>
            </tr>
            <tr>
                <td><?= isset($this->data["emisor"]["tipoIdentificador"]) ? $this->identificadorDesc($this->data["emisor"]["tipoIdentificador"]) : '&nbsp;' ?></td>
                <td colspan="3"><?= (isset($this->data["emisor"]["identificacion"]) && $this->data["emisor"]["identificacion"] != '0') ? $this->data["emisor"]["identificacion"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Nombre(s) o Razón Social</th>
                <th>Apellido paterno</th>
                <th colspan="2">Apellido materno</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["emisor"]["nombre"]) && $this->data["emisor"]["nombre"] != '') ? $this->data["emisor"]["nombre"] : '&nbsp;' ?></td>
                <td>&nbsp;</td>
                <td colspan="2">&nbsp;</td>
            </tr>
            <tr>
                <th>Calle</th>
                <th>No. exterior</th>
                <th>No. interior</th>
                <th>Código postal</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["emisor"]["domicilio"]["calle"]) && $this->data["emisor"]["domicilio"]["calle"] != '') ? $this->data["emisor"]["domicilio"]["calle"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["emisor"]["domicilio"]["numeroExterior"]) && $this->data["emisor"]["domicilio"]["numeroExterior"] != '') ? $this->data["emisor"]["domicilio"]["numeroExterior"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["emisor"]["domicilio"]["numeroInterior"]) && $this->data["emisor"]["domicilio"]["numeroInterior"] != '') ? $this->data["emisor"]["domicilio"]["numeroInterior"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["emisor"]["domicilio"]["codigoPostal"]) && $this->data["emisor"]["domicilio"]["codigoPostal"] != '') ? $this->data["emisor"]["domicilio"]["codigoPostal"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Colonia</th>
                <th colspan="3">Localidad (Ciudad)</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["emisor"]["domicilio"]["colonia"]) && $this->data["emisor"]["domicilio"]["colonia"] != '') ? $this->data["emisor"]["domicilio"]["colonia"] : '&nbsp;' ?></td>
                <td colspan="3"><?= (isset($this->data["emisor"]["domicilio"]["localidad"]) && $this->data["emisor"]["domicilio"]["localidad"] != '') ? $this->data["emisor"]["domicilio"]["localidad"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Municipio</th>
                <th colspan="3">Entidad federativa</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["emisor"]["domicilio"]["municipio"]) && $this->data["emisor"]["domicilio"]["municipio"] != '') ? $this->data["emisor"]["domicilio"]["municipio"] : '&nbsp;' ?></td>
                <td colspan="3"><?= (isset($this->data["emisor"]["domicilio"]["entidadFederativa"]) && $this->data["emisor"]["domicilio"]["entidadFederativa"] != '') ? $this->data["emisor"]["domicilio"]["entidadFederativa"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th colspan="4">País</th>
            </tr>
            <tr>
                <td colspan="4"><?= (isset($this->data["emisor"]["domicilio"]["pais"]) && $this->data["emisor"]["domicilio"]["pais"] != '') ? $this->data["emisor"]["domicilio"]["pais"] : '&nbsp;' ?></td>
            </tr>
        </table>
        <h4>Datos generales del destinatario</h4>
        <table>
            <tr>
                <th>Tipo de identificador</th>
                <th colspan="3">Tax ID/Sin Tax ID/RFC/CURP</th>                
            </tr>
            <tr>
                <td><?= (isset($this->data["destinatario"]["tipoIdentificador"])) ? $this->identificadorDesc($this->data["destinatario"]["tipoIdentificador"]) : '&nbsp;' ?></td>
                <td colspan="3"><?= (isset($this->data["destinatario"]["identificacion"]) && $this->data["destinatario"]["identificacion"] != '') ? $this->data["destinatario"]["identificacion"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Nombre(s) o Razón Social</th>
                <th>Apellido paterno</th>
                <th colspan="2">Apellido materno</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["destinatario"]["nombre"]) && $this->data["destinatario"]["nombre"] != '') ? $this->data["destinatario"]["nombre"] : '&nbsp;' ?></td>
                <td>&nbsp;</td>
                <td colspan="2">&nbsp;</td>
            </tr>
            <tr>
                <th>Calle</th>
                <th>No. exterior</th>
                <th>No. interior</th>
                <th>Código postal</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["destinatario"]["domicilio"]["calle"]) && $this->data["destinatario"]["domicilio"]["calle"] != '') ? $this->data["destinatario"]["domicilio"]["calle"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["destinatario"]["domicilio"]["numeroExterior"]) && $this->data["destinatario"]["domicilio"]["numeroExterior"] != '') ? $this->data["destinatario"]["domicilio"]["numeroExterior"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["destinatario"]["domicilio"]["numeroInterior"]) && $this->data["destinatario"]["domicilio"]["numeroInterior"] != '') ? $this->data["destinatario"]["domicilio"]["numeroInterior"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["destinatario"]["domicilio"]["codigoPostal"]) && $this->data["destinatario"]["domicilio"]["codigoPostal"] != '') ? $this->data["destinatario"]["domicilio"]["codigoPostal"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Colonia</th>
                <th colspan="3">Localidad (Ciudad)</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["destinatario"]["domicilio"]["colonia"]) && $this->data["destinatario"]["domicilio"]["colonia"] != '') ? $this->data["destinatario"]["domicilio"]["colonia"] : '&nbsp;' ?></td>
                <td colspan="3"><?= (isset($this->data["destinatario"]["domicilio"]["localidad"]) && $this->data["destinatario"]["domicilio"]["localidad"] != '') ? $this->data["destinatario"]["domicilio"]["localidad"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Municipio</th>
                <th colspan="3">Entidad federativa</th>
            </tr>
            <tr>        
                <td><?= (isset($this->data["destinatario"]["domicilio"]["municipio"]) && $this->data["destinatario"]["domicilio"]["municipio"] != '') ? $this->data["destinatario"]["domicilio"]["municipio"] : '&nbsp;' ?></td>
                <td colspan="3"><?= (isset($this->data["destinatario"]["domicilio"]["entidadFederativa"]) && $this->data["destinatario"]["domicilio"]["entidadFederativa"] != '') ? $this->data["destinatario"]["domicilio"]["entidadFederativa"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th colspan="4">País</th>
            </tr>
            <tr>
                <td colspan="4"><?= (isset($this->data["destinatario"]["domicilio"]["pais"]) && $this->data["destinatario"]["domicilio"]["pais"] != '') ? $this->data["destinatario"]["domicilio"]["pais"] : '&nbsp;' ?></td>
            </tr>
        </table>
        <h4>Datos de la mercancía</h4>
        <table>
            <tr>
                <th>Descripción genérica de la mercancía</th>
                <th>Num.Parte</th>
                <th>Tipo moneda</th>
                <th>Valor unitario</th>
                <th>Valor total</th>
                <th>Valor total en dólares</th>
                <th>Clave OMA</th>
                <th>Cantidad OMA</th>
            </tr>
            <?php if (isset($this->data["mercancias"]["descripcionGenerica"])) { ?>
                <tr>
                    <td><?= (isset($this->data["mercancias"]["descripcionGenerica"]) && $this->data["mercancias"]["descripcionGenerica"] != '') ? $this->data["mercancias"]["descripcionGenerica"] : '&nbsp;' ?></td>
                    <td style="text-align: center"><?= (isset($this->data["mercancias"]["numparte"]) && $this->data["mercancias"]["numparte"] != '') ? $this->data["mercancias"]["numparte"] : '&nbsp;' ?></td>
                    <td style="text-align: center"><?= (isset($this->data["mercancias"]["tipoMoneda"]) && $this->data["mercancias"]["tipoMoneda"] != '') ? $this->data["mercancias"]["tipoMoneda"] : '&nbsp;' ?></td>
                    <td style="text-align: right"><?= (isset($this->data["mercancias"]["valorUnitario"]) && $this->data["mercancias"]["valorUnitario"] != '') ? '$ ' . $this->number6($this->data["mercancias"]["valorUnitario"]) : '&nbsp;' ?></td>
                    <td style="text-align: right"><?= (isset($this->data["mercancias"]["valorTotal"]) && $this->data["mercancias"]["valorTotal"] != '') ? '$ ' . $this->number6($this->data["mercancias"]["valorTotal"]) : '&nbsp;' ?></td>
                    <td style="text-align: right"><?= (isset($this->data["mercancias"]["valorDolares"]) && $this->data["mercancias"]["valorDolares"] != '') ? '$ ' . $this->number4($this->data["mercancias"]["valorDolares"]) : '&nbsp;' ?></td>        
                    <td style="text-align: center"><?= (isset($this->data["mercancias"]["claveUnidadMedida"]) && $this->data["mercancias"]["claveUnidadMedida"] != '') ? $this->data["mercancias"]["claveUnidadMedida"] : '&nbsp;' ?></td>
                    <td style="text-align: right"><?= (isset($this->data["mercancias"]["cantidad"]) && $this->data["mercancias"]["cantidad"] != '') ? $this->number($this->data["mercancias"]["cantidad"]) : '&nbsp;' ?></td>
                </tr>
                <?php if (isset($this->data["mercancias"]["descripcionesEspecificas"])) { ?>
                    <tr>
                        <td colspan="8" style="margin:0; padding: 0;">
                            <table class="merc" style="width: 100%">
                                <tr>
                                    <th style="border-left:0;">Marca</th>
                                    <th>Modelo</th>
                                    <th>Submodelo</th>
                                    <th>Num. de Serie</th>
                                </tr>
                                <tr>
                                    <td style="text-align: left"><?= (isset($this->data["mercancias"]["descripcionesEspecificas"]["marca"])) ? $this->data["mercancias"]["descripcionesEspecificas"]["marca"] : '&nbsp;' ?></td>
                                    <td style="text-align: center"><?= (isset($this->data["mercancias"]["descripcionesEspecificas"]["modelo"])) ? $this->data["mercancias"]["descripcionesEspecificas"]["modelo"] : '&nbsp;' ?></td>
                                    <td style="text-align: center"><?= (isset($this->data["mercancias"]["descripcionesEspecificas"]["subModelo"])) ? $this->data["mercancias"]["descripcionesEspecificas"]["subModelo"] : '&nbsp;' ?></td>
                                    <td style="text-align: center"><?= (isset($this->data["mercancias"]["descripcionesEspecificas"]["numeroSerie"])) ? $this->data["mercancias"]["descripcionesEspecificas"]["numeroSerie"] : '&nbsp;' ?></td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                <?php } ?>
            <?php } elseif (isset($this->data["mercancias"][0]["descripcionGenerica"])) { ?>
                <?php foreach ($this->data["mercancias"] as $merc) { ?>
                    <tr>
                        <td><?= (isset($merc["descripcionGenerica"]) && $merc["descripcionGenerica"] != '') ? $merc["descripcionGenerica"] : '&nbsp;' ?></td>
                        <td style="text-align: center"><?= (isset($merc["numparte"]) && $merc["numparte"] != '') ? $merc["numparte"] : '&nbsp;' ?></td>
                        <td style="text-align: center"><?= (isset($merc["tipoMoneda"]) && $merc["tipoMoneda"] != '') ? $merc["tipoMoneda"] : '&nbsp;' ?></td>
                        <td style="text-align: right"><?= (isset($merc["valorUnitario"]) && $merc["valorUnitario"] != '') ? '$ ' . $this->number6($merc["valorUnitario"]) : '&nbsp;' ?></td>
                        <td style="text-align: right"><?= (isset($merc["valorTotal"]) && $merc["valorTotal"] != '') ? '$ ' . $this->number6($merc["valorTotal"]) : '&nbsp;' ?></td>
                        <td style="text-align: right"><?= (isset($merc["valorDolares"]) && $merc["valorDolares"] != '') ? '$ ' . $this->number4($merc["valorDolares"]) : '&nbsp;' ?></td>        
                        <td style="text-align: center"><?= (isset($merc["claveUnidadMedida"]) && $merc["claveUnidadMedida"] != '') ? $merc["claveUnidadMedida"] : '&nbsp;' ?></td>
                        <td style="text-align: right"><?= (isset($merc["cantidad"]) && $merc["cantidad"] != '') ? $this->number($merc["cantidad"]) : '&nbsp;' ?></td>
                    </tr>    
                    <?php if (isset($merc["descripcionesEspecificas"])) { ?>
                        <tr>
                            <td colspan="8" style="margin:0; padding: 0;">
                                <table class="merc" style="width: 100%">
                                    <tr>
                                        <th style="border-left:0;">Marca</th>
                                        <th>Modelo</th>
                                        <th>Submodelo</th>
                                        <th>Num. de Serie</th>
                                    </tr>
                                    <tr>
                                        <td style="text-align: left"><?= (isset($merc["descripcionesEspecificas"]["marca"])) ? $merc["descripcionesEspecificas"]["marca"] : '&nbsp;' ?></td>
                                        <td style="text-align: center"><?= (isset($merc["descripcionesEspecificas"]["modelo"])) ? $merc["descripcionesEspecificas"]["modelo"] : '&nbsp;' ?></td>
                                        <td style="text-align: center"><?= (isset($merc["descripcionesEspecificas"]["subModelo"])) ? $merc["descripcionesEspecificas"]["subModelo"] : '&nbsp;' ?></td>
                                        <td style="text-align: center"><?= (isset($merc["descripcionesEspecificas"]["numeroSerie"])) ? $merc["descripcionesEspecificas"]["numeroSerie"] : '&nbsp;' ?></td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } ?>
            <?php } ?>    
        </table>
        <h4>Datos del COVE (Firma electrónica)</h4>
        <table>
            <tr>
                <th>Cadena original</th>
            </tr>
            <tr>
                <td class="signature"><?= (isset($this->data["firmaElectronica"]["cadenaOriginal"]) && $this->data["firmaElectronica"]["cadenaOriginal"] != '') ? wordwrap($this->data["firmaElectronica"]["cadenaOriginal"], 100, "<br />", true) : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Firma</th>
            </tr>
            <tr>
                <td class="signature"><?= (isset($this->data["firmaElectronica"]["firma"]) && $this->data["firmaElectronica"]["firma"] != '') ? wordwrap($this->data["firmaElectronica"]["firma"], 100, "<br />", true) : '&nbsp;' ?></td>
            </tr>
        </table>
    </div>
    <p class="legend" style="font-size:11px">Esto es una representación gráfica del XML de un COVE su uso es exclusivo para interpretar la información de una forma más clara, su valides ante la autoridad es de 240 días a partir de la fecha de solicitud ya que es borrado de la base de datos de Ventanilla Única, pasado este tiempo su valides es meramente histórica. Este acuse no sustituye el de Ventanilla Única y es generado por el sistema VUCEM OAQ como alternativa. Solicitud generada el día <?= $this->fechas["enviado"] ?> y fue actualizada el día <?= $this->fechas["actualizado"] ?>.</p>
    <?php //} ?>
<?php } ?>
<div class="traffic-clear-5"></div>
<a href="/vucem/index/index" class="traffic-btn">
    <i class="fas fa-angle-double-left"></i> Regresar</a>