    <div class="traffic-clear-5"></div>
<a href="<?= $this->url(array('action' => 'e-documents')) ?>" class="traffic-btn">
    <i class="fas fa-angle-double-left"></i> Regresar</a>
<?php if (isset($this->solicitud)) { ?>
    <a href="/automatizacion/vucem/imprimir-acuse-edocument?uuid=<?= $this->id ?>&solicitud=<?= $this->solicitud ?>" target="_blank" class="traffic-btn traffic-btn-right">IMPRIMIR PDF</a>
<?php } ?>
<a href="<?= $this->url(array('controller' => 'data', 'action' => 'xml-edocument')) ?>?id=<?= $this->data["id"] ?>" target="_blank" class="traffic-btn traffic-btn-right">XML EDOCUMENT</a>
<button class="button-save" style="width: 160px" data-id="<?= $this->idEdoc ?>" data-solicitud="<?= $this->solicitud ?>">Guardar en repositorio</button>
<div class="traffic-clear-5"></div>
<div class="traffic-edocument" style="padding: 5px">
    <?php if(isset($this->error)) { ?>
        <table class="table-error">
            <tr>
                <th>ERRORES ENCONTRADOS</th>
            </tr>
            <?php if(is_array($this->error)) { ?>
                <?php foreach ($this->error as $error) { ?>
                <tr>
                    <td><?= $error ?></td>
                </tr>
                <?php } ?>
            <?php } ?>            
        </table>
    <?php } ?>
    <table style="border-top: 1px #e5e5e5 solid;">
        <tr>
            <td align="left"><h3>ACUSE DIGITALIZACIÓN DE DOCUMENTOS</h3></td>
        </tr>
        <tr>
            <td align="left" style="text-align: left"><p style="font-size: 13px"><strong>Referencia:</strong> <?= $this->data["referencia"] ?>, <strong>Pedimento:</strong> <?= $this->data["pedimento"] ?>, <strong>Solicitud:</strong> <?= isset($this->solicitud) ? $this->solicitud : '<span style="color: red">NO COMPLETADO</span>' ?></p></td>
        </tr>
        <tr>
            <td align="right" style="text-align: left"><strong>Folio de la solicitud:</strong> <?= isset($this->data["numTramite"]) ? $this->data["numTramite"] : '' ?></td>
        </tr>
        <tr>
            <td style="text-align: left"><strong>RFC:</strong> <?= $this->data["rfc"] ?><br />Siendo las <?= date('H:i', strtotime($this->data["enviado"])) ?> del <?= date('d/m/Y', strtotime($this->data["enviado"])) ?> se tiene por recibida y atendida la solicitud de registro de Documentos Digitalizados presentado a través de la ventanilla única (Web Service).</td>
        </tr>
    </table>
    <table>
        <tr>            
            <th class="invoice-title" colspan="2">Los datos del documento son los siguientes:</th>
        </tr>
        <tr>
            <th>Operación</th>
            <th>Registro de documentos digitalizados</th>
        </tr>
        <tr>
            <td>Número E-Document</td>
            <td><?= isset($this->data["edoc"]) ? $this->data["edoc"] : '<span style="color: red">NO COMPLETADO</span>' ?></td>
        </tr>
        <tr>
            <td>Tipo de documento</td>
            <td><?= $this->tipoEdoc($this->data["tipoDoc"]) ?></td>
        </tr>
        <tr>
            <td>Nombre del documento</td>
            <td><?= $this->data["nomArchivo"] ?></td>
        </tr>
        <tr>
            <td>RFC de consulta</td>
            <td><?= isset($this->data["rfcConsulta"]) ? $this->data["rfcConsulta"] : 'OAQ030623UL8' ?></td>
        </tr>
        <tr>
            <td>Cadena original</td>
            <td><?= $this->data["cadena"] ?></td>
        </tr>
        <tr>
            <td>Sello digital del solicitante (del documento)</td>
            <td>
                <?= wordwrap($this->data["firma"], 90, "<br />", true) ?>
            </td>
        </tr>
        <tr>
            <td>Leyenda</td>
            <td>Tiene 90 días a partir de esta fecha para utilizar su documento digitalizado, si en ese tiempo no lo utiliza, será dado de baja del sistema de la Ventanilla Única.</td>
        </tr>
    </table>
    <div class="traffic-clear-10"></div>        
</div>