<table class="traffic-table traffic-table-left">
    <tr>
        <td style="width: 30px"><div class="statusCove"></div></td>
        <td>No enviado</td>
        <td style="width: 30px"><div class="statusCove sent"></div></td>
        <td>Enviado a VU</td>
        <td style="width: 30px"><div class="statusCove cove"></div></td>
        <td>EDocument recibido</td>        
    </tr>
    <tr>
        <td><div class="statusCove error"></div></td>
        <td>Error en COVE, dar clic sobre cuadro para ver error.</td>
        <td><i class="icon icon-file"></i></td>
        <td>Consultar/ver el COVE</td>
        <td colspan="2"><strong>Importante:</strong>&nbsp;Las horas y fechas aquí mostradas (Servidor) pueden diferir de la de su equipo (PC). Sin embargo <strong>no</strong> afectan el proceso de entrega y recepción en VUCEM.</td>
    </tr>
    <tr>

    </tr>
</table>    
<div class="traffic-clear-5"></div>
<a class="traffic-btn" onclick="downloadAllEdocuments();">
    <i class="fas fa-download"></i> Descargar
</a>&nbsp;
<a class="traffic-btn" onclick="selectAllEdocuments();">
    <i class="fas fa-check-square"></i> Seleccionar todo
</a>&nbsp;
<a class="traffic-btn" onclick="unselectAllEdocuments();">
    <i class="far fa-square"></i> Quitar selección
</a>
<div class="traffic-clear-5"></div>
<table cellpadding="0" cellspacing="0" border="0" class="traffic-table hover" id="example">
    <thead>
        <tr>
            <th style="width: 30px">&nbsp;</th>
            <th style="width: 30px">&nbsp;</th>
            <th>Acción</th>
            <th>RFC</th>
            <th>Pedimento</th>
            <th>Referencia</th>
            <th>TipDoc</th>
            <th>Nom. Archivo</th>
            <th>EDOC</th>
            <th>Tamaño (Mb)</th>
            <th>Enviado</th>
            <th>Actualizado</th>
            <th>Usuario</th>
        </tr>
    </thead>
    <tbody>
        <?php if (isset($this->result)) { ?>
            <?php foreach ($this->result as $item) { ?>
                <tr id="row_<?= $item["id"] ?>">
                    <td>
                        <?php if ($item["expediente"] == 1 && $item["estatus"] > 1) { ?>
                            <input type="checkbox" name="files" value="<?= $item["edoc"] ?>" >
                        <?php } else { ?>
                            <?php if ($item["estatus"] == 1) { ?>
                                <!--<div class="traffic-icon traffic-icon-vucem" onclick="checkVucem(<?= $item["id"] ?>);"></div>-->
                                <i class="fab fa-uniregistry" onclick="checkVucem(<?= $item["id"] ?>);" style="color: #0099ff; margin-right: 5px; font-size: 1.3em"></i>
                            <?php } else { ?>
                                &nbsp;
                            <?php } ?>
                        <?php } ?>
                    </td>
                    <td><?= $this->estatusEdoc($item["estatus"], $item["id"]) ?></td>
                    <td>
                        <?php if ($item["estatus"] == 1 && isset($this->delete)) { ?>
                            <div class="traffic-icon traffic-icon-delete" onclick="borrarEdoc(<?= $item["id"] ?>);"></div>
                        <?php } ?>
                        <?= $this->accionEdoc($item["estatus"], $item["uuid"], $item["solicitud"], $item["edoc"], $item["expediente"], $item["id"]) ?>
                    </td>
                    <td><?= $item["rfc"] ?></td>
                    <td><?= $item["aduana"] . "-" . $item["patente"] . "-" . $item["pedimento"] ?></td>
                    <td><?= $item["referencia"] ?></td>
                    <td><a href="#" title="<?= $this->tipoEdoc($item["tipoDoc"]) ?>"><?= $item["tipoDoc"] ?></a></td>
                    <td style="text-align: left">
                        <?php if ($item["size"] > 1) { ?>                    
                            <!--<img src="/images/icons/eye-24-gray.png" class="openFile" data-id="<?= $item["id"] ?>" style="cursor: pointer; float: right" />-->
                            <div style="font-size:1.2em; color: #2f3b58; float: right; margin-right: 5px; margin-top: 2px">                                
                                <i class="fas fa-eye openFile" data-id="<?= $item["id"] ?>" style="cursor: pointer"></i>
                            </div>
                            <a href="/vucem/data/descargar-archivo?uuid=<?= $item["uuid"] ?>&solicitud=<?= $item["solicitud"] ?>">
                                    <?php if(strlen($item["nomArchivo"]) < 60) { 
                                            echo $item["nomArchivo"];
                                        } else { 
                                            echo substr($item["nomArchivo"], 0, 20) . " ... .pdf";
                                        } ?>
                            </a>
                        <?php } else { ?>
                            <?php if(strlen($item["nomArchivo"]) < 60) { 
                                echo $item["nomArchivo"];
                            } else { 
                                echo substr($item["nomArchivo"], 0, 20) . " ... .pdf";
                            } ?>
                        <?php } ?>
                    </td>
                    <td><?= isset($item["edoc"]) ? '<a href="/vucem/index/consultar-edoc-enviado?uuid=' . $item["uuid"] . '&solicitud=' . $item["solicitud"] . '">' . $item["edoc"] . '</a>' : '' ?></td>                    
                    <td><?= ($item["size"] > 1) ? round($item["size"] / 1024 / 1024, 2) . " mb" : "" ?></td>
                    <td><?= (isset($item["enviado"])) ? date('d/m/Y h:i a', strtotime($item["enviado"])) : '' ?></td>
                    <td><?= (isset($item["actualizado"])) ? date('d/m/Y h:i a', strtotime($item["actualizado"])) : '' ?></td>
                    <td><?= $item["usuario"] ?></td>
                </tr>
            <?php } ?>
        <?php } else { ?>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><em>No hay Edocuments</em></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
        <?php } ?>
    </tbody>
</table>
<a href="/vucem/index/digitalizar-documentos" class="traffic-btn">
    <i class="fas fa-file-alt"></i> Nuevo E-Document
</a>
<a href="#" id="gearman-reload" class="traffic-btn-close traffic-btn-right" style="min-width: 30px">
    <i class="fas fa-redo-alt"></i>
</a>
<a href="#" id="refresh" class="traffic-btn traffic-btn-right">
    <i class="fas fa-sync-alt"></i> Actualizar
</a>
<a href="#" id="refresh-hdd" class="traffic-btn traffic-btn-right" style="min-width: 30px">
    <i class="fas fa-hdd"></i>
</a>
<div class="traffic-clear-5"></div>
<form action="<?= $this->url() ?>" method="get">
    <table class="traffic-table traffic-table-left">
        <tr>
            <th colspan="4">BURCAR EDOCUMENTS ANTERIORES</th>
        </tr>
        <tr>
            <td style="width: 220px">
                <label style="font-weight: bold">EDOCUMENT:</label>
                <input type="text" name="edoc" class="traffic-input-medium" value="<?= $this->edocument ?>" />
            </td>
            <td style="width: 220px">
                <label style="font-weight: bold">REFERENCIA:</label>
                <input type="text" name="referencia" class="traffic-input-medium" value="<?= $this->referencia ?>" />
            </td>
            <td style="width: 220px">
                <label style="font-weight: bold">PEDIMENTO:</label>
                <input type="text" name="pedimento" class="traffic-input-medium" value="<?= $this->pedimento ?>" />
            </td>
            <td style="text-align: right">
                <button type="submit" class="traffic-btn traffic-btn-right">
                    <i class="fas fa-search"></i> Buscar
                </button>
                <a class="traffic-btn traffic-btn-right" href="/vucem/index/e-documents">
                    <i class="fas fa-broom"></i> Limpiar
                </a>
            </td>
        </tr>
    </table>
</form>
