<div class="traffic-clear-5"></div>
<div class="traffic-edocument">
    <h4>Error encontrado en COVE</h4>
    <table>
        <tr>
            <th>Num. Operación</th>
            <th>Factura</th>
        </tr>
        <tr>
            <td><?= $this->operacion ?></td>
            <td><?= $this->factura ?></td>
        </tr>
        <tr>
            <th colspan="2">Errores encontrados</th>
        </tr>    
        <tr>
            <td colspan="2">
                <?php
                if (is_array($this->errores)) {
                    foreach ($this->errores as $err) {
                        echo $err . '<br />';
                    }
                } else {
                    echo $this->errores . '<br />';
                }
                ?>
            </td>
        </tr>
    </table>
</div>
<div class="traffic-clear-5"></div>
<a href="<?= $this->url(array('action' => 'index')) ?>" class="traffic-btn-back">&Lt;&nbsp;Regresar</a>
<div class="traffic-clear-5"></div>