<div align="center">
  <div class="content">
    <h1>Dirección</h1>
    <h4>
      Organización Aduanal de Querétaro, S.C.<br>
    </h4>
    <p>
      Calle: Mariano Perrusquia No. 102, interior 7.<br>
      Colonia: San Angel. CP 76030<br>
      Ciudad: Querétaro, Qro.<br>
      Teléfonos: +52 (442)216 0870 y 216 0750 / Fax: +52(442)216 0836<br>
    </p>
    <h1>Ubicación</h1>
    <div>
        <iframe width="100%" height="480" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps/ms?msa=0&amp;msid=205658447501081189772.0004de56c5c7658ad8665&amp;ie=UTF8&amp;t=m&amp;ll=20.582799,-100.400459&amp;spn=0.004821,0.006866&amp;z=17&amp;iwloc=0004de56d4cbaeb560864&amp;output=embed" style="border: 1px #ccc solid; border-radius: 5px"></iframe><br /><small>Ver <a href="https://maps.google.com/maps/ms?msa=0&amp;msid=205658447501081189772.0004de56c5c7658ad8665&amp;ie=UTF8&amp;t=m&amp;ll=20.584099,-100.400459&amp;spn=0.004821,0.006866&amp;z=17&amp;iwloc=0004de56d4cbaeb560864&amp;source=embed" style="color:#0000FF;text-align:left"><?= $this->appConfig('empresa') ?></a> en un mapa más grande</small>
    </div>    
  </div>
</div>
