<div align="center">
  <div class="content">
        <!-- form -->
        <form id="forgotPassword" method="post" style="margin:0">
            <input type="text" placeholder="Usuario" name="username" id="username" style="width: 300px"/>
            <br>
            <input type="submit" id="submit" value="Enviar email" id="recover-password" style="width: 150px"/>
            <br>
            <br>
            <div id="clear"></div>
            <p>» Válido solo para usuarios de OAQ no clientes, si usted es cliente contacte a nuestro departamento de ventas enviando un correo a <a href="mailto:<?= $this->appConfig('contact-email') ?>"><?= $this->appConfig('contact-email') ?></a> solicitando su contraseña de acceso o llamando a los teléfonos <?= $this->appConfig('contact-tel') ?>.</p>
            <p>» Un email será enviado a la dirección de correo eletrónico registrada con su contraseña. Si usted desconoce dicho email por favor no lleve a cabo este proceso o pongase en contacto con nosotros para más aclaraciones.</p>
        </form>
        <!-- form -->
  </div>
</div>
