<div style="height: 10px"></div>
<?= $this->form ?>
<?php if(isset($this->ctas) && !empty($this->ctas)) { ?>        
<ul id="download-links">
    <li>Descargar este reporte en: <img src="/images/icons/ms-excel.png" />&nbsp;<a href="/administracion/index/excel-cuenta-de-gastos">Excel</a>&nbsp;<img src="/images/icons/pdf-icon.png" />&nbsp;<a href="#">PDF</a></li>
</ul>
<?php } ?>
<?php if(isset($this->ctas) && !empty($this->ctas)) { ?>
    <?php if(isset($this->ctas)) { ?>
    <?php echo $this->paginationControl($this->ctas,'Sliding', 'pagination.phtml'); ?>
    <div style="height: 20px"></div>
    <?php } ?>
<table class="table table-striped table-bordered table-hover small">
    <thead>
        <tr>
            <th>Fecha</th>
            <th>Folio</th>
            <th>Referencia</th>
            <th>Aduana</th>
            <th>Patente</th>            
            <th>Pedimento</th>
            <th>I/E</th>
            <th>Cve. Doc</th>
            <th>Fecha Pedimento</th>
            <th>Factura Pedimento</th>
            <th>Bultos/Piezas</th>
            <th>Anticipo</th>
            <th>Valor Aduana</th>            
            <th>Subtotal Maniobras</th>
            <th>IVA Maniobras</th>
            <th>Total Maniobras</th>
            <th>Subtotal Almacenaje</th>
            <th>IVA Almacenaje</th>
            <th>Total Almacenaje</th>
            <th>Subtotal Demoras</th>
            <th>IVA Demoras</th>
            <th>Total Demoras</th>
            <th>Subtotal Fletes aéreos</th>
            <th>IVA Fletes aéreos</th>
            <th>Total Fletes aéreos</th>
            <th>Subtotal Fletes marítimos</th>
            <th>IVA Fletes marítimos</th>
            <th>Total Fletes marítimos</th>
            <th>Subtotal Fletes terrestres</th>
            <th>IVA Fletes terrestres</th>
            <th>Total Fletes terrestres</th>
            <th>Subtotal Fletes y acarreos</th>
            <th>IVA Fletes y acarreos</th>
            <th>Total Fletes y acarreos</th>
            <th>Honorarios</th>
            <th>Gastos complementarios</th>
            <th>Gastos complementarios alijadores</th>
            <th>Gastos complementarios maniobras</th>
            <th>Gastos complementarios demoras</th>
            <th>Gastos complementarios almacenajes</th>            
            <th>Impuestos Aduanales</th>
            <th>Revalidación</th>
            <th>Rectificación</th>
            <th>Sub Total</th>
            <th>IVA</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        <?php if($this->ctas) { $i=1; ?>
        <?php foreach($this->ctas as $factura) { ?>
        <tr>
            <td><?= $factura['fecha_factura'] ?></td>
            <td><?= $factura['factura'] ?></td>
            <td><?= $factura['referencia'] ?></td>            
            <td><?= $factura['aduana'] ?></td>
            <td><?= $factura['patente'] ?></td>            
            <td><?= $factura['pedimento'] ?></td>
            <td><?= $factura['ie'] ?></td>
            <td><?= $factura['regimen'] ?></td>
            <td><?= $factura['fecha_pedimento'] ?></td>
            <td><?= $factura['ref_factura'] ?></td>
            <td><?= $factura['bultos'] ?></td>
            <td align="right"><?= number_format($factura['anticipo'], 2, '.', ',') ?></td>
            <td align="right"><?= number_format($factura['valor_aduana'], 2, '.', ',') ?></td>            
            <?php if(isset($factura['maniobras'])) { ?>
            <td>$ <?= number_format($factura['subtotal_maniobras'], 2, '.', ',') ?></td>
            <td>$ <?= number_format($factura['iva_maniobras'], 2, '.', ',') ?></td>
            <td>$ <?= number_format($factura['maniobras'], 2, '.', ',') ?></td>
            <?php } else { ?>
            <td><span style="color: #ddd">n/d</span></td>
            <td><span style="color: #ddd">n/d</span></td>
            <td><span style="color: #ddd">n/d</span></td>
            <?php } ?>
            <?php if(isset($factura['almacenaje'])) { ?>
            <td>$ <?= number_format($factura['subtotal_almacenaje'], 2, '.', ',') ?></td>
            <td>$ <?= number_format($factura['iva_almacenaje'], 2, '.', ',') ?></td>
            <td>$ <?= number_format($factura['almacenaje'], 2, '.', ',') ?></td>
            <?php } else { ?>
            <td><span style="color: #ddd">n/d</span></td>
            <td><span style="color: #ddd">n/d</span></td>
            <td><span style="color: #ddd">n/d</span></td>
            <?php } ?>
            <?php if(isset($factura['demoras'])) { ?>
            <td>$ <?= number_format($factura['subtotal_demoras'], 2, '.', ',') ?></td>
            <td>$ <?= number_format($factura['iva_demoras'], 2, '.', ',') ?></td>
            <td>$ <?= number_format($factura['demoras'], 2, '.', ',') ?></td>
            <?php } else { ?>
            <td><span style="color: #ddd">n/d</span></td>
            <td><span style="color: #ddd">n/d</span></td>
            <td><span style="color: #ddd">n/d</span></td>
            <?php } ?>
            <?php if(isset($factura['fleteaereo'])) { ?>
            <td>$ <?= number_format($factura['subtotal_fleteaereo'], 2, '.', ',') ?></td>
            <td>$ <?= number_format($factura['iva_fleteaereo'], 2, '.', ',') ?></td>
            <td>$ <?= number_format($factura['fleteaereo'], 2, '.', ',') ?></td>
            <?php } else { ?>
            <td><span style="color: #ddd">n/d</span></td>
            <td><span style="color: #ddd">n/d</span></td>
            <td><span style="color: #ddd">n/d</span></td>
            <?php } ?>
            <?php if(isset($factura['fletemaritimo'])) { ?>
            <td>$ <?= number_format($factura['subtotal_fletemaritimo'], 2, '.', ',') ?></td>
            <td>$ <?= number_format($factura['iva_fletemaritimo'], 2, '.', ',') ?></td>
            <td>$ <?= number_format($factura['fletemaritimo'], 2, '.', ',') ?></td>
            <?php } else { ?>
            <td><span style="color: #ddd">n/d</span></td>
            <td><span style="color: #ddd">n/d</span></td>
            <td><span style="color: #ddd">n/d</span></td>
            <?php } ?>
            <?php if(isset($factura['fleteterrestre'])) { ?>
            <td>$ <?= number_format($factura['subtotal_fleteterrestre'], 2, '.', ',') ?></td>
            <td>$ <?= number_format($factura['iva_fleteterrestre'], 2, '.', ',') ?></td>
            <td>$ <?= number_format($factura['fleteterrestre'], 2, '.', ',') ?></td>
            <?php } else { ?>
            <td><span style="color: #ddd">n/d</span></td>
            <td><span style="color: #ddd">n/d</span></td>
            <td><span style="color: #ddd">n/d</span></td>
            <?php } ?>
            <?php if(isset($factura['fletesacarreos'])) { ?>
            <td>$ <?= number_format($factura['subtotal_fletesacarreos'], 2, '.', ',') ?></td>
            <td>$ <?= number_format($factura['iva_fletesacarreos'], 2, '.', ',') ?></td>
            <td>$ <?= number_format($factura['fletesacarreos'], 2, '.', ',') ?></td>
            <?php } else { ?>
            <td><span style="color: #ddd">n/d</span></td>
            <td><span style="color: #ddd">n/d</span></td>
            <td><span style="color: #ddd">n/d</span></td>
            <?php } ?>
            <td align="right"><?= number_format($factura['honorarios'], 2, '.', ',') ?></td>
            <td align="right"><?php
                if(isset($factura['gastos_complementarios'])) {
                    echo '$ '.number_format($factura['gastos_complementarios'], 2, '.', ',');
                } else {
                    echo '<span style="color: #ddd">n/d</span>';
                }
            ?></td>
            <td align="right"><?php
                if(isset($factura['gastos_alijadores'])) {
                    echo '$ '.number_format($factura['gastos_alijadores'], 2, '.', ',');
                } else {
                    echo '<span style="color: #ddd">n/d</span>';
                }
            ?></td>
            <td align="right"><?php
                if(isset($factura["conceptos"]["gastos_maniobras"])) {
                    echo '$ '.number_format($factura["conceptos"]["gastos_maniobras"]["total"], 2, '.', ',');
                } else {
                    echo '<span style="color: #ddd">n/d</span>';
                }
            ?></td>
            <td align="right"><?php
                if(isset($factura['gastos_demoras'])) {
                    echo '$ '.number_format($factura['gastos_demoras'], 2, '.', ',');
                } else {
                    echo '<span style="color: #ddd">n/d</span>';
                }
            ?></td>
            <td align="right"><?php
                if(isset($factura['gastos_almacenajes'])) {
                    echo '$ '.number_format($factura['gastos_almacenajes'], 2, '.', ',');
                } else {
                    echo '<span style="color: #ddd">n/d</span>';
                }
            ?></td>
            
            <td align="right"><?php
                if(isset($factura["conceptos"]["impuestos_aduanales"])) {
                    echo '$ '.number_format($factura["conceptos"]["impuestos_aduanales"]["total"], 2, '.', ',');
                } else {
                    echo '<span style="color: #ddd">n/d</span>';
                }
            ?></td>
            <td align="right"><?php
                if(isset($factura['revalidacion'])) {   
                    echo '$ '.number_format($factura['revalidacion'], 2, '.', ',');
                } else {
                    echo '<span style="color: #ddd">n/d</span>';
                }
            ?></td>
            <td align="right"><?php
                if(isset($factura['rectificaciones'])) {   
                    echo '$ '.number_format($factura['rectificaciones'], 2, '.', ',');
                } else {
                    echo '<span style="color: #ddd">n/d</span>';
                }
            ?></td>
            <td align="right">$ <?= number_format($factura['subtotal'], 2, '.', ',') ?></td>
            <td align="right">$ <?= number_format($factura['iva'], 2, '.', ',') ?></td>
            <td align="right">$ <?= number_format($factura['total'], 2, '.', ',') ?></td>
        </tr>
        <?php } ?>
        <?php } ?>
    </tbody>
</table>
    <?php if(isset($this->ctas)) { ?>
    <?php echo $this->paginationControl($this->ctas,'Sliding', 'pagination.phtml'); ?>
    <div style="height: 50px"></div>
    <?php } ?>
<?php } ?>
<script>
    // http://www.eyecon.ro/bootstrap-datepicker/
  $("input[name='fechaIni']").datepicker({
        format: 'yyyy-mm-dd'
  }).on('changeDate', function() {
        if( $("#bootstrap-rfc").val().length > 9 ) {
            $("#bootstrap-submit").removeAttr("disabled");
        }
  });
  
  $("input[name='fechaFin']").datepicker({
      format: 'yyyy-mm-dd'
  }).on('changeDate', function() {
        if( $("#bootstrap-rfc").val().length > 9 ) {
            $("#bootstrap-submit").removeAttr("disabled");
        }
  });
  
  var elementsText = ["bootstrap-rfc",'bootstrap-nombre'];    
    $.each(elementsText,function(index, value){ 
        $('#'+value).keyup(function() {
            $(this).val($(this).val().toUpperCase());
        });
    });
    
    $("#bootstrap-submit").attr("disabled", "disabled");
    
    $("#bootstrap-rfc").keypress(function() {
        if($(this).val().length > 9) {
            $("#bootstrap-submit").removeAttr("disabled");
        } else if($(this).val().length <= 8) {
            $("#bootstrap-submit").attr("disabled", "disabled");
        }
    }).blur(function(){
        if($(this).val().length > 9) {
            $("#bootstrap-submit").removeAttr("disabled");
        }
    });
    
    $("#customer-list").click(function(){
        $('#myModal').modal({
            remote: '/administracion/index/clientes'
        });
    });
    
    $('#bootstrap-nombre').typeahead({
        source: function(query, process) {
        return $.ajax({
                url: '/comercializacion/index/json-customers-by-name',
                type: 'get',
                data: { name: query },
                dataType: 'json',
                success: function(res) {
                    return process(res);
                }
            });
        }
    }).change(function(){
        $("#bootstrap-rfc").val('');
    });
    
    $('#bootstrap-nombre').change(function(){
        $.ajax({
            url: '/comercializacion/index/json-customer-rfc-by-name',
            type: 'get',
            data: { name: $("#bootstrap-nombre").val() },
            dataType: 'json',
            success: function(res) {
                if(res) {
                    $("#bootstrap-rfc").val(res);
                    $("#bootstrap-submit").removeAttr("disabled");
                }
            }
        });
    });
</script>
 
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Clientes SICA</h3>
  </div>
  <div class="modal-body">
    <p>One fine body…</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
  </div>
</div>