<form method="<?= $this->form->getMethod() ?>" action="/administracion/ajax/ingresos-corresponsal" enctype="application/x-www-form-urlencoded" id="form">
    <table class="traffic-table traffic-table-left">
        <tr>
            <th><label for="year">Año:</label></th>
            <td><?= $this->form->year ?></td>
        </tr>
        <tr>
            <th><label for="corresponsal">Corresponsal:</label></th>
            <td><?= $this->form->corresponsal ?></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>
                <button id="submit" class="traffic-btn">
                    <i class="fas fa-table"></i> Generar reporte</button>
            </td>
        </tr>   
        <?php if (isset($this->data)) { ?>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <p>Descargar este reporte en: <img src="/images/icons/ms-excel.png" />&nbsp;<a href="/administracion/index/excel-ingresos-corresponsales">Excel</a></p>
                </td>
            </tr>
        <?php } ?>
    </table>
</form>
<div id="result"></div>
<div class="traffic-clear-10"></div>
<div id="graph" style="width: 100%; height: 350px; display: none"></div>
<div class="traffic-clear-10"></div>
<a onclick="window.history.back();" class="traffic-btn">
    <i class="fas fa-angle-double-left"></i>&nbsp;Regresar</a>
<div class="traffic-clear-20"></div>