<div style="padding: 10px; border: 1px #95B8E7 solid; width: 270px; float: left; height: 540px">
    <form id="ff" method="post" enctype="multipart/form-data">
        <div>
            <label for="idAduana">Aduana:</label>
            <input id="idAduana" class="easyui-combobox" name="idAduana"  style="width:250px" data-options="
                   valueField: 'id',
                   textField: 'aduana',
                   panelHeight: 250,
                   panelWidth: 400,
                   url: '/trafico/crud/aduanas'" />
        </div>
        <div>
            <label for="idCliente">Nom. Cliente:</label>
            <input id="idCliente" class="easyui-combobox" name="idCliente"  style="width:250px" data-options="
                   valueField: 'id',
                   textField: 'razonSocial',
                   required: false,
                   panelHeight: 250,
                   panelWidth: 400,
                   url: '/trafico/crud/clientes'" />
        </div>
        <div>
            <label for="name">Fecha inicio:</label>
            <input id="fechaInicio" name="fechaInicio" type="text" class="easyui-datebox" required="required" style="width:150px">
        </div>
        <div>
            <label for="name">Fecha fin:</label>
            <input id="fechaFin" name="fechaFin" type="text" class="easyui-datebox" required="required" style="width:150px">
        </div>
        <div style="text-align:right;padding:5px 0">
            <a href="javascript:void(0)" class="easyui-linkbutton" onclick="submitForm()" style="width:80px">Generar</a>
        </div>
    </form>
</div>
<div style="margin-left: 280px;">
    <table id="dg"></table>
</div>
