<div class="traffic-cols">

    <form method="get" action="<?= $this->url() ?>">            
        <table class="traffic-table">
            <tr>
                <td style="vertical-align: top; text-align: left">
                    <label for="poliza">Poliza:</label>
                    <input type="text" class="focused" placeholder="Poliza" value="<?= $this->poliza ?>" id="poliza" name="poliza">                        
                </td>
                <td style="vertical-align: top; text-align: left">
                    <label for="fechaIni">Fecha Inicio:</label>
                    <input type="text" class="focused" placeholder="fechaIni" value="<?= $this->fechaIni ?>" id="fechaIni" name="fechaIni" style="width: 70px"><img src="/images/icons/calendar.png" style="margin-left: 5px" id="dp4" data-date="<?= $this->fechaIni ?>" data-date-format="yyyy-mm-dd">                        
                </td>
                <td style="vertical-align: top; text-align: left">
                    <label for="fechaFin">Fecha Fin:</label>
                    <input type="text" class="focused" placeholder="fechaFin" value="<?= $this->fechaFin ?>" id="fechaFin" name="fechaFin" style="width: 70px"><img src="/images/icons/calendar.png" style="margin-left: 5px" id="dp5" data-date="<?= $this->fechaFin ?>" data-date-format="yyyy-mm-dd">                        
                </td>
                <td style="vertical-align: bottom; text-align: left">
                    <button class="traffic-btn traffic-btn-add" buttons="danger info primary success warning inverse link" value="Buscar" type="submit" id="submit" name="submit">Buscar</button>                        
                </td>
            </tr>
        </table>
    </form>
</div>
<div class="traffic-clear-5"></div>        
<table class="traffic-table">
    <thead>
        <tr>                
            <th>Tipo de poliza</th>
            <th>Tipo de archivo</th>            
            <th>Poliza</th>
            <th>Folio</th>
            <th>Archivo</th>
            <th>Creado</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php if (isset($this->paginator)) { ?>
            <?php foreach ($this->paginator as $item) { ?>
                <tr>
                    <td><?= mb_strtoupper($this->tipoPoliza($item["tipoPoliza"]), 'UTF-8') ?></td>
                    <td><?= $this->tipoArchivo($item["tipoArchivo"]) ?></td>
                    <td><?= $item["poliza"] ?></td>
                    <td><?= $item["folio"] ?></td>
                    <td><?= $item["nombreArchivo"] ?></td>
                    <td><?= date('d/m/Y', strtotime($item["creado"])) ?></td>
                    <td>
                        <a href="<?= $this->url(array('action' => 'ver-archivos', 'id' => $item["id"])) ?>">
                            <img class="btn-icons" src="/images/icons/folder.png" />
                        </a>
                    </td>
                </tr>
            <?php } ?>
        <?php } else { ?>
            <tr>
                <td colspan="4">No hubo resultado para la búsqueda realizada.</td>
            </tr>
        <?php } ?>
    </tbody>
</table>
<?= (isset($this->paginator)) ? $this->paginationControl($this->paginator, 'Sliding') : null ?>
<a href="/administracion/index/crear-repositorio-admin" class="traffic-btn traffic-btn-create traffic-btn-right">Nuevo documento</a>
