<form action="<?= $this->url() ?>" method="get" enctype="application/x-www-form-urlencoded" id="form">
    <table class="traffic-table traffic-table-left">
        <thead>
            <tr>
                <th colspan="2" class="traffic-table-title">TIEMPOS DE COMPROBACION</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><label for="rfc">RFC:</label></td>
                <td><?= $this->form->rfc ?></td>
            </tr>
            <tr>
                <td><label for="nombre">Nombre:</label></td>
                <td><?= $this->form->nombre ?></td>
            </tr>
            <tr>
                <td><label for="fechaIni">Fecha Inicio:</label></td>
                <td><?= $this->form->fechaIni ?> <i class="far fa-calendar-alt" style="font-size: 1.2em"></i></td>
            </tr>
            <tr>
                <td><label for="fechaFin">Fecha Fin:</label></td>
                <td><?= $this->form->fechaFin ?> <i class="far fa-calendar-alt" style="font-size: 1.2em"></i></td>
            </tr>
        </tbody>
    </table>
</form>
<?= (isset($this->paginator)) ? $this->paginationControl($this->paginator, "Sliding") . "<a class=\"traffic-btn-save traffic-btn-small traffic-btn-right\" href=\"/administracion/index/excel-tiempos-de-comprobacion?" . $this->params . "\">Excel</a>" : null ?>
<div class="traffic-clear-5"></div>
<table class="traffic-table traffic-table-left hover">
    <thead>
        <tr>
            <th>Cuenta de Gastos</th>
            <th>Referencia</th>
            <th>Regimen</th>
            <th>Fecha Factura</th>
            <th>Fecha Acuse</th>
            <th>Fecha Pago</th>
            <th>Plazo</th>
            <th>F.Pago - F.Factura</th>
            <th>F.Acuse - F.Factura</th>
        </tr>
    </thead>
    <tbody>
        <?php if (isset($this->paginator)) { ?>
            <?php foreach ($this->paginator as $item) { ?>
                <tr>
                    <td style="text-align: center"><?= $item['FolioID'] ?></td>
                    <td style="text-align: center"><?= $item['Referencia'] ?></td>
                    <td style="text-align: center"><?= $item['Regimen'] ?></td>
                    <td style="text-align: center"><?= $item['FechaFactura'] ?></td>
                    <td style="text-align: center"><?= $item['FechaAcuse'] ?></td>
                    <td style="text-align: center"><?= $item['FechaPago'] ?></td>
                    <td style="text-align: center"><?= $item['Plazo'] ?></td>
                    <td style="text-align: center"><?= $item['DiffPago'] ?></td>
                    <td style="text-align: center"><?= $item['DiffAcuse'] ?></td>
                </tr>
            <?php } ?>
        <?php } else { ?>
            <tr>
                <td colspan="9" style="text-align: center">
                    <em>No hay resultados.</em>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>
<div class="traffic-clear-5"></div>
<?= (isset($this->paginator)) ? $this->paginationControl($this->paginator, "Sliding") : null ?>
<div class="traffic-clear-5"></div>
<button id="submit" class="traffic-btn traffic-btn-right">
        <i class="fas fa-table"></i> Generar reporte</button>
<a onclick="window.history.back();" class="traffic-btn">
        <i class="fas fa-angle-double-left"></i> Regresar</a>
<div class="traffic-clear-20"></div>