<!DOCTYPE html>
<html>
    <head>
        <title>Reporte I.V.A.</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <link href="/css/reportes.css?<?= time() ?>" media="screen" rel="stylesheet" type="text/css" >
        <link href="/less/traffic-module.css?<?= time() ?>" media="screen" rel="stylesheet" type="text/css" >
    <body>
        <a href="/clientes/get/reporte-iva?aduana=<?= $this->aduana ?>&year=<?= $this->year ?>&mes=<?= $this->mes ?>&download=true" class="download" style="margin: 1px 1px 3px 1px">Descarga Excel</a>
        <table>
            <thead>                
                <tr>
                    <th>Operacion</th>
                    <th>I/E</th>
                    <th>Referencia</th>
                    <th>Cve. Ped.</th>
                    <th>Tax Id</th>
                    <th>Proveedor</th>
                    <th>O. Fraccion</th>
                    <th>Fraccion</th>
                    <th>Desc.</th>
                    <th>Valor</th>
                    <th>I.V.A.</th>
                </tr>
            </thead>
            <tbody>
                <?php if (isset($this->result)) { ?>
                    <?php foreach ($this->result as $item) { ?>
                        <tr>
                            <td><?= $item["operacion"] ?></td>
                            <td><?= $item["impexp"] ?></td>
                            <td><?= $item["trafico"] ?></td>
                            <td><?= $item["cvePedimento"] ?></td>
                            <td><?= $item["taxID"] ?></td>
                            <td><?= $item["nomProveedor"] ?></td>
                            <td><?= $item["ordenFraccion"] ?></td>
                            <td><?= $item["fraccion"] ?></td>
                            <td><?= $item["descripcion"] ?></td>
                            <td style="text-align: right; padding-right: 2px;"><span style="float:left;">$</span><?= number_format($item["valor"], 2, '.', ',') ?></td>
                            <td style="text-align: right; padding-right: 5px;"><span style="float:left;">$</span><?= number_format($item["iva"], 2, '.', ',') ?></td>
                        </tr>
                    <?php } ?>
                <?php } else { ?>
                    <tr>
                        <td colspan="11">
                            <em>No hubo resultados.</em>                            
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
        <div class="traffic-clear-20"></div>
    </body>
</html>