<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <!-- page content -->
            <div class="col-md-12">
                <div class="col-middle">
                    <div class="text-center text-center">
                        <h1 class="error-number">403</h1>
                        <h2>Acceso denegado</h2>
                        <p>Se requiere de un código de acceso correcto para poder acceder a esta página.</p>
                    </div>
                </div>
            </div>
            <!-- /page content -->
        </div>
    </div>