<div class="traffic-pagination">
    <ul>
        <?php if (isset($this->first)): ?>
            <li class="active"><a onclick="<?= $this->function ?>(<?= $this->first ?>);">«</a></li>
        <?php else: ?>
            <li class="disabled"><a>«</a></li>
        <?php endif ?>
        <?php if (isset($this->previous)): ?>
            <li class="active"><a onclick="<?= $this->function ?>(<?= $this->previous ?>);">Ant</a></li>
        <?php else: ?>
            <li class="disabled"><a>Ant.</a></li>
        <?php endif ?>
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li class="active"><a onclick="<?= $this->function ?>(<?= $page ?>);"><?= $page ?></a></li>
            <?php else: ?>
                <li class="disabled"><a><?= $page ?></a></li>
            <?php endif ?>
        <?php endforeach ?>
        <?php if (isset($this->next)): ?>
            <li class="active"><a onclick="<?= $this->function ?>(<?= $this->next ?>);">Sig</a></li>
        <?php else: ?>
            <li class="disabled"><a>Sig.</a></li>
        <?php endif ?>

        <?php if (isset($this->last)): ?>
            <li class="active"><a onclick="<?= $this->function ?>(<?= $this->last ?>);">»</a></li>
        <?php else: ?>
            <li class="disabled"><a>»</a></li>
            <?php endif ?>
    </ul>
</div>