<div style="height: 400px">
    <table class="traffic-table traffic-table-left hover">
        <thead>
            <tr>
                <th>TIGIE 2012</th>
                <th>TIGIE 2020</th>
                <th>NICO</th>
            </tr>
        </thead>
        <?php foreach ($this->paginator as $item) { ?>
            <tr>
                <td style="text-align: center"><?= $item["tigie_2012"] ?></td>
                <td style="text-align: center"><?= $item["tigie_2020"] ?></td>
                <td style="text-align: center"><?= $item["nico"] ?></td>
            </tr>
        <?php } ?>
    </table>
</div>
<?= (isset($this->paginator)) ? $this->paginationControl($this->paginator, "Sliding", "paginacion.phtml", array("function" => $this->funcion, "busqueda" => $this->busqueda)) : null ?>