<style>
    .row {
        font-size: 14px;
    }
</style>
<input type="hidden" id="id" name="id" value="<?= $this->row['id'] ?>" />
<div class="row">
    <div class="col"><strong>ADUANA:</strong> <?= $this->row['aduana'] . '-' . $this->row['patente'] ?></div>
    <div class="col"><strong>REFERENCIA:</strong> <?= $this->row['referencia'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>PEDIMENTO:</strong> <?= $this->row['pedimento'] ?></div>
    <div class="col"><strong>RFC:</strong> <?= $this->row['rfcCliente'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>CLIENTE:</strong> <?= $this->row['nombreCliente'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>CLAVE:</strong> <?= $this->row['cvePedimento'] ?></div>
    <div class="col"><strong>IMP/EXP:</strong> <?= ($this->row["ie"] == 'TOCE.IMP') ? '<i class="fas fa-arrow-circle-down" style="color: #2f3b58"></i>' : '<i class="fas fa-arrow-circle-up" style="color: #2f3b58"></i>' ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>USUARIO:</strong> <?= mb_strtoupper($this->row['nombre']) ?><br><br></div>
    <div class="w-100"></div>
</div>

<a href="javascript:window.history.back();" class="btn btn-sm btn-secondary"><i class="fas fa-angle-left"></i> Regresar</a>
