<style>
    .row {
        font-size: 14px;
    }
</style>
<input type="hidden" id="id" name="id" value="<?= $this->row['id'] ?>" />
<div class="row">
    <div class="col"><strong>ADUANA:</strong> <?= $this->row['aduana'] . '-' . $this->row['patente'] ?></div>
    <div class="col"><strong>REFERENCIA:</strong> <?= $this->row['referencia'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>PEDIMENTO:</strong> <?= $this->row['pedimento'] ?></div>
    <div class="col"><strong>RFC:</strong> <?= $this->row['rfcCliente'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>CLIENTE:</strong> <?= $this->row['nombreCliente'] ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>CLAVE:</strong> <?= $this->row['cvePedimento'] ?></div>
    <div class="col"><strong>IMP/EXP:</strong> <?= ($this->row["ie"] == 'TOCE.IMP') ? '<i class="fas fa-arrow-circle-down" style="color: #2f3b58"></i>' : '<i class="fas fa-arrow-circle-up" style="color: #2f3b58"></i>' ?></div>
    <div class="w-100"></div>
    <div class="col"><strong>USUARIO:</strong> <?= mb_strtoupper($this->row['nombre']) ?><br><br></div>
    <div class="w-100"></div>
    <div class="col">
        <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
            <a href="/mobile/traficos/trafico?id=<?= $this->row['id'] ?>" class="btn btn-primary active">Básico</a>
            <a href="/mobile/traficos/archivos?id=<?= $this->row['id'] ?>" class="btn btn-secondary">Archivos</a>
            <a href="/mobile/traficos/fotos?id=<?= $this->row['id'] ?>" class="btn btn-secondary">Fotos</a>
            <a href="/mobile/traficos/comentarios?id=<?= $this->row['id'] ?>" class="btn btn-secondary">Comentarios</a>
            <a href="/mobile/traficos/bitacora?id=<?= $this->row['id'] ?>" class="btn btn-secondary">Bitacora</a>
        </div>
        <br><br>
    </div>
    <div class="w-100"></div>
    <div class="col">
        <table class="table table-sm table-striped facturas">
            <thead>
                <tr class="table-active">
                    <th colspan="3" class="">
                        FACTURAS <a href="/mobile/traficos/agregar-factura?id=<?= $this->row['id'] ?>"><i class="fas fa-plus-square float-right" style="font-size: 20px"></i></a>
                    </th>
                </tr>
                <tr>
                    <th>Num. Factura</th>
                    <th>COVE</th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <div class="w-100"></div>
    <div class="col">
        <table class="table table-sm table-striped guias">
            <thead>
                <tr class="table-active">
                    <th colspan="3" class="">
                        GUÍAS  <a href="/mobile/traficos/agregar-guia?id=<?= $this->row['id'] ?>"><i class="fas fa-plus-square float-right" style="font-size: 20px"></i></a>
                    </th>
                </tr>
                <tr>
                    <th>GUIA</th>
                    <th>TIPO</th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

<a href="javascript:window.history.back();" class="btn btn-sm btn-secondary"><i class="fas fa-angle-left"></i> Regresar</a>
