<style>
    .traffic-table,
    .traffic-table td,
    .traffic-table th {
        line-height: 14px;
        padding: 2px 2px !important;
    }
    label {
        line-height: 14px;        
    }
    .l-btn-left .l-btn-empty {
        width: 0;
    }
</style>
<?= $this->inputHidden("hidden","idCliente", $this->basico["idCliente"]) ?>
<?= $this->inputHidden("hidden","idRepositorio", $this->basico["idRepositorio"]) ?>
<div style="width: 100%">
    <div style="float: left; width: 50%">
        <form id="form-information">
            <?= $this->inputHidden("hidden","idTrafico", $this->idTrafico) ?>
            <table class="traffic-table traffic-table-left">
                <tr>
                    <th colspan="6" class="invoice-title"><?= $this->basico["nombreAduana"] ?></th>
                </tr>
                <tr>
                    <th style="width: 75px; text-align: right">Pedimento</th>
                    <td>
                        <?= $this->basico["aduana"] . '-' . $this->basico["patente"] . '-' . $this->basico["pedimento"] ?>
                    </td>
                    <th style="text-align: right">Referencia</th>
                    <td colspan="3">
                        <?= $this->basico["referencia"] ?>
                        <?php if ($this->basico["pagado"] == null) { ?>
                            <div style="font-size:1.3em; color: #2f3b58; float: right; margin-right: 5px">
                                <i class="fas fa-save" id="saveTraffic" data-id="<?= $this->basico["id"] ?>" style="cursor: pointer"></i>
                                &nbsp;
                                <a href="/trafico/index/modificar-trafico?id=<?= $this->basico["id"] ?>" title="Editar tráfico.">
                                    <i class="fas fa-pencil-alt"></i>
                                </a>
                                &nbsp;
                                <i id="deleteTraffic" class="fas fa-trash-alt" data-id="<?= $this->basico["id"] ?>" style="cursor: pointer"></i>
                            </div>
                        <?php } ?>
                        <?php if ($this->basico["pagado"] !== null && $this->edit == true) { ?>
                            <div style="font-size:1.3em; color: #2f3b58; float: right; margin-right: 5px">
                                <a href="/trafico/index/modificar-trafico?id=<?= $this->basico["id"] ?>" title="Editar tráfico.">
                                    <i class="fas fa-pencil-alt"></i>
                                </a>
                                &nbsp;
                            </div>
                        <?php } ?>
                        <a id="soia" 
                           data-id="<?= $this->basico["id"] ?>" 
                           style="color: #fff; background-color: #2f3b58; float: right; font-size: 9px; padding: 2px; border-radius: 2px; cursor: pointer; margin-right: 5px">SOIA<a/>
                    </td>
                </tr>
                <tr>
                    <th style="text-align: right">RFC Cliente</th>
                    <td><?= $this->basico["rfc"] ?></td>
                    <th style="text-align: right">Nombre</th>                
                    <td colspan="3">
                        <?= $this->basico["nombreCliente"] ?>
                        <i class="fas fa-address-card ttip">
                            <p class="ttiptext"><?= 'PECA: ' . (($this->basico["peca"] == 1) ? 'SI' : 'NO') . ' - ' . $this->basico["peca_num"] ?>
                                <br><?= 'INMEX: ' . (($this->basico["inmex"] == 1) ? 'SI' : 'NO') . ' - ' . $this->basico["inmex_num"] ?></p>
                        </i>
                    </td>
                </tr>
                <tr>
                    <th style="text-align: right">Tipo Op.</th>
                    <td>
                        <?= ($this->basico["ie"] == 'TOCE.IMP') ? '<i class="fas fa-arrow-circle-down" style="color: #2f3b58"></i>' : '<i class="fas fa-arrow-circle-up" style="color: #2f3b58"></i>' ?>
                        <?= ($this->basico["ie"] == 'TOCE.IMP') ? 'IMPO' : 'EXPO' ?>
                    </td>
                    <th style="text-align: right">Cve. Ped.</th>
                    <td><?= $this->basico["cvePedimento"] ?></td>
                    <th style="text-align: right">Tipo Cam.</th>
                    <td><?= number_format($this->basico["tipoCambio"], 4) ?></td>
                </tr>
                <tr>
                    <th style="text-align: right">Regimen</th>
                    <td><?= $this->basico["regimen"] ?></td>                
                    <th style="text-align: right">Conso.</th>
                    <td><?= ($this->basico["consolidado"] == '0') ? 'N' : 'S' ?></td>
                    <th style="text-align: right">Rect.</th>
                    <td><?= ($this->basico["rectificacion"] == '0') ? 'N' : 'S' ?></td>
                </tr>
                <tr>
                    <th style="text-align: right">Usuario</th>
                    <td colspan="5"><?= mb_strtoupper($this->basico["nombre"]) ?></td>
                </tr>
                <tr>
                    <th>Candados</th>
                    <td colspan="5">
                        <?php if ($this->basico["pagado"] == null) { ?>
                            <input type="text" class="traffic-input-medium" name="candados" id="candados" value="<?= $this->basico["candados"] ?>" />
                        <?php } else { ?>
                            <?= mb_strtoupper($this->basico["candados"]) ?>
                        <?php }  ?>
                    </td>
                </tr>
                <tr>
                    <th>Cont./Caja</th>
                    <td colspan="5">
                        <?php if ($this->basico["pagado"] == null) { ?>
                            <input type="text" class="traffic-input-medium" name="contenedorCaja" id="contenedorCaja" value="<?= $this->basico["contenedorCaja"] ?>" />
                        <?php } else { ?>
                            <?= mb_strtoupper($this->basico["contenedorCaja"]) ?>
                        <?php }  ?>
                    </td>
                </tr>
                <tr>
                    <th>Placas</th>
                    <td colspan="5">
                        <?php if ($this->basico["pagado"] == null) { ?>
                            <input type="text" class="traffic-input-medium" name="placas" id="placas" value="<?= $this->basico["placas"] ?>" />
                        <?php } else { ?>
                            <?= mb_strtoupper($this->basico["placas"]) ?>
                        <?php }  ?>
                    </td>
                </tr>
                <tr>
                    <th>Nombre de buque</th>
                    <td colspan="5">
                        <?php if ($this->basico["pagado"] == null) { ?>
                            <input type="text" class="traffic-input-medium" name="nombreBuque" id="nombreBuque" value="<?= $this->basico["nombreBuque"] ?>" />
                        <?php } else { ?>
                            <?= mb_strtoupper($this->basico["nombreBuque"]) ?>
                        <?php }  ?>
                    </td>
                </tr>
                <tr>
                    <th>P.O.</th>
                    <td colspan="5">
                        <?php if ($this->basico["pagado"] == null) { ?>
                            <input type="text" class="traffic-input-medium" name="ordenCompra" id="ordenCompra" value="<?= $this->basico["ordenCompra"] ?>" />
                        <?php } else { ?>
                            <?= mb_strtoupper($this->basico["ordenCompra"]) ?>
                        <?php }  ?>
                    </td>
                </tr>
                <tr>
                    <th>TIPO CARGA</th>
                    <td colspan="5">
                        <?php if ($this->basico["pagado"] == null) { ?>
                            <select id="tipoCarga" name="tipoCarga" class="traffic-select-medium">
                                <option value="">---</option>
                                <?php if (isset($this->tipoCargas)) { ?>
                                    <?php foreach($this->tipoCargas as $item) { ?>
                                        <option value="<?= $item["id"] ?>" <?= (isset($this->basico["tipoCarga"]) && $this->basico["tipoCarga"] == $item['id']) ? 'selected="true"' : '' ?>><?= $item["descripcion"] ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        <?php } else { ?>
                            
                        <?php }  ?>
                    </td>
                </tr>
                <tr>
                    <th>PLANTA</th>
                    <td colspan="5">
                        <?php if (isset($this->plantas)) { ?>
                            <select id="idPlanta" name="idPlanta" class="traffic-select-medium"
                                    <?= ($this->basico["pagado"] == null) ? '' : 'disabled="true"' ?>>
                                <option value="">---</option>
                                <?php foreach($this->plantas as $item) { ?>
                                    <option value="<?= $item["id"] ?>" <?= (isset($this->basico["idPlanta"]) && $this->basico["idPlanta"] == $item['id']) ? 'selected="true"' : '' ?>><?= $item["descripcion"] ?></option>
                                <?php } ?>
                            </select>
                        <?php } ?>
                    </td>
                </tr>
            </table><!-- informacion -->
        </form>
        <form id="form-invoice">
            <?= $this->inputHidden("hidden","factura") ?>
            <?= $this->inputHidden("hidden","idTrafico", $this->idTrafico) ?>
            <table class="traffic-table traffic-table-left" style="height: 100px">
                <tr>
                    <th colspan="5" class="invoice-title">
                        FACTURAS
                    </th>
                </tr>
                <tr>
                    <th style="text-align: left"><label for="numFactura">Num. Factura:</label></th>
                    <th>                        
                        <div style="font-size:1.4em; color: #2f3b58; float: right; margin-right: 5px; margin-top: 2px">
                            <i class="fas fa-code" id="cargarXml" style="cursor: pointer" title="Subir CDFi (XML)"></i>
                            &nbsp;
                            <i class="fas fa-file-excel" id="loadTemplate" style="cursor: pointer" title="Cargar plantilla"></i>
                            &nbsp;
                            <i class="fas fa-download easyui-menubutton" id="mbt" data-options="menu:'#mmt'" style="cursor: pointer; color: #2f3b58" title="Descargar plantilla"> 
                                <span style="font-family: sans-serif">Plantilla</span></i>
                            <div id="mmt" style="width:150px; display: none">
                                <div><a id="template-casa" data-id="<?= $this->idTrafico ?>">Sistema CASA</a></div>
                                <div><a id="template-slam" data-id="<?= $this->idTrafico ?>">SLAM</a></div>
                            </div>
                            <i class="fas fa-sync easyui-menubutton" id="mbt" data-options="menu:'#mms'" style="cursor: pointer; color: #2f3b58" title="Importar facturas"></i>
                            <div id="mms" style="width:150px; display: none">
                                <div id="mn-casa" data-id="<?= $this->idTrafico ?>">CASA</div>
                                <div id="mn-slam" data-id="<?= $this->idTrafico ?>">SLAM</a></div>
                            </div>
                        </div>                        
                    </th>
                </tr>
                <tr>
                    <td>
                        <input type="text" id="numFactura" name="numFactura" style="width: 130px">
                    </td>
                    <td>
                        <button type="submit" id="addInvoice" class="traffic-btn traffic-btn-right">
                            <i class="fas fa-plus-square"></i> Agregar
                        </button>
                    </td>
                </tr>
            </table>
        </form>
        <table class="traffic-table hover">
            <thead>
                <tr>
                    <th>
                        <input type="checkbox" id="selectAllInvoices" />
                    </th>
                    <th style="text-align: left">Num. Factura
                        <i class="fab fa-uniregistry" id="sendToVucem" style="color: #0099ff; float: right; margin-right: 5px; font-size: 1.3em"></i>
                    </th>
                    <th>COVE</th>
                    <th>Valor Mon. Ext.</th>
                    <th style="width: 40px">Mon.</th>
                    <th style="width: 80px" style="text-align: center">
                        <div style="font-size:1.2em; color: #2f3b58; float: right; margin-right: 5px">
                            <i onclick="loadInvoices();" id="loadInvoices" class="fas fa-sync-alt" style="cursor: pointer"></i>
                        </div>
                    </th>
                </tr>                    
            </thead>
            <tbody id="traffic-invoices">
                <tr>
                    <td colspan="6">
                        <span style="font-family: sans-serif; font-size: 12px">Cargando... <div class="traffic-icon traffic-loader"></div></span>
                    </td>
                </tr>
            </tbody>
        </table>
        <div id="div-tracking">
            <form id="form-tracking">
                <?= $this->inputHidden("hidden", "guia") ?>
                <?= $this->inputHidden("hidden", "idTrafico", $this->idTrafico) ?>
                <table class="traffic-table traffic-table-left" style="height: 100px">
                    <tr>
                        <th colspan="4" class="invoice-title">GUÍAS</th>
                    </tr>
                    <tr>                        
                        <th style="text-align: left; width: 140px"><label for="tipoguia">Tipo:</label></th>
                        <th style="text-align: left"><label for="number">Guía:</label></th>
                        <th>&nbsp;</th>
                    </tr>
                    <tr>
                        <td>
                            <select id="tipoguia" name="tipoguia" class="traffic-select-small">
                                <option value="">-- Seleccionar --</option>
                                <option value="M">Master</option>
                                <option value="H">House</option>
                            </select>
                        </td>
                        <td>
                            <input type="text" id="number" name="number" style="width: 130px">
                        </td>
                        <td>
                            <button type="submit" id="add-tracking-number" class="traffic-btn traffic-btn-right">
                                <i class="fas fa-plus-square"></i> Agregar
                            </button>
                            <!--<input type="submit" id="add-tracking-number" class="traffic-btn-add traffic-btn-right" value="Agregar guía">-->
                        </td>
                    </tr>
                </table>
            </form>
            <div id="traffic-trackings" style="max-height: 450px; overflow-y: scroll; border-bottom: 1px #c7d0d3 solid"></div>
        </div>
    </div>
    <div style="float: left; width: 50%">
        <div id="traffic-comments">
            
            <table class="traffic-table traffic-table-left">
                <thead>
                    <tr>
                        <th colspan="3" class="traffic-table-title">BITACORA</th>
                    </tr>
                    <tr>
                        <th style="text-align: left;">Evento</th>
                        <th style="text-align: left;">Usuario</th>
                        <th style="text-align: center; width: 110px">Fecha</th>
                    </tr>
                </thead>
                <tbody id="trafficLog">
                    <tr>
                        <td colspan="3">
                            <span style="font-family: sans-serif; font-size: 12px">Cargando... <div class="traffic-icon traffic-loader"></div></span>
                        </td>
                    </tr>
                </tbody>
            </table>            
            <table class="traffic-table traffic-table-left">
                <thead>
                    <tr>
                        <th colspan="3" class="traffic-table-title">COMENTARIOS</th>
                    </tr>                
                    <tr>
                        <th style="width: 150px">Usuario</th>
                        <th>Comentario/mensaje</th>
                        <th style="width: 125px">Fecha
                            <div style="font-size:1.2em; color: #2f3b58; float: right; margin-right: 5px">
                                <i onclick="loadComments();" class="fas fa-sync-alt" style="cursor: pointer"></i>
                            </div>
                        </th>
                    </tr>
                </thead>
                <tbody id="trafficComments">
                    <tr>
                        <td colspan="3">
                            <span style="font-family: sans-serif; font-size: 12px">Cargando... <div class="traffic-icon traffic-loader"></div></span>
                        </td>
                    </tr>
                </tbody>
            </table>
            <table class="traffic-table traffic-table-left">
                <tbody>                    
                    <tr>
                        <td colspan="2">
                            <form id="commentsForm" method="post" enctype="multipart/form-data">                    
                                <input type="hidden" name="idTrafico" id="idTrafico" value="<?= $this->idTrafico ?>" >
                                <input type="file" name="filess" id="filess" visibility="hidden" style="display: none"/>
                                <textarea id="comment" name="comment" class="traffic-textarea-medium"></textarea>
                                <div id="attachedFiles"></div>
                            </form>
                        </td>
                        <td>
                            <button id="addComment" class="traffic-btn traffic-btn-right">
                                <i class="far fa-comment-alt"></i> Comentario
                            </button>
                            <div style="font-size:1.4em; color: #2f3b58; float: right; margin-right: 5px; margin-top: 2px">
                                <i class="fas fa-paperclip" id="attach" data-id="<?= $this->idTrafico ?>" style="cursor: pointer"></i>
                                &nbsp;
                                <i class="far fa-envelope mensajeroEnTrafico" data-id="<?= $this->idTrafico ?>" style="cursor: pointer"></i>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
            
        </div>
    </div><!-- 50% -->
</div>
<div class="traffic-clear-5"></div>
<a href="/trafico/index/traficos" class="traffic-btn" tabindex="99">
    <i class="fas fa-angle-double-left"></i>&nbsp;Regresar
</a>
<div class="traffic-clear"></div>
<script type="text/javascript">    
    $("#mensajeroEnTrafico").qtip({ 
        content: {
            text: "Enviar un mensaje personalizado o predeterminado."
        }
    });
    
    $("#attach").qtip({ 
        content: {
            text: "Adjuntar archivo."
        }
    });
    
    $("#commentsForm").validate({
        errorPlacement: function (error, element) {
            $(element)
                    .closest("form")
                    .find("#" + element.attr("id"))
                    .after(error);
        },
        errorElement: "span",
        errorClass: "traffic-error",
        rules: {
            comment: {required: true}
        },
        messages: {
            comment: "SE REQUIERE COMENTARIO"
        }
    });

</script>