<div class="traffic-cols">
    <div class="traffic-col-50">
        <table class="traffic-table">
            <tr>
                <th class="traffic-table-title">RECTIFICACIÓN</th>
            </tr>
            <tr>
                <td>
                    <div class="traffic-radio-block">
                        <div class="traffic-radio-input">
                            <input type="radio" name="peca-default" value="0">&nbsp;<p>Con cargo al cliente.</p>
                        </div>
                        <div class="traffic-radio-input">
                            <input type="radio" name="peca-default" value="1">&nbsp;<p>Con cargo directo (OAQ).</p>
                        </div>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <div class="traffic-col-50">
        <table class="traffic-table">
            <tr>
                <th class="traffic-table-title">TIPO DE FACTURACIÓN</th>
            </tr>
            <tr>
                <td>
                    <div class="traffic-radio-block">
                        <div class="traffic-radio-input">
                            <input type="radio" name="peca-default" value="0">&nbsp;<p>Directo.</p>
                        </div>
                        <div class="traffic-radio-input">
                            <input type="radio" name="peca-default" value="1">&nbsp;<p>Tercero.</p>
                        </div>
                        <div class="traffic-radio-input">
                            <input type="radio" name="peca-default" value="1">&nbsp;<p>Honorarios directo y comprobados <em>forwarder</em>.</p>
                        </div>
                    </div>
                </td>
            </tr>
        </table>
    </div>        
</div>
<div class="traffic-clear-5"></div>
<a href="/trafico/index/trafico" class="traffic-btn traffic-btn-back">« Regresar</a>
<div class="traffic-clear"></div>