<div style="overflow-y: scroll; max-height: 450px; border: 1px #c6d7e7 solid">    
    <table class="traffic-table hover">
        <tr>
            <th>&nbsp;</th>
            <th>Nombre de archivo</th>
            <th>Tipo de archivo</th>
            <th>VU</th>
            <th>Creado</th>
            <th>Usuario</th>
            <th style="width: 90px;">
                <div style="font-size:1.2em; color: #2f3b58; float: right; margin-right: 5px">
                    <i onclick="loadFiles();" id="loadInvoices" class="fas fa-sync-alt" style="cursor: pointer"></i>
                </div>
            </th>
        </tr>
        <?php foreach ($this->archivos as $item) { ?>
            <tr>
                <td>
                    <?= (file_exists($item["ubicacion"])) ? '' : '<div style="color: red"><i class="fas fa-exclamation" title="El archivo no existe"></i></div>' ?>
                </td>
                <td class="traffic-td-left">
                    <a class="traffic-a" onclick="descargarArchivo('/archivo/get/descargar-archivo?id=<?= $item["id"] ?>')">
                        <?= $item["nom_archivo"] ?>
                    </a>
                    <div style="float: right; font-size: 1.2em; color: #2f3b58">
                    <?php if ($item["tipo_archivo"] == 34) { ?>
                        <i class="fas fa-pen-square editInvoideData" data-id="<?= $item["id"] ?>" style="cursor: pointer" title="Editar datos de factura"></i>
                    <?php } ?>
                    <?php if (file_exists($item["ubicacion"]) && preg_match('/.pdf$/', $item["nom_archivo"])) { ?>
                        <i class="fas fa-eye openFile" data-id="<?= $item["id"] ?>" style="cursor: pointer"></i>
                    <?php } ?>
                    </div>
                </td>
                <td class="traffic-td-left">
                    <div id="edit_<?= $item["id"] ?>">
                        <p>
                            <?= wordwrap($this->tipoArchivo($item["tipo_archivo"]), 50, "<br />\n") ?>
                        </p>
                    </div>
                </td>
                <td><?= $item["edocument"] ?></td>
                <td style="width: 120px;"><?= date('d/m/Y H:i a', strtotime($item["creado"])) ?></td>
                <td style="width: 150px;"><?= ucwords(strtolower($item["usuario"])) ?></td>
                <td>
                    <div id="icon_<?= $item["id"] ?>">
                        <?= $this->archivosIconos($item["id"], $item["tipo_archivo"], isset($this->canDelete) ? true : null, $item["nom_archivo"]) ?>            
                    </div>
                </td>
            </tr>            
        <?php } ?>
            
        <?php if (isset($this->complementos) && !empty($this->complementos)) { ?>
            <?php foreach ($this->complementos as $item) { ?>
                <tr>
                    <td>
                        C <?= (file_exists($item["ubicacion"])) ? '' : '<div style="color: red"><i class="fas fa-exclamation" title="El archivo no existe"></i></div>' ?>
                    </td>
                    <td class="traffic-td-left">
                        <a class="traffic-a" onclick="descargarArchivo('/archivo/get/descargar-archivo?id=<?= $item["id"] ?>')">
                            <?= $item["nom_archivo"] ?>
                        </a>
                        <?php if (file_exists($item["ubicacion"]) && preg_match('/.pdf$/', $item["nom_archivo"])) { ?>
                            <img src="/images/icons/eye-24-gray.png" class="openFile" data-id="<?= $item["id"] ?>" style="cursor: pointer; float: right" />
                        <?php } ?>
                    </td>
                    <td class="traffic-td-left">
                        <div id="edit_<?= $item["id"] ?>">
                            <p>
                                <?= wordwrap($this->tipoArchivo($item["tipo_archivo"]), 50, "<br />\n") ?>
                            </p>
                        </div>
                    </td>
                    <td><?= $item["edocument"] ?></td>
                    <td style="width: 120px;"><?= date('d/m/Y H:i a', strtotime($item["creado"])) ?></td>
                    <td style="width: 150px;"><?= ucwords(strtolower($item["usuario"])) ?></td>
                    <td>
                        <div id="icon_<?= $item["id"] ?>">
                            <?= $this->archivosIconos($item["id"], $item["tipo_archivo"], isset($this->canDelete) ? true : null, $item["nom_archivo"]) ?>            
                        </div>
                    </td>
                </tr>            
            <?php } ?>
        <?php } ?>
            
        <?php if (isset($this->validacion) && !empty($this->validacion)) { ?>
            <?php if (isset($this->validacion["validacion"]) && !empty($this->validacion["validacion"])) { ?>
                <tr>
                    <td>&nbsp;</td>
                    <td style="text-align: left">
                        <a class="traffic-a" href="/archivo/data/descarga-archivo-validacion?id=<?= $this->validacion["validacion"]["idArchivoValidacion"] ?>"><?= $this->validacion["validacion"]["archivoNombre"] ?></a>
                    </td>
                    <td style="text-align: left">Archivo M3</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            <?php } ?>
            <?php if (isset($this->validacion["firma"]) && !empty($this->validacion["firma"])) { ?>
                <tr>
                    <td>&nbsp;</td>
                    <td style="text-align: left">
                        <a class="traffic-a" href="/archivo/data/descarga-archivo-validacion?id=<?= $this->validacion["firma"]["idArchivoValidacion"] ?>"><?= $this->validacion["firma"]["archivoNombre"] ?></a>
                    </td>
                    <td style="text-align: left">Archivo de firma de validación</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            <?php } ?>
            <?php if (isset($this->validacion["pago"]) && !empty($this->validacion["pago"])) { ?>
                <tr>
                    <td>&nbsp;</td>
                    <td style="text-align: left">
                        <a class="traffic-a" href="/archivo/data/descarga-archivo-validacion?id=<?= $this->validacion["pago"]["idArchivoValidacion"] ?>"><?= $this->validacion["pago"]["archivoNombre"] ?></a>
                    </td>
                    <td style="text-align: left">Archivo de pago</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            <?php } ?>
        <?php } ?>           
    </table>
</div>