<?php if (isset($this->data) && !empty($this->data)) { ?>
    <table class="traffic-table">            
        <tr>
            <th>&nbsp;</th>
            <th>Transportista</th>
            <th>Guia</th>
            <th>Tipo</th>
            <th>
                <!--<div class="traffic-icon traffic-icon-reload traffic-btn-right" onclick="loadTrackings();"></div>-->
                <div style="font-size:1.2em; color: #2f3b58; float: right; margin-right: 5px">
                    <i onclick="loadTrackings();" class="fas fa-sync-alt" style="cursor: pointer"></i>
                </div>
            </th>
        </tr>     
        <?php foreach ($this->data as $item) { ?>
            <tr>
                <td>&nbsp;</td>
                <td><?= ($item["idTransportista"] != null) ? $item["nombre"] : 'N/D' ?></td>
                <td><?= $item["guia"] ?></td>
                <td><?= $item["tipo"] ?></td>
                <td style="width: 80px">
                    <div style="font-size:1.2em; color: #2f3b58; float: right; margin-right: 5px">                        
                        <i class="fas fa-pencil-alt" onclick="parent.editarGuia(<?= $item["id"] ?>);" style="cursor: pointer"></i>&nbsp;
                        <i class="fas fa-trash-alt" onclick="parent.borrarGuia(<?= $item["id"] ?>);" style="cursor: pointer"></i>&nbsp;
                        <i class="fas fa-folder-open" onclick="parent.abrirPrevio(<?= $item["id"] ?>);" style="cursor: pointer"></i>
                    </div>
                </td>
            </tr>
        <?php } ?>
    </table>
<?php } else { ?>
    <table class="traffic-table">
        <tr>
            <td><em>No tiene guías.</em></td>
        </tr>
    </table>
<?php } ?>
