<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Reporte de cuenta de gastos <?= $this->rfc ?></title>
        <link href="/css/reportes.css?<?= time() ?>" media="screen" rel="stylesheet" type="text/css" >
    </head>
    <body>
        <table class="table table-striped table-bordered table-hover small">
            <thead>
                <tr>
                    <th style="width: 120px">Fecha</th>
                    <th>Folio</th>
                    <th>Patente</th>
                    <th>Aduana</th>
                    <th>Num.Pedimento</th>
                    <th>Referencia</th>
                    <th>RFC Cliente</th>
                    <th>I/E</th>
                    <th>Cve. Doc</th>
                    <th>Fecha Pago Pedimento</th>
                    <th>Fecha de Entrada</th>
                    <th>Tipo de Cambio</th>
                    <th>Factura Pedimento</th>
                    <th>Bultos/Piezas</th>
                    <th>Valor Aduana</th>
                    <th>DTA</th>
                    <th>IVA (Ped)</th>
                    <th>CNT</th>
                    <th>IGI (Adv)</th>
                    <th>Prevalidación</th>
                    <th>Guías</th>
                    <th>Maniobras</th>
                    <th>Almacenajes</th>
                    <th>Demoras</th>
                    <th>Flete aereo</th>
                    <th>Flete marítimo</th>
                    <th>Fletes y acarreos</th>
                    <th>Fletes</th>
                    <th>Alijadores</th>
                    <th>Total de Comprobados</th>
                    <th>Gastos complementarios</th>
                    <th>Impuestos aduanales</th>
                    <th>Revalidación</th>
                    <th>Rectificaciones</th>
                    <th>Honorarios</th>
                    <th>SubTotal</th>
                    <th>IVA</th>
                    <th>Anticipo</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                <?php if (isset($this->results)) { ?>
                    <?php foreach ($this->results as $item) { ?>
                        <?php
                        if ((int) $item["patente"] == 3589 && (int) $item["aduana"] == 640) {
                            $pedimento = $this->soapSitawinQro->detallePedimento($item["patente"], 640, $item["pedimento"]);
                        } else if ((int) $item["patente"] == 3589 && (int) $item["aduana"] == 240) {
                            $pedimento = $this->soapSitawinNld->detallePedimento($item["patente"], 240, $item["pedimento"]);
                        } else if ((int) $item["patente"] == 3589 && (int) $item["aduana"] == 800) {
                            $pedimento = $this->soapSitawinCol->detallePedimento($item["patente"], 800, $item["pedimento"]);
                            
                        }                        
                        if (!empty($pedimento)) {
                            $item["fecha_entrada"] = $pedimento["FechaEntrada"];
                            $item["tipo_cambio"] = $pedimento["TipoCambio"];
                            $item["dta"] = $pedimento["DTA"];
                            $item["iva"] = $pedimento["IVA"];
                            $item["cnt"] = $pedimento["CNT"];
                            $item["igi"] = $pedimento["IGI"];
                            $item["prev"] = $pedimento["PREV"];
                            $item["guias"] = $pedimento["Guias"];
                        }
                        ?>
                        <tr>
                            <td><?= $item["fecha_factura"] ?></td>
                            <td><?= $item["factura"] ?></td>
                            <td><?= $item["patente"] ?></td>
                            <td><?= $item["aduana"] ?></td>
                            <td><?= $item["pedimento"] ?></td>
                            <td><?= $item["referencia"] ?></td>
                            <td><?= $item["rfc"] ?></td>
                            <td><?= $item["ie"] ?></td>
                            <td><?= $item["regimen"] ?></td>
                            <td><?= $item["fecha_pedimento"] ?></td>
                            <td><?= isset($item["fecha_entrada"]) ? $item["fecha_entrada"] : "" ?></td>
                            <td><?= isset($item["tipo_cambio"]) ? $item["tipo_cambio"] : "" ?></td>
                            <td><?= $item["ref_factura"] ?></td>
                            <td><?= $item["bultos"] ?></td>
                            <td><?= number_format($item["valor_aduana"], 2, '.', ',') ?></td>
                            <td><?= isset($item["dta"]) ? number_format($item["dta"], 2, '.', ',') : "" ?></td>
                            <td><?= isset($item["iva"]) ? number_format($item["iva"], 2, '.', ',') : "" ?></td>
                            <td><?= isset($item["cnt"]) ? number_format($item["cnt"], 2, '.', ',') : "" ?></td>
                            <td><?= isset($item["igi"]) ? number_format($item["igi"], 2, '.', ',') : "" ?></td>
                            <td><?= isset($item["prev"]) ? number_format($item["prev"], 2, '.', ',') : "" ?></td>
                            <td><?= isset($item["guias"]) ? $item["guias"] : "" ?></td>
                            <td><?= $this->sumArray($item["conceptos"], array('maniobras')) ?></td>
                            <td><?= $this->sumArray($item["conceptos"], array('almacenaje', 'almacenajes')) ?></td>
                            <td><?= $this->sumArray($item["conceptos"], array('demoras')) ?></td>
                            <td><?= $this->sumArray($item["conceptos"], array('flete_aereo')) ?></td>
                            <td><?= $this->sumArray($item["conceptos"], array('flete_maritimo')) ?></td>
                            <td><?= $this->sumArray($item["conceptos"], array('fletes_y_acarreos', 'flete_terrestre')) ?></td>
                            <td><?= $this->sumArray($item["conceptos"], array('flete', 'fletes')) ?></td>
                            <td><?= $this->sumArray($item["conceptos"], array('alijadores')) ?></td>
                            <td><?= $this->sumArray($item["conceptos"], array('maniobras', 'almacenaje', 'almacenajes', 'demoras', 'flete_aereo', 'flete_maritimo', 'fletes_y_acarreos', 'flete_terrestre', 'flete', 'fletes', 'alijadores')) ?></td>
                            <td><?= $this->sumArray($item["conceptos"], array('gastos_complementarios_maniobras', 'gastos_complementarios_alijadores', 'gastos_complementarios', 'gastos_complementarios_almacenajes', 'gastos_complementarios_demoras', 'gastos_complementarios_fletes', 'gastos_compl_fletes', 'servicios_de_charter', 'tiempo_extra', 'servicio_extraordinario', 'gastos_fletes', 'gastos_alijadores', 'gastos_maniobras', 'gastos_almacenajes', 'gastos_demoras', 'gastos_alijadores')) ?></td>
                            <td><?= $this->sumArray($item["conceptos"], array('impuestos_aduanales')) ?></td>
                            <td><?= $this->sumArray($item["conceptos"], array('revalidacion')) ?></td>
                            <td><?= $this->sumArray($item["conceptos"], array('rectificaciones')) ?></td>
                            <td><?= number_format($item["honorarios"], 2, '.', ',') ?></td>
                            <td><?= number_format($item["sub_total"], 2, '.', ',') ?></td>
                            <td><?= number_format($item["iva"], 2, '.', ',') ?></td>
                            <td><?= number_format($item["anticipo"], 2, '.', ',') ?></td>
                            <td><?= number_format($item["total"], 2, '.', ',') ?></td>
                        </tr>
                    <?php } ?>
                <?php } else { ?>
                    <tr>
                        <td colspan="39">
                            <em>No se encontraton resultados para la búsqueda.</em>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
    </body>
</html>
