<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <title>Reportes</title>
        <link href="/css/reportes.css?<?= time() ?>" media="screen" rel="stylesheet" type="text/css" >
        <link href="/less/traffic-module.css" media="screen" rel="stylesheet" type="text/css" >
    </head>
    <body>
        <?php if (isset($this->content) && in_array($this->type, array("encabezado", "prasad", "anexo", "proveedores", "cnh"))) { ?>
            <a href="/clientes/data/excel" class="download" style="margin: 1px 1px 3px 1px">Descarga Excel</a>
            <?= $this->content ?>
        <?php } elseif (isset($this->content) && in_array($this->type, array("tecnico"))) { ?>
            <a href="/clientes/data/excel-layout-tecnico?patente=<?= $this->patente ?>&aduana=<?= $this->aduana ?>&rfc=<?= $this->rfc ?>&fechaIni=<?= $this->fechaIni ?>&fechaFin=<?= $this->fechaFin ?>" class="download" style="margin: 1px 1px 3px 1px">Descarga Excel</a>
            <?= $this->content ?>
        <?php } elseif (isset($this->content) && in_array($this->type, array("cargoquin"))) { ?>
            <a href="/clientes/data/excel-cargoquin" class="download" style="margin: 1px 1px 3px 1px">Descarga Excel</a>
            <div class="traffic-tabs">
                <ul class="traffic-tab-links">
                    <li class="active"><a href="#tab1">Assessment PN</a></li>
                    <li><a href="#tab2">Tariff Report</a></li>
                    <li><a href="#tab3">PN Report</a></li>
                </ul>
                <div class="traffic-tab-content">
                    <div id="tab1" class="traffic-tab active">
                        <?= $this->content ?>                        
                    </div>
                    <div id="tab2" class="traffic-tab">
                        <?= $this->fracciones ?>                        
                    </div>
                    <div id="tab3" class="traffic-tab">
                        <?= $this->partes ?>                        
                    </div>
                </div>
            </div>
            <div class="traffic-clear-10"></div>
            <script type="text/javascript" src="/js/jquery-1.9.1.min.js"></script>
            <script type="text/javascript">
                $(document).ready(function() {
                    $(".traffic-tabs .traffic-tab-links a").on("click", function(e)  {
                        var currentAttrValue = $(this).attr("href");
                        $(".traffic-tabs " + currentAttrValue).show().siblings().hide();
                        $(this).parent("li").addClass("active").siblings().removeClass("active");
                        e.preventDefault();
                    });
                });
            </script>
        <?php } else { ?>
            <h3><?= $this->error ?></h3>
        <?php } ?>
    </body>
</html>