<!doctype html>

<html lang="es">

<head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<?= $this->appConfig("website-description") ?>">
    <meta name="author" content="Jaime E. Valdez">
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />
    <title><?= $this->title ?></title>
    <link rel="icon" type="image/png" href="/favicon.png" />
    <?= $this->headMeta(); ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
    <style type="text/css">
        @media only screen and (max-width : 640px) {
            .traffic-navbar {
                display: none;
            }

            .twitter-timeline {
                display: none;
            }
        }

        @media only screen and (min-width : 640px) {
            .traffic-navbar-mobile {
                display: none;
            }
        }
    </style>
</head>

<body>
    <div id="top">
        <?= $this->partial("menus.phtml", array("menu" => $this->menu, "rol" => $this->rol)) ?>
        <div id="clear" style="height: 41px"></div>
    </div>
    <div id="status" class="traffic-status-bar">
        <div style="float:left; margin-left: 3px; height: 20px">
            <div style="float:left; padding-left: 5px">
                <i class="fas fa-user"></i>
            </div>
            <div style="float:left; padding-left: 5px; padding-top: 2px">
                <a href="/principal/index/mis-datos" style="color: white"><strong><?= strtoupper($this->username) ?></strong></a>
            </div>
        </div>
        <?php if (APPLICATION_ENV == "development") { ?>
            <div style="float:right; padding-left: 5px; padding-right: 5px; padding-top: 2px; background-color: #dddd00; color: #000; font-size: 10px">DEVELOPMENT</div>
        <?php } ?>
        <?php if (APPLICATION_ENV == "staging") { ?>
            <div style="float:right; padding-left: 5px; padding-right: 5px; padding-top: 2px; background-color: #ff9933; color: #000; font-size: 10px">STAGE</div>
        <?php } ?>
    </div>
    <div id="content">
        <?php if (isset($this->noticias) && !empty($this->noticias)) { ?>
            <p class="alert" style="margin: 5px; padding: 5px; border: 1px #cccc00 solid; font-size: 11px; color: #555">
                <?php foreach ($this->noticias as $item) { ?>
                    <strong><?= $item["alerta"] ?></strong>:&nbsp;<?= $item["contenido"] ?><br>
                <?php } ?>
            </p>
        <?php } ?>
        <?= $this->layout()->content ?>
        <div class="traffic-clear-20"></div>
    </div>
    <div id="footer-copy">&copy;&nbsp;2013-<?= date("Y") ?>
        &nbsp;Derechos reservados del programador. Este portal se encuentra bajo licencia de uso de <?= $this->appConfig('empresa') ?>.<?= $this->rev ?><span style="float: right; color: #000; margin-right: 5px;"><strong>¿Problemas?</strong>&nbsp;<a href="/soporte/" target="_blank">Genera un Ticket de soporte aqui.</a></span>
    </div>
    <div class="traffic-clear-20"></div>
    <div class="traffic-clear-20"></div>

</body>

</html>