<div class="navbar navbar-fixed-top traffic-navbar">
    <div class="navbar-inner traffic-navbar-inner">
        <ul class="nav">
            <li>
                <a href="/principal/index/index">
                    <i class="fas fa-home" style="font-size: 1.2em; color: white"></i>
                </a>
            </li>
            <?php if (isset($this->menu) && !empty($this->menu) && is_array($this->menu)) { ?>
                <?php if (isset($this->menu)) { ?>
                    <?php foreach ($this->menu as $item) { ?>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle"
                               data-toggle="dropdown"><?= mb_strtoupper($item["moduloNombre"], "UTF-8") ?></a>
                            <ul class="dropdown-menu">
                                <?php foreach (json_decode($item["menus"]) as $m) { ?>
                                    <li><a href="<?= $m->link ?>"><?= $m->title ?></a></li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>
                    <?php if (!in_array($this->rol, array("inhouse", "corresponsal", "cliente"))) { ?>
                        <li>
                            <a href="/principal/index/iso">SGC 2015</a>
                        </li>
                        <li>
                            <a href="/principal/index/oea">OEA</a>
                        </li>
                        <li>
                            <a href="/principal/index/oaq-te-escucha">OAQ Te escucha</a>
                        </li>
                    <?php } ?>
                <?php } ?>
            <?php } ?>
        </ul><!-- nav -->
        <ul class="nav pull-right">
            <li class="btn-logout">
                <a title="Salir del portal" href="<?= $this->appConfig("link-logout") ?>">
                    <i class="fas fa-sign-out-alt" style="font-size: 1.2em; color: white"></i>
                </a>
            </li>
        </ul>
    </div><!-- navbar-inner -->
</div>
<div class="navbar navbar-fixed-top traffic-navbar-mobile">
    <div class="navbar-inner traffic-navbar-inner ">
        <ul class="nav">
            <li>
                <a href="/principal/index/index">
                    <i class="fas fa-home" style="font-size: 1.2em; color: white"></i>
                </a>
            </li>
        </ul>
        <ul class="nav pull-right">
            <li class="btn-logout">
                <a title="Salir del portal" href="<?= $this->appConfig("link-logout") ?>">
                    <i class="fas fa-sign-out-alt" style="font-size: 1.2em; color: white"></i>
                </a>
            </li>
        </ul>
    </div>
</div>
