<style>
    input[readonly]{
        background-color: #eee;
    }
    .infodialog .ZebraDialog_Title { background:#073d75; border-bottom: 1px solid #222; }
    .infodialog .ZebraDialog_Body { background-image: none; }
    .selectboxit-container .selectboxit, .selectboxit-container .selectboxit-options {
        width: 400px; /* Width of the dropdown button */
        border-radius:0;
        max-height:240px;
        font-size: 11px;
    }
    .selectboxit-options .selectboxit-option .selectboxit-option-anchor {
        white-space: normal;
        min-height: 30px;
        height: auto;
        font-size: 11px;
        line-height: 14px;
        margin: 0;
        padding: 0;
    }
</style>
<div class="semaphoreBox" style="float: left">
    <div class="semaphore-holder">
        <div class="semaphore-black"></div><span>No se completo</span>
    </div>
    <div class="semaphore-holder">
        <div class="semaphore-blue"></div><span>Edoc enviado</span>
    </div>
    <div class="semaphore-holder">
        <div class="semaphore-green"></div><span>Edoc completado</span>
    </div>
    <div class="semaphore-holder">
        <div class="semaphore-red"></div><span>Edoc con error</span>
    </div>
</div>
<form id="files" method="post" enctype="multipart/form-data">
    <input type="hidden" name="directory" value="<?= $this->directory ?>" />
    <table class="traffic-table traffic-table-left">
        <tr>
            <th colspan="5" class="traffic-table-subtitle">DATOS DEL DOCUMENTO<span style="color:red; float: right; font-size: 10px">* Campos requeridos</span></th>
        </tr>
        <tr>
            <td rowspan="3" style="width: 410px;"><?= $this->form->firmante ?></td>
            <td style="width: 220px;"><?= $this->form->patente ?></td>
            <td><?= $this->form->aduana ?></td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td><?= $this->form->referencia ?></td>
            <td><?= $this->form->pedimento ?></td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td><?= $this->form->rfc ?></td>
            <td colspan="2"><?= $this->form->nombre ?></td>
        </tr>
    </table>
    <table class="traffic-table traffic-table-left">
        <tr>
            <th colspan="4" class="traffic-table-subtitle">ARCHIVO</th>
        </tr>
        <tr>
            <th class="traffic-table-subtitle">ARCHIVO</th>
            <th class="traffic-table-subtitle">TIPO DE ARCHIVO</th>
            <th class="traffic-table-subtitle">SUB TIPO</th>
            <th class="traffic-table-subtitle">&nbsp;</th>
        </tr>
        <tr>
            <td><input type="file" name="file" id="file" /></td>
            <td style="width: 340px">
                <?= $this->form->tipo ?>
            </td>
            <td style="width: 340px">
                <select id="subTipo" name="subTipo" disabled="true">
                    <option value="">---</option>
                </select>
            </td>
            <td><button id="upload" tabindex="5" class="traffic-btn traffic-btn-primary traffic-btn-right">Agregar</button></td>
        </tr>
    </table>
</form>
<div id="edocuments"></div>
<div class="traffic-clear-20"></div>
<a onclick="window.history.back();" class="traffic-btn traffic-btn-back">&Lt;&nbsp;Regresar</a>
<button id="enviar" tabindex="5" class="traffic-btn traffic-btn-save traffic-btn-right">Enviar VUCEM</button>
<div class="traffic-clear-5"></div>