<?php 
//require_once 'Casa/Casa.php';
//$casa = new Casa("C:\Tmp\espejo");
//$pedimento = $casa->pedimentoXml();
?>
<!doctype html>
<head>  
  <meta charset="utf-8">  
  <title>Archivo de validación</title>  
  <meta name="description" content="Welcome to my basic template.">
  <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
</head>
<style>
    table td,
    table th,
    table tr {
        font-size: 11px;
        margin: 2px;
        padding: 2px;
    }
    table td,
    table th {
        border: 1px #d2d2d2 solid;
    }
    table td {
        text-align: center;
        padding: 2px 5px;
    }    
</style>
<body>  
    <?php if($this->pre) { ?>
    <table>
        <thead>
            <tr>
                <th>Archivo</th>
                <th>NumArchivo</th>
                <th>NumJuliano</th>
                <th>Fecha</th>
                <th>ArchivoValidado</th>
<!--                <th>Cotenido</th>-->
            </tr>
        </thead>
        <tbody>
        <?php foreach($this->pre as $item) { ?>        
            <tr>
                <td><?= $item["archivoNombre"] ?></td>
                <td><?= $item["archivoNum"] ?></td>
                <td><?= $item["archivoNumJuliano"] ?></td>
                <td><?= $item["fecha"] ?></td>
                <td><?= $item["archivoValidado"] ?></td>
<!--                <td><?= $item["contenido"] ?></td>-->
            </tr>        
        <?php } ?>
        </tbody>
    </table>
    <?php } ?>
</body>  
</html>