<!doctype html>
<html lang="en">
    <head>
        <title>Fracciones</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="OAQ Web Portal">
        <meta name="author" content="Jaime E. Valdez">
        <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
        <meta http-equiv="Pragma" content="no-cache" />
        <meta http-equiv="Expires" content="0" />
    </head>
    <style>
        body {
            font-family: sans-serif;
            border: 0;
            margin: 0;
        }
        table {
            border-collapse: collapse;
        }
        table tr {
            background: transparent;
        }
        table th,
        table td {
            padding: 2px 3px;
            font-size: 12px;
            border: 1px #999 solid;
            text-align: center;
        }
        table th {
            background-color: #e1e1f9;
            min-width: 80px;
        }
    </style>
    <body>
        <?php if (isset($this->data)) { ?>
            <table>
                <thead>
                    <tr>
                        <th># Tariff</th>
                        <th>P.N.</th>
                        <th>Quantity</th>
                        <th>Tariff Descrption</th>
                        <th>UM</th>
                        <th>Origin Country</th>
                        <th>Unit Price</th>
                        <th>Total Quantity</th>
                        <th>Invoice #</th>
                        <th>Reference</th>
                        <th>% IGI</th>
                        <th>IGI</th>
                        <th>P.N. Assessment</th>
                        <th>IVA</th>
                        <th>P.N. Assessment</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                        $i = 1;
                        foreach ($this->data as $ped) { 
                        if($i & 1) {
                            $style = "background-color: #fefefe;";
                        } else {
                            $style = "background-color: #f3f3f3;";                            
                        }
                        $i++;
                        ?>
                        <tr<?= $style ?>>
                            <td><?= $ped["ordenFactura"] ?></td>
                            <td><?= $ped["numParte"] ?></td>
                            <td><?= $ped["cantidadFactura"] ?></td>
                            <td><?= $ped["descripcion"] ?></td>
                            <td><?= $ped["umc"] ?></td>
                            <td><?= $ped["paisOrigen"] ?></td>
                            <td><?= number_format($ped["precioUnitario"], 6) ?></td>
                            <td><?= $ped["cantidadFactura"] ?></td>
                            <td><?= $ped["numFactura"] ?></td>
                            <td><?= $ped["referencia"] ?></td>
                            <td><?= $ped["igi"] ?></td>
                            <td><?= $ped["importeIgi"] ?></td>
                            <td><?= (isset($ped["importeIgi"])) ? number_format(($ped["importeIgi"] / $ped["cantidadFactua"]), 2) : '0' ?></td>
                            <td><?= $ped["importeIva"] ?></td>
                            <td><?= (isset($ped["importeIgi"])) ? number_format(($ped["importeIva"] / $ped["cantidadFactua"]), 2) : '0' ?></td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        <?php } ?>
    </body>
</html>
