<!doctype html>
<html lang="en">
    <head>
        <title>Gearman Pedimentos</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="OAQ Web Portal">
        <meta name="author" content="Jaime E. Valdez">
        <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
        <meta http-equiv="Pragma" content="no-cache" />
        <meta http-equiv="Expires" content="0" />
    </head>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: sans-serif;
            font-size: 11px;
        }
        table {
            border-collapse:collapse;
        }
        th, td {
            border: 1px #ccc solid;
            padding: 2px 5px;
        }
        th {
            background: #d8d8d8;
        }
    </style>
    <body>
        <table>
            <thead>
                <tr>
                    <th>Operación</th>
                    <th>I/E</th>
                    <th>Patente</th>
                    <th>Aduana</th>
                    <th>Pedimento</th>
                    <th>Referencia</th>
                    <th>F. Pago</th>
                    <th>RFC</th>
                </tr>
            </thead>
            <tbody>
                <?php if (isset($this->arr) && !empty($this->arr)) { ?>
                    <?php foreach ($this->arr as $item) { ?>
                        <tr>
                            <td><?= $item["operacion"] ?></td>
                            <td><?= $item["tipoOperacion"] ?></td>
                            <td><?= $item["patente"] ?></td>
                            <td><?= $item["aduana"] ?></td>
                            <td><?= $item["pedimento"] ?></td>
                            <td><?= $item["referencia"] ?></td>
                            <td><?= $item["fechaPago"] ?></td>
                            <td><?= $item["rfc"] ?></td>
                        </tr>
                    <?php } ?>
                <?php } else { ?>
                        <tr>
                            <td colspan="8">
                                <em>No hay pedimentos pagados.</em>
                            </td>
                        </tr>
                <?php } ?>
            </tbody>
        </table> 
    </body>
</html>