<style>
    body {
        font-family: helvetica;
    }
    table {
        
    }
    table td {
        vertical-align: top
    }
    table.info td {
        border: 1px #333 solid;
    }
    table.info td.highlight {
        background-color: #e2e2e2;
        font-weight: bold;
    }
</style>
<table cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td><img src="/images/oaq_transportes.jpg" ></td>
        <td><table cellspacing="0" cellpadding="0" border="0">
            <tr>
                <td>OAQ TRANSPORTES DE QUERETARO, S.A. DE C.V.</td>                    
            </tr>
            <tr>
                <td>RFC: OTQ131120BW4<br>
Mariano Perrusquia No. 102 int. 4 Col. San Angel<br>
Querétaro, Queretaro. C.P. 76030 Tel. 442-2160533<br>
Nextel ID 62*168729*9 Nextel No. (01 449)4411740<br>
Régimen Fiscal: Personas Morales Régimen General de Ley<br>
SERVICIO DE TRANSPORTE DE CARGA FEDERAL</td>
            </tr>
        </table></td>
        <td><table cellspacing="0" cellpadding="0" border="0" class="info">
            <tr>
                <td colspan="2">CARTA PORTE</td>
            </tr>
            <tr>
                <td class="highlight">FOLIO</td>
                <td>XXXXX</td>
            </tr>
            <tr>
                <td class="highlight">FECHA</td>
                <td>XX/XX/XXXX</td>
            </tr>
        </table></td>
    </tr>
</table>
<table cellspacing="0" cellpadding="0" border="0" class="info">
    <tr>
        <td class="highlight">CLIENTE:</td>
        <td>SOLUCION E INGENIO SA DE C.V.</td>
    </tr>
    <tr>
        <td class="highlight">RFC:</td>
        <td>SIN040329BV2</td>
    </tr>
    <tr>
        <td class="highlight">DOMICILIO:</td>
        <td>AV. UNIVERSIDAD PONIENTE NUM 286 COL VIVEROS QRO.QRO. CP 76155</td>
    </tr>
</table>
<table cellspacing="0" cellpadding="0" border="0" class="info">
    <tr>
        <td class="highlight">ORIGEN:</td>
        <td>NUEVO LAREDO</td>
        <td class="highlight">DESTINO:</td>
        <td>QUERETARO</td>
    </tr>
    <tr>
        <td colspan="2">&nbsp;</td>
        <td colspan="2">&nbsp;</td>
    </tr>
</table>
<table cellspacing="0" cellpadding="0" border="0" class="info">
    <tr>
        <td class="highlight">CANTIDAD:</td>
        <td class="highlight">UNIDAD:</td>
        <td class="highlight">PESO:</td>
        <td class="highlight">EL REMITENTE DICE QUE CONTIENE:</td>
    </tr>
    <tr>
        <td>6</td>
        <td>PIEZAS</td>
        <td>20</td>
        <td>MERCANCIA DE SU PROPIEDAD</td>
    </tr>
</table>
<table cellspacing="0" cellpadding="0" border="0" class="info">
    <tr>
        <td class="highlight">PEDIMENTO:</td>
        <td class="highlight">REFERENCIA:</td>
        <td class="highlight">PLACAS:</td>
        <td class="highlight">OPERADOR:</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>XXXXX0000</td>        
        <td>ROLANDO HERNANDEZ<br>
RADIO 42*674596*2</td>
    </tr>
</table>
<table cellspacing="0" cellpadding="0" border="0" class="info">
    <tr>
        <td class="highlight">DOCUMENTO:</td>
        <td class="highlight">RECIBI DE CONFORMIDAD:</td>
        <td class="highlight">OBSERVACIONES:</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
</table>