<form id="form-signin" class="form-signin">
    <img src="/images/oaq-logo-landing.png" class="img-fluid" alt="Logo OAQ"/>
    <br>
    <br>
    <label for="username" class="sr-only">Usuario</label>
    <input type="text" id="username" name="username" class="form-control" placeholder="Usuario" required autofocus autocomplete="off">
    <label for="password" class="sr-only">Contraseña</label>
    <input type="password" id="password" name="password" class="form-control" placeholder="Contraseña" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit" id="submit">
        <i class="fas fa-sign-in-alt"></i> Entrar
    </button>
</form>