<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link href="<?= $this->appConfig('cove-css') ?>" media="screen" rel="stylesheet" type="text/css" >
    </head>
    <body>
        <img src="<?= $this->appConfig('cove-logo') ?>" />
        <h3>COMPROBANTE DE VALOR ELECTRÓNICO</h3>
        <p style="font-size: 9px; text-align: center; color: #000"><strong>REFERENCIA:</strong> <?= $this->referencia ?><br><strong>PEDIMENTO:</strong> <?= $this->pedimento ?></p>
        <p>Datos del comprobante <span><?= ($this->cove != '') ? $this->cove : '<span style="color:red">{COMPROBANTE NO VÁLIDO}</span>' ?></span></p>
        <table>
            <tr>
                <th>Tipo de operación</th>
                <th>Relación de facturas</th>
                <th>No. de factura</th>                
            </tr>
            <tr>
                <td><?= ($this->data["tipoOperacion"] == 'TOCE.EXP') ? 'Exportación' : 'Importación' ?></td>
                <td><?= (isset($this->data["numeroRelacionFacturas"])) ? 'CON RELACIÓN DE FACTURAS' : 'SIN RELACIÓN DE FACTURAS' ?></td>
                <td><?= $this->data["numeroFacturaOriginal"] ?></td>
            </tr>
            <tr>
                <th>Tipo de figura</th>                
                <th colspan="2">Fecha Exp.</th>                
            </tr>            
            <tr>
                <td><?= ($this->data["tipoFigura"] == '1') ? 'Agente aduanal' : $this->data["tipoFigura"] ?></td>
                <td colspan="2"><?= $this->data["fechaExpedicion"] ?></td>
            </tr>
            <tr>
                <th colspan="3">Observaciones</th>
            </tr>
            <tr>
                <?php if(isset($this->data["observaciones"])) { ?>
                <td colspan="3"><?= (!isset($this->data["observaciones"])) ? '&nbsp;' : (mb_check_encoding($this->data["observaciones"], 'UTF-8')) ? utf8_decode($this->data["observaciones"]) : $this->data["observaciones"] ?></td>
                <?php } else { ?>
                <td colspan="3">&nbsp;</td>
                <?php } ?>
            </tr>
        </table>
        <p>RFC con permisos de consulta</p>
        <table>
            <tr>
                <th>RFC de consulta</th>
            </tr>
            <?php if(is_array($this->data["rfcConsulta"] )) { ?>
            <?php foreach($this->data["rfcConsulta"] as $rfcConsulta) { ?>
            <tr>
                <td><?= $rfcConsulta ?></td>
            </tr>
            <?php } ?>
            <?php } else { ?>
            <tr>
                <td><?= (isset($this->data["rfcConsulta"])) ? $this->data["rfcConsulta"] : '&nbsp;' ?></td>
            </tr>
            <?php } ?>
        </table>
        <p>Número de patente aduanal</p>
        <table>
            <tr>
                <th>Número autorización aduanal</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["patenteAduanal"])) ? $this->data["patenteAduanal"] : '&nbsp;' ?></td>
            </tr>
        </table>
        <p>Datos de la factura</p>
        <table>
            <tr>
                <th>Subdivisión</th>
                <th>Certificado de origen</th>
                <th>No. de exportador autorizado</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["factura"]["subdivision"]) && $this->data["factura"]["subdivision"] != '0') ? 'Con Subdivisión' : 'Sin subdivisión' ?></td>
                <td><?= (isset($this->data["factura"]["certificadoOrigen"]) && $this->data["factura"]["certificadoOrigen"] != '0') ? 'Si funge como certificado de origen' : 'No funge como certificado de origen' ?></td>
                <td><?= (isset($this->data["factura"]["numeroExportadorAutorizado"]) && $this->data["factura"]["numeroExportadorAutorizado"] != '') ? $this->data["factura"]["numeroExportadorAutorizado"] : '' ?></td>
            </tr>
        </table>
        <p>Datos generales del emisor</p>
        <table>
            <tr>
                <th>Tipo de identificador</th>
                <th colspan="2">Tax ID/Sin Tax ID/RFC/CURP</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["emisor"]["tipoIdentificador"])) ? $this->identificadorDesc($this->data["emisor"]["tipoIdentificador"]) : '&nbsp;' ?></td>
                <td colspan="2"><?= (isset($this->data["emisor"]["identificacion"]) && $this->data["emisor"]["identificacion"] != '0') ? $this->data["emisor"]["identificacion"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Nombre(s) o Razón Social</th>
                <th>Apellido paterno</th>
                <th>Apellido materno</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["emisor"]["nombre"]) && $this->data["emisor"]["nombre"] != '') ? $this->data["emisor"]["nombre"] : '&nbsp;' ?></td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        </table>
        <p>Domicilio emisor</p>
        <table>
            <tr>
                <th>Calle</th>
                <th>No. exterior</th>
                <th>No. interior</th>
                <th>Código postal</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["emisor"]["domicilio"]["calle"]) && $this->data["emisor"]["domicilio"]["calle"] != '') ? $this->data["emisor"]["domicilio"]["calle"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["emisor"]["domicilio"]["numeroExterior"]) && $this->data["emisor"]["domicilio"]["numeroExterior"] != '') ? $this->data["emisor"]["domicilio"]["numeroExterior"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["emisor"]["domicilio"]["numeroInterior"]) && $this->data["emisor"]["domicilio"]["numeroInterior"] != '') ? $this->data["emisor"]["domicilio"]["numeroInterior"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["emisor"]["domicilio"]["codigoPostal"]) && $this->data["emisor"]["domicilio"]["codigoPostal"] != '') ? $this->data["emisor"]["domicilio"]["codigoPostal"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Colonia</th>
                <th colspan="3">Localidad</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["emisor"]["domicilio"]["colonia"]) && $this->data["emisor"]["domicilio"]["colonia"] != '') ? $this->data["emisor"]["domicilio"]["colonia"] : '&nbsp;' ?></td>
                <td colspan="3"><?= (isset($this->data["emisor"]["domicilio"]["localidad"]) && $this->data["emisor"]["domicilio"]["localidad"] != '') ? $this->data["emisor"]["domicilio"]["localidad"] : '&nbsp;' ?></td>
            </tr>
            <tr>
				<th>Municipio</th>
				<th colspan="3">Entidad federativa</th>
			</tr>
			<tr>
				<td><?= (isset($this->data["emisor"]["domicilio"]["municipio"]) && $this->data["emisor"]["domicilio"]["municipio"] != '') ? $this->data["emisor"]["domicilio"]["municipio"] : '&nbsp;' ?></td>
				<td colspan="3"><?= (isset($this->data["emisor"]["domicilio"]["entidadFederativa"]) && $this->data["emisor"]["domicilio"]["entidadFederativa"] != '') ? $this->data["emisor"]["domicilio"]["entidadFederativa"] : '&nbsp;' ?></td>
			</tr>
            <tr>
                <th colspan="4">País</th>
            </tr>
            <tr>
                <td colspan="4"><?= (isset($this->data["emisor"]["domicilio"]["pais"]) && $this->data["emisor"]["domicilio"]["pais"] != '') ? $this->data["emisor"]["domicilio"]["pais"] : '&nbsp;' ?></td>
            </tr>
        </table>
        <p>Datos generales del destinatario</p>
        <table style="page-break-after:always">
            <tr>
                <th>Tipo de identificador</th>
                <th colspan="2">Tax ID/Sin Tax ID/RFC/CURP</th>                
            </tr>
            <tr>
                <td><?= (isset($this->data["destinatario"]["tipoIdentificador"])) ? $this->identificadorDesc($this->data["destinatario"]["tipoIdentificador"]) : '&nbsp;' ?></td>
                <td colspan="2"><?= (isset($this->data["destinatario"]["identificacion"]) && $this->data["destinatario"]["identificacion"] != '') ? $this->data["destinatario"]["identificacion"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Nombre(s) o Razón Social</th>
                <th>Apellido paterno</th>
                <th>Apellido materno</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["destinatario"]["nombre"]) && $this->data["destinatario"]["nombre"] != '') ? $this->data["destinatario"]["nombre"] : '&nbsp;' ?></td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        </table>
        <p>Domicilio del destinatario</p>
        <table>
            <tr>
                <th>Calle</th>
                <th>No. exterior</th>
                <th>No. interior</th>
                <th>Código postal</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["destinatario"]["domicilio"]["calle"]) && $this->data["destinatario"]["domicilio"]["calle"] != '') ? $this->data["destinatario"]["domicilio"]["calle"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["destinatario"]["domicilio"]["numeroExterior"]) && $this->data["destinatario"]["domicilio"]["numeroExterior"] != '') ? $this->data["destinatario"]["domicilio"]["numeroExterior"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["destinatario"]["domicilio"]["numeroInterior"]) && $this->data["destinatario"]["domicilio"]["numeroInterior"] != '') ? $this->data["destinatario"]["domicilio"]["numeroInterior"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["destinatario"]["domicilio"]["codigoPostal"]) && $this->data["destinatario"]["domicilio"]["codigoPostal"] != '') ? $this->data["destinatario"]["domicilio"]["codigoPostal"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Colonia</th>
                <th colspan="3">Localidad</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["destinatario"]["domicilio"]["colonia"]) && $this->data["destinatario"]["domicilio"]["colonia"] != '') ? $this->data["destinatario"]["domicilio"]["colonia"] : '&nbsp;' ?></td>
                <td colspan="3"><?= (isset($this->data["destinatario"]["domicilio"]["localidad"]) && $this->data["destinatario"]["domicilio"]["localidad"] != '') ? $this->data["destinatario"]["domicilio"]["localidad"] : '&nbsp;' ?></td>
            </tr>
            <tr>
				<th>Municipio</th>
				<th colspan="3">Entidad federativa</th>
			</tr>
			<tr>        
				<td><?= (isset($this->data["destinatario"]["domicilio"]["municipio"]) && $this->data["destinatario"]["domicilio"]["municipio"] != '') ? $this->data["destinatario"]["domicilio"]["municipio"] : '&nbsp;' ?></td>
				<td colspan="3"><?= (isset($this->data["destinatario"]["domicilio"]["entidadFederativa"]) && $this->data["destinatario"]["domicilio"]["entidadFederativa"] != '') ? $this->data["destinatario"]["domicilio"]["entidadFederativa"] : '&nbsp;' ?></td>
			</tr>
            <tr>
                <th colspan="4">País</th>
            </tr>
            <tr>
                <td colspan="4"><?= (isset($this->data["destinatario"]["domicilio"]["pais"]) && $this->data["destinatario"]["domicilio"]["pais"] != '') ? $this->data["destinatario"]["domicilio"]["pais"] : '&nbsp;' ?></td>
            </tr>
        </table>
        <p>Datos de la mercancía</p>
        <table>
            <tr>
                <th>Descripción genérica de la mercancía</th>
                <th>Num.Parte</th>
                <th>Tipo moneda</th>
                <th>Valor unitario</th>
                <th>Valor total</th>
                <th>Valor total en dólares</th>
                <th>Clave UMC</th>
                <th>Cantidad UMC</th>
            </tr>
            <?php if(isset($this->data["mercancias"]["descripcionGenerica"])) { ?>
            <tr>
                <td><?= (isset($this->data["mercancias"]["descripcionGenerica"]) && $this->data["mercancias"]["descripcionGenerica"] != '') ? $this->data["mercancias"]["descripcionGenerica"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["mercancias"]["numparte"]) && $this->data["mercancias"]["numparte"] != '') ? $this->data["mercancias"]["numparte"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["mercancias"]["tipoMoneda"]) && $this->data["mercancias"]["tipoMoneda"] != '') ? $this->data["mercancias"]["tipoMoneda"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["mercancias"]["valorUnitario"]) && $this->data["mercancias"]["valorUnitario"] != '') ? '$ ' . number_format($this->data["mercancias"]["valorUnitario"], 6, '.', ',') : '&nbsp;' ?></td>
                <td><?= (isset($this->data["mercancias"]["valorTotal"]) && $this->data["mercancias"]["valorTotal"] != '') ? '$ ' . number_format($this->data["mercancias"]["valorTotal"], 6, '.', ',') : '&nbsp;' ?></td>
                <td><?= (isset($this->data["mercancias"]["valorDolares"]) && $this->data["mercancias"]["valorDolares"] != '') ? '$ ' . number_format($this->data["mercancias"]["valorDolares"], 4, '.', ',') : '&nbsp;' ?></td>
                <td><?= (isset($this->data["mercancias"]["claveUnidadMedida"]) && $this->data["mercancias"]["claveUnidadMedida"] != '') ? $this->data["mercancias"]["claveUnidadMedida"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["mercancias"]["cantidad"]) && $this->data["mercancias"]["cantidad"] != '') ? number_format($this->data["mercancias"]["cantidad"], 3, '.', ',') : '&nbsp;' ?></td>                
            </tr>
            <?php if(isset($this->data["mercancias"]["descripcionesEspecificas"])) { ?>
            <tr>
                <td colspan="8" style="margin:0; padding: 0;">
                    <table class="merc" style="width: 100%">
                        <tr>
                            <th style="border-left:0;">Marca</th>
                            <th>Modelo</th>
                            <th>Submodelo</th>
                            <th>Num. de Serie</th>
                        </tr>
                        <tr>
                            <td><?= (isset($this->data["mercancias"]["descripcionesEspecificas"]["marca"])) ? $this->data["mercancias"]["descripcionesEspecificas"]["marca"] : '&nbsp;' ?></td>
                            <td><?= (isset($this->data["mercancias"]["descripcionesEspecificas"]["modelo"])) ? $this->data["mercancias"]["descripcionesEspecificas"]["modelo"] : '&nbsp;' ?></td>
                            <td><?= (isset($this->data["mercancias"]["descripcionesEspecificas"]["subModelo"])) ? $this->data["mercancias"]["descripcionesEspecificas"]["subModelo"] : '&nbsp;' ?></td>
                            <td><?= (isset($this->data["mercancias"]["descripcionesEspecificas"]["numeroSerie"])) ? $this->data["mercancias"]["descripcionesEspecificas"]["numeroSerie"] : '&nbsp;' ?></td>
                        </tr>
                    </table>
                </td>
            </tr>
            <?php } ?>
            <?php } elseif(isset($this->data["mercancias"][0]["descripcionGenerica"])) { ?>
            <?php foreach($this->data["mercancias"] as $merc) { ?>
            <tr>
                <td><?= (isset($merc["descripcionGenerica"]) && $merc["descripcionGenerica"] != '') ? $merc["descripcionGenerica"] : '&nbsp;' ?></td>
                <td><?= (isset($merc["numparte"]) && $merc["numparte"] != '') ? $merc["numparte"] : '&nbsp;' ?></td>
                <td><?= (isset($merc["tipoMoneda"]) && $merc["tipoMoneda"] != '') ? $merc["tipoMoneda"] : '&nbsp;' ?></td>
                <td><?= (isset($merc["valorUnitario"]) && $merc["valorUnitario"] != '') ? '$ ' . number_format($merc["valorUnitario"], 6, '.', ',') : '&nbsp;' ?></td>
                <td><?= (isset($merc["valorTotal"]) && $merc["valorTotal"] != '') ? '$ ' . number_format($merc["valorTotal"], 6, '.', ',') : '&nbsp;' ?></td>
                <td><?= (isset($merc["valorDolares"]) && $merc["valorDolares"] != '') ? '$ ' . number_format($merc["valorDolares"], 4, '.', ',') : '&nbsp;' ?></td>

                <td><?= (isset($merc["claveUnidadMedida"]) && $merc["claveUnidadMedida"] != '') ? $merc["claveUnidadMedida"] : '&nbsp;' ?></td>
                <td><?= (isset($merc["cantidad"]) && $merc["cantidad"] != '') ? number_format($merc["cantidad"], 3, '.', ',') : '&nbsp;' ?></td>
            </tr>
            <?php if(isset($merc["descripcionesEspecificas"])) { ?>
            <tr>
                <td colspan="8" style="margin:0; padding: 0;">
                    <table class="merc" style="width: 100%; border:0">
                        <tr>
                            <th style="border-left:0; background-color: #fff;">Marca</th>
                            <th style="background-color: #fff;">Modelo</th>
                            <th style="background-color: #fff;">Submodelo</th>
                            <th style="background-color: #fff;">Num. de Serie</th>
                        </tr>
                        <tr>
                            <td><?= (isset($merc["descripcionesEspecificas"]["marca"])) ? $merc["descripcionesEspecificas"]["marca"] : '&nbsp;' ?></td>
                            <td><?= (isset($merc["descripcionesEspecificas"]["modelo"])) ? $merc["descripcionesEspecificas"]["modelo"] : '&nbsp;' ?></td>
                            <td><?= (isset($merc["descripcionesEspecificas"]["subModelo"])) ? $merc["descripcionesEspecificas"]["subModelo"] : '&nbsp;' ?></td>
                            <td><?= (isset($merc["descripcionesEspecificas"]["numeroSerie"])) ? $merc["descripcionesEspecificas"]["numeroSerie"] : '&nbsp;' ?></td>
                        </tr>
                    </table>
                </td>
            </tr>
            <?php } ?>
            <?php } ?>
            <?php } ?>
        </table>        
        <p>Datos del COVE (Firma electrónica)</p>
        <table>
            <tr>
                <th>Cadena original</th>
            </tr>
            <tr>
                <td class="signature"><?= (isset($this->data["firmaElectronica"]["cadenaOriginal"]) && $this->data["firmaElectronica"]["cadenaOriginal"] != '') ? wordwrap($this->data["firmaElectronica"]["cadenaOriginal"], 100, "<br />", true) : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Firma</th>
            </tr>
            <tr>
                <td class="signature"><?= (isset($this->data["firmaElectronica"]["firma"]) && $this->data["firmaElectronica"]["firma"] != '') ? wordwrap($this->data["firmaElectronica"]["firma"], 100, "<br />", true) : '&nbsp;' ?></td>
            </tr>
        </table>
        <br />
        <p class="legend" style="font-size:9px">Esto es una representación gráfica del XML de un COVE su uso es exclusivo para interpretar la información de una forma más clara, su valides ante la autoridad es de 240 días a partir de la fecha de solicitud ya que es borrado de la base de datos de Ventanilla Única, pasado este tiempo su valides es meramente histórica. Este acuse no sustituye el de Ventanilla Única y es generado por el sistema VUCEM OAQ como alternativa. Solicitud generada el día <?= $this->fechas["enviado"] ?> y fue actualizada el día <?= $this->fechas["actualizado"] ?>.</p>
    </body>
</html>
