<!DOCTYPE html>
<html>
    <head>
        <title><?= $this->cove ?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link href="http://oaqintranet.localhost/css/cove.css" media="screen" rel="stylesheet" type="text/css" >
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
    </head>
    <body>
        <img src="http://oaqintranet.localhost/images/logo_oaq.jpg" />
        <h3>COMPROBANTE DE VALOR ELECTRÓNICO</h3>
        <?php if($this->data) { ?>
        <h2 style="text-align: center"><?= $this->cove ?></h2>
        <?php if(isset($this->adenda)) { 
            echo "<h4 style=\"text-align: center\"> ADENDA {$this->adenda}</h4>";
        } ?>
        <table class="table table-striped table-bordered table-hover small">
            <tr>
                <th>Tipo de operación</th>
                <th>Relación de facturas</th>
                <th>No. de factura</th>                
            </tr>
            <tr>
                <td><?= ($this->data["tipoOperacion"] == 'TOCE.EXP') ? 'Exportación' : 'Importación' ?></td>
                <td><?= (isset($this->data["numeroRelacionFacturas"])) ? 'CON RELACIÓN DE FACTURAS' : 'SIN RELACIÓN DE FACTURAS' ?></td>
                <td><?= isset($this->data["numeroFacturaOriginal"]) ? $this->data["numeroFacturaOriginal"] : $this->data["numeroFacturaRelacionFacturas"] ?></td>
            </tr>
            <tr>
                <th>Tipo de figura</th>                
                <th colspan="2">Fecha Exp.</th>                
            </tr>            
            <tr>
                <td><?= ($this->data["tipoFigura"] == '1') ? 'Agente aduanal' : $this->data["tipoFigura"] ?></td>
                <td colspan="2"><?= $this->data["fechaExpedicion"] ?></td>
            </tr>
            <tr>
                <th colspan="3">Observaciones</th>
            </tr>
            <tr>
                <td colspan="3"><?= isset($this->data["observaciones"]) ? !empty($this->data["observaciones"]) ? (mb_check_encoding($this->data["observaciones"], 'UTF-8')) ? utf8_decode($this->data["observaciones"]) : $this->data["observaciones"] : '&nbsp;' : '&nbsp;' ?></td>
            </tr>
        </table>
        <h4>RFC con permisos de consulta</h4>
        <table class="table table-striped table-bordered table-hover small">
            <tr>
                <th>RFC de consulta</th>
            </tr>
            <?php if(is_array($this->data["rfcsConsulta"]["rfcConsulta"] )) { ?>
            <?php foreach($this->data["rfcsConsulta"]["rfcConsulta"] as $rfcConsulta) { ?>
            <tr>
                <td><?= $rfcConsulta ?></td>
            </tr>
            <?php } ?>
            <?php } else { ?>
            <tr>
                <td><?= (isset($this->data["rfcsConsulta"]["rfcConsulta"])) ? $this->data["rfcsConsulta"]["rfcConsulta"] : '&nbsp;' ?></td>
            </tr>
            <?php } ?>
        </table>
        <h4>Número de patente aduanal</h4>
        <table class="table table-striped table-bordered table-hover small">
            <tr>
                <th>Número autorización aduanal</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["patentesAduanales"]["patenteAduanal"])) ? $this->data["patentesAduanales"]["patenteAduanal"] : '&nbsp;' ?></td>
            </tr>
        </table>
        <h4>Datos de la factura</h4>
        <table class="table table-striped table-bordered table-hover small">
            <tr>
                <th>Subdivisión</th>
                <th>Certificado de origen</th>
                <th>No. de exportador autorizado</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["factura"]["subdivision"]) && $this->data["factura"]["subdivision"] != '0') ? 'Con Subdivisión' : 'Sin subdivisión' ?></td>
                <td><?= (isset($this->data["factura"]["certificadoOrigen"]) && $this->data["factura"]["certificadoOrigen"] != '0') ? "Si funge como certificado de origen" : 'NO funge como certificado de origen' ?></td>
                <td><?= (isset($this->data["factura"]["numeroExportadorAutorizado"]) && $this->data["factura"]["numeroExportadorAutorizado"] != '') ? $this->data["factura"]["numeroExportadorAutorizado"] : '' ?></td>
            </tr>
        </table>
        <h4>Datos generales del emisor</h4>
        <table class="table table-striped table-bordered table-hover small">
            <tr>
                <th>Tipo de identificador</th>
                <th colspan="3">Tax ID/Sin Tax ID/RFC/CURP</th>
            </tr>
            <tr>
                <td><?= isset($this->data["emisor"]["tipoIdentificador"]) ? $this->identificadorDesc($this->data["emisor"]["tipoIdentificador"]) : '&nbsp;' ?></td>
                <td colspan="3"><?= (isset($this->data["emisor"]["identificacion"]) && $this->data["emisor"]["identificacion"] != '0') ? $this->data["emisor"]["identificacion"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Nombre(s) o Razón Social</th>
                <th>Apellido paterno</th>
                <th colspan="2">Apellido materno</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["emisor"]["nombre"]) && $this->data["emisor"]["nombre"] != '') ? $this->data["emisor"]["nombre"] : '&nbsp;' ?></td>
                <td>&nbsp;</td>
                <td colspan="2">&nbsp;</td>
            </tr>
            <tr>
                <th>Calle</th>
                <th>No. exterior</th>
                <th>No. interior</th>
                <th>Código postal</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["emisor"]["domicilio"]["calle"]) && $this->data["emisor"]["domicilio"]["calle"] != '') ? $this->data["emisor"]["domicilio"]["calle"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["emisor"]["domicilio"]["numeroExterior"]) && $this->data["emisor"]["domicilio"]["numeroExterior"] != '') ? $this->data["emisor"]["domicilio"]["numeroExterior"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["emisor"]["domicilio"]["numeroInterior"]) && $this->data["emisor"]["domicilio"]["numeroInterior"] != '') ? $this->data["emisor"]["domicilio"]["numeroInterior"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["emisor"]["domicilio"]["codigoPostal"]) && $this->data["emisor"]["domicilio"]["codigoPostal"] != '') ? $this->data["emisor"]["domicilio"]["codigoPostal"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Colonia</th>
                <th colspan="3">Localidad</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["emisor"]["domicilio"]["colonia"]) && $this->data["emisor"]["domicilio"]["colonia"] != '') ? $this->data["emisor"]["domicilio"]["colonia"] : '&nbsp;' ?></td>
                <td colspan="3"><?= (isset($this->data["emisor"]["domicilio"]["localidad"]) && $this->data["emisor"]["domicilio"]["localidad"] != '') ? $this->data["emisor"]["domicilio"]["localidad"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Municipio</th>
                <th colspan="3">Entidad federativa</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["emisor"]["domicilio"]["municipio"]) && $this->data["emisor"]["domicilio"]["municipio"] != '') ? $this->data["emisor"]["domicilio"]["municipio"] : '&nbsp;' ?></td>
                <td colspan="3"><?= (isset($this->data["emisor"]["domicilio"]["entidadFederativa"]) && $this->data["emisor"]["domicilio"]["entidadFederativa"] != '') ? $this->data["emisor"]["domicilio"]["entidadFederativa"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th colspan="4">País</th>
            </tr>
            <tr>
                <td colspan="4"><?= (isset($this->data["emisor"]["domicilio"]["pais"]) && $this->data["emisor"]["domicilio"]["pais"] != '') ? $this->data["emisor"]["domicilio"]["pais"] : '&nbsp;' ?></td>
            </tr>
        </table>
        <h4>Datos generales del destinatario</h4>
        <table class="table table-striped table-bordered table-hover small">
            <tr>
                <th>Tipo de identificador</th>
                <th colspan="3">Tax ID/Sin Tax ID/RFC/CURP</th>                
            </tr>
            <tr>
                <td><?= (isset($this->data["destinatario"]["tipoIdentificador"])) ? $this->identificadorDesc($this->data["destinatario"]["tipoIdentificador"]) : '&nbsp;' ?></td>
                <td colspan="3"><?= (isset($this->data["destinatario"]["identificacion"]) && $this->data["destinatario"]["identificacion"] != '') ? $this->data["destinatario"]["identificacion"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Nombre(s) o Razón Social</th>
                <th>Apellido paterno</th>
                <th colspan="2">Apellido materno</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["destinatario"]["nombre"]) && $this->data["destinatario"]["nombre"] != '') ? $this->data["destinatario"]["nombre"] : '&nbsp;' ?></td>
                <td>&nbsp;</td>
                <td colspan="2">&nbsp;</td>
            </tr>
            <tr>
                <th>Calle</th>
                <th>No. exterior</th>
                <th>No. interior</th>
                <th>Código postal</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["destinatario"]["domicilio"]["calle"]) && $this->data["destinatario"]["domicilio"]["calle"] != '') ? $this->data["destinatario"]["domicilio"]["calle"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["destinatario"]["domicilio"]["numeroExterior"]) && $this->data["destinatario"]["domicilio"]["numeroExterior"] != '') ? $this->data["destinatario"]["domicilio"]["numeroExterior"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["destinatario"]["domicilio"]["numeroInterior"]) && $this->data["destinatario"]["domicilio"]["numeroInterior"] != '') ? $this->data["destinatario"]["domicilio"]["numeroInterior"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["destinatario"]["domicilio"]["codigoPostal"]) && $this->data["destinatario"]["domicilio"]["codigoPostal"] != '') ? $this->data["destinatario"]["domicilio"]["codigoPostal"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Colonia</th>
                <th colspan="3">Localidad</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["destinatario"]["domicilio"]["colonia"]) && $this->data["destinatario"]["domicilio"]["colonia"] != '') ? $this->data["destinatario"]["domicilio"]["colonia"] : '&nbsp;' ?></td>
                <td colspan="3"><?= (isset($this->data["destinatario"]["domicilio"]["localidad"]) && $this->data["destinatario"]["domicilio"]["localidad"] != '') ? $this->data["destinatario"]["domicilio"]["localidad"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th>Municipio</th>
                <th colspan="3">Entidad federativa</th>
            </tr>
            <tr>        
                <td><?= (isset($this->data["destinatario"]["domicilio"]["municipio"]) && $this->data["destinatario"]["domicilio"]["municipio"] != '') ? $this->data["destinatario"]["domicilio"]["municipio"] : '&nbsp;' ?></td>
                <td colspan="3"><?= (isset($this->data["destinatario"]["domicilio"]["entidadFederativa"]) && $this->data["destinatario"]["domicilio"]["entidadFederativa"] != '') ? $this->data["destinatario"]["domicilio"]["entidadFederativa"] : '&nbsp;' ?></td>
            </tr>
            <tr>
                <th colspan="4">País</th>
            </tr>
            <tr>
                <td colspan="4"><?= (isset($this->data["destinatario"]["domicilio"]["pais"]) && $this->data["destinatario"]["domicilio"]["pais"] != '') ? $this->data["destinatario"]["domicilio"]["pais"] : '&nbsp;' ?></td>
            </tr>
        </table>
        <h4>Datos de la mercancía</h4>
        <table class="table table-striped table-bordered table-hover small">
            <tr>
                <th colspan="2">Descripción genérica de la mercancía</th>
                <th>Tipo moneda</th>
                <th>Valor unitario</th>
                <th>Valor total</th>
                <th>Valor total en dólares</th>
                <th>Clave UMC</th>
                <th>Cantidad UMC</th>
            </tr>
            <?php if(isset($this->data["facturas"]["factura"]["mercancias"]["mercancia"]["descripcionGenerica"])) { ?>
            <tr>
                <td colspan="2"><?= (isset($this->data["facturas"]["factura"]["mercancias"]["mercancia"]["descripcionGenerica"]) && $this->data["facturas"]["factura"]["mercancias"]["mercancia"]["descripcionGenerica"] != '') ? $this->data["facturas"]["factura"]["mercancias"]["mercancia"]["descripcionGenerica"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["facturas"]["factura"]["mercancias"]["mercancia"]["tipoMoneda"]) && $this->data["facturas"]["factura"]["mercancias"]["mercancia"]["tipoMoneda"] != '') ? $this->data["facturas"]["factura"]["mercancias"]["mercancia"]["tipoMoneda"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["facturas"]["factura"]["mercancias"]["mercancia"]["valorUnitario"]) && $this->data["facturas"]["factura"]["mercancias"]["mercancia"]["valorUnitario"] != '') ? '$ ' . $this->number6($this->data["facturas"]["factura"]["mercancias"]["mercancia"]["valorUnitario"]) : '&nbsp;' ?></td>
                <td><?= (isset($this->data["facturas"]["factura"]["mercancias"]["mercancia"]["valorTotal"]) && $this->data["facturas"]["factura"]["mercancias"]["mercancia"]["valorTotal"] != '') ? '$ ' . $this->number6($this->data["facturas"]["factura"]["mercancias"]["mercancia"]["valorTotal"]) : '&nbsp;' ?></td>
                <td><?= (isset($this->data["facturas"]["factura"]["mercancias"]["mercancia"]["valorDolares"]) && $this->data["facturas"]["factura"]["mercancias"]["mercancia"]["valorDolares"] != '') ? '$ ' . $this->number4($this->data["facturas"]["factura"]["mercancias"]["mercancia"]["valorDolares"]) : '&nbsp;' ?></td>        
                <td><?= (isset($this->data["facturas"]["factura"]["mercancias"]["mercancia"]["claveUnidadMedida"]) && $this->data["facturas"]["factura"]["mercancias"]["mercancia"]["claveUnidadMedida"] != '') ? $this->data["facturas"]["factura"]["mercancias"]["mercancia"]["claveUnidadMedida"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["facturas"]["factura"]["mercancias"]["mercancia"]["cantidad"]) && $this->data["facturas"]["factura"]["mercancias"]["mercancia"]["cantidad"] != '') ? $this->number($this->data["facturas"]["factura"]["mercancias"]["mercancia"]["cantidad"]) : '&nbsp;' ?></td>
            </tr>
            <?php } elseif(isset($this->data["facturas"]["factura"]["mercancias"]["mercancia"][0]["descripcionGenerica"])) { ?>
            <?php foreach($this->data["facturas"]["factura"]["mercancias"]["mercancia"] as $merc) { ?>
            <tr>
                <td colspan="2"><?= (isset($merc["descripcionGenerica"]) && $merc["descripcionGenerica"] != '') ? $merc["descripcionGenerica"] : '&nbsp;' ?></td>
                <td><?= (isset($merc["tipoMoneda"]) && $merc["tipoMoneda"] != '') ? $merc["tipoMoneda"] : '&nbsp;' ?></td>
                <td><?= (isset($merc["valorUnitario"]) && $merc["valorUnitario"] != '') ? '$ ' . $this->number6($merc["valorUnitario"]) : '&nbsp;' ?></td>
                <td><?= (isset($merc["valorTotal"]) && $merc["valorTotal"] != '') ? '$ ' . $this->number6($merc["valorTotal"]) : '&nbsp;' ?></td>
                <td><?= (isset($merc["valorDolares"]) && $merc["valorDolares"] != '') ? '$ ' . $this->number4($merc["valorDolares"]) : '&nbsp;' ?></td>        
                <td><?= (isset($merc["claveUnidadMedida"]) && $merc["claveUnidadMedida"] != '') ? $merc["claveUnidadMedida"] : '&nbsp;' ?></td>
                <td><?= (isset($merc["cantidad"]) && $merc["cantidad"] != '') ? $this->number($merc["cantidad"]) : '&nbsp;' ?></td>
            </tr>
            <?php } ?>
            <?php } ?>    
        </table>
        <?php if(isset($this->data["facturas"]["factura"]["mercancias"]["mercancia"]["descripcionesEspecificas"])) { ?>
        <h4>Descripción de la mercancía</h4>
        <table class="table table-striped table-bordered table-hover small">
            <tr>
                <th>Marca</th>
                <th>Modelo</th>
                <th>Submodelo</th>
                <th>No. Serie</th>
            </tr>
            <tr>
                <td><?= (isset($this->data["facturas"]["factura"]["mercancias"]["mercancia"]["descripcionesEspecificas"]["marca"])) ? $this->data["mercancias"]["descripcionesEspecificas"]["marca"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["facturas"]["factura"]["mercancias"]["mercancia"]["descripcionesEspecificas"]["modelo"])) ? $this->data["mercancias"]["descripcionesEspecificas"]["modelo"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["facturas"]["factura"]["mercancias"]["mercancia"]["descripcionesEspecificas"]["subModelo"])) ? $this->data["mercancias"]["descripcionesEspecificas"]["subModelo"] : '&nbsp;' ?></td>
                <td><?= (isset($this->data["facturas"]["factura"]["mercancias"]["mercancia"]["descripcionesEspecificas"]["numeroSerie"])) ? $this->data["mercancias"]["descripcionesEspecificas"]["numeroSerie"] : '&nbsp;' ?></td>
            </tr>
        </table>
        <?php } ?>
        <p class="legend" style="font-size:11px">Esto es una representación gráfica del XML de un COVE su uso es exclusivo para interpretar la información de una forma más clara, su valides ante la autoridad es de 240 días a partir de la fecha de solicitud ya que es borrado de la base de datos de Ventanilla Única, pasado este tiempo su valides es meramente histórica. Este acuse no sustituye el de Ventanilla Única y es generado por el sistema VUCEM OAQ como alternativa.</p>
        <?php } ?>
    </body>
</html>