<form method="post" id="form">
    <table class="traffic-table traffic-table-left">
        <tr>
            <th colspan="4" class="invoice-title">CREAR NUEVO TRAFICO</th>
        </tr>
        <tr>
            <th style="text-align: right"><label for="idBodega">BODEGA:<span style="color: red">*</span></label></th>
            <td colspan="3">
                <?= $this->form->idBodega ?>
            </td>
        </tr>
        <tr>
            <th style="width: 150px; text-align: right"><label for="idCliente">CLIENTE:<span style="color: red">*</span></label></th>
            <td style="width: 360px">
                <?= $this->form->idCliente ?>
            </td>
            <td>
                <label style="display: table-cell; float: left; font-weight: bold">RFC SOCIEDAD: </label>                
            </td>
            <td>
                <input type="text" id="rfcSociedad" value="" disabled="disabled" style="width: 150px"/>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="idProveedor">PROVEEDOR:<span style="color: red">*</span></label></th>
            <td colspan="3">
                <div id="divproveedor"><?= $this->form->idProveedor ?></div>
                <i class="fas fa-pencil-alt edit-provider" style="font-size: 1.2em; color: #2f3b58; cursor: pointer"></i>
                <i class="far fa-file new-provider" style="font-size: 1.2em; color: #2f3b58; cursor: pointer"></i>
            </td>
        </tr>
        <!--<tr>
            <th style="text-align: right"><label for="proveedores">PROVEEDORES:</label></th>
            <td colspan="3">
                <?= $this->form->proveedores ?>
            </td>
        </tr>-->
        <tr>
            <th style="text-align: right"><label for="idPlanta">PLANTA:</label></th>
            <td colspan="3">
                <div id="divplanta"><?= $this->form->idPlanta ?></div>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="referencia">REFERENCIA:<span style="color: red">*</span></label></th>
            <td colspan="3">
                <?= $this->form->referencia ?>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="blGuia">BL / GUÍA:<span style="color: red">*</span></label></th>
            <td colspan="3">
                <?= $this->form->blGuia ?>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="contenedorCajaEntrada">CONTENEDOR / CAJA:<span style="color: red">*</span></label></th>
            <td colspan="3">
                <?= $this->form->contenedorCajaEntrada ?>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="idLineaTransporte">LÍNEA / TRANSPORTE:</label></th>
            <td colspan="3">
                <div id="divtransporte"><?= $this->form->idLineaTransporte ?></div>
                <i class="fas fa-pencil-alt edit-transport" style="font-size: 1.2em; color: #2f3b58; cursor: pointer"></i>
                <i class="far fa-file new-transport" style="font-size: 1.2em; color: #2f3b58; cursor: pointer"></i>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="bultos">BULTOS:<span style="color: red">*</span></label></th>
            <td colspan="3">
                <?= $this->form->bultos ?>
            </td>
        </tr>
        <tr>
            <th style="text-align: right"><label for="fechaEta">Fecha ETA:<span style="color: red">*</span></label></th>
            <td colspan="3"><?= $this->form->fechaEta ?></td>
        </tr>
    </table>
</form>
<div class="traffic-clear-5"></div>
<button id="submit" class="traffic-btn traffic-btn-right" tabindex="20">
    <i class="far fa-file-alt"></i> Crear entrada
</button>
<a href="javascript:void(0)" onclick="javascript:window.history.back();" class="traffic-btn" tabindex="99">
    <i class="fas fa-angle-double-left"></i>&nbsp;Regresar
</a>
<div class="traffic-clear"></div>
