<?php if (isset($this->form)) { ?>
    <form method="post" id="form">
        <input type="hidden" id="idTrafico" name="idTrafico" value="<?= $this->idTrafico ?>" />
        <table class="traffic-table traffic-table-left">
            <tr>
                <th colspan="4" class="invoice-title">MODIFICAR ENTRADA</th>
            </tr>            
            <tr>
                <th style="text-align: right"><label for="idBodega">BODEGA:<span style="color: red">*</span></label></th>
                <td colspan="3">
                    <?= $this->form->idBodega ?>
                </td>
            </tr>
            <tr>
                <th style="width: 150px; text-align: right"><label for="idCliente">CLIENTE:<span style="color: red">*</span></label></th>
                <td style="width: 360px" colspan="3">
                    <?= $this->form->idCliente ?>
                </td>
            </tr>
            <tr>
                <th style="text-align: right"><label for="referencia">REFERENCIA:<span style="color: red">*</span></label></th>
                <td colspan="3">
                    <?= $this->form->referencia ?>
                </td>
            </tr>
        </table>
    </form>
    <div class="traffic-clear-5"></div>
    <button id="submit" class="traffic-btn traffic-btn-right">
        <i class="far fa-save"></i> GUARDAR</button>
<?php } else { ?>
    <div class="traffic-clear-5"></div>
    <span class="traffic-eta-yellow">El pedimento ha sido pagado y no puede ser modificado.</span>
    <div class="traffic-clear-5"></div>
<?php } ?>
<a href="/bodega/index/editar-entrada?id=<?= $this->idTrafico ?>" class="traffic-btn">
    <i class="fas fa-angle-double-left"></i> Regresar</a>
<div class="traffic-clear"></div>
