<form method="get" action="<?= $this->url ?>">
    <table class="traffic-table traffic-table-left">
        <tr>
            <th>RFC</th>
            <th>Nombre</th>
            <th>&nbsp;</th>
        </tr>
        <tr>
            <td>
                <input type="text" value="<?= $this->rfc ?>" id="rfc" name="rfc" class="rfc">
            </td>
            <td>
                <input type="text" value="<?= $this->nombre ?>" id="nombre" name="nombre" style="width: 450px;" autocomplete="off">
            </td>
            <td>
                <a href="/comercializacion/index/clientes" class="traffic-btn traffic-btn-back traffic-btn-right">Limpiar</a>&nbsp;
                <a href="/comercializacion/index/nuevo-cliente" class="traffic-btn traffic-btn-add traffic-btn-right">Nuevo cliente</a>&nbsp;
                <button value="Buscar" type="submit" id="submit" name="submit" class="traffic-btn traffic-btn-primary traffic-btn-right">Buscar</button>
            </td>
            <?php if (isset($this->clientes) && !empty($this->clientes)) { ?>
            <tr>
                <td>&nbsp;</td>
                <td colspan="2">
                    Descargar este reporte en: <div class="traffic-icon traffic-icon-excel" style="display: inline-block; float: none"></div>&nbsp;<a href="/comercializacion/index/excel-clientes">Excel</a>
                </td>
            </tr>
            <?php } ?>
        </tr>
    </table>
</form>
<table class="traffic-table traffic-table-left hover">
    <thead>
        <tr>
            <th>RFC</th>
            <th>Nombre</th>
            <th>Acceso Web</th>
        </tr>
    </thead>
    <tbody>
        <?php if (isset($this->data) && !empty($this->data)) { ?>
            <?php foreach ($this->data as $item) { ?>
                <tr>
                    <td><a href="/comercializacion/index/datos-cliente?id=<?= $item['sica_id'] ?>&internal=<?= $item['id'] ?>&rfc=<?= $item['rfc'] ?>"><?= $item['rfc'] ?></a></td>
                    <td><?= strtoupper($item['nombre']) ?></td>
                    <td><?= ($item['access'] == 0) ? '<span style="color: red;">No</span>' : '<span style="color: blue;">Si</span>' ?></td>
                </tr>
            <?php } ?>
        <?php } else { ?>
            <tr>
                <td colspan="3">No hubo resultados.</td>
            </tr>
        <?php } ?>
    </tbody>
</table>
<div class="traffic-clear-5"></div>
<?= isset($this->data) ? $this->paginationControl($this->data, 'Sliding') : '' ?>
<div class="traffic-clear-10"></div>