<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
        <style>
            body {
                margin: 0;
                padding: 0;
                min-width: 750px;
                line-height: 12px;
            }
            .pagination {
                margin: 0;
                float: right;
                display: inline-block;
            }
        </style>
    <body>
    <?= isset($this->data) ? $this->paginationControl($this->data, 'Sliding', 'paginationiframe.phtml') : '' ?>
    <div style="clear:both;"></div>
    <table class="traffic-table">
        <tr>
            <th colspan="4" class="traffic-table-title">PARTES</th>
        </tr>
        <tr>
            <th class="title">Material</th>
            <th class="title">Descripción</th>
            <th class="title">Número de parte</th>
            <th>&nbsp;</th>
        </tr>        
        <?php foreach($this->data as $item) { ?>        
        <tr>
            <td><?= trim($item["material"]) ?></td>
            <td><?= trim($item["descripcion"]) ?></td>
            <td><?= trim($item["numParte"]) ?></td>
            <td>&nbsp;</td>
        </tr>
        <?php } ?>
    </table>
    </body>
</html>