<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
        <style>
            body {
                min-width: 1900px;
            }
        </style>
    <body>
    <table>
        <tr>
            <th class="title">Factura</th>
            <th class="title">COVE</th>
            <th class="title">fechaFactura</th>
            <th class="title">Incoterm</th>
            <th class="title">Valor F. (Usd)</th>
            <th class="title">Valor F. (MonExt)</th>
            <th class="title">taxId</th>
            <th class="title">nomProveedor</th>
            <th class="title">paisFactura</th>
            <th class="title">divisa</th>
            <th class="title">factorMonExt</th>
            <th class="title">Num. Parte</th>
            <th class="title">Desc.</th>
            <th class="title">Fraccion</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach($this->data as $item) { ?>
        <tr>
            <td><?= $item["numFactura"] ?></td>
            <td><?= $item["cove"] ?></td>
            <td><?= date('d/m/Y',strtotime($item["fechaFactura"])) ?></td>
            <td><?= $item["incoterm"] ?></td>
            <td><?= round($item["valorFacturaUsd"],4) ?></td>
            <td><?= round($item["valorFacturaMonExt"],4) ?></td>
            <td><?= $item["taxId"] ?></td>
            <td><?= $item["nomProveedor"] ?></td>
            <td><?= $item["paisFactura"] ?></td>
            <td><?= $item["divisa"] ?></td>
            <td><?= round($item["factorMonExt"],4) ?></td>
            <td><?= $item["numParte"] ?></td>
            <td><?= $item["descripcion"] ?></td>
            <td><?= $item["fraccion"] ?></td>
            <td>&nbsp;</td>
        </tr>
        <?php } ?>
    </table>
    </body>
</html>