<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <?= $this->headMeta(); ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
        <script type="text/javascript">
            $().ready(function () {
                
                $("#nombre, #rfc").on('input', function (evt) {        
                    var input = $(this);
                    var start = input[0].selectionStart;
                    $(this).val(function (_, val) {
                        return val.toUpperCase();
                    });
                    input[0].selectionStart = input[0].selectionEnd = start;
                });

                $("#nueva-facturacion").validate({
                    rules: {
                        nombre: "required",
                        rfc: "required"
                    },
                    messages: {
                        nombre: "Se requiere razón social.",
                        rfc: "Se requiere RFC."
                    }
                });

                $("#add-scheme").click(function (e) {
                    e.preventDefault();
                    if ($("#nueva-facturacion").valid()) {
                        $("#nueva-facturacion").ajaxSubmit({
                            dataType: "json",
                            success: function (res) {
                                if (res.success === true) {
                                    window.location.replace("/trafico/data/customer-information?idAduana=" + $("#idAduana").val() + "&idCliente=" + $("#idCliente").val());
                                }
                            }
                        });
                    }
                });
            });
        </script>
    </head>
    <body>
        <?php if (isset($this->aduana)) { ?>
        <h4><?= $this->aduana["patente"] . ', ' . $this->aduana["aduana"] . ' [' . $this->aduana["nombre"] . ']' ?></h4>
        <table>
            <tr>
                <td style="width: 50%">
                    <h4>TIPO DE FACTURACIÓN</h4>
                    <form action="<?= $this->factForm->getAction() ?>" method="<?= $this->factForm->getMethod() ?>" id="<?= $this->factForm->getAttrib("id") ?>">
                        <?= $this->inputHidden('hidden', 'idAduana', $this->idAduana) ?>
                        <?= $this->inputHidden('hidden', 'idCliente', $this->idCliente) ?>
                        <table>
                            <tr>
                                <th>Nombre</th>
                                <th>RFC</th>
                                <th>&nbsp;</th>
                            </tr>
                            <tr>
                                <th><?= $this->factForm->nombre ?></th>
                                <th><?= $this->factForm->rfc ?></th>
                                <th><button class="btn btn-success btn-small" id="add-scheme">Agregar</button></th>
                            </tr>
                        </table>
                    </form>                    
                    <?php if (isset($this->facturacion) && !empty($this->facturacion)) { ?>
                        <table>
                            <tr>
                                <th>Razon Social</th>
                                <th>RFC</th>
                                <th>&nbsp;</th>
                            </tr>
                            <?php foreach ($this->facturacion as $k => $item) { ?>
                                <tr>
                                    <td><?= $item["nombre"] ?></td>
                                    <td><?= $item["rfc"] ?></td>
                                    <td>
                                        <div class="traffic-icon traffic-icon-delete"></div>
                                    </td>
                                </tr>
                            <?php } ?>
                        </table>
                    <?php } else { ?>
                        La facturación será a nombre del cliente.
                    <?php } ?>
                </td>
                <td style="width: 50%"></td>
            </tr>
        </table>
        <?php } ?>        
    </body>
</html>
