<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <?= $this->headMeta(); ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>  
    </head>
    <script>
        function close_window() {
            close();
        }
    </script>
    <body>

        <div class="traffic-clear-5"></div>
        <a class="traffic-btn-close" onclick="close_window();">Cerrar</a>
        <div class="traffic-clear-5"></div>
        <table class="traffic-table">
            <thead>                
                <tr>
                    <th colspan="16" class="traffic-table-title">REPORTE: <?= $this->layoutTitle ?> AL DÍA <?= $this->myHelpers->dateSpanish(date('Y-m-d')) ?></th>
                </tr>
                <tr>
                    <th>Fecha ETA</th>
                    <th>Fecha Elab.</th>
                    <th>Referencia</th>
                    <th>Adu</th>
                    <th>Patente</th>
                    <th>Ped</th>
                    <th>Tipo Op.</th>
                    <th>Cliente</th>
                    <th>BL</th>
                    <th>Factura</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                <?php if(isset($this->data) && !empty($this->data)) { ?>
                    <?php foreach ($this->data as $item) { ?>
                        <tr>
                            <td><?= $this->eta($item['fechaEta'], $item["deposito"]) ?></td>
                            <td><?= $this->myHelpers->dateSpanish($item['enviada']) ?></td>
                            <td><?= $item['referencia'] ?></td>
                            <td><?= $item["aduana"] ?></td>
                            <td><?= $item["patente"] ?></td>
                            <td><?= $item["pedimento"] ?></td>
                            <td><?= $item['tipoOperacion'] ?></td>
                            <td><?= $item['nombreCliente'] ?></td>
                            <td><?= $item['bl'] ?></td>
                            <td><?= $item['numFactura'] ?></td>
                            <td><?= $this->currency(($item["subtotal"] - $item["anticipo"]), 90) ?></td>                        
                        </tr>
                    <?php } ?>
                <?php } else { ?>
                        <tr>
                            <td colspan="11"><em>No existen resultados.</em></td>
                        </tr>
                <?php } ?>
            </tbody>
        </table>
    </body>
</html>