<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <style>
            body {
                margin: 0;
                padding: 0;
            }
            table {
                font-size: 12px;
                font-family: sans-serif;
                margin: 0;
                padding: 0;        
                width: 100%;
                border-collapse: collapse;
            }
            table th, table td {
                border: 1px #fff solid;
                background-color: #eee;
            }
            table td {
                background-color: #fafafa;
            }
            table th {
                text-align: left;
                color: #333;
            }
            p {
                margin: 0;
                padding: 0;
                font-family: sans-serif;
                font-size: 11px;
            }
            td.total {
                border-top: 3px #999 double;
                border-bottom: 1px #999 solid;
            }
        </style>
    </head>
    <body></body>
</html>
