<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <?= $this->headMeta(); ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>  
        <style type="text/css">
            table {
                font-size: 12px;
            }
        </style>
    </head>
    <body>
        <table class="traffic-table-iframe">
            <tr>
                <th style="width: 32px">&nbsp;</th>
                <th style="text-align: left">Cliente</th>
                <th>Pedimento</th>
                <th>Referencia</th>
                <th>Complemento</th>
                <th class="th-datetime">Creado</th>
                <th class="th-icons">&nbsp;</th>
            </tr>     
            <?php if (isset($this->data)) { ?>
                <?php foreach ($this->data as $item) { ?>
                    <tr>
                        <td>
                            <?php if ($item["detalle"] != null && $item["conceptos"] != null) { ?>
                                <div class="traffic-icon traffic-icon-send" onclick="parent.sendRequest(<?= $item["id"] ?>,<?= $item["idAduana"] ?>);"></div>
                            <?php } ?>
                        </td>
                        <td style="text-align: left"><?= $item["nombreCliente"] ?></td>
                        <td><?= $item["aduana"] . "-" . $item["patente"] . "-" . $item["pedimento"] ?></td>
                        <td><?= $item["referencia"] ?></td>
                        <td><?= isset($item["complemento"]) ? "S" : "N" ?></td>
                        <td><?= date("d/m/Y H:i a", strtotime($item["creado"])) ?></td>
                        <td>
                            <i class="fas fa-pencil-alt" onclick="parent.editRequest(<?= $item["id"] ?>,<?= $item["idAduana"] ?>);" style="font-size: 1.4em; color: #2f3b58; cursor: pointer"></i>&nbsp;
                            <i class="far fa-trash-alt" onclick="parent.deletePreRequest(<?= $item["id"] ?>);" style="font-size: 1.4em; color: #2f3b58; cursor: pointer"></i>
                        </td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <tr>
                    <td colspan="7"><em>Usted no tiene solicitudes recientes.</em></td>
                </tr>
            <?php } ?>
        </table>
    </body>
</html>
