<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <?= $this->headMeta(); ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>  
    </head>
    <body>
        <table class="traffic-table-iframe">            
            <tr>
                <th>&nbsp;</th>
                <th>Concepto</th>
                <th>Importe</th>
                <th class="th-icons">&nbsp;</th>
            </tr>     
            <?php if (isset($this->data)) { ?>
                <?php
                $total = 0;
                foreach ($this->data as $item) {
                    ?>
                    <tr>
                        <td>&nbsp;</td>
                        <td><?= $item["concepto"] ?></td>
                        <td class="currency"><span style="float: left;">$</span><?= number_format($item["importe"], 4, '.', ',') ?></td>
                        <td>
                            <div class="traffic-icon traffic-icon-edit" onclick="parent.editRequest(<?= $item["id"] ?>);"></div>
                            <div class="traffic-icon traffic-icon-delete"></div>
                        </td>
                    </tr>
                    <?php $total += $item["importe"]; } ?>
                <tr>
                    <td colspan="2" style="text-align: right;"><strong>TOTAL: </strong>&nbsp;</td>
                    <td class="currency total"><span style="float: left;">$</span><?= number_format($total, 4, '.', ',') ?></td>
                    <td>&nbsp;</td>
                </tr>
            <?php } else { ?>
                <tr>
                    <td colspan="">Usted no tiene conceptos.</td>
                </tr>
            <?php } ?>
        </table>
    </body>
</html>
