<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="OAQ Web Portal">
        <meta name="author" content="Jaime E. Valdez">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <title>OAQ | Nueva Tarifa</title>
        <link rel="icon" type="image/png" href="/favicon.png" />
        <meta name="description" content="" >        <link href="/favicon.png" rel="icon shortcut" >
        <link href="/less/traffic-module.css?1486060080" media="screen" rel="stylesheet" type="text/css" >
        <script type="text/javascript" src="/js/common/jquery-1.9.1.min.js"></script>
        <script type="text/javascript" src="/js/common/jquery.form.min.js"></script>
        <script type="text/javascript" src="/js/common/jquery.validate.min.js"></script>
        <script type="text/javascript" src="/js/common/principal.js"></script>
    </head>
    <body>
        <?php if (isset($this->idCliente)) { ?>
            <input type="hidden" value="<?= $this->idCliente ?>" name="idCliente" />
        <?php } ?>          
        <form id="formCustom" enctype="application/x-www-form-urlencoded">
            <table class="traffic-table traffic-table-left">
                <tr>
                    <th colspan="4" class="traffic-table-subtitle" style="height: 35px; vertical-align: middle">LADO MEXICANO MXP</th>
                </tr>
                <tr>
                    <th style="width: 200px">Agregar tipo de aduana</th>
                    <td style="width: 130px">
                        <?= $this->selectTipoAduana("tipoAduana") ?>
                    </td>
                    <td>
                        <div id="htmlAduana">
                            <select id="aduana" class="traffic-select-large" disabled="true">
                                <option value="">---</option>                                
                            </select>
                        </div>
                    </td>
                    <td>
                        <input type="submit" value="Agregar Aduana" id="addCustom" class="traffic-btn-add traffic-btn-right"/>
                    </td>
                </tr>
            </table>
        </form>
        <div id="concepts">
            <div class="concepts">
                <div style="width: 10%; text-align: center; font-weight: bold">Aduana</div>
                <div style="width: 30%; text-align: center; font-weight: bold">Tarifa Flat (Mercancia En General)</div>
                <div style="width: 15%; text-align: center; font-weight: bold">Importación</div>                    
                <div style="width: 15%; text-align: center; font-weight: bold">Exportación</div>                    
                <div style="width: 20%; text-align: center; font-weight: bold">Modo de calculo</div>                    
            </div>
            <div id="concept_2" class="concepts"><div style="width: 10%; text-align: center">Aérea</div><div style="width: 30%; text-align: center">Ciudad de México (AICM)</div><div style="width: 15%; text-align: center"><input type="text" class="traffic-input-small"></div><div style="width: 15%; text-align: center"><input type="text" class="traffic-input-small"></div><div style="width: 20%; text-align: center"><input type="text" class="traffic-input-small"></div></div>
            <div id="concept_3" class="concepts"><div style="width: 10%; text-align: center">Aérea</div><div style="width: 30%; text-align: center">Ciudad de México (AICM)</div><div style="width: 15%; text-align: center"><input type="text" class="traffic-input-small"></div><div style="width: 15%; text-align: center"><input type="text" class="traffic-input-small"></div><div style="width: 20%; text-align: center"><input type="text" class="traffic-input-small"></div></div>
            <div id="concept_4" class="concepts"><div style="width: 10%; text-align: center">Aérea</div><div style="width: 30%; text-align: center">Ciudad de México (AICM)</div><div style="width: 15%; text-align: center"><input type="text" class="traffic-input-small"></div><div style="width: 15%; text-align: center"><input type="text" class="traffic-input-small"></div><div style="width: 20%; text-align: center"><input type="text" class="traffic-input-small"></div></div>
            <div id="concept_5" class="concepts"><div style="width: 10%; text-align: center">Aérea</div><div style="width: 30%; text-align: center">Ciudad de México (AICM)</div><div style="width: 15%; text-align: center"><input type="text" class="traffic-input-small"></div><div style="width: 15%; text-align: center"><input type="text" class="traffic-input-small"></div><div style="width: 20%; text-align: center"><input type="text" class="traffic-input-small"></div></div>
            <div id="concept_6" class="concepts"><div style="width: 10%; text-align: center">Aérea</div><div style="width: 30%; text-align: center">Ciudad de México (AICM)</div><div style="width: 15%; text-align: center"><input type="text" class="traffic-input-small"></div><div style="width: 15%; text-align: center"><input type="text" class="traffic-input-small"></div><div style="width: 20%; text-align: center"><input type="text" class="traffic-input-small"></div></div>
        </div>
        <div class="traffic-clear-10"></div>
        <a id="saveTariff" class="traffic-btn-success traffic-btn-right">Guardar</a>
        <a id="closeTariff" class="traffic-btn-close">Cerrar</a>
        <style>
            p.error {
                color: red;
                background: none;
                background-color: none;
                font-size: 11px !important;
                font-style: italic; 
                border: none;
                margin: 0;
                padding: 0;
                padding-top: 2px;
            }
            .concepts {
                width: 100%;
                display: inline-table;
                height: 20px;
                padding: 0;
                margin: 0;
                clear: both;
                border-bottom: 1px #999 solid;
            }
            .concepts div {
                float: left;
                font-size: 12px;
                display: table-cell;
                height: 32px;
            }
            .concepts input[type=text] {
                height: 22px;
            }
        </style>
        <script type="text/javascript">

            $("#formCustom").validate({
                errorElement: "p",
                rules: {
                    tipoAduana: {required: true},
                    aduana: {required: true}
                },
                messages: {
                    tipoAduana: {required: "Necesario"},
                    aduana: {required: "Necesario"}
                }
            });

            $(document.body).on("click", "#addCustom", function (ev) {
                ev.preventDefault();
                var html = '<div id="concept_' + $("#tipoAduana").val() + '\" class=\"concepts\">';
                html += '<div style="width: 10%; text-align: center">' + $("#tipoAduana option[value='" + $("#tipoAduana").val() + "']").text() + '</div>';
                html += '<div style="width: 30%; text-align: center">' + $("#aduana option[value='" + $("#aduana").val() + "']").text() + '</div>';
                html += '<div style="width: 15%; text-align: center"><input type="text" class="traffic-input-small"></div>';
                html += '<div style="width: 15%; text-align: center"><input type="text" class="traffic-input-small"></div>';
                html += '<div style="width: 20%; text-align: center"><input type="text" class="traffic-input-small"></div>';
                html += '</div>';
                $("#concepts").append(html);
            });

            $(document.body).on("change", "#tipoAduana", function (ev) {
                ev.preventDefault();
                $.post("/trafico/post/tarifa-obtener-aduanas", {value: $(this).val()}, function (res) {
                    if (res.success === true) {
                        $("#htmlAduana").html(res.html);
                    }
                });
            });

            $(document.body).on("click", "#closeTariff", function (ev) {
                ev.preventDefault();
                $("#tariffModal").html('Please wait... <img src="/images/loader.gif" alt="loading" />');
                $("#tariffModal").jqmHide();
            });

            $(document).one("click", "#saveTariff", function (ev) {
                ev.preventDefault();
                $(this).addClass("traffic-btn-disabled")
                        .removeClass("traffic-btn-success");
                $("#formChecklist").ajaxSubmit({
                    url: "/trafico/post/guardar-checklist-cliente",
                    type: "post",
                    dataType: "json",
                    success: function (res) {
                        if (res.success === true) {
                            $('#tariffModal').jqmHide();
                        }
                    }
                });
            });

        </script>
    </body>
</html>