<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <?= $this->headMeta(); ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
    </head>
    <body>
        <?php if (isset($this->data)) { ?>
            <table class="traffic-table">            
                <tr>
                    <th>&nbsp;</th>
                    <th>Transportista</th>
                    <th>Tipo</th>
                    <th>Guia</th>
                    <th>&nbsp;</th>
                </tr>     
                <?php 
                foreach($this->data as $item) { ?>
                <tr>
                    <td>&nbsp;</td>
                    <td><?= ($item["idTransportista"] != null) ? $item["nombre"] : 'N/D' ?></td>
                    <td><?= $item["guia"] ?></td>
                    <td><?= $item["tipo"] ?></td>
                    <td>
                        <div class="traffic-icon traffic-icon-edit" onclick="parent.editarGuia('<?= $item["id"] ?>');"></div>
                        <div class="traffic-icon traffic-icon-delete" onclick="parent.borrarGuia('<?= $item["id"] ?>');"></div>
                    </td>
                </tr>
                <?php } ?>
            </table>
        <?php } else { ?>
        <p><em>No tiene guías.</em></p>
        <?php } ?>
    </body>
</html>
