<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <?= $this->headMeta(); ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>  
    </head>
    <body>
        <?php if (isset($this->data)) { ?>
            <table class="traffic-table">            
                <tr>
                    <th>&nbsp;</th>
                    <th>COVE</th>
                    <th>Num. Factura</th>
                    <th>Proveedor</th>
                    <th>Valor Mon. Ext.</th>
                    <th>Moneda</th>
                    <th>&nbsp;</th>
                </tr>     
                <?php foreach ($this->data as $item) { ?>
                    <tr>
                        <td>&nbsp;</td>
                        <td><?= ($item["cove"] !== null) ? "<a class=\"traffic-link\" href=\"/automatizacion/vucem/imprimir-detalle-cove?cove={$item["cove"]}&download=true\" target=\"_blank\">{$item["cove"]}</a>" : '' ?></td>
                        <td><?= $item["numFactura"] ?></td>
                        <td><?= $item["proveedor"] ?></td>
                        <td style="text-align: right;"><span style="float:left;">$</span><?= number_format($item["valorMonExt"], 2, '.', ',') ?></td>
                        <td><?= $item["moneda"] ?></td>
                        <td>
                            <?php if (isset($item["cove"]) && $item["cove"] !== null) { ?>
                                <div class="traffic-icon traffic-icon-delete" onclick="parent.borrarFactura(<?= $item["id"] ?>);"></div>                        
                            <?php } ?>
                                <div class="traffic-icon traffic-icon-import" onclick="parent.importarFactura('<?= $item["id"] ?>');"></div>
                            <?php if (isset($item["idFactura"]) && $item["idFactura"] !== null) { ?>
                                <div class="traffic-icon traffic-icon-view" onclick="parent.verFactura('<?= $item["id"] ?>');"></div>
                            <?php } ?>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        <?php } else { ?>
            <p><em>No tiene facturas.</em></p>
        <?php } ?>
    </body>
</html>
