<input type="button" id="nuevoTrafico" value="Nuevo Tráfico" />
<input type="button" id="nuevoTrafico" value="Nuevo Tráfico" class="disabled" />
<input type="button" id="nuevoTrafico" value="Nuevo Tráfico" disabled="disabled" />

<div class="clear"></div>

<input type="text" value="" placeholder="Valor" />
<input type="text" value="Value" placeholder="Valor" />
<input type="text" value="Value" placeholder="Valor" class="disabled" />
<input type="text" value="Value" placeholder="Valor" disabled="disabled" />

<div class="clear"></div>

<select name="empresa" id="empresa">
    <option value="1">OAQ</option>
    <option value="2">AIQ</option>
    <option value="3">Laredo, Tx.</option>
    <option value="4">Nuevo Laredo, Tamps.</option>
</select>
<select name="empresa" id="empresa" class="disabled" disabled="disabled">
    <option value="1">OAQ</option>
    <option value="2">AIQ</option>
    <option value="3">Laredo, Tx.</option>
    <option value="4">Nuevo Laredo, Tamps.</option>
</select>

<div class="clear"></div>

<button>Tráfico</button>
<button class="disabled">Tráfico</button>
<button disabled="disabled">Tráfico</button>

<div class="clear"></div>

<textarea>Nueva</textarea>
<textarea class="disabled">Nueva</textarea>
<textarea disabled="disabled">Nueva</textarea>

<div class="clear"></div>

 <form>
  <input type="radio" name="gender" value="male" checked> Male<br>
  <input type="radio" name="gender" value="female"> Female<br>
  <input type="radio" name="gender" value="other"> Other
</form> 

<div class="clear"></div>

<input type="checkbox" name="cc"><label for="cc">Before</label>
<input type="checkbox" name="cc"><label for="cc">After</label>

<div class="clear"></div>

<div>
    <input type="text" id="more" class="tiny"/>
    <button id="addMore" class="button-green button-plus">+</button>
    <button id="addMore" class="button-red button-minus">-</button>
    <button id="addMore" class="button-green button-plus small">&plus;</button>
    <button id="addMore" class="button-green button-plus small">&hybull;</button>
    <button id="addMore" class="button-green button-plus small">&laquo;</button>
    <button id="addMore" class="button-green button-plus small">&raquo;</button>
    <button id="addMore" class="button-green button-plus small">&lsaquo;</button>
    <button id="addMore" class="button-green button-plus small">&rsaquo;</button>
    <button id="addMore" class="button-green button-plus small">&leftarrow;</button>
    <button id="addMore" class="button-green button-plus small">&rightarrow;</button>
    <button id="addMore" class="button-green button-plus small">&vltri;</button>
    <button id="addMore" class="button-green button-plus small">&vrtri;</button>
    <button id="addMore" class="button-green button-plus small">&check;</button>
    <button id="addMore" class="button-green button-plus small">&cross;</button>
    <button id="addMore" class="button-green button-plus small">&lt;</button>
    <button id="addMore" class="button-green button-plus small">&gt;</button>
</div>