<form enctype="multipart/form-data" method="POST" id="uploadInvoicePdf">
    <input type="hidden" id="idTrafico" name="idTrafico" value="<?= $this->idTrafico ?>" />
    <input type="hidden" id="idFactura" name="idFactura" value="<?= $this->idFactura ?>" />
    <input type="hidden" name="MAX_FILE_SIZE" value="3145728" />
    <input type="file" id="files" name="files[]" style="display:none" >
    <label>Num. Factura:</label>
    <input type="text" id="numeroFactura" name="numeroFactura" value="<?= $this->numeroFactura ?>" readonly="true" class="traffic-input-medium" />
    <label>Proveedor:</label>
    <input type="text" id="nombreProveedor" name="nombreProveedor" value="<?= $this->nombreProveedor ?>" readonly="true"  class="traffic-input-medium" />
    <div class="traffic-clear-5"></div>
    <label>Archivo a subir:</label>
    <div id="selected"></div>
    <div class="input-append">
        <div class="traffic-clear-5"></div>
        <a class="traffic-btn-add" onclick="$('input[id=files]').click();">Seleccionar archivo...</a>
    </div>
</form>
<script type="text/javascript">    
    
    $("#selected").html('');
    
    $(document.body).on('change', '#files', function () {
        var files = $(this).prop("files");
        var names = $.map(files, function(val) {
            var nomProveedor = $("#uploadInvoicePdf #nombreProveedor").val();
            $("#selected").append('<p style="font-size: 12px; margin: 2px 0 2px 0">' + 
                    'FO_' + $("#uploadInvoicePdf #numeroFactura").val() + '_' + nomProveedor.replace(' ', '_') + '.pdf' + '</p>');
            return val.name; 
        });
    });
    
    $('#uploadInvoicePdf').validate({
        errorPlacement: function (error, element) {
            $(element)
                    .closest('form')
                    .find('#' + element.attr('id'))
                    .after(error);
        },
        ignore:'',
        errorElement: 'span',
        errorClass: 'traffic-error',
        rules: {
            'files[]': {required: true}
        },
        messages: {
            'files[]': {required: "Se requiere seleccionar archivo PDF."}
        }
    });
    
</script>