<form id="formUploadKey" method="post">
    <input type="hidden" id="idAgente" name="idAgente" value="<?= $this->idAgente ?>" />
    <table class="traffic-table traffic-table-left hover">
        <tbody>
            <tr>
                <th>Patente:</th>
                <td>
                    <input type="text" name="patente" id="patente" class="traffic-input-small" readonly="true" value="<?= $this->patente ?>">
                </td>
            </tr>
            <tr>
                <th>Tipo de figura:</th>
                <td>
                    <select name="figura" id="figura" class="traffic-select-medium" disabled="true">
                        <option value="">-- Seleccionar --</option>
                        <option value="1" selected="true">Agente Aduanal</option>
                    </select>
                </td>
            </tr>
            <tr>
                <th>Password Ventanilla:</th>
                <td>
                    <input type="text" name="pwdvu" id="pwd-vu" class="traffic-input-medium">
                </td>
            </tr>
            <tr>
                <th>Password Servicios Web:</th>
                <td>
                    <input type="text" name="pwdws" id="pwd-ws" class="traffic-input-large" style="width: 520px !important">
                </td>
            </tr>
            <tr>
                <th>Tipo de sello:</th>
                <td>
                    <input type="radio" name="tipo" value="0"> Anterior<br>
                    <input type="radio" name="tipo" value="1" checked="true"> Nuevo
                </td>
            </tr>
            <tr>
                <th>Archivo .KEY</th>
                <td><input type="file" id="file-select" name="keyfile"/></td>
            </tr>
            <tr>
                <th>Archivo .CER</th>
                <td><input type="file" id="cer-select" name="cerfile"/></td>
            </tr>
        </tbody>
    </table>
</form>

<script type="text/javascript">
    var validator = $("#formUploadKey").validate({
        errorPlacement: function (error, element) {
            $(element)
                    .closest("form")
                    .find("#" + element.attr("id"))
                    .after(error);
        },
        errorElement: "span",
        errorClass: "traffic-error",
        rules: {
            figura: { required: true },
            pwdvu: { required: true },
            pwdws: { required: true },
            keyfile: { required: true },
            cerfile: { required: true }
        },
        messages: {
            figura: { required: " [Seleccionar tipo de figura]" },
            pwdvu: { required: " [Proporcionar contraseña de VUCEM]" },
            pwdws: { required: " [Proporcionar contraseña de Servicios Web]" },
            keyfile: { required: " [Seleccionar archivo .Key]" },
            cerfile: { required: " [Seleccionar archivo .Cer]" }
            
        }
    });
    
</script>