<table class="traffic-table traffic-table-left hover">
    <thead>
        <tr>
            <th style="width: 20px">
                <input type="checkbox" class="selectAll" />
            </th>
            <th style="width: 20px">&nbsp;</th>
            <th style="width: 60px">Patente</th>
            <th style="width: 60px">Aduana</th>
            <th style="width: 80px">Pedimento</th>
            <th style="width: 90px">Referencia</th>
            <th style="width: 70px">Clave</th>
            <th style="width: 90px">Fecha ETA</th>
            <th>Cliente</th>
            <th>&nbsp;</th>
        </tr>        
    </thead>
    <tbody>
        <?php if (isset($this->data)) { ?>
            <?php foreach ($this->data as $item) { ?>
                <tr class="trafficRow_<?= $item["id"] ?>">
                    <td>
                        <input type="checkbox" class="sTraffic" data-id="<?= $item["id"] ?>" />
                    </td>
                    <td><?= ($item["tipoOperacion"] == 'TOCE.IMP') ? '<i class="fas fa-arrow-circle-down" style="font-size:1.2em; color: #2f3b58"></i>' : 
                    '<i class="fas fa-arrow-circle-up" style="font-size:1.2em; color: #2e963a"></i>' ?></td>
                    <td style="text-align: center"><?= $item["patente"] ?></td>
                    <td style="text-align: center"><?= $item["aduana"] ?></td>
                    <td style="text-align: center"><?= $item["pedimento"] ?></td>
                    <td style="text-align: center"><?= $item["referencia"] ?></td>
                    <td style="text-align: center"><?= $item["cvePedimento"] ?></td>
                    <td style="text-align: center"><?= date("Y-m-d", strtotime($item["fechaEta"])) ?></td>
                    <td><?= $item["nombre"] ?></td>
                    <td style="width: 50px">
                        <div style="font-size:1.2em; color: #2f3b58; float: right; margin-right: 5px">
                            <i data-id="<?= $item["id"] ?>" class="fas fa-pencil-alt editTraffic" style="cursor: pointer; margin-right: 5px"></i>
                            <i data-id="<?= $item["id"] ?>" class="fas fa-trash-alt deleteTraffic" style="cursor: pointer"></i>
                        </div>
                    </td>
                </tr>
            <?php } ?>
        <?php } else { ?>
            <tr>
                <td style="text-align: center" colspan="10">
                    <em>No hay tráficos.</em>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>