<!DOCTYPE html>
<html>
    <head>
        <title><?= $this->cove ?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <?= $this->headMeta(); ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>  
    </head>
    <script>
        function close_window() {
            close();
        }
    </script>
    <body>
        <div class="traffic-edocument">
            <?= $this->content ?>
            <div class="traffic-clear-5"></div>
            <a class="traffic-btn-close" onclick="close_window();">Cerrar</a>
            <a class="traffic-btn-success traffic-btn-right" target="_blank" href="/trafico/get/imprimir-cove?idFactura=<?= $this->idFactura ?>&cove=<?= $this->cove ?>">ACUSE</a>            
            <a class="traffic-btn-success traffic-btn-right" target="_blank" href="/trafico/get/imprimir-cove-detalle?idFactura=<?= $this->idFactura ?>&cove=<?= $this->cove ?>">DETALLE</a>            
            <div class="traffic-clear-5"></div>
        </div>
    </body>
</html>
