<form action="<?= $this->url() ?>" method="post" enctype="application/x-www-form-urlencoded" id="form">
    <table class="traffic-table traffic-table-left">
        <thead>
            <tr>
                <th colspan="2" class="traffic-table-title">ARCHIVOS XML (CUENTAS DE GASTO)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th style="width: 150px"><label for="rfc">RFC:</label></th>
                <td><?= $this->form->rfc ?></td>
            </tr>
            <tr>
                <th><label for="fechaIni">Fecha Inicio:</label></th>
                <td><div style="font-size:1.4em; color: #2f3b58; float: left; margin-right: 5px">
                        <i class="far fa-calendar-alt"></i>
                    </div> <?= $this->form->fechaIni ?></td>
            </tr>
            <tr>
                <th><label for="fechaFin">Fecha Fin:</label></th>
                <td><div style="font-size:1.4em; color: #2f3b58; float: left; margin-right: 5px">
                        <i class="far fa-calendar-alt"></i>
                    </div> <?= $this->form->fechaFin ?></td>
            </tr>
            <tr>
                <td>
                    <a onclick="window.history.back();" class="traffic-btn">
                        <i class="fas fa-angle-double-left"></i>&nbsp;Regresar
                    </a>
                </td>
                <td>
                    <button id="submit" class="traffic-btn traffic-btn-right">Consultar</button>
                </td>
            </tr>
        </tbody>
    </table>
</form>
    <div class="traffic-clear-5"></div>    
    <table class="traffic-table traffic-table-left">
        <thead>
            <tr>
                <th><input type="checkbox" id="selectall"></th>
                <th>Referencia</th>
                <th>Patente</th>
                <th>Aduana</th>
                <th>Folio</th>
                <th>Fecha</th>
                <th>Emisor</th>
                <th>Cliente</th>
                <th>Archivo</th>
            </tr>
        </thead>
        <tbody>
            <?php if (isset($this->paginator)) { ?>
                <?php foreach ($this->paginator as $item) { ?>
                    <tr>
                        <td><input type="checkbox" name="cuentas" class="cuentas" value="<?= $item['id'] ?>"></td>
                        <td><?= $item['referencia'] ?></td>
                        <td><?= $item['patente'] ?></td>
                        <td><?= $item['aduana'] ?></td>
                        <td><?= $item['folio'] ?></td>
                        <td><?= $item['fecha'] ?></td>
                        <td><?= $item['emisor_nombre'] ?></td>
                        <td><?= $item['receptor_nombre'] ?></td>
                        <td><a href="/archivo/index/descargar-archivo?id=<?= $this->encrypt($item['id']) ?>"><?= $item['nom_archivo'] ?></a></td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                    <tr>
                        <td colspan="9" style="text-align: center">
                            <em>No hubo resultados para búsqueda seleccionada.</em>
                        </td>
                    </tr>
            <?php } ?>
        </tbody>
    </table>
<?= isset($this->paginator) ? $this->paginationControl($this->paginator) : "" ?>
<div class="traffic-clear-20"></div>
