<div id="mm" class="easyui-menu" style="width:120px;">
    <div onclick="javascript:uploadDialog()">Subir fotos</div>
    <div onclick="javascript:photosDialog()">Ver fotos</div>
    <div class="menu-sep"></div>
    <div>Salir</div>
</div>
<input id="idCliente" type="hidden" value="<?= $this->idCliente ?>">
<div class="traffic-cols">
    <table id="providers"></table>
</div>
<div class="traffic-clear-10"></div>
<div id="dlg" style="display: none">
    <div class="easyui-panel" style="width:100%;padding:10px 20px;">        
        <form id="fmimage" method="post" enctype="multipart/form-data">
            <input type="hidden" name="idProducto" id="idProducto" required="true">
            <input name="file" id="fb" class="easyui-filebox" style="width:100%" data-options="prompt:'Seleccionar archivo...'">
            <div style="margin-top: 5px">
                <a href="#" onclick="javascript:uploadImage()" class="easyui-linkbutton" style="width:100%">Subir</a>
            </div>
        </form>
    </div>
</div>
<div id="dlgimg" style="display: none">        
    <img id="sourceImage" src="" />
</div>
<div id="dlgimgs" style="display: none">        
    
</div>
<div class="traffic-clear-5"></div>
<a href="/clientes" class="traffic-btn">
    <i class="fas fa-angle-double-left"></i> Regresar</a>