<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Expedientes digitales</h2>
                <div id="reportrange" class="pull-right">
                    <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                    <span>April 5, 2017 - May 4, 2017</span> <b class="caret"></b>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Patente</th>
                            <th>Aduana</th>
                            <th>Pedimento</th>
                            <th>Referencia</th>
                            <th>Creado</th>
                            <th>Última modificación</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($this->paginator) { ?>
                            <?php foreach ($this->paginator as $item) { ?>
                                <tr>
                                    <td><?= $item["patente"] ?></td>
                                    <td><?= $item["aduana"] ?></td>
                                    <td><?= $item["pedimento"] ?></td>
                                    <td><?= strtoupper($item['referencia']) ?></td>
                                    <td>
                                        <?= isset($item["creado"]) ? date("d/m/Y", strtotime($item["creado"])) : "" ?>
                                    </td>
                                    <td>
                                        <?= isset($item["modificado"]) ? date("d/m/Y h:i a", strtotime($item["modificado"])) : "" ?>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>