<style type="text/css">
    .btn-menu {
        display: inline-block;
        background-color: #f3f3f3;
        border: 1px #d3d3d3 solid;
        border-radius: 5px;
        min-width: 220px;
        padding: 5px;
        vertical-align: middle;
        cursor: pointer;
        margin-bottom: 5px;
    }
    .btn-menu:hover {
        background-color: #f6f5dc;
        border: 1px #e8e7c1 solid;
    }
    .btn-menu img, .btn-menu p {
        position: relative;
        float: left;
    }
    .btn-menu p {
        margin-left: 5px;
        margin-right: 5px;
        margin-top: 5px;
        margin-bottom: 5px;
        font-size: 12px;
    }
</style>
<div style="clear: both; height: 10px"></div>
<div class="row-fluid">
    <div class="span3" style="padding-left: 5px">
        <?php foreach ($this->menu as $item) { ?>
            <?php foreach (json_decode($item["menus"]) as $m) { ?>
                <?= $this->menuIcono($m->link, $m->title) ?>
            <?php } ?>
        <?php } ?>
    </div>
    <div class="span9" style="padding-left: 5px">
        <div id="container" style="width: 100%"></div>
    </div>
</div>
<div class="traffic-clear-5"></div>
<script type="text/javascript">
    $(document.body).on('click', '.btn-menu', function (ev) {
        ev.preventDefault();
        window.location = $(this).data("url");
    });

    $("#container").highcharts({
        title: {
            text: 'Pedimentos liberados <?= $this->year ?>'
        },
        subtitle: {
            text: ''
        },
        yAxis: {
            title: {
                text: 'Pedimentos'
            },
            min: 0
        },
            xAxis: {
            categories: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
            type: 'category'
        },
        plotOptions: {
            series: {
                pointStart: 0
            }
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle'
        },
        series: [<?php if(isset($this->results)) { 
            foreach ($this->results as $item) {
                echo "{name: '{$item["nombre"]}', data: [";
                foreach(range(1, 12) as $v) {
                    if ((int) $item["porMes"][$v] !== 0) {
                        echo $item["porMes"][$v] . ",";
                    } else {
                        echo "null,";
                    }
                }
                echo "]},";
            }
        } ?>]
    });

</script>