<div class="semaphoreBox">
    <div class="semaphore-holder">
        <div class="semaphore-black"></div><span>Programado</span>
    </div>
    <div class="semaphore-holder">
        <div class="semaphore-pink"></div><span>En captura</span>
    </div>
    <div class="semaphore-holder">
        <div class="semaphore-yellow"></div><span>Proforma</span>
    </div>
    <div class="semaphore-holder">
        <div class="semaphore-blue"></div><span>Pagado</span>
    </div>
    <div class="semaphore-holder">
        <div class="semaphore-green"></div><span>Liberado</span>
    </div>
    <div class="semaphore-holder">
        <div class="semaphore-red"></div><span>Urgente</span>
    </div>
    <div class="semaphore-holder">
        <i class="fas fa-arrow-circle-down" style="color: #2f3b58"></i><span style="padding-left: 3px">Importación</span>
    </div>
    <div class="semaphore-holder">
        <i class="fas fa-arrow-circle-up" style="color: #2e963a"></i><span style="padding-left: 3px">Exportación</span>
    </div>
</div>
<table id="dg" style="width:100%;height:630px"></table>