<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Traficos</h2>
                <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
                    <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                    <span>April 5, 2017 - May 4, 2017</span> <b class="caret"></b>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                        <tr class="headings">
                            <th>Pedimento </th>
                            <th>Referencia </th>
                            <th>Cve. Ped. </th>
                            <th>Regimen </th>
                            <th>Tip. Op. </th>
                            <th>Consolidado </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($this->paginator) { ?>
                            <?php foreach ($this->paginator as $item) { ?>
                                <tr>
                                    <td><?= $item["aduana"] . "-" . $item["patente"] . "-" . $item["pedimento"] ?></td>
                                    <td><?= $item["referencia"] ?></td>
                                    <td><?= $item["cvePedimento"] ?></td>
                                    <td><?= $item["regimen"] ?></td>
                                    <td><?= substr($item["ie"], 5, 3) . "O" ?></td>
                                    <td class="a-right a-right "><?= ($item["consolidado"] == "0") ? "N" : "S" ?></td>
                                </tr>
                            <?php } ?>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>