<input type="hidden" id="id_trafico" name="id_trafico" value="<?= $this->id_trafico ?>">
<div class="traffic-clear-5"></div>
<ul class="nav nav-tabs" id="traffic-tabs" style="margin-bottom: 0;">
    <li>
        <a href="#information" data-toggle="tab">Información</a>
    </li>
    <li>
        <a href="#files" data-toggle="tab"><div id="estatusChecklist" style="float:left; margin-right: 5px"></div>Archivos</a>
    </li>
</ul>
<div class="tab-content">
    <div class="tab-pane" id="information">
        <div style="float: left; width: 50%">
            <table class="traffic-table traffic-table-left">
                <tr>
                    <th colspan="6" class="invoice-title"><?= $this->basico["nombreAduana"] ?></th>
                </tr>
                <tr>
                    <th style="width: 75px; text-align: right">Pedimento</th>
                    <td>
                        <?= $this->basico["aduana"] . '-' . $this->basico["patente"] . '-' . $this->basico["pedimento"] ?>
                    </td>
                    <th style="text-align: right">Referencia</th>
                    <td colspan="3">
                        <?= $this->basico["referencia"] ?>
                    </td>
                </tr>
                <tr>
                    <th style="text-align: right">Tipo Op.</th>
                    <td>
                        <?= ($this->basico["ie"] == 'TOCE.IMP') ? '<i class="fas fa-arrow-circle-down" style="color: #2f3b58"></i>' : '<i class="fas fa-arrow-circle-up" style="color: #2f3b58"></i>' ?>
                        <?= ($this->basico["ie"] == 'TOCE.IMP') ? 'IMPO' : 'EXPO' ?>
                    </td>
                    <th style="text-align: right">Cve. Ped.</th>
                    <td><?= $this->basico["cvePedimento"] ?></td>
                    <th style="text-align: right">Tipo Cam.</th>
                    <td><?= number_format($this->basico["tipoCambio"], 4) ?></td>
                </tr>
                <tr>
                    <th style="text-align: right">Regimen</th>
                    <td><?= $this->basico["regimen"] ?></td>                
                    <th style="text-align: right">Conso.</th>
                    <td><?= ($this->basico["consolidado"] == '0') ? 'N' : 'S' ?></td>
                    <th style="text-align: right">Rect.</th>
                    <td><?= ($this->basico["rectificacion"] == '0') ? 'N' : 'S' ?></td>
                </tr>
                <tr>
                    <th style="text-align: right">Pagado</th>
                    <td><?= ($this->basico["pagado"] == NULL) ? 'N' : 'S' ?></td>
                    <th style="text-align: right">Firma Val.</th>
                    <td><?= $this->basico["firmaValidacion"] ?></td>
                    <th style="text-align: right">Firma Ban.</th>
                    <td><?= $this->basico["firmaBanco"] ?></td>
                </tr>
                <tr>
                    <th style="text-align: right">Candado (s)</th>
                    <td>
                        <?php if(isset($this->basico["candados"])) { ?>
                            <?php foreach ($this->basico["candados"] as $item) { ?>
                                <?= $item["numero"] ?>
                            <?php } ?>
                        <?php } ?>
                    </td>
                    <th style="text-align: right">Placas</th>
                    <td>
                        <?= mb_strtoupper($this->basico["contenedorCaja"]) ?>
                    </td>
                    <th style="text-align: right">Usuario</th>
                    <td><?= mb_strtoupper($this->basico["nombre"]) ?></td>
                </tr>
                <tr>
                    <th>Nombre de buque</th>
                    <td colspan="4">
                        <?= mb_strtoupper($this->basico["nombreBuque"]) ?>
                    </td>
                </tr>
            </table><!-- informacion -->
        </div>
        <div style="float: left; width: 50%">
            <div id="traffic-comments">
                <table class="traffic-table traffic-table-left">
                    <thead>
                        <tr>
                            <th colspan="3" class="traffic-table-title">BITACORA</th>
                        </tr>
                        <tr>
                            <th style="text-align: left;">Evento</th>
                            <th style="text-align: left;">Usuario</th>
                            <th style="text-align: center; width: 110px">Fecha</th>
                        </tr>
                    </thead>
                    <tbody id="traffic_log">
                        <tr>
                            <td colspan="3">
                                <span style="font-family: sans-serif; font-size: 12px">Cargando... <div class="traffic-icon traffic-loader"></div></span>
                            </td>
                        </tr>
                    </tbody>
                </table>            
                <table class="traffic-table traffic-table-left">
                    <thead>
                        <tr>
                            <th colspan="3" class="traffic-table-title">COMENTARIOS</th>
                        </tr>                
                        <tr>
                            <th style="width: 150px">Usuario</th>
                            <th>Mensaje</th>
                            <th style="width: 125px">Fecha
                                <div style="font-size:1.2em; color: #2f3b58; float: right; margin-right: 5px">
                                    <i onclick="load_comments();" class="fas fa-sync-alt" style="cursor: pointer"></i>
                                </div>
                            </th>
                        </tr>
                    </thead>
                    <tbody id="traffic_comments">
                        <tr>
                            <td colspan="3">
                                <span style="font-family: sans-serif; font-size: 12px">Cargando... <div class="traffic-icon traffic-loader"></div></span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div><!-- 50% -->
    </div>
    <div class="tab-pane" id="files" style="overflow-x: hidden">
        <div id="traffic_files" style="display: none; min-height: 460px">
            <div style="overflow-y: scroll; max-height: 450px; border: 1px #c6d7e7 solid">    
                <table class="traffic-table hover traffic-table-left" id="table_files">
                    <thead>                        
                        <tr>
                            <th>Nombre de archivo</th>
                            <th>Tipo de archivo</th>
                            <th>Creado</th>
                            <th>
                                Usuario
                                <div style="font-size:1.2em; color: #2f3b58; float: right; margin-right: 5px; margin-left: 10px">
                                    <i onclick="load_files();" class="fas fa-sync-alt" style="cursor: pointer"></i>
                                </div>
                            </th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>