<!DOCTYPE html>
<html style="height: 100%">
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <?= $this->headMeta(); ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
    </head>
    <body style="height: 100%">
        <?php if (isset($this->arr)) { ?>
            <table class="traffic-table traffic-table-left">            
                <tr>
                    <th class="traffic-table-subtitle">Patente</th>
                    <th class="traffic-table-subtitle">Aduana</th>
                    <th class="traffic-table-subtitle">Pedimento</th>
                    <th class="traffic-table-subtitle">Referencia</th>
                    <th class="traffic-table-subtitle">Creado</th>
                </tr>     
                <?php foreach ($this->arr as $k => $item) { ?>
                    <tr class="hover">
                        <td><?= $item["patente"] ?></td>
                        <td><?= $item["aduana"] ?></td>
                        <td><?= $item["pedimento"] ?></td>
                        <td><?= $item["referencia"] ?></td>
                        <td><?= $item["creado"] ?></td>
                    </tr>
                <?php } ?>
            </table>
        <?php } ?>
    </body>
</html>
