<style type="text/css">
    table.activities {
        width: 100%;
    }
    table.activities th,
    table.activities-form th {
        font-size: 12px;
        background: #f5f5f5;
        color: #333;
        height: 18px;
        line-height: 18px;
        top: 2px;
        padding: 0 3px;
        border-radius: 4px 4px 4px 4px;
        font-family: sans-serif !important;
    }    
    table.activities th.subtitle {
        background: #fafafa;
        color: #8d8d8d;
    }
    table.activities-form th,
    table.activities-form td {
        padding: 2px 2px;
        text-align: left;
    }
    table.activities tr {
        background: #fdfdfd;
    }
    table.activities td {
        font-size: 12px;
        color: #333;
        height: 18px;
        line-height: 18px;
        top: 2px;
        padding: 0 3px;
        border-radius: 4px 4px 4px 4px;
        font-family: sans-serif !important;        
    }
    table.activities tr:hover {
        background-color: #ffffdd;
    }
    tr.activityRow {
        cursor: pointer;
    }
</style>
<div class="row-fluid">
    <div class="span4">
        <div id="cc" style="width: 100%"></div>
        <table class="activities" style="margin-top: 5px">
            <thead>
                <tr style="border-top: 1px #f3f3f3 solid; border-left: 1px #f3f3f3 solid; border-right: 1px #f3f3f3 solid">
                    <th colspan="2" style="text-align: left">Mis actividades&nbsp;<div id="selectedDate" style="float: right"><?= date("Y-m-d") ?></div></th>
                </tr>
                <tr>
                    <th class="subtitle" style="border-left: 1px #f3f3f3 solid; border-right: 1px #f3f3f3 solid; text-align: right" colspan="2" >
                        <img src="/images/icons/small_plus.png" class="addActivity" style="cursor: pointer; float: right" />
                    </th>
                </tr>
                <tr id="newActivity" style="display: none">
                    <td>
                        <input type="text" id="textActivity" style="width: 90%; margin-bottom: 5px" />
                    </td>
                    <td>
                        <img src="/images/icons/disk.png" class="saveActivity" style="cursor: pointer; float: right" />
                    </td>
                </tr>
            </thead>
            <tbody id="myActivities">
                <?php if (isset($this->actividades)) { ?>
                    <?php foreach ($this->actividades as $item) { ?>
                        <tr style="border: 1px #f3f3f3 solid">
                            <td style="padding: 3px; cursor: pointer" class="activityRow" data-id="<?= $item["id"] ?>"><?= mb_strtoupper($item["titulo"]) ?></td>
                            <td style="width: 20px; text-align: right">
                                <img data-id="<?= $item["id"] ?>" src="/images/icons/small_delete.png" class="deleteActivity" style="cursor: pointer"/>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } else { ?>
                    <tr style="border: 1px #f3f3f3 solid">
                        <td colspan="2" style="padding: 3px">
                            <em>No hay actividades.</em>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <div class="span8"style="border: 1px #ddd solid">
        <form id="activityForm">
            <table class="activities-form" style="width: 100%">
                <thead>
                    <tr>
                        <th style="text-align: left; width: 150px">Id:</th>
                        <th style="text-align: left">
                            <input type="text" id="idActividad" name="idActividad" class="traffic-input-tiny" readonly="true" style="width: 50px"/>
                        </th>
                    </tr>
                    <tr>
                        <th style="text-align: left">Titulo:</th>
                        <th style="text-align: left">
                            <input type="text" id="titulo" name="titulo" class="traffic-input-large" disabled="true"/>
                        </th>
                    </tr>
                    <tr>
                        <th style="text-align: left">Departamento:</th>
                        <th style="text-align: left">
                            <select id="idDepto" name="idDepto" class="traffic-select-large" disabled="true">
                                <option value="">---</option>
                                <?php if(isset($this->empresas)) { ?>
                                    <?php foreach ($this->empresas as $item) { ?>
                                        <option value="<?= $item["id"] ?>"><?= mb_strtoupper($item["descripcion"]) ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        </th>
                    </tr>
                </thead>
            </table>
            <div id="formulario"></div>
            <table class="activities-form" style="width: 100%">
                <tbody>
                    <tr>
                        <th colspan="2">Observaciones:</th>
                    </tr>
                    <tr>
                        <th colspan="2">
                            <textarea id="observaciones" name="observaciones"></textarea>
                        </th>
                    </tr>
                    <tr>
                        <th>
                            <button style="float: right" id="submit" class="traffic-btn traffic-btn-add" disabled="true">
                                Guardar
                            </button>                            
                        </th>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>
<div style="clear: both; height: 5px"></div>
<a onclick="window.history.back();" class="traffic-btn-back" style="margin-left: 6px">«&nbsp;Regresar</a>

