<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="OAQ Web Portal">
        <meta name="author" content="Jaime E. Valdez">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <title>Editar Factura</title>
        <link rel="icon" type="image/png" href="/favicon.png" />
        <meta name="description" content="" >
        <link href="/favicon.png" rel="icon shortcut" >
        <link href="/js/common/bootstrap/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="/less/traffic-module.css?<?= time() ?>" media="screen" rel="stylesheet" type="text/css" >
        <link href="/easyui/themes/default/easyui.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="/js/common/bootstrap/datepicker/css/datepicker.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="/easyui/themes/icon.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="/js/common/toast/jquery.toast.min.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="/v2/js/common/confirm/jquery-confirm.min.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="/css/fontawesome/css/fontawesome-all.min.css" media="screen" rel="stylesheet" type="text/css" >

        <script type="text/javascript" src="/js/common/jquery-1.9.1.min.js"></script>
        <script type="text/javascript" src="/easyui/jquery.easyui.min.js"></script>
        <script type="text/javascript" src="/easyui/jquery.edatagrid.js"></script>
        <script type="text/javascript" src="/easyui/datagrid-filter.js"></script>
        <script type="text/javascript" src="/easyui/locale/easyui-lang-es.js"></script>
        <script type="text/javascript" src="/js/common/loadingoverlay.min.js"></script>
        <script type="text/javascript" src="/js/common/bootstrap/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="/js/common/bootstrap/bootstrap-datepicker/js/locales/bootstrap-datepicker.es.js"></script>
        <script type="text/javascript" src="/js/common/jquery.form.min.js"></script>
        <script type="text/javascript" src="/js/common/jquery.validate.min.js"></script>
        <script type="text/javascript" src="/js/common/toast/jquery.toast.min.js?"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-3-typeahead/4.0.2/bootstrap3-typeahead.min.js"></script>
        <script type="text/javascript" src="/v2/js/common/confirm/jquery-confirm.min.js"></script>
        <style>
            select {
                line-height: 16px;
                height: 22px;
                margin-left: 2px;
            }
            select option {
                font-family: sans-serif;
                font-size: 14px;
            }
            input[type="text"] {
                padding: 0px 2px;
                margin-left: 2px;
            }
            table.traffic-table,
            table.traffic-table td, 
            table.traffic-table th {
                padding: 0 !important;
            }
            label {
                font-weight: bold;
                margin-right: 2px;
            }
            .divTable{
                display: table;
                width: 100%;
            }
            .divTableRow {
                display: table-row;
            }
            .divTableHeading {
                background-color: #EEE;
                display: table-header-group;
            }
            .divTableCell, .divTableHead {
                display: table-cell;
                padding: 0px 2px;
            }
            .divTableHeading {
                background-color: #EEE;
                display: table-header-group;
                font-weight: bold;
            }
            .divTableFoot {
                background-color: #EEE;
                display: table-footer-group;
                font-weight: bold;
            }
            .divTableBody {
                display: table-row-group;
            }
            .divTableBody .divTableRow {
                border-bottom: 1px #e6e6e6 solid;
            }
            .divTableBody .divTableRow .divTableCell {
                margin: 0 !important;
                padding: 0 !important;
                height: 16px !important;
                line-height: 16px !important;
            }
            i.fas, i.far {
                cursor: pointer; 
                font-size:1.4em;
                color: #2f3b58;
                margin: 5px;
            }
        </style>
    </head>
    <body>
        <script type="text/javascript">
            $.LoadingOverlay("show", {color: "rgba(255, 255, 255, 0.9)"});
        </script>
        <form id="formInvoice">
            <input type="hidden" name="idTrafico" id="idTrafico" value="<?= $this->idTrafico ?>">
            <input type="hidden" name="idCliente" id="idCliente" value="<?= $this->idCliente ?>">           
            <input type="hidden" name="idFactura" id="idFactura" value="<?= $this->idFactura ?>">           
            <?php if (isset($this->idProv)) { ?>
                <input type="hidden" name="idProveedor" id="idProveedor" value="<?= $this->idProv ?>" />
            <?php } ?>
            <?php if (isset($this->closed)) { ?>
                <input type="hidden" name="edit" id="edit" value="false" />
            <?php } ?>
            <table class="traffic-table">
                <tbody>
                    <tr>                    
                        <td>
                            <label style="float: left; width: 80px; text-align: right">Cliente:</label>
                            <input style="float: left; width: 350px" type="text" value="<?= $this->invoice["razonSocial"] ?>" disabled="true" />
                            <label style="float: left; width: 80px; text-align: right">Referencia:</label>
                            <input style="float: left; width: 90px; text-align: center" type="text" value="<?= $this->invoice["referencia"] ?>" disabled="true">
                            <?php if (!isset($this->closed)) { ?>
                                <i class="far fa-save" onclick="guardar();" title="Guardar" style="float: right; margin-right: 10px"></i>
                                <i class="fas fa-download" onclick="importarFactura();" title="Importar factura" style="float: right"></i>
                            <?php } ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label style="float: left; width: 80px; text-align: right">Num.:</label>
                            <input style="float: left; width: 120px" type="text" name="numFactura" id="numFactura" value="<?= $this->invoice["numFactura"] ?>">
                            <label style="float: left; width: 45px; text-align: right">Fecha:</label>
                            <input name="fechaFactura" id="fechaFactura" style="float: left; width: 90px" type="text" value="<?= date("Y-m-d", strtotime($this->invoice["fechaFactura"])) ?>">
                            <i class="far fa-calendar-alt" id="changeDate" title="Cambiar la fecha de factura" style="float: left; margin: 1px 0 0 5px"></i>
                            <label style="float: left; width: 55px; text-align: right">Moneda:</label>
                            <select name="divisa" id="divisa" style="float: left; width: 225px">
                                <option value="">---</option>
                            </select>
                        </td>
                    </tr>
                </tbody>
            </table>
            <table class="traffic-table">
                <tbody>
                    <tr>
                        <td>
                            <table class="traffic-table">
                                <tbody>
                                    <tr>
                                        <td style="font-weight: bold">Proveedor / Destinatario</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Nombre:</label>
                                            <select name="idProv" id="idProv" style="float: left; width: 410px">
                                                <option value="">---</option>
                                            </select>
                                            <?php if (!isset($this->closed)) { ?>
                                                <i class="fas fa-file-alt" onclick="nuevoProveedor();" title="Nuevo proveedor" style="float: left"></i>
                                                <i class="fas fa-pencil-alt" onclick="editarProveedor();" title="Editar proveedor" style="float: left"></i>
                                            <?php } ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Iden:</label>
                                            <input name="identificador" id="identificador" style="float: left; width: 150px" type="text" value="">
                                            <label style="float: left; width: 65px; text-align: right">Tipo Iden.:</label>
                                            <select name="tipoIdentificador" id="tipoIdentificador" style="float: left; width: 110px" disabled="true">
                                                <option value="">---</option>
                                                <option value="0">Tax ID</option>
                                                <option value="1">RFC</option>
                                                <option value="2">CURP</option>
                                                <option value="3">Sin Tax ID</option>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Calle:</label>
                                            <input name="calle" id="calle" style="float: left; width: 250px" type="text" value="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Num. Ext.:</label>
                                            <input name="numExt" id="numExt" style="float: left; width: 90px" type="text" value="">
                                            <label style="float: left; width: 60px; text-align: right">Num. Int.:</label>
                                            <input name="numInt" id="numInt" style="float: left; width: 90px" type="text" value="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Colonia:</label>
                                            <input name="colonia" id="colonia" style="float: left; width: 250px" type="text" value="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Loc. (Cd.):</label>
                                            <input name="localidad" id="localidad" style="float: left; width: 250px" type="text" value="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Municipio:</label>
                                            <input name="municipio" id="municipio" style="float: left; width: 250px" type="text" value="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Estado:</label>
                                            <input name="estado" id="estado" style="float: left; width: 250px" type="text" value="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">CP:</label>
                                            <input name="codigoPostal" id="codigoPostal" style="float: left; width: 70px" type="text" value="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">País:</label>
                                            <select name="pais" id="pais" style="float: left; width: 250px">
                                                <option value="">---</option>
                                            </select>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                        <td style="width: 250px">
                            <table class="traffic-table">
                                <tbody>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Fletes:</label>
                                            <input name="fletes" id="fletes" style="float: left; width: 120px; text-align: right" type="text" value="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Seguros:</label>
                                            <input name="seguros" id="seguros" style="float: left; width: 120px; text-align: right" type="text" value="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Embalajes:</label>
                                            <input name="embalajes" id="embalajes" style="float: left; width: 120px; text-align: right" type="text" value="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Otros:</label>
                                            <input name="otros" id="otros" style="float: left; width: 120px; text-align: right" type="text" value="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Incoterm:</label>
                                            <select name="incoterm" id="incoterm" style="float: left; width: 120px">
                                                <option value="">---</option>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Subdivision:</label>
                                            <select name="subdivision" id="subdivision" style="float: left; width: 120px">
                                                <option value="">---</option>
                                                <option value="1">Si</option>
                                                <option value="0">No</option>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Cert. orig.:</label>
                                            <select name="certificadoOrigen" id="certificadoOrigen" style="float: left; width: 120px">
                                                <option value="">---</option>
                                                <option value="1">Si</option>
                                                <option value="0">No</option>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Num. Expor.:</label>
                                            <input name="numExportador" id="numExportador" style="float: left; width: 120px" type="text" value="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Val.:</label>
                                            <input name="valorFacturaMonExt" id="valorFacturaMonExt" style="float: left; width: 120px; text-align: right" type="text" value="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Val USD:</label>
                                            <input name="valorFacturaUsd" id="valorFacturaUsd" style="float: left; width: 120px; text-align: right" type="text" value="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Equiv.:</label>
                                            <input name="factorMonExt" id="factorMonExt" style="float: left; width: 120px; text-align: right" type="text" value="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <label style="float: left; width: 80px; text-align: right">Observaciones:</label>
                                            <br>
                                            <textarea name="observaciones" id="observaciones" style="float: left; width: 200px"></textarea>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
        <table class="traffic-table">
            <tbody>
                <tr>
                    <td style="font-weight: bold">Productos / Items
                        <?php if (!isset($this->closed)) { ?>
                            <i class="fas fa-sync-alt" onclick="productos();" title="Actualizar productos" style="float: left"></i>
                            <i class="far fa-plus-square" onclick="nuevoProducto();" title="Agregar producto" style="float: right"></i>
                        <?php } ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="divTable">
                            <div class="divTableHeading">
                                <div class="divTableRow">
                                    <div class="divTableCell">Fracción</div>
                                    <div class="divTableCell">Num. Parte</div>
                                    <div class="divTableCell">Desc.</div>
                                    <div class="divTableCell">P. Unit.</div>
                                    <div class="divTableCell">Cant.</div>
                                    <div class="divTableCell">Val. Com.</div>
                                    <div class="divTableCell">UMC</div>
                                    <div class="divTableCell">Cant OMA.</div>
                                    <div class="divTableCell">OMA</div>
                                    <div class="divTableCell" style="width: 50px">&nbsp;</div>
                                </div>
                            </div>
                            <div class="divTableBody" id="products">
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </body>
    <script type="text/javascript" src="/js/bodega/facturas/editar-factura.js?<?= time() ?>"></script>
</html>