<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="OAQ Web Portal">
        <meta name="author" content="Jaime E. Valdez">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <title>XML COVE</title>
        <link rel="icon" type="image/png" href="/favicon.png" />
        <meta name="description" content="" >
        <link href="/favicon.png" rel="icon shortcut" >
        <link href="/js/common/bootstrap/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="/less/traffic-module.css?<?= time() ?>" media="screen" rel="stylesheet" type="text/css" >
        <link href="/js/common/highlight/styles/github.css" media="screen" rel="stylesheet" type="text/css" >
        <script type="text/javascript" src="/js/common/jquery-1.9.1.min.js"></script>
        <script type="text/javascript" src="/js/common/highlight/highlight.pack.js"></script>        
    </head>
    <body>
        <script type="text/javascript">
            $.LoadingOverlay("show", {color: "rgba(255, 255, 255, 0.9)"});
        </script>
        <pre style="padding: 2px; line-height: 12px; margin: 0">
            <code style="padding: 2px; line-height: 12px"><?= htmlentities($this->contenido) ?></code>
        </pre>
    </body>
    <script type="text/javascript">
        $(document).ready(function() {
            $("pre code").each(function(i, block) {
                hljs.highlightBlock(block);
            });
        });
    </script>
</html>