<div style="float: left; margin-left: 2px"> 
    <h5 style="float: left; margin-left: 5px" style="margin: 0;">CARTA DE INSTRUCCIONES</h5>
</div>
<table id="dg" style="width:100%;height:530px"></table>
<div class="traffic-clear-10"></div>
<button class="traffic-btn traffic-btn-right" id="nuevaCarta">
    <i class="far fa-file-alt"></i> Nueva carta
</button>
<button class="traffic-btn traffic-btn-right" id="subirFacturas">
    <i class="fas fa-upload"></i> Subir facturas
</button>
<button class="traffic-btn traffic-btn-right" id="subirCatalogo">
    <i class="fas fa-upload"></i> Subir catalogo
</button>
<a class="traffic-btn traffic-btn-right" href="/operaciones/catalogo/deliveries">
    <i class="fas fa-binoculars"></i> Deliveries
</a>