<div id="mm" class="easyui-menu" style="width:120px;">
    <div onclick="javascript:uploadDialog()">Subir fotos</div>
    <div onclick="javascript:photosDialog()">Ver fotos</div>
    <div class="menu-sep"></div>
    <div>Salir</div>
</div>
<input id="idCliente" type="hidden" value="<?= $this->idCliente ?>">
<div class="traffic-cols">
    <div class="traffic-col-30">
        <div class="easyui-panel" title="Proveedor" style="width:100%; padding:20px 30px; height: 345px">
            <form id="fmprov" method="post">
                <div style="margin-bottom:10px">
                    <label>Identificador (TaxID, RUT, etc.):</label>
                    <input name="identificador" class="easyui-textbox" required="true" style="width: 170px" >
                </div>
                <div style="margin-bottom:10px">
                    <label>Nombre del proveedor:</label>
                    <input name="nombre" class="easyui-textbox" required="true" style="width: 250px" >
                </div>
<!--                <div style="margin-bottom:10px">
                    <label>Clave SITA:</label>
                    <input name="clave" class="easyui-textbox" required="true" style="width: 100px">
                </div>-->
            </form>
            <div id="dlg-buttonsprov">
                <a href="javascript:void(0)" class="easyui-linkbutton c6" iconCls="icon-ok" onclick="saveProvider()" style="width:90px">Guardar</a>
            </div>
        </div>
    </div>
    <div class="traffic-col-70">
        <table id="providers"></table>        
    </div>
</div>
<div class="traffic-clear-10"></div>
<div class="traffic-cols">
    <div class="traffic-col-30">
        <div class="easyui-panel" title="Producto" style="width:100%; padding:20px 30px; height: 400px">
            <form id="fm" method="post">
                <input type="hidden" name="idCliente" id="idCliente" value="<?= $this->idCliente ?>">
                <input type="hidden" name="idProveedor" id="idProveedor" required="true">
                <div style="margin-bottom:10px">
                    <label>Proveedor:</label>
                    <input name="proveedor" id="proveedor" class="easyui-textbox" required="true" style="width: 320px">
                </div>
                <div style="margin-bottom:10px">
                    <label>Fracción:</label>
                    <input name="fraccion" class="easyui-textbox" required="true" style="width: 150px">
                </div>
                <div style="margin-bottom:10px">
                    <label>Numero de parte cliente:</label>
                    <input name="numParteCliente" class="easyui-textbox" required="true"  style="width: 150px">
                </div>
                <div style="margin-bottom:10px">
                    <label>Descripción:</label>
                    <input name="descripcion" class="easyui-textbox" required="true"  style="width: 320px">
                </div>
            </form>
            <div id="dlg-buttons">
                <a href="javascript:void(0)" class="easyui-linkbutton c6" iconCls="icon-ok" onclick="saveProduct()" style="width:90px">Guardar</a>
            </div>
        </div>
    </div>
    <div class="traffic-col-70">
        <table id="parts"></table>
    </div>
</div>
<div id="dlg" style="display: none">
    <div class="easyui-panel" style="width:100%;padding:10px 20px;">        
        <form id="fmimage" method="post" enctype="multipart/form-data">
            <input type="hidden" name="idProducto" id="idProducto" required="true">
            <input name="file" id="fb" class="easyui-filebox" style="width:100%" data-options="prompt:'Seleccionar archivo...'">
            <div style="margin-top: 5px">
                <a href="#" onclick="javascript:uploadImage()" class="easyui-linkbutton" style="width:100%">Subir</a>
            </div>
        </form>
    </div>
</div>
<div id="dlgimg" style="display: none">        
    <img id="sourceImage" src="" />
</div>
<div id="dlgimgs" style="display: none">        
    
</div>
<div class="traffic-clear-5"></div>
<a href="/operaciones/catalogo/index" class="traffic-btn">
    <i class="fas fa-angle-double-left"></i> Regresar</a>