<form id="form_parts">
    <input type="hidden" name="id" id="id" value="<?= $this->arr["id"] ?>"/>
    <table class="traffic-table traffic-table-left">
        <thead></thead>
        <tbody>
            <tr>
                <th style="text-align: right">NUM. CARTA:</th>
                <td>
                    <input class="traffic-input-medium" type="text" name="numCarta" id="numCarta" value="<?= $this->arr["numCarta"] ?>" readonly="true"/>
                </td>
            </tr>
<!--            <tr>
                <th style="text-align: right">PROVEEDOR:</th>
                <td>
                    <input class="traffic-input-medium" type="text" name="proveedor" id="proveedor" readonly="true"/>
                </td>
            </tr>
            <tr>
                <th style="text-align: right">RFC:</th>
                <td>
                    <input class="traffic-input-medium" type="text" name="rfc" id="rfc" readonly="true"/>
                </td>
            </tr>-->
            
            <tr>
                <th style="text-align: right">TIPO OPERACIÓN:</th>
                <td>
                    <select class="traffic-select-small" name="tipoOperacion" id="tipoOperacion">
                        <option value="">-- Seleccionar --</option>
                        <option value="1">Importación</option>
                        <option value="2">Exportación</option>
                    </select>
                </td>
            </tr>
            <tr>
                <th style="text-align: right">SELLO:</th>
                <td>
                    <input class="traffic-input-medium" type="text" name="sello" id="sello" value="<?= $this->arr["sello"] ?>" />
                </td>
            </tr>
            <tr>
                <th style="text-align: right">DIGIRIDA A:</th>
                <td>
                    <input class="traffic-input-large" type="text" name="dirigida" id="dirigida" value="<?= $this->arr["dirigida"] ?>" />
                </td>
            </tr>
            <tr>
                <th style="text-align: right">FECHA:</th>
                <td>
                    <input class="traffic-input-date" type="text" name="fecha" id="fecha" value="<?= ($this->arr["fecha"]) ? date("Y-m-d", strtotime($this->arr["fecha"])) : '' ?>"/><i class="far fa-calendar-alt" style="padding-left: 5px; font-size: 1.2em"></i>
                </td>
            </tr>
            <tr>
                <th style="text-align: right">OBSERVACIONES:</th>
                <td>
                    <input class="traffic-input-large" type="text" name="observaciones" id="observaciones" />
                </td>
            </tr>
            <tr>
                <th style="text-align: right">LÍNEA DE TRANSPORTE:</th>
                <td>
                    <input class="traffic-input-large" type="text" name="lineaTransporte" id="lineaTransporte" />
                </td>
            </tr>
            <tr>
                <th style="text-align: right; width: 150px">
                    DELIVERY NUMBER:
                </th>
                <td>
                    <input class="traffic-input-medium" type="text" name="deliveryNumber" id="deliveryNumber" autocomplete="false" /><i title="Agregrar" class="fas fa-plus" style="padding-left: 5px; font-size: 1.2em; cursor: pointer"></i>
                    <button class="traffic-btn traffic-btn-right" id="save">
                        <i class="fas fa-save"></i> Guardar</button>
                    <button class="traffic-btn traffic-btn-right" id="add-element">
                        <i class="fas fa-plus-square"></i> Agregar retornable</button>
                </td>
            </tr>
        </tbody>
    </table>
</form>
<div style="float: left; margin-left: 2px"> 
    <h5 style="float: left; margin-left: 5px" style="margin: 0;">EDITAR CARTA DE INSTRUCCIONES</h5>
</div>
<table id="dg" style="width:100%;height:530px"></table>
<div class="traffic-clear-10"></div>
<a class="traffic-btn" onclick="window.history.back();" tabindex="99">
        <i class="fas fa-angle-double-left"></i> Regresar
</a>