<?php $helper = $this->getHelper('ItemsFactura'); ?>
<table class="traffic-table traffic-table-left">
    <tbody>
        <tr>
            <th style="width: 100px">Línea</th>
            <td><?= $this->linea ?></td>            
            <th style="width: 130px">Num. Facturas</th>
            <td><?= $this->numFacturas ?></td>            
        </tr>
        <tr>
            <th>Bultos</th>
            <td><?= $this->bultos ?></td>
            <th>Observaciones</th>
            <td><?= $this->observaciones ?></td>            
        </tr>
        <tr>
            <th>Completa</th>
            <td><?= (isset($this->completa) && $this->completa == 1) ? "SI" : "NO" ?></td>            
            <th>Avería</th>
            <td><?= (isset($this->averia) && $this->averia == 1) ? "SI" : "NO" ?></td>            
        </tr>
    </tbody>
</table>
<?php if ($this->facturas) { ?>
    <?php foreach ($this->facturas as $factura) { ?>
        <table class="traffic-table traffic-table-left">
            <thead>
                <tr>
                    <th style="width: 150px">Num. de Factura</th>
                    <td colspan="8">
                        <?= $factura["numFactura"] ?>
                    </td>
                </tr>
            </thead>
            <tbody>                
                <tr>
                    <th>Item</th>
                    <th>Cantidad</th>
                    <th>Peso</th>
                    <th>Marca</th>
                    <th>Modelo</th>
                    <th>Num. Serie</th>
                    <th>Num. Parte</th>
                    <th>Fotos</th>
                </tr>
                <?php if (($items = $helper->itemsFactura($factura["idGuia"], $factura["idFactura"]))) { ?>
                    <?php foreach ($items as $item) { ?>
                        <tr>
                            <td><?= $item["descripcion"] ?></td>
                            <td><?= number_format($item["cantidad"], 3, ".", ",") ?></td>
                            <td><?= number_format($item["peso"], 3, ".", ",") ?></td>
                            <td><?= $item["marca"] ?></td>
                            <td><?= $item["modelo"] ?></td>
                            <td><?= $item["numeroSerie"] ?></td>
                            <td><?= $item["numeroParte"] ?></td>
                            <td>
                                <?php if (($fotos = $helper->fotosItem($factura["idGuia"], $factura["idFactura"], $item["idItem"]))) { ?>
                                    <?php foreach ($fotos as $foto) { ?>
                                        <img class="foto"data-id="<?= $foto["id"] ?>" src="<?= $helper->verImagen($foto["thumb"]) ?>" width="120" style="float: left; margin: 2px; cursor: pointer" />
                                    <?php } ?>
                                <?php } ?>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } ?>
            </tbody>
        </table>
    <?php } ?>
<?php } ?>
<script type="text/javascript">
    $(document.body).on("click", ".foto", function(){
        window.open("/bitacora/get/ver-foto?id=" + $(this).data("id"), "_blank", "toolbar=0,location=0,menubar=0,height=650,width=1024,scrollbars=yes");
        
    });
</script>
    