<div id="mm" class="easyui-menu" style="width:180px;">
    <div onclick="javascript:previo();">Datos previo</div>
    <div onclick="javascript:agrupar();">Agrupar</div>
    <div onclick="javascript:crearTrafico();">Crear tráfico</div>
    <div onclick="javascript:borrar();">Borrar</div>
    <div class="menu-sep"></div>
    <div>Salir</div>
</div>
<table id="log"></table>
<div class="traffic-clear-5"></div>