<div style="overflow-y: scroll; max-height: 400px">
    <div id="alert"></div>
    <form id="formChecklist" enctype="application/x-www-form-urlencoded">
        <?php if(isset($this->idRepo)) { ?>
            <input type="hidden" value="<?= $this->idRepo ?>" name="idRepo" />
        <?php } ?>
        <?php if(isset($this->idTrafico)) { ?>
            <input type="hidden" value="<?= $this->idTrafico ?>" name="idTrafico" />
        <?php } ?>
        <input type="hidden" value="<?= $this->patente ?>" name="patente" />
        <input type="hidden" value="<?= $this->aduana ?>" name="aduana" />
        <input type="hidden" value="<?= $this->pedimento ?>" name="pedimento" />
        <input type="hidden" value="<?= $this->referencia ?>" name="referencia" />
        <input type="hidden" value="<?= $this->cvePedimento ?>" name="clavePedimento" id="clavePedimento" />
        <table class="traffic-table traffic-table-left">
            <tr>
                <td colspan="2"><strong>REFERENCIA:</strong>&nbsp;<?= $this->referencia ?></td>
                <td colspan="2"><strong>PEDIMENTO:</strong>&nbsp;<?= $this->pedimento ?></td>
            </tr>
            <?php if (isset($this->preguntas)) { ?>
                <?php
                $i = 1;
                $title = '';
                foreach ($this->preguntas as $item) {
                    ?>
                    <?php
                    if ($title != $item["tipo"]) {
                        $title = $item["tipo"];
                        ?>
                        <tr>
                            <th colspan="2" class="traffic-tablae-subtitle"><?= $item["tipo"] ?></th>
                            <th>Si</th>
                            <th>N/A</th>
                        </tr>
                    <?php } ?>
                    <tr>
                        <td><?= $i++ ?></td>
                        <td><?= $item["documento"] ?></td>
                        <td style="text-align: center; width: 40px">
                            <input type="radio" value="1" name="<?= $item["nombre"] ?>">
                        </td>
                        <td style="text-align: center; width: 40px">
                            <input type="radio" value="0" name="<?= $item["nombre"] ?>">
                        </td>
                    </tr>
                <?php } ?>
                <tr>
                    <td colspan="5">
                        Observaciones:<br>
                        <textarea name="observaciones" id="observaciones" class="traffic-textarea-large"><?= isset($this->observaciones) ? $this->observaciones : "" ?></textarea>
                    </td>
                </tr>
                <tr>
                    <th colspan="2" class="traffic-tablae-subtitle">&nbsp;</th>
                    <th>Si</th>
                    <th>No</th>
                </tr>
                <?php if(isset($this->operacion)) { ?>
                    <tr>
                        <td colspan="2" style="text-align: right"><strong>Revisión operaciones:</strong></td>
                        <td style="text-align: center"><input type="radio" value="1" name="revisionOperaciones" <?= isset($this->revOp) && $this->revOp == "1" ? "checked=\"checked\"" : "" ?>></td>
                        <td style="text-align: center"><input type="radio" value="0" name="revisionOperaciones" <?= isset($this->revOp) && $this->revOp == "0" ? "checked=\"checked\"" : "" ?>></td>
                    </tr>
                <?php } ?>
                <?php if(isset($this->administracion)) { ?>
                    <tr>
                        <td colspan="2" style="text-align: right"><strong>Revisión administración:</strong></td>
                        <td style="text-align: center"><input type="radio" value="1" name="revisionAdministracion" <?= isset($this->revAdm) && $this->revAdm == "1" ? "checked=\"checked\"" : "" ?>></td>
                        <td style="text-align: center"><input type="radio" value="0" name="revisionAdministracion" <?= isset($this->revAdm) && $this->revAdm == "0" ? "checked=\"checked\"" : "" ?>></td>
                    </tr>
                <?php } ?>
                <?php if(isset($this->admin)) { ?>
                    <tr>
                        <td colspan="2" style="text-align: right"><strong>Expediente completo:</strong></td>
                        <td style="text-align: center"><input type="radio" value="1" name="completo" <?= isset($this->completo) && $this->completo == "1" ? "checked=\"checked\"" : "" ?>></td>
                        <td style="text-align: center"><input type="radio" value="0" name="completo" <?= isset($this->completo) && $this->completo == "0" ? "checked=\"checked\"" : "" ?>></td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <tr>
                    <td colspan="3">No existe checklist para esta aduana.</td>
                </tr>
            <?php } ?>
        </table>
    </form>
    <table class="traffic-table traffic-table-left">
        <thead>
            <tr>
                <th colspan="3">Bitacora</th>
            </tr>
        </thead>
        <tbody>
            <?php if (isset($this->bitacora)) { ?>
                <tr>
                    <th>BITACORA</th>
                    <th>USUARIO</th>
                    <th>FECHA</th>
                </tr>
                <?php foreach ($this->bitacora as $item) { ?>
                    <tr>
                        <td><?= $item["bitacora"] ?></td>
                        <td style="text-align: center"><?= strtoupper($item["usuario"]) ?></td>
                        <td style="width: 120px"><?= $item["creado"] ?></td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <tr>
                    <td colspan="3" style="text-align: center"><em>No hay bitacora asociada.</em></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<script type="text/javascript">

<?php foreach ($this->preguntas as $item) { ?>
        $(document).on("change", "input:radio[name='<?= $item["nombre"] ?>']", function () {
            $("input:radio[name='<?= $item["nombre"] ?>']").removeAttr("checked");
            $("input:radio[name='<?= $item["nombre"] ?>']").filter("[value='" + $(this).val() + "']").attr("checked", true).
                    prop("checked", true);
        });
<?php } ?>

<?php if (isset($this->data)) { ?>
        var checklist = JSON.parse('[<?= json_encode($this->data) ?>]');
        $.each(checklist[0], function (key, value) {
            $("input:radio[name='" + key + "']").filter("[value='" + value + "']").attr("checked", true);
        });
<?php } ?>
    
<?php 
$arrg = array(
    array("name" => "pedimentos", "ids" => array(1, 23, 24, 32)),
    array("name" => "doda", "ids" => array(63)),
    array("name" => "gastos", "ids" => array(2)),
    array("name" => "factura", "ids" => array(3, 34, 170)),
    array("name" => "cartai", "ids" => array(4)),
    array("name" => "cartas", "ids" => array(55, 192)),
    array("name" => "cartase", "ids" => array(18, 5, 436)),
    array("name" => "covese", "ids" => array(6, 7, 8, 36, 171, 172, 176, 184, 185, 189, 420)),
    array("name" => "manif", "ids" => array(10, 11)),
    array("name" => "bill", "ids" => array(12, 38, 438)),
    array("name" => "certi", "ids" => array(14, 35)),
    array("name" => "coves", "ids" => array(21, 22)),
    array("name" => "pedimentosim", "ids" => array(31, 33)),
    array("name" => "otros", "ids" => array(25, 37, 442)),
    array("name" => "serviex", "ids" => array(58)),
    array("name" => "mani", "ids" => array(42, 40)),
    array("name" => "gastosamericana", "ids" => array(59)),
    array("name" => "gastoscorresponsal", "ids" => array(29, 30)),
);
?>
    
<?php if (isset($this->tipos)) { ?>
    
        Array.prototype.contains = function(obj) {
            var i = this.length;
            while (i--) {
                if (this[i] === obj) {
                    return true;
                }
            }
            return false;
        };
        
        var tipos = JSON.parse('[<?= json_encode($this->tipos) ?>]');
        function llenarChecklist() {
            var arr = tipos[0];
            $.each(arr, function (key, value) {
                <?php foreach ($arrg as $item) { ?>
                    if([<?= implode(",", $item["ids"]) ?>].contains(parseInt(key))) {
                        $("input:radio[name='<?= $item["name"] ?>']").filter("[value='1']").attr("checked", true);
                    } else if(!$("input:radio[name='<?= $item["name"] ?>']").filter("[value='1']").is(":checked")) {
                        $("input:radio[name='<?= $item["name"] ?>']").filter("[value='0']").attr("checked", true);
                    }
                <?php } ?>
            });
            let claves = ["A1","AF","H8","AJ","F4","G1","E1"];
            let cvePedimento = $("#clavePedimento").val();
            if (claves.includes(cvePedimento)) {
                let ch = $("input:radio[name='manif']").filter("[value='1']");
                if (!$("input:radio[name='manif']").filter("[value='1']").is(':checked')) {
                    $("#alert").html('<p style="color: red; text-align: center; font-size: 11px; padding: 3px; border: 1px red solid">Clave de pedimento A1, AF, H8, AJ, F4, G1 y E1 deben contar con manifestación de valor y hoja de cálculo.</p>');
                }
            }
        }      
<?php } ?>
    
    var not = "input:radio[name='completo'],input:radio[name='revisionOperaciones'],input:radio[name='revisionAdministracion']";
    var radios = $("input:radio").not(not).filter("[value='1']").length;
    var checked = 0;
    
    $(document.body).on("click", "input:radio", function (ev) {
        checked = $("input:radio").not(not).length;        
    });
    
    var chi = 0;
    $("input:radio").each(function() {
        var name = $(this).attr("name");
        if (name !== "completo"  && name !== "revisionOperaciones" && name !== "revisionAdministracion") {
            if ($("input[name='" + name + "']:checked").length === 1) {
                chi = chi + 1;
            }
        }
    });
    if (chi !== 0) {
        checked = chi / 2;
    }
    
    $(document.body).on("mousedown", not, function (ev) {
        ev.preventDefault();
        var val = $(this).val();
        if(parseInt(val) === 1) {
            if(radios === checked) {
                $(this).attr("checked", true);
            } else {
                alert("Debe seleccionar todos los elementos del cuestionario.");
            }
        } else {
            $(this).attr("checked", true);
        }
    });

    $("input[name='completo']").click(function () {
        if ($(this).val() === 1) {
        }
    });

    $("#autoChecklist").qtip({
        content: {
            text: "Llena de forma automática el checklist."
        }
    });

    $(document.body).on("input", "#observaciones", function () {
        var input = $(this);
        var start = input[0].selectionStart;
        $(this).val(function (_, val) {
            return val.toUpperCase();
        });
        input[0].selectionStart = input[0].selectionEnd = start;
    });

</script>