<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="OAQ Web Portal">
        <meta name="author" content="Jaime E. Valdez">
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <title>Archivo validador</title>
        <link rel="icon" type="image/png" href="/favicon.png" />
        <meta name="description" content="" >        
        <link href="/favicon.png" rel="icon shortcut" >
        <link href="/js/common/bootstrap/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="/css/fontawesome/css/fontawesome-all.min.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="/less/traffic-module.css?1497552035" media="screen" rel="stylesheet" type="text/css" >
        <link href="/easyui/themes/icon.css" media="screen" rel="stylesheet" type="text/css" >
        <script type="text/javascript" src="/js/common/jquery-1.9.1.min.js"></script>
        <script type="text/javascript" src="/js/common/jquery-linedtextarea.js"></script>
        <style>    
            .datagrid-cell, .datagrid-cell-group, .datagrid-header-rownumber, .datagrid-cell-rownumber,
            .datagrid-editable {
                padding: 0 !important;
            }    
        </style>
    </head>
    <body>
        <style>
            .linedwrap .codelines .lineno,
            .linedwrap .lines .codelines .lineno,
            .linedtextarea textarea {
                font-family: Courier, 'New Courier', monospace, sans-serif !important;
                line-height: 12px;
                font-size: 12px;            
            }
            .linedtextarea textarea {
                padding: 0;
                padding-top: 3px;
                border-radius: 0;
            }
        </style>
        <table class="traffic-table traffic-table-left" id="customersList">
            <thead>
                <tr>
                    <th style="width: 55px">Id</th>
                    <th style="width: 65px">Patente</th>
                    <th style="width: 65px">Aduana</th>
                    <th style="width: 150px">Nombre de archivo</th>
                    <th style="width: 100px">Creado por</th>
                    <th style="text-align: left">Fecha</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td style="text-align: center"><?= $this->arr["id"] ?></td>
                    <td style="text-align: center"><?= $this->arr["patente"] ?></td>
                    <td style="text-align: center"><?= $this->arr["aduana"] ?></td>
                    <td style="text-align: center"><?= $this->arr["archivoNombre"] ?></td>
                    <td style="text-align: center"><?= strtoupper($this->arr["usuario"]) ?></td>
                    <td style="text-align: left"><?= $this->arr["creado"] ?></td>
                </tr>
                <tr>
                    <td colspan="6" style="margin: 0; padding: 0">
                        <textarea id="fileContent" style="height: 350px; width: 90%"><?= utf8_encode(base64_decode($this->arr["contenido"])) ?></textarea>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="traffic-clear-5"></div>
        <a id="closeModal" class="traffic-btn traffic-btn-right">
            <i class="fas fa-times"></i> Cerrar</a>
        <a href="/operaciones/validador/descargar-archivo?id=<?= $this->arr["id"] ?>" class="traffic-btn">
            <i class="fas fa-save"></i> Descargar</a>
        <a href="/operaciones/validador/imprimir-archivo?id=<?= $this->arr["id"] ?>" class="traffic-btn">
            <i class="fas fa-print"></i> Imprimir</a>
        <script type="text/javascript">

            $(document.body).on("click", "#closeModal", function (ev) {
                ev.preventDefault();
                $("#file").html('Please wait... <img src="/images/loader.gif" alt="loading" />');
                $("#file").jqmHide();
            });

            $("#fileContent").linedtextarea();

        </script>
    </body>
</html>