<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<?= $this->appConfig('website-description') ?>">
    <meta name="author" content="Jaime E. Valdez">
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />
    <title><?= $this->title ?></title>
    <link rel="icon" type="image/png" href="<?= $this->appConfig('favicon') ?>" />
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <?= $this->headMeta(); ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
    <!--[if lt IE 9]>
        <script src="/js/common/html5shiv/dist/html5shiv.js"></script>
        <![endif]-->
    <style>
        @media only screen and (max-width : 640px) {
            .fixed-nav-bar {
                display: none;
            }
        }

        @media only screen and (min-width : 640px) {
            .fixed-nav-bar-mobile {
                display: none;
            }
        }

        .fixed-nav-bar-mobile {
            border-bottom: 5px solid #014079;
            position: fixed;
            top: 0;
            left: 0;
            z-index: 9999;
            width: 100%;
            height: 50px;
            background-color: #fff;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        }

        .mobile-link {
            height: 20px;
            margin: auto auto;
            margin-top: -10px;
            text-align: center;
        }

        .mobile-link p,
        .mobile-link a {
            color: #fff !important;
            font-size: 1.0em;
            text-decoration: none;
        }

        .mobile-link a {
            text-shadow: 1px 1px #333;
        }

        @media only screen and (min-width : 640px) {
            .mobile-link {
                display: none;
            }
        }
    </style>
</head>

<body>
    <nav class="fixed-nav-bar-mobile">
        <a href="/">
            <img src="/images/oaq_queretaro_small.png" class="logo">
        </a>
    </nav>
    <nav class="fixed-nav-bar">
        <!-- Fixed navigation bar content -->
        <a href="/">
            <img src="/images/oaq_queretaro_small.png" class="logo">
        </a>
        <p>
            <a href="/default/index/terminos">Términos</a>
        </p>
        <p>
            <a href="/default/index/privacidad">Privacidad</a>
        </p>
        <p>
            <a href="/neec/Index.html" target="_blank">NEEC</a>
        </p>
        <p>
            <a href="/soporte" target="_blank">Soporte</a>
        </p>
        <p class="right">
            <a href="/default/index/contacto">Contacto</a>
        </p>
    </nav>

    <div id="parent">
        <?= $this->layout()->content ?>
    </div>

    <div class="mobile-link">
        <p><a href="/mobile/main">Versión móvil</a></p>
    </div>

    <?php if (isset($this->browser_sync)) { ?>
        <script id="__bs_script__">
            //<![CDATA[
            document.write("<?= $this->browser_sync ?>".replace("HOST", location.hostname));
            //]]>
        </script>
    <?php } ?>

</body>

</html>