<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=10, user-scalable=yes">
        <title><?= $this->title ?></title>
        <?= $this->headMeta() ?>
        <?= $this->headLink() ?>
        <link href="/favicon.png" rel="icon shortcut" >
    </head>
    <body>
        <div class="container">
            <?= $this->layout()->content ?>
        </div> <!-- /container -->
        <?= $this->headScript() ?>
    </body>
</html>
