<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=10, user-scalable=yes">
        <title><?= $this->title ?></title>
        <link href="/favicon.png" rel="icon shortcut" >
        <?= $this->headMeta() ?>
        <?= $this->headLink() ?>
    </head>
    <body>
        <nav class="navbar navbar-dark bg-primary">
            <a class="navbar-brand" href="/mobile/main/inicio">OAQ <?= $this->title ?></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item <?= ($this->title == 'Tráficos') ? 'active' : '' ?>">
                        <a class="nav-link" href="/mobile/traficos">Tráficos</a>
                    </li>
                    <li class="nav-item <?= ($this->title == 'Bodega') ? 'active' : '' ?>">
                        <a class="nav-link" href="/mobile/bodega">Bodega</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/mobile/main/logout">Salir</a>
                    </li>
                </ul>
            </div>
        </nav>
        <?= $this->layout()->content ?>
        <?= $this->headScript() ?>
    </body>
</html>
